### ISSUE TITLE
IFTTT notification at start of sync?

### ISSUE THREAD

**Issue by bahree** [marcone/teslausb#106]
Not really an issue, but rather a question / suggestion - I wanted to know if it is possible to send out a alert at the start when the pi connects to wifi and kicks off the copy? I have this configured to get the alert when it finishes, but at start would be good too. Thanks.

**Comment by kdvlr** [comment]
I like the idea. I was planning to push a PR for making the push notification generic so they could be used elsewhere. I'll add it to my list.

**Comment by kdvlr** [comment]
Added PR https://github.com/marcone/teslausb/pull/107 which should address this.

**Comment by bahree** [comment]
Awesome thanks. So how can one get this? Would the self update work or if that once the PR is approved?

**Comment by kdvlr** [comment]
@marcone - Makes the final decision on what is merged to this repository. They are usually pretty good with it. However, you can get it from my repo if you're in a hurry.

**Comment by bahree** [comment]
Ah ok, I can wait. So should I reopen this issue until @marcone decides, or that doesn't matter?
