### ISSUE TITLE
USB Mode not working when using add-on board

### ISSUE THREAD

**Issue by inahas** [marcone/teslausb#111]
My TeslaUSB was working great. Seen by the car and archiving properly.

I wanted to reduce the clutter to make a more compact setup, so I got a USB add-on board (http://www.raspberrypiwiki.com/index.php/Raspberry_Pi_Zero_W_USB-A_Addon_Board) to stick the RPI directly in the car USB. 

Now the car no longer sees the RPI. When I do 

`ls -l /sys/devices/platform/soc/20980000.usb/gadget/`

I get

```
total 0
drwxr-xr-x 3 root root    0 Jul  1 06:52 lun0
drwxr-xr-x 3 root root    0 Jul  1 06:52 lun1
drwxr-xr-x 2 root root    0 Jul  1 06:52 power
-r--r--r-- 1 root root 4096 Jul  1 06:52 suspended
-rw-r--r-- 1 root root 4096 Jul  1 06:52 uevent
```

I'm guessing USB mode is pointing to lun0 and it needs to change to lun1.

How do I go about doing that?

**Comment by marcone** [comment]
No, lun0 and lun1 are the music and camera drives.
The board you linked to simply moves the micro usb port  on the side of the Pi to a full-size port on the end. There's no logic in it, it's just wiring. My guess is your add-on board is not making proper contact with the Pi.
