### ISSUE TITLE
Expected Behavior To Lose Tesla Mount While Syncing?

### ISSUE THREAD

**Issue by lapean111** [marcone/teslausb#13]
My teslacam is finally running pretty smoothly.  The only thing I have noticed is that it disconnects from the car when it connects to my wifi to sync.  Is that expected behavior?

**Comment by marcone** [comment]
Currently, yes. Since concurrent access from two hosts (the Pi and the car) to the filesystem on the emulated device is unsafe, the device needs to be disconnected from the car while archiving. I do have plans to significantly shorten and perhaps completely eliminate this problem though.
