### ISSUE TITLE
Setup won't complete

### ISSUE THREAD

**Issue by gonzonia** [marcone/teslausb#130]
I'm able to get the setup to start but it never completes. I can ssh into the pi and see WIFI_ENABLED and TESLAUSB_SETUP_STARTED but waiting hours and it doesn't complete. I never see the lights flashing the way the doc says it should either. 
On the current attempt the log ends with Updating package index files... previous attempts have gotten further sometimes, or not as far.
I'm connecting it to my mac only by the power connection (right micro usb). Should I be using the other one? It seemed like when I tried that the Wifi never worked. 

Thanks

**Comment by marcone** [comment]
Not enough information. Please see https://github.com/marcone/teslausb/issues/35
