### ISSUE TITLE
Only Saving Sentry Events-No CAM or MUSIC folders being created

### ISSUE THREAD

**Issue by dhtguru** [marcone/teslausb#131]
Please excuse my ignorance I am a greenhorn.  The system will upload some videos to my shared Windows folder, but only those that I manually save or those that are sentry events.  The code did not create either of  the folders in windows.  I did received an "All Done" in the setup log.

[teslausb-headless-setup.log](https://github.com/marcone/teslausb/files/3390163/teslausb-headless-setup.log)

**Comment by marcone** [comment]
Not sure what you mean by "did not create either of the folders in windows", but only manual or sentry events being archived is working as intended.
Your setup log looks fine. Please see https://github.com/marcone/teslausb/issues/35 for more troubleshooting info.
