### ISSUE TITLE
CIFS Sharing with Mac [SOLVED]

### ISSUE THREAD

**Issue by luzer** [marcone/teslausb#132]
i had been dealing with CIFS share issues for a while. the local share is on a Mac. some tricks that might help others

- my WiFi password has non-standard characters that needed to be escaped with a \
- my Mac share settings (Yosemite) required setting to "SMB" (see below) that allows
- CIFS version should actually be 3.0, not 2.1 or 2.0 {pending confirmation}
![share](https://user-images.githubusercontent.com/3173585/61189237-a3fb5080-a658-11e9-8ebe-c1ec527065eb.png)

**Comment by dragonxlwang** [comment]
might worth for @marcone to help put it on readme for people with a os x server:

need to select all the three boxes like in above picture -- i was selecting only smb (as default) and struggling to figure out how to login from linux (and hence raspberry pi).

**Comment by marcone** [comment]
@dragonxlwang Pretty sure that "Share files and folders using AFP" is not required for the Pi to access the share

**Comment by DMBlakeley** [comment]
I concur that "Share files and folders using AFP" is not required. Found that the CIFS 3.0 is correct for the Mac also.
