### ISSUE TITLE
Stuck on initial setup.  Stage 2.

### ISSUE THREAD

**Issue by cman2011** [marcone/teslausb#145]
Very new to this stuff.
Seems it's stuck with 2 flashes of the LED.
Server is reachable but can't mount.

STOP: The archive couldn't be mounted with CIFS version 3.0. Try specifying a lower number for the CIFS version like this:
Wed 24 Jul 04:36:22 BST 2019 : verify-archive-configuration:   export cifs_version=2.1
Wed 24 Jul 04:36:22 BST 2019 : verify-archive-configuration: Other versions you can try are 2.0 and 1.0
Wed 24 Jul 04:35:15 BST 2019 : Detecting whether to update wpa_supplicant.conf

I'm also not using any user/pass for the shared folder in Win10 so the credentials are left blank in the config.

**Comment by marcone** [comment]
Not enough information. See https://github.com/marcone/teslausb/issues/35
