### ISSUE TITLE
Drives not recognized

### ISSUE THREAD

**Issue by bladec59** [marcone/teslausb#151]
[teslausb-headless-setup 2.log](https://github.com/marcone/teslausb/files/3457263/teslausb-headless-setup.2.log)
Have done the one-step-setup and all appears to have finished correctly (setup log looks clean), but the usb isn't being recognized by PC/MAC or Tesla.  Did 100% cam, fyi.

**Comment by bladec59** [comment]
My bad...wrong cable.

**Comment by bladec59** [comment]
correction: recognized by PC/Mac but not by Tesla 2019.24; ordered new cables, will see how that goes.

**Comment by bladec59** [comment]
Found out it works fine in my wife's X (2018 MCU2) and doesn't in my S (2017 MCU1) even with 2 cables. Both are on 2019.24.  At this point I'd say MCU1 is the core problem.

**Comment by marcone** [comment]
Does a regular USB drive work with your MCU1 car?

**Comment by bladec59** [comment]
Yes

**Comment by marcone** [comment]
If you ssh into the Pi and then
```
sudo -i
modprobe -r g_mass_storage
modprobe g_mass_storage
```
does that change anything?

**Comment by bladec59** [comment]
While connected to the S/MCU1?

Sent from my iPhone

On Aug 2, 2019, at 12:03 PM, marcone <notifications@github.com<mailto:notifications@github.com>> wrote:


If you ssh into the Pi and then

sudo -i
modprobe -r g_mass_storage
modprobe g_mass_storage


does that change anything?

**Comment by marcone** [comment]
Yes, while connected to the car

**Comment by bladec59** [comment]
No luck.

**Comment by DMBlakeley** [comment]
Have this issue with CAM and MUSIC drives not be mounted when connected to my Mac. If I perform the steps of the previous post the drives mount and are accessible. As soon as I issue a halt to the ssh session the drives are unmounted.

As the drives did not mount on my Mac I did not try in the Tesla.

**Comment by The-Lor** [comment]
I have found that the g_ether in /boot/cmdline.txt caused my issues, once I removed it everything worked just fine except that windows didn't like to wait for the g_mass_storage to load, used the pwr in usb let the device boot then plugged in the data usb and it came up fine, but didn't have to do that in the car just took a min before it was showing available.  Apparently there is a g_multi that will do both ether and mass storage but once wifi is working then the g_eather wasn't needed https://www.raspberrypi.org/forums/viewtopic.php?t=238280 pointed me in this direction.

**Comment by marcone** [comment]
@DMBlakeley what do you mean by "issue a halt to the ssh session" ?
If you're typing `halt` into the command line, you're shutting down the Pi, so of course the drives will be unmounted.

**Comment by bdoooh** [comment]
I'm having the exact same issue. Tried multiple cables but the green light keeps doing the double blinks.

**Comment by marcone** [comment]
See https://github.com/marcone/teslausb/issues/35

**Comment by bladec59** [comment]
Per request. Moved from X, where it was working to S, where it was not working.  Ran diagnostics.
[diagnostics.txt](https://github.com/marcone/teslausb/files/3465032/diagnostics.txt)

**Comment by marcone** [comment]
Can you do that again, but wait a bit longer for the Pi to start before running diagnostics? It looks like archiveloop was still in the middle of checking the disk image for errors for this report.

**Comment by bdoooh** [comment]
@marcone looks like I'm an idiot. I didn't realize I needed to plug in both the USB data cable to the car and the USB charging port to a charging port. Splitter galore here now.

**Comment by bladec59** [comment]
So I tried a different SD card; reflashed and configured and set up rpi.  Same (2 cables, no luck) result in the Model S.  Diags attached.
[diagnostics2.txt](https://github.com/marcone/teslausb/files/3465083/diagnostics2.txt)

**Comment by marcone** [comment]
Diagnostics file shows the Pi has published the cam drive and that the car has connected to it. No idea why it's not actually working for you.

**Comment by bladec59** [comment]
Thanks

Sent from my iPhone

On Aug 4, 2019, at 4:09 PM, marcone <notifications@github.com<mailto:notifications@github.com>> wrote:


Diagnostics file shows the Pi has published the cam drive and that the car has connected to it. No idea why it's not actually working for you.
