### ISSUE TITLE
Consider using Apache MiNiFi

### ISSUE THREAD

**Issue by danshev** [marcone/teslausb#16]
You might consider using Apache MiNiFi on the Pi Zero. It has a very nice, durable way of transferring data.

I have a Pi Zero running MiNiFi, monitoring TeslaCam/SavedClips.  When a new file is detected, it will read it, and then transfer it to a Raspberry Pi on my home network running a full NiFi instance.  The full NiFi instance then uses a PutS3 processor to save my clips to AWS.

**Comment by marcone** [comment]
After browsing around https://nifi.apache.org/minifi/index.html I'm still having a hard time understanding what it even is or does, but I get the impression it's probably overkill for teslausb.
