### ISSUE TITLE
Does anyone have music sync working with Google Drive?

### ISSUE THREAD

**Issue by djlauria** [marcone/teslausb#162]
I did a manual setup, and using rclone, I have video successfully syncing. Music does not however. There's a line in archiveloop.log that states "Music archive not configured or unreachable". I'm not sure where else to go for troubleshooting, however. The command '/root/bin/setup-teslausb diagnose > /mutable/diagnostics.txt' errors out with "cat: /tmp/root2834/var/log/boot.log: No such file or directory".

**Comment by djlauria** [comment]
I did a manual setup, and using rclone, I have video successfully syncing. Music does not however. There's a line in archiveloop.log that states "Music archive not configured or unreachable". I'm not sure where else to go for troubleshooting, however. The command '/root/bin/setup-teslausb diagnose > /mutable/diagnostics.txt' errors out with "cat: /tmp/root2834/var/log/boot.log: No such file or directory".

**Comment by marcone** [comment]
Music sync is only supported for cifs, as stated in the documentation and in the sample config file.
