### ISSUE TITLE
Network Path Issue Undetected?

### ISSUE THREAD

**Issue by jbienz** [marcone/teslausb#164]
First let me give a disclaimer that it's been ages since I spent time in Linux, so I may have done something silly. I do, however, have teslausb up and running correctly now and I wanted to document an issue I ran into when setting it up yesterday.

I _believe_ the problem was due to the network path format. In [SetupShare.md](https://github.com/marcone/teslausb/blob/main-dev/doc/SetupShare.md) the example for the share name is simple:

`export sharename="SailfishCam"`

But in my case my share is nested. Coming from a Windows background, I setup my export like this:

`export sharename="Videos\\Projects\\TeslaCam"`

I used double backslashes because I had read about escaping things in [OneStepSetup.md](https://github.com/marcone/teslausb/blob/main-dev/doc/OneStepSetup.md).

The headless setup appeared to complete successfully. I had `TESLAUSB_SETUP_FINISHED` and `WIFI_ENABLED` files in my `/boot` folder. I could also see the device on my network and ssh into it. But no video files ever copied over to the network share.

So next I looked at `/mutable/archiveloop.log` and it gave me a clue.

`/mnt/cam/TeslaCam/SavedClips does not exist, skipping`

But I knew for a fact that folder existed. I had verified manually that it did and that the user I was logging in with had access.

Next I checked `/boot/teslausb-headless-setup.log` and saw this:

```
Wed 14 Aug 21:50:53 CDT 2019 : verify-and-configure-archive: The archive share is mountable using: mount -t cifs '//ServerName\Videos\Projects\TeslaCam' '/tmp/archivetestmount' -o 'credentials=/tmp/teslaCamArchiveCredentials,iocharset=utf8,file_mode=0777,dir_mode=0777,,'
```

At that point I remembered back to my Linux days that Linux uses forward slash for network paths rather than back slash.

I couldn't find an easy way to fix just this part so just I ended up recreating my headless config file and running `/root/bin/setup-teslausb` again. After this completed, I rebooted the device and video files started showing up on my share.

I'm logging this issue for 2 reasons:

1. If this was in fact a path issue, I'd like to see [SetupShare.md](https://github.com/marcone/teslausb/blob/main-dev/doc/SetupShare.md) updated to warn about this potential pitfall.

2. I also wonder if the archive loop code needs to be updated to handle this situation? I'm still confused as to why it was telling me `SavedClips does not exist` rather than failing to connect to the share.

For completeness, I'll paste in the full archive log below from when the path was using backslashes.

```
Wed 14 Aug 20:53:12 CDT 2019: Archiving...
Wed 14 Aug 20:53:12 CDT 2019: Disconnecting usb from host...
Wed 14 Aug 20:53:12 CDT 2019: Disconnected usb from host.
Wed 14 Aug 20:53:12 CDT 2019: Ensuring cam archive is mounted...
Wed 14 Aug 20:53:12 CDT 2019: /mnt/archive is already mounted.
Wed 14 Aug 20:53:12 CDT 2019: Ensured cam archive is mounted.
Wed 14 Aug 20:53:12 CDT 2019: Starting recording archiving...
Wed 14 Aug 20:53:12 CDT 2019: Ensuring cam file is mounted...
Wed 14 Aug 20:53:12 CDT 2019: Mounting /mnt/cam...
Wed 14 Aug 20:53:12 CDT 2019: Mounted /mnt/cam.
Wed 14 Aug 20:53:12 CDT 2019: Ensured cam file is mounted.
Wed 14 Aug 20:53:12 CDT 2019: Running fsck on /mnt/cam...
Wed 14 Aug 20:53:13 CDT 2019: | fsck from util-linux 2.29.2
Wed 14 Aug 20:53:14 CDT 2019: | fsck.fat 4.1 (2017-01-24)
Wed 14 Aug 20:53:14 CDT 2019: | 0x41: Dirty bit is set. Fs was not properly unmounted and some data may be corrupt.
Wed 14 Aug 20:53:14 CDT 2019: |  Automatically removing dirty bit.
Wed 14 Aug 20:53:14 CDT 2019: | Performing changes.
Wed 14 Aug 20:53:14 CDT 2019: | /dev/loop0: 2 files, 2/1846457 clusters
Wed 14 Aug 20:53:14 CDT 2019: Finished fsck on /mnt/cam.
Wed 14 Aug 20:53:14 CDT 2019: wake up car process is 1218
Wed 14 Aug 20:53:14 CDT 2019: Moving clips to archive...
Wed 14 Aug 20:53:14 CDT 2019: Creating output directory ''
Wed 14 Aug 20:53:14 CDT 2019: /mnt/cam/TeslaCam/SavedClips does not exist, skipping
Wed 14 Aug 20:53:14 CDT 2019: Moved 0 file(s), failed to copy 0, deleted 0.
Wed 14 Aug 20:53:14 CDT 2019: Finished moving clips to archive.
Wed 14 Aug 20:53:14 CDT 2019: killing PID 1218
Wed 14 Aug 20:53:15 CDT 2019: Unmounting /mnt/cam...
Wed 14 Aug 20:53:15 CDT 2019: Unmounted /mnt/cam.
Wed 14 Aug 20:53:15 CDT 2019: Finished archiving.
```

**Comment by marcone** [comment]
It's odd that the log showed it was mountable using the invalid path. Can you post the output of `setup-teslausb diagnose` ?
