### ISSUE TITLE
Not Using TeslaCam Folders?

### ISSUE THREAD

**Issue by jbienz** [marcone/teslausb#165]
Please note that this issue may somehow be related to #164.

After getting everything setup and running last night, I noticed that teslausb isn't organizing videos as I would expect it to on the share. I expected that videos under `SavedClips` in the car would end up under `SavedClips` on the share. But instead I'm seeing the dated folders show up in the root of the share.

![image](https://user-images.githubusercontent.com/2062886/63114505-a48a4e00-bf5a-11e9-8e0e-3e01dfc32da1.png)

Is this to be expected?

**Comment by marcone** [comment]
Yes. If you want the TeslaCam folder, just create it on the share, and add it to the share name

**Comment by jbienzms** [comment]
I do have a `TeslaCam` folder and it is part of my share name. The path on the server is shown in the screenshot above. My export is as follows:

`export sharename="Videos/Projects/TeslaCam"`

Are you saying that my export should have instead been:

`export sharename="Videos/Projects"`

?

**Comment by jbienz** [comment]
I do have a `TeslaCam` folder and it is part of my share name. The path on the server is shown in the screenshot above. My export is as follows:

`export sharename="Videos/Projects/TeslaCam"`

Are you saying that my export should have instead been:

`export sharename="Videos/Projects"`

?

**Comment by marcone** [comment]
Sorry, I meant 'SavedClips': export sharename="Videos/Projects/TeslaCam/SavedClips"

**Comment by jbienz** [comment]
Oh I see what you mean. Does TeslaUSB only backup SavedClips then and not RecentClips? This may have been my misunderstanding of what to expect there.
