### ISSUE TITLE
How to expand root filesystem

### ISSUE THREAD

**Issue by joverdijk** [marcone/teslausb#170]
Hi

I would really like to expand my root filesystem, because I want to install some additional stuff (like apache etc).
When I try to resize partition in raspi-config it says its not the last partition. 
I intentionally left some space not filling up SDcard size with CAM/MUSIC fize, but this just gives free space on the /backingfiles mountpoint, not the root-filesystem ;-(
So I guess this has to be done during setup process.

I suspect using Gparted will definatly soup some stuff up?

Can i set a root partition size somewhere during setup from the pre-baked image? 
Rootfs is now 1.6G, i need at least 4G 

Thanks!

**Comment by marcone** [comment]
I'm not sure what decides the 1.6 GB root partition size, but after flashing the prebuilt image the root partition will be the last partition, so you could expand it at that time.
You would have to set HEADLESS_SETUP to false in the config file, boot the pi, change the partition size, change HEADLESS_SETUP to true in the config file, then reboot again to run the rest of the setup.
