### ISSUE TITLE
When setting up, pi zero gets stuck on "Detecting whether to update wpa_supplicant.conf"

### ISSUE THREAD

**Issue by Blckbrry-Pi** [marcone/teslausb#177]
I've been trying many things, but I just can't get this to work. SSH works just fine too. Image of the SD Card is attached.

16Gb card, 2 regular USB micro B cables. 

SD card image is at [https://1drv.ms/u/s!AiYuossZrDmSaSru8Wa0-hPNCCY?e=iGtJ2B](url)

**Comment by marcone** [comment]
See https://github.com/marcone/teslausb/issues/35

**Comment by ghost** [comment]
I was having this same issue. I created a wpa_supplicant.conf in addition to the telsausb_setup_variables.conf and that solved the problem.
