### ISSUE TITLE
Seems to be functional, but doesn't transfer files to CIFS share

### ISSUE THREAD

**Issue by bobk2824** [marcone/teslausb#178]
I went through setup. Split the storage 50/50 for music/teslacam.
The rpi connects to wifi fine and functions fine in the car as far as presenting the music and tesla cam folders to the car, but it never seems to connect to the cifs share.

The /boot/teslausb-headless-setup.log does not end with All done, so I ran sudo /etc/rc.local. This outputs the following:
pi@teslausb:~ $ sudo /etc/rc.local
My IP address is 192.168.1.173
Detecting whether to update wpa_supplicant.conf
pi@teslausb:~ $ already running

I've created the diagnostics.txt and uploaded it:
[diagnostics.txt](https://github.com/marcone/teslausb/files/3538208/diagnostics.txt)

Thanks for any help,
Bob

**Comment by marcone** [comment]
From the summary at the top of the diagnostics:
```
CIFS archiving selected, but archive not defined in fstab
```
which explains why it's not archiving anything.
Looking at your setup log, it seems that something went wrong during the initial try:
```
Fri  2 Aug 15:38:53 BST 2019 : verify-and-configure-archive: STOP: The archive server bobdev is unreachable. Try specifying its IP address instead.
```
but then after that it appears that setup was never run again, though the Pi was rebooted many times.
At this point I'd just start over from scratch.
