### ISSUE TITLE
Feature Request: Integrate video compiling

### ISSUE THREAD

**Issue by LBegnaud** [marcone/teslausb#18]
Would be slick to include this project and clean up the folder structure before uploading files:

https://pypi.org/project/tesla-dashcam/

My thought is to pipe videos through this tool during the upload process and the result after the archive is a clean folder structure with one video per event.

**Comment by marcone** [comment]
I think that post-processing of the recordings is probably better done on a more powerful machine. This seems like it would be quite slow when running on the rpi itself, since it needs to re-encode the video files.
