### ISSUE TITLE
teslausb random reboots

### ISSUE THREAD

**Issue by chiwalfrm** [marcone/teslausb#182]
I am using two usb cables so this isn't the same issue as the one with one single usb cable for power/data.

Basically, my raspberry pi zero w reboots randomly.  I added logging to /etc/rc.local so I can track the reboots, it will echo 'reboot start' at the beginning and 'reboot finish' at the end of rc.local.  In the past 48 hours, I see the following:

```
pi@teslausb:~ $ cat /mutable/reboot.log
Reboot start  Thu  3 Nov 12:17:24 CDT 2016
Reboot finish Sun 25 Aug 11:20:00 CDT 2019
Reboot start  Thu  3 Nov 12:17:05 CDT 2016*
Reboot start  Thu  3 Nov 12:17:06 CDT 2016*
Reboot start  Thu  3 Nov 12:17:05 CDT 2016
Reboot finish Mon 26 Aug 09:23:46 CDT 2019
Reboot start  Thu  3 Nov 12:17:07 CDT 2016*
Reboot start  Thu  3 Nov 12:17:04 CDT 2016*
Reboot start  Thu  3 Nov 12:17:06 CDT 2016*
Reboot start  Thu  3 Nov 12:17:06 CDT 2016*
Reboot start  Thu  3 Nov 12:17:06 CDT 2016*
Reboot start  Thu  3 Nov 12:17:06 CDT 2016
Reboot finish Mon 26 Aug 09:45:38 CDT 2019
pi@teslausb:~ $
```

the '2016' date-timestamps for 'reboot start' is because the hardware clock isn't set yet at the beginning of rc.local. 

*As you can see, there are multiple reboots that did not even get to the end of rc.local, although the script would only write 'reboot finish' if wifi is available/connected, but the car has been parked in my garage the entire time.

It has rebooted 9 times in the past 2 days.

I thought maybe it is power related, if Tesla is cutting off the power so I bought a charge-through power bank, but the reboots are still happening.

Does this happen to anyone else?  for example, if you ssh into it, and do 'uptime', does it show a large uptime?

**Comment by chiwalfrm** [comment]
i wrote a script that logs the cpu temperature every 60 seconds, and the highest reading is 43C.

**Comment by chiwalfrm** [comment]
it rebooted 6 times this morning from 9:23 am to 9:45am.

**Comment by marcone** [comment]
I'd start by taking the Pi out of the car and just powering it from a regular USB charger and see if it stays up then.

**Comment by chiwalfrm** [comment]
Took the Pi out of the car, plugged into power strip, same room as Wifi router.  Also rebooted randomly.  Next, bought a second Pi Zero W since it's only $5.  Different memory card.  This one does the same thing, so we can rule out that this is caused by defective Raspberry Pi or memory card.

**Comment by marcone** [comment]
You must live near a MicroCenter... (only place I know of that sells RPI0W for $5 :smile: )

Unfortunately I don't know what might be causing this. Teslausb does not reboot the Pi, except during initial setup.

**Comment by chiwalfrm** [comment]
also I am using Samsung Evo memory cards so it's unlikely to be the root cause:

https://www.amazon.com/gp/product/B07MKSGZM6 (512GB Evo Select)
and 
https://www.amazon.com/Samsung-MicroSDHC-Adapter-MB-ME32GA-AM/dp/B06XWN9Q99 (32GB)

**Comment by marcone** [comment]
Nothing actionable here
