### ISSUE TITLE
Two things not to do to your working Pi0W...

### ISSUE THREAD

**Issue by sTevefor3** [marcone/teslausb#183]
Installed the @marcone image; brilliant, by the way.  It just works.  My Model 3 says the 128 Gb SD card I'm using is too slow, so I'll redo the image on this [card](https://www.amazon.com/Samsung-Endurance-64GB-Micro-Adapter/dp/B07B984HJ5/ref=as_li_ss_tl?tag=carcamcen-20&ie=UTF8&qid=1549745993&sr=8-1&keywords=64gb%2Bsamsung%2Bpro%2Bendurance&linkId=8afebdc525511670edb8e20f88ed39e6&language=en_US&th=1
).  I have 54 Gb of music on the MUSIC partition; the rest is for CAM.  Networking works as intended; however, when music is playing from the SD card, it will randomly pause for 20 - 30 sec, I assume this is when data is being written to CAM.

In the meantime, I got ambitious and tried to upgrade to Buster using this [guide](https://pimylifeup.com/upgrade-raspbian-stretch-to-raspbian-buster/).  After following the steps, the subsequent reboot got stuck at this point: `cp: cannot create directory '//lib/modules/4.19.67+/kernel/drivers/net/ppp': No space left on device`.

I'm sure this is because of the prebuilt image based on Stretch, and I only tried this once just to see if it would work, and crashed and burned.  I was intending to move to a Pi 4B to see if it would perform any better than the Pi0W.

The second thing not to do is [this](https://github.com/lukicdarkoo/rpi-wifi) (Configures simultaneous AP and Managed Mode Wifi on Raspberry Pi).  SSH would not respond after installation.  I don't know exactly why.  This would be a nice addition to the TeslaUSB project; I have a need to access the Pi when the car is away from my home WiFi.

**Comment by AlbyZ** [comment]
When I followed:

 https://blog.thewalr.us/2017/09/26/raspberry-pi-zero-w-simultaneous-ap-and-managed-mode-wifi/ 
 
did you do this to make sure the AP and WLAN came up in the correct order:

$ sudo ifdown --force wlan0
$ sudo ifdown --force ap0
$ sudo ifup ap0
$ sudo ifup wlan0

An alternative in the comments is to use the pre-up statement in the wpa_supplicant file:

allow-hotplug wlan0
iface wlan0 inet manual
        pre-up ifup ap0
        wpa-roam /etc/wpa_supplicant/wpa_supplicant.conf
        pre-down ifdown ap0
iface AP1 inet dhcp
iface AP2 inet dhcp

Works ok.

**Comment by marcone** [comment]
I have simultaneous client and AP working, and will be merging that into the main branch soon. It seems to work well, and I did not have to do anything special to ensure the order in which the interfaces come up.

**Comment by sTevefor3** [comment]
Terrific!  No, I did not follow those instructions, @AlbyZ ; after installation, I rebooted and could no longer ssh into my Pi.  Await anxiously the merge!  Thanks to both of you!

**Comment by marcone** [comment]
@sTevefor3 It was merged 2 days ago

**Comment by sTevefor3** [comment]
Thanks, @marcone !  I was on holiday the last few days.  Forgive my lack of Linux command-line skill:  how do we incorporate the merge into a running setup?

**Comment by marcone** [comment]
Add the new variables to specify SSID and password to teslausb_setup_variables.conf and rerun setup:
```
sudo -i
/root/bin/remountfs_rw
/root/bin/setup-teslausb selfupdate
/root/bin/setup-teslausb
reboot
```
You can find the variables to add here: https://github.com/marcone/teslausb/blob/main-dev/doc/teslausb_setup_variables.conf.sample (look for the ones starting with "AP_")
If you think that's beyond your command line skills, just redo setup from scratch.

**Comment by sTevefor3** [comment]
Hat tip to @marcone et al for your infinite patience and timely advice.  This project is not possible without the work you're doing.

My Pi0W is now functioning perfectly 4 days +.  AP working, I can ssh into the Pi anytime, anywhere.  Recording icon pops up immediately upon entering the vehicle.  Plays nice with Sentry Mode.  Uploads CAM drive contents when I pull into my driveway.  Music library updates itself.  Magical!

**Comment by sTevefor3** [comment]
And my setup lasted 4 days, then the red exclamation icon.  Since there was an update available and recommended, I updated.  That lasted a little over 24 hrs, then the red exclamation icon (USB drive unreadable).  Fortunately, I can reboot the Pi anytime I'm near the car, and each time, so far, the recording icon pops right up after boot.  I'm afraid that I don't know precisely *when* the Pi is disconnected from the car (haven't looked at the logs, yet); hate to lose precious recordings that might benefit me legally.  Work-in-progress...

**Comment by SemoTech** [comment]
@sTevefor3 save yourself the headache and use a USB portable battery like the [Zendure](https://www.amazon.com/gp/product/B07HRD3LX1/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1&tag=tmc064-20), which also has a hub in it and can be charged while in use!  See my writeup with that info [HERE](https://teslamotorsclub.com/tmc/posts/3975052/).

**Comment by sTevefor3** [comment]
@SemoTech That's one of the nicest setups I've seen; great write-up.  Thanks for the links!

**Comment by SemoTech** [comment]
Glad you liked it @sTevefor3
Lots of good mods there from me to inspire Tesla owners.

**Comment by sTevefor3** [comment]
> Glad you liked it @sTevefor3
> Lots of good mods there from me to inspire Tesla owners.

The Zendure may become useful to those of us using Teslausb, especially now that the Pi 4B is available.

**Comment by marcone** [comment]
Gonna close this since both AP and Buster can now be used "out of the box"
