### ISSUE TITLE
Get_Script Failed

### ISSUE THREAD

**Issue by kennygunit** [marcone/teslausb#184]
I keep receiving the following error:

Here are the steps i completed:

New SD Card
Raspberry Pi 0 W

Formatted my SD Card
Loaded the ISO onto it using Etcher
Modified the conf.sample file:
Added my PC name
User Name
User Password
Wifi info

When i verify the info on the PC (plug into the data port), i'm able to ssh into it, but get this error when looking at the files. 

it also doesn't show up when i plug it into my car. 
 
![Capture](https://user-images.githubusercontent.com/54561152/63731457-74795f80-c824-11e9-8674-c16a1956cd30.JPG)

**Comment by marcone** [comment]
> Modified the conf.sample file:

Did you forget to rename it to teslausb_setup_variables.conf by any chance?

**Comment by kennygunit** [comment]
I just re-did the whole process for the 3rd time, and it seemed to be working now. I was able to get it to be recognized from on the tesla, but now the files aren't being converted to my PC. lol

**Comment by marcone** [comment]
check /mutable/archiveloop.log and the output of "/root/bin/setup-teslausb diagnose"
