### ISSUE TITLE
Stops archiving 

### ISSUE THREAD

**Issue by gonzonia** [marcone/teslausb#187]
Aside from the Keep Alive not seeming to work on my model X, I've noticed that even if I turn on Sentry mode so the Pi0 stays on it stops copying. Not sure why, looking at the logs it could be a couple of things, hopefully you might have some ideas. Here's my diagnostics.txt which is pretty long. Happy to edit/truncate/etc just let me know what'll help. This is a great project and I wish my skills were up to contributing. Until then all I can do is try to help troubleshoot.

https://gist.github.com/gonzonia/335abeee570e6fa5ac2c04d730a4e010

**Comment by marcone** [comment]
How's your wifi connection where you park the car?
The diagnostics show it archiving files, but then the archive script seems to think it can no longer reach the archive server, and aborts archiving.
I should probably make the connection-checker less aggressive.

**Comment by gonzonia** [comment]
It should be good. The garage is about 10 ft from the access point and there's only 1 door between car and the AP. I can still ssh remotely from my desktop even after the archive has stopped.

**Comment by gonzonia** [comment]
Of course, after I did the update (prior to diagnostics) and reboot it finished. and moved 518 files.

**Comment by ppamidimarri** [comment]
I seem to have a similar problem. I am able to ssh to my Pi0W and get this log. 

```
==============================================
Thu  3 Nov 10:17:05 PDT 2016: Starting archiveloop...
Thu  3 Nov 10:17:05 PDT 2016: Waiting for time to be set by ntpd
Tue 27 Aug 19:12:01 PDT 2019: Time still not set, attempting to force it
Tue 27 Aug 19:12:01 PDT 2019: Failed to set time
Tue 27 Aug 19:12:01 PDT 2019: Ensuring music backing file is mounted...
Tue 27 Aug 19:12:01 PDT 2019: Mounting /mnt/music...
Tue 27 Aug 19:12:02 PDT 2019: Mounted /mnt/music.
Tue 27 Aug 19:12:02 PDT 2019: Ensured music drive is mounted.
Tue 27 Aug 19:12:02 PDT 2019: Running fsck on /mnt/music...
Tue 27 Aug 19:12:02 PDT 2019: | fsck from util-linux 2.29.2
Tue 27 Aug 19:12:05 PDT 2019: | fsck.fat 4.1 (2017-01-24)
Tue 27 Aug 19:12:05 PDT 2019: | 0x41: Dirty bit is set. Fs was not properly unmounted and some data may be corrupt.
Tue 27 Aug 19:12:05 PDT 2019: |  Automatically removing dirty bit.
Tue 27 Aug 19:12:05 PDT 2019: | Performing changes.
Tue 27 Aug 19:12:05 PDT 2019: | /dev/loop0: 2405 files, 328123/1513658 clusters
Tue 27 Aug 19:12:05 PDT 2019: Finished fsck on /mnt/music.
Tue 27 Aug 19:12:05 PDT 2019: Unmounting /mnt/music...
Tue 27 Aug 19:12:05 PDT 2019: Unmounted /mnt/music.
Tue 27 Aug 19:12:05 PDT 2019: Archiving...
Tue 27 Aug 19:12:05 PDT 2019: Disconnecting usb from host...
Tue 27 Aug 19:12:05 PDT 2019: Disconnected usb from host.
Tue 27 Aug 19:12:05 PDT 2019: Ensuring cam archive is mounted...
Tue 27 Aug 19:12:05 PDT 2019: /mnt/archive is already mounted.
Tue 27 Aug 19:12:05 PDT 2019: Ensured cam archive is mounted.
Tue 27 Aug 19:12:05 PDT 2019: Starting recording archiving...
Tue 27 Aug 19:12:06 PDT 2019: Ensuring cam file is mounted...
Tue 27 Aug 19:12:06 PDT 2019: Mounting /mnt/cam...
Tue 27 Aug 19:12:06 PDT 2019: Mounted /mnt/cam.
Tue 27 Aug 19:12:06 PDT 2019: Ensured cam file is mounted.
Tue 27 Aug 19:12:06 PDT 2019: Running fsck on /mnt/cam...
Tue 27 Aug 19:12:06 PDT 2019: | fsck from util-linux 2.29.2
Tue 27 Aug 19:12:08 PDT 2019: | fsck.fat 4.1 (2017-01-24)
Tue 27 Aug 19:12:09 PDT 2019: | 0x41: Dirty bit is set. Fs was not properly unmounted and some data may be corrupt.
Tue 27 Aug 19:12:09 PDT 2019: |  Automatically removing dirty bit.
Tue 27 Aug 19:12:09 PDT 2019: | Free cluster summary wrong (2865915 vs. really 2868603)
Tue 27 Aug 19:12:09 PDT 2019: |   Auto-correcting.
Tue 27 Aug 19:12:09 PDT 2019: | Performing changes.
Tue 27 Aug 19:12:09 PDT 2019: | /dev/loop0: 184 files, 159551/3028154 clusters
Tue 27 Aug 19:12:09 PDT 2019: Finished fsck on /mnt/cam.
Tue 27 Aug 19:12:09 PDT 2019: wake up car process is 1481
Tue 27 Aug 19:12:09 PDT 2019: Moving clips to archive...
Tue 27 Aug 19:12:09 PDT 2019: Creating output directory ''
Tue 27 Aug 19:12:09 PDT 2019: Creating output directory ''
Tue 27 Aug 19:12:09 PDT 2019: Moved 0 file(s), failed to copy 0, deleted 0.
Tue 27 Aug 19:12:09 PDT 2019: Finished moving clips to archive.
Tue 27 Aug 19:12:09 PDT 2019: killing PID 1481
Tue 27 Aug 19:12:09 PDT 2019: Unmounting /mnt/cam...
Tue 27 Aug 19:12:09 PDT 2019: Unmounted /mnt/cam.
Tue 27 Aug 19:12:09 PDT 2019: Finished archiving.
Tue 27 Aug 19:12:10 PDT 2019: Music archive not configured or unreachable
Tue 27 Aug 19:12:10 PDT 2019: unmounting /mnt/archive
Tue 27 Aug 19:12:10 PDT 2019: Connecting usb to host...
Tue 27 Aug 19:12:10 PDT 2019: Connected usb to host.
Tue 27 Aug 19:12:10 PDT 2019: Waiting for archive to be unreachable...
```
It was running fine yesterday. I tried rebooting the Pi to see if that fixes it, but the log looks very similar after.

**Comment by marcone** [comment]
@ppamidimarri that log shows that there was nothing to archive

**Comment by ppamidimarri** [comment]
@marcone Thanks for your help. I was confused by the fsck output showing 184 files and the `Creating output directory ''` line. If this is how the log looks when there is nothing to archive, then it's all good!

**Comment by gonzonia** [comment]
Still having problems. It'll start copying. Get through some files and then stop. When I SSH over it looks like it's lost the mount points (both for the archive and the cam). Can't see files in either. 
https://gist.github.com/gonzonia/dd80dd1a56ac0137ea06564719d8e889#file-diagnostics_0829-txt

I've also noticed since the last teslausb update I did that the drive will randomly stop working too and I'll get this message
![UNADJUSTEDNONRAW_thumb_3ec2b](https://user-images.githubusercontent.com/36857621/63959618-8fcdb000-ca5a-11e9-946b-09d11cc90b2f.jpg)

**Comment by marcone** [comment]
@gonzonia your diagnostics show some file system corruption on the disk image, which is probably why the car can't read it anymore. You may have a bad sd card.
As for "losing the mount points": the disk images are only mounted during archiving.

**Comment by spalt** [comment]
I'm also in the boat where it used to work great but lately I'm getting some weird issues and clips are not archiving.. 

==============================================
Sun  1 Sep 08:44:24 EDT 2019: Starting archiveloop...
Sun  1 Sep 08:44:25 EDT 2019: Ensuring cam file is mounted...
Sun  1 Sep 08:44:25 EDT 2019: Mounting /mnt/cam...
Sun  1 Sep 08:44:25 EDT 2019: Mounted /mnt/cam.
Sun  1 Sep 08:44:25 EDT 2019: Ensured cam file is mounted.
Sun  1 Sep 08:44:25 EDT 2019: Running fsck on /mnt/cam...
Sun  1 Sep 08:44:25 EDT 2019: | fsck from util-linux 2.29.2
Sun  1 Sep 08:44:26 EDT 2019: | fsck.fat 4.1 (2017-01-24)
Sun  1 Sep 08:44:26 EDT 2019: | 0x41: Dirty bit is set. Fs was not properly unmounted and some data may be corrupt.
Sun  1 Sep 08:44:26 EDT 2019: |  Automatically removing dirty bit.
Sun  1 Sep 08:44:26 EDT 2019: | Performing changes.
Sun  1 Sep 08:44:26 EDT 2019: | /dev/loop0: 203 files, 1009/1397614 clusters
Sun  1 Sep 08:44:26 EDT 2019: Finished fsck on /mnt/cam.
Sun  1 Sep 08:44:26 EDT 2019: Unmounting /mnt/cam...
Sun  1 Sep 08:44:27 EDT 2019: Unmounted /mnt/cam.
Sun  1 Sep 08:44:27 EDT 2019: Ensuring music backing file is mounted...
Sun  1 Sep 08:44:27 EDT 2019: Mounting /mnt/music...
Sun  1 Sep 08:44:27 EDT 2019: Mounted /mnt/music.
Sun  1 Sep 08:44:27 EDT 2019: Ensured music drive is mounted.
Sun  1 Sep 08:44:27 EDT 2019: Running fsck on /mnt/music...
Sun  1 Sep 08:44:27 EDT 2019: | fsck from util-linux 2.29.2
Sun  1 Sep 08:44:28 EDT 2019: | fsck.fat 4.1 (2017-01-24)
Sun  1 Sep 08:44:28 EDT 2019: | 0x41: Dirty bit is set. Fs was not properly unmounted and some data may be corrupt.
Sun  1 Sep 08:44:28 EDT 2019: |  Automatically removing dirty bit.
Sun  1 Sep 08:44:28 EDT 2019: | Performing changes.
Sun  1 Sep 08:44:28 EDT 2019: | /dev/loop0: 40 files, 3973/1048754 clustersSun  1 Sep 08:44:28 EDT 2019: Finished fsck on /mnt/music.
Sun  1 Sep 08:44:28 EDT 2019: Unmounting /mnt/music...
Sun  1 Sep 08:44:29 EDT 2019: Unmounted /mnt/music.
Sun  1 Sep 08:44:29 EDT 2019: Connecting usb to host...
Sun  1 Sep 08:44:29 EDT 2019: Connected usb to host.
Sun  1 Sep 08:44:29 EDT 2019: Waiting for archive to be reachable...
Sun  1 Sep 08:44:29 EDT 2019: Archive is reachable.
Sun  1 Sep 08:44:29 EDT 2019: Waiting for time to be set by ntpd...
Sun  1 Sep 08:44:30 EDT 2019: Time now set
Sun  1 Sep 08:44:50 EDT 2019: Archiving...
Sun  1 Sep 08:44:50 EDT 2019: Disconnecting usb from host...
Sun  1 Sep 08:44:50 EDT 2019: Disconnected usb from host.
Sun  1 Sep 08:44:50 EDT 2019: Ensuring cam archive is mounted...
Sun  1 Sep 08:44:50 EDT 2019: /mnt/archive is already mounted.
Sun  1 Sep 08:44:50 EDT 2019: Ensured cam archive is mounted.
Sun  1 Sep 08:44:50 EDT 2019: Ensuring music archive is mounted...
Sun  1 Sep 08:44:50 EDT 2019: /mnt/musicarchive is already mounted.
Sun  1 Sep 08:44:50 EDT 2019: Ensured music archive is mounted.
Sun  1 Sep 08:44:50 EDT 2019: Starting recording archiving...
Sun  1 Sep 08:44:50 EDT 2019: Sending IFTTT message for moved files.
Sun  1 Sep 08:44:51 EDT 2019: Ensuring cam file is mounted...
Sun  1 Sep 08:44:51 EDT 2019: Mounting /mnt/cam...
Sun  1 Sep 08:44:51 EDT 2019: Mounted /mnt/cam.
Sun  1 Sep 08:44:51 EDT 2019: Ensured cam file is mounted.
Sun  1 Sep 08:44:51 EDT 2019: Running fsck on /mnt/cam...
Sun  1 Sep 08:44:51 EDT 2019: | fsck from util-linux 2.29.2
Sun  1 Sep 08:44:52 EDT 2019: | fsck.fat 4.1 (2017-01-24)
Sun  1 Sep 08:44:52 EDT 2019: | 0x41: Dirty bit is set. Fs was not properly unmounted and some data may be corrupt.
Sun  1 Sep 08:44:52 EDT 2019: |  Automatically removing dirty bit.
Sun  1 Sep 08:44:52 EDT 2019: | Performing changes.
Sun  1 Sep 08:44:52 EDT 2019: | /dev/loop0: 203 files, 1009/1397614 clusters
Sun  1 Sep 08:44:52 EDT 2019: Finished fsck on /mnt/cam.
Sun  1 Sep 08:44:52 EDT 2019: wake up car process is 1342
Sun  1 Sep 08:44:52 EDT 2019: Moving clips to archive...
Sun  1 Sep 08:44:52 EDT 2019: Creating output directory ''
Sun  1 Sep 08:44:52 EDT 2019: Creating output directory ''
Sun  1 Sep 08:44:52 EDT 2019: Moved 0 file(s), failed to copy 0, deleted 0.Sun  1 Sep 08:44:52 EDT 2019: Finished moving clips to archive.
Sun  1 Sep 08:44:52 EDT 2019: killing PID 1342
Sun  1 Sep 08:44:52 EDT 2019: Unmounting /mnt/cam...
Sun  1 Sep 08:44:53 EDT 2019: Unmounted /mnt/cam.
Sun  1 Sep 08:44:53 EDT 2019: Finished archiving.
Sun  1 Sep 08:44:53 EDT 2019: Copying music...
Sun  1 Sep 08:44:53 EDT 2019: Starting music sync...
Sun  1 Sep 08:44:53 EDT 2019: Ensuring music backing file is mounted...
Sun  1 Sep 08:44:53 EDT 2019: Mounting /mnt/music...
Sun  1 Sep 08:44:53 EDT 2019: Mounted /mnt/music.
Sun  1 Sep 08:44:53 EDT 2019: Ensured music drive is mounted.
Sun  1 Sep 08:44:53 EDT 2019: Running fsck on /mnt/music...
Sun  1 Sep 08:44:53 EDT 2019: | fsck from util-linux 2.29.2
Sun  1 Sep 08:44:54 EDT 2019: | fsck.fat 4.1 (2017-01-24)
Sun  1 Sep 08:44:54 EDT 2019: | 0x41: Dirty bit is set. Fs was not properly unmounted and some data may be corrupt.
Sun  1 Sep 08:44:54 EDT 2019: |  Automatically removing dirty bit.
Sun  1 Sep 08:44:54 EDT 2019: | Performing changes.
Sun  1 Sep 08:44:54 EDT 2019: | /dev/loop0: 40 files, 3973/1048754 clustersSun  1 Sep 08:44:54 EDT 2019: Finished fsck on /mnt/music.
Sun  1 Sep 08:44:54 EDT 2019: Copying music from archive...
Sun  1 Sep 08:44:54 EDT 2019: Copied 0 music file(s), skipped 28 previously-copied files, encountered 0 errors.
Sun  1 Sep 08:44:54 EDT 2019: Unmounting /mnt/music...
Sun  1 Sep 08:44:54 EDT 2019: Unmounted /mnt/music.
Sun  1 Sep 08:44:54 EDT 2019: Finished copying music.
Sun  1 Sep 08:44:54 EDT 2019: unmounting /mnt/archive
Sun  1 Sep 08:44:54 EDT 2019: unmounting /mnt/musicarchive
Sun  1 Sep 08:44:55 EDT 2019: Connecting usb to host...
Sun  1 Sep 08:44:55 EDT 2019: Connected usb to host.
Sun  1 Sep 08:44:55 EDT 2019: Waiting for archive to be unreachable...
pi@teslausb:~ $

**Comment by marcone** [comment]
@spalt according to that bit of archiveloop log, it didn't archive anything because there was nothing to archive.

**Comment by marcone** [comment]
> I should probably make the connection-checker less aggressive.

I just did that in the main-dev branch. It now checks more times, and longer, before deeming the server unreachable.
