### ISSUE TITLE
Archive Sentry Mode videos

### ISSUE THREAD

**Issue by ghost** [marcone/teslausb#190]
When my Pi syncs, I only get videos from RecentClips and they're dropped in the root "TeslaCam" directory as opposed to the sub folders the car creates on USB drives. I saw a previous issue posted stating the opposite where they were only getting SavedClips archived. 
How can I get either both directories or switch to SavedClips to archive from my Pi?

**Comment by marcone** [comment]
That doesn't seem possible, so please run `/root/bin/setup-teslausb diagnose` as described in https://github.com/marcone/teslausb/issues/35

**Comment by ghost** [comment]
> That doesn't seem possible, so please run `/root/bin/setup-teslausb diagnose` as described in #35

I figured it out after posting this, that was actually just a lot of Sentry Mode events after I got the Pi Zero W working. It's performing as expected. Thanks for the reply!
