### ISSUE TITLE
Using the smb function to copy Recent Clips in Windows

### ISSUE THREAD

**Issue by chilman408** [marcone/teslausb#195]
I tried this a couple of times and it works but the very next day the Pi show the gray X issue.

If I dont mount the Pi to windows (or try to copy recent clips), there isn't any error with using it for as long as I remember.

Just pointing this out...not really desperate for this function to work.

**Comment by marcone** [comment]
You're talking about accessing the pi via cifs/samba, right, not about cifs backup?

**Comment by chilman408** [comment]
Yes, I was copying the 'Recent' clips over to the PC.  This works but every time I do this, the very next day I get a gray X on the M3

**Comment by marcone** [comment]
Weird. Accessing the pi via smb shouldn't affect anything. It doesn't even unmount the drive or anything. How are you powering the Pi? Does it stay on overnight?

**Comment by chilman408** [comment]
I'm powering the pi via usb from the 12v socket.  It stays on.

**Comment by marcone** [comment]
Have you tried unplugging and reconnecting the data port when it shows the X? (while keeping the Pi powered)

**Comment by chilman408** [comment]
Yes, tried.  Stays corrupted with the grey X.

When I plug the PI to a PC, none of the files that show up in TeslaCam can be deleted via Windows.

**Comment by marcone** [comment]
Is there any way to fix it, like restarting the Pi, or do you have to reinstall?
It sounds like there's some kind of problem with the sd card that causes filesystems to be remounted read-only.

**Comment by chilman408** [comment]
Yes, I had to reflash.  Bring the Pi over to Windows restarts.

**Comment by XmemphistoX** [comment]
I just started getting this after enabling either AP mode or Samba.  Disconnecting the Pi and reconnecting it fixes it.  I'll try to disable that and see if it comes back.

**Comment by XmemphistoX** [comment]
I just redid the whole setup and turned off samba/AP. Seems to be fine now.
