### ISSUE TITLE
Force Archive via SSH?

### ISSUE THREAD

**Issue by DavidGagne** [marcone/teslausb#197]
TL;DR: Is there a command to execute via an SSH connection to "force" an archive process?

I know it's not technically supported via this fork, but I'm trying to test rsync and I'm not sure why it's not working.

Inspecting _/mutable/archiveloop.log_ shows me the log messages:

> Archiving through rsync...
> No files to archive through rsync.

But I can see that there are files in the TeslaCam directory which _should_ be getting uploaded. I know that passwordless ssh is working correctly from my Raspberry Pi to my server, so I'm trying to track down where it's failing.

**Comment by marcone** [comment]
`touch /tmp/archive_is_unreachable` will simulate a disconnect/reconnect from wifi, which will trigger archiving. Note that teslausb only archives files under SavedClips, not under RecentClips (in case that explains why you're seeing files under TeslaCam but nothing is getting archived)

**Comment by DavidGagne** [comment]
Is the archiveloop executed by the user pi or the user root?

The answer is root.

And I've got it working now with rsync, so now when I come home, the RPi connects to my home WiFi and then uploads my SavedClips to my [DreamHost](https://www.dreamhost.com/r.cgi?8624) webserver.

The tricky part was making sure [passwordless ssh](https://help.dreamhost.com/hc/en-us/articles/216499537-How-to-configure-passwordless-login-in-Mac-OS-X-and-Linux) was working correctly.
