### ISSUE TITLE
Stuck on 2 led flashes

### ISSUE THREAD

**Issue by lifeisgrand** [marcone/teslausb#198]
<script src="https://pastebin.com/embed_js/t7V7NXpt"></script>

**Comment by lifeisgrand** [comment]
[teslausb-headless-setup.log](https://github.com/marcone/teslausb/files/3553897/teslausb-headless-setup.log)

**Comment by rohan3au** [comment]
Also having this problem, stuck on two flashes. Have tried many fixes with nothing working. Any advice? Won't even seem to connect to wifi and stuck on a boot loop, also can't SSH in, and no log file present.

**Comment by marcone** [comment]
https://github.com/marcone/teslausb/issues/35

**Comment by lifeisgrand** [comment]
<script src="https://pastebin.com/embed_js/t7V7NXpt"></script>

**Comment by rohan3au** [comment]
Have gone through all of the problems and still not working. Pi won't even reach SSH stage, and doesn't produce a log file.

**Comment by marcone** [comment]
@lifeisgrand I can't access that link ("this is a private paste")

@rohan3au then you probably specified the wrong wifi credentials. Note that special characters in SSID or password need to be escaped.

**Comment by lifeisgrand** [comment]
I made the link hidden instead of private - it should work now

**Comment by marcone** [comment]
@lifeisgrand that looks like a perfectly normal working install. Regarding the flashes, please see the first sentence in the wiki (https://github.com/marcone/teslausb/wiki referenced from https://github.com/marcone/teslausb/issues/35)
