### ISSUE TITLE
Design to 3D print a Pi Holder for Model 3

### ISSUE THREAD

**Issue by wowiejr** [marcone/teslausb#206]
[3D Printed Model 3 Pi Holder](https://www.thingiverse.com/thing:3837448)

Not really an issue but I wanted to share this with this community.

I designed this to hold and mount a Raspberry Pi Zero W in a Vilros case. Held in place by the usb's plugged into the car. Double sided tape could also be used.

![IMG_3033](https://user-images.githubusercontent.com/51070032/64044069-d2ef5800-cb1a-11e9-87fa-6198bf9a1be4.JPG)

Feel free to delete this if not appropriate.

Thanks again!

**Comment by SemoTech** [comment]
Nice and creative @wowiejr, but you may also want to get a shorter cable :-) They are just $1-$2 on Amazon...

**Comment by wowiejr** [comment]
Oh, for sure that is on the list. But I wanted to make it useful for multiple people, thus the wire guides/wraps.

**Comment by SemoTech** [comment]
Yeah @wowiejr very creative and practical.  I actually separated the cavernous hold that is the front of the console in 2 layers.  At the bottom I have the Pi, a Zendue Pack, a Metromile plug, a HotSpot and a power distribution block, see picture [HERE](https://i.imgur.com/7obTYqs.jpg).  On top of that I installed a [full length tray](https://www.amazon.com/gp/product/B07TWHC41H/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1) that hides everything and gives me space to put my daily stuff without having to dig for it while making everything neater. I am afraid that if I had that holder I could not fit the full top tray....

**Comment by DineshCyanam** [comment]
@SemoTech: Do you have a guide on how to get additional power?

**Comment by SemoTech** [comment]
I sure do @DineshCyanam Check my Modifications for 12V Power

[HERE](https://teslamotorsclub.com/tmc/posts/3933288/) 
and 
[HERE](https://teslamotorsclub.com/tmc/posts/3974968/)

**Comment by miles267** [comment]
Is there a need for anything beyond a Pi Zero for this project if the SD card meets the spec?

**Comment by SemoTech** [comment]
> Is there a need for anything beyond a Pi Zero for this project if the SD card meets the spec?

Nope!  The Pi 0 W works great with a good microSD card.  No errors and smooth recording.
