### ISSUE TITLE
Got the Your USB Device is Not Fast Enough

### ISSUE THREAD

**Issue by DonC52** [marcone/teslausb#217]
I get the message from my Tesla saying that my USB device is not fast enough. It does not happen all the time but I have only had this running for a couple of days.

**Comment by marcone** [comment]
I don't think there's anything that can be done about that on the teslausb side. Maybe a faster sd card would help.

**Comment by DonC52** [comment]
(Sorry for the duplicate issue - new to GitHub.

I got a fast SanDisk 64GB Ultra Class 10 card. Its a camera card that full HD Video can be recorded on.
