### ISSUE TITLE
USB Device Not Fast Enough

### ISSUE THREAD

**Issue by DonC52** [marcone/teslausb#218]
I get the message from my Tesla saying that my USB device is not fast enough. It does not happen all the time but I have only had this running for a couple of days.

**Comment by marcone** [comment]
Duplicate of https://github.com/marcone/teslausb/issues/217

**Comment by DonC52** [comment]
I got a fast SanDisk 64GB Ultra Class 10 card. Its a camera card that full HD Video can be recorded on.
