### ISSUE TITLE
TeslaUSB randomly stops working, then back on

### ISSUE THREAD

**Issue by yarzy1** [marcone/teslausb#221]
I can go a few days with the TeslaUSB recording video fine and allowing me to play music via USB, then it will just go away. I need to power cycle the Pi (pull the USB plug and plug it back in) and then it shows up again and works fine. What can I do to get this to be more consistent? I have tried different ports on the USB hub as well as directly into the USB ports on the car. Same thing. Thanks!

**Comment by marcone** [comment]
Not enough information here for me to help in any way, but you could start by looking at issue https://github.com/marcone/teslausb/issues/35
