### ISSUE TITLE
How to Start Over?

### ISSUE THREAD

**Issue by dsestes** [marcone/teslausb#223]
Was up and running very reliably, and then got away fro Wifi for a few days and wound up with a ton of videos that were taking too long / filling up Google Drive. Couldn't interrupt the archive process in order to delete the videos - ended up breaking the system. Have tried to re-run setup but rclone archiving isn't working, though not generating an error message. 

Easy way to just wipe the slate clean and start over?

**Comment by marcone** [comment]
re-flashing the card with the latest prebuilt is the easiest.
