### ISSUE TITLE
Use Raspberry's mirror redirection system

### ISSUE THREAD

**Issue by skyred** [marcone/teslausb#226]
Not sure if this request should be made upstream, but the end goal is to use http://mirrordirector.raspbian.org/ to replace http://archive.raspbian.org/ in the `/etc/apt/sources.list` and to the folder `/etc/apt/sources.list.d`

Raspbian Mirrors doc: https://www.raspbian.org/RaspbianMirrors

**Comment by marcone** [comment]
Not sure if you mean upstream teslausb or upstream raspbian, but the upstream teslausb is basically abandoned.
I feel this is beyond the scope of teslausb though. If the Raspbian maintainers prefer people to use the mirrors, then they should put the mirror redirector in the source list by default. Maybe suggest/request it over at https://github.com/RPi-Distro/pi-gen ?
Thanks.
