### ISSUE TITLE
mounted dirs/shares don't show up with df -h

### ISSUE THREAD

**Issue by tuupos** [marcone/teslausb#233]
Hello,

Just installed the teslausb on a Rpi zero W. 
Wifi connection no problem. But I dont see my shares when I do a df -h.

In etc/fstab they are present with correct IP address to my shares (192.x.x.x/TeslaCam). I can manually mount them and then they show up. But after every reboot I have to add them manually again.

Here is an excerpt form my diagnostics.txt in /mutable (edited the IP adres for posting purposes):

LABEL=backingfiles /backingfiles xfs auto,rw,noatime 0 2
LABEL=mutable /mutable ext4 auto,rw 0 2
/backingfiles/cam_disk.bin /mnt/cam vfat utf8,noauto,users,umask=000,offset=1048576 0 0
/backingfiles/music_disk.bin /mnt/music vfat utf8,noauto,users,umask=000,offset=1048576 0 0
//192.168.XXX.XX/TeslaCam /mnt/archive cifs credentials=/root/.teslaCamArchiveCredentials,iocharset=utf8,file_mode=0777,dir_mode=0777,, 0
//192.168.XXX.XXX/TeslaMusic /mnt/musicarchive cifs credentials=/root/.teslaCamArchiveCredentials,iocharset=utf8,file_mode=0777,dir_mode=0777,, 0
tmpfs /var/run/samba tmpfs nodev,nosuid 0 0
-----------------------------------------------------------------------------------

Here is my df -h output:

Filesystem      Size  Used Avail Use% Mounted on
/dev/root       1.6G  1.3G  216M  86% /
devtmpfs        213M     0  213M   0% /dev
tmpfs           217M     0  217M   0% /dev/shm
tmpfs           217M  5.9M  211M   3% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           217M     0  217M   0% /sys/fs/cgroup
tmpfs           217M   20K  217M   1% /var/log
tmpfs           217M     0  217M   0% /mnt/smbexport
tmpfs           217M   24K  217M   1% /tmp
tmpfs           217M  176K  217M   1% /run/samba
tmpfs           217M     0  217M   0% /var/tmp
tmpfs           217M  420K  216M   1% /var/cache/samba
/dev/mmcblk0p1   44M   23M   22M  52% /boot
/dev/mmcblk0p4   94M  3.8M   83M   5% /mutable
/dev/mmcblk0p3   58G   52G  6.0G  90% /backingfiles
/dev/loop0p1     41G   64K   41G   1% /backingfiles/snapshots/snap-000000/mnt
tmpfs            44M     0   44M   0% /run/user/1000

Fun part is that de raspberry pi is reading the music files in the shares map because so says the log in my synology NAS.... It read them all but the shares don't show up.... Anyone an idea how to get the shares up and running?  What is the snapshots all about?

thanks

**Comment by marcone** [comment]
Working as intended. They are mounted and unmounted as needed, instead of keeping them permanently mounted.
