### ISSUE TITLE
Fork is behind

### ISSUE THREAD

**Issue by DonC52** [marcone/teslausb#241]
Looking at my fork of your repository I see the following...
This branch is 2 commits ahead, 3 commits behind marcone:main-dev.

I tried to do the fork sync thing shown in help but got merge issues and the project went to the MERGING status in GIT BASH.  It seems that with us both changing stuff to the README.md it is in conflict. Is there an easy way to just resolve the issue by getting the file again? My local file is attached if it would help. Reading the help for merge conflicts is kinda worded strange. Maybe your interpretation will help.

[README.zip](https://github.com/marcone/teslausb/files/3586260/README.zip)

**Comment by marcone** [comment]
Sorry, I'm not a git/github expert, but I think that once it's in the "merging" state you need to resolve the conflict (by editing the conflicting file), then "git add" / "git commit" the result.
