### ISSUE TITLE
Bug in tesla_api.py assumes teslausb_setup_variable.conf always exists in /root

### ISSUE THREAD

**Issue by kdvlr** [marcone/teslausb#246]
in line 507 of tesla_api.py, it has  ```with open('/root/teslausb_setup_variables.conf', 'r') as conf_file:```  , however if you  use the manual setup (like I am doing for pi4), it seems the file remains in /boot. I created softlink for that, but not sure if this needs to be fixed.

**Comment by marcone** [comment]
How do you do the manual setup? Don't you still run setup-teslausb?

**Comment by marcone** [comment]
Oh I see, if you're not using the prebuilt image's rc.local, then the file doesn't get moved.
Pull request welcome, though one could argue that if you do manual setup, you should move the file manually too.
