### ISSUE TITLE
rawgithubusercontent.com certificate errors

### ISSUE THREAD

**Issue by mf-pa-26** [marcone/teslausb#247]
Hi, I'm seeing errors in setup due the invalid cert on this domain. Is teslausb still safe?

Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.60.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.60.133|:443... connected.
ERROR: The certificate of ‘raw.githubusercontent.com’ is not trusted.
ERROR: The certificate of ‘raw.githubusercontent.com’ is not yet activated.
The certificate has not yet been activated

**Comment by marcone** [comment]
> ERROR: The certificate of ‘raw.githubusercontent.com’ is not yet activated.
> The certificate has not yet been activated

This means the Pi didn't set the time/date.

**Comment by marcone** [comment]
You can probably find more info in the diagnostics, as described in  https://github.com/marcone/teslausb/issues/35
