### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by GCustom** [marcone/teslausb#255]
Would like to be able to use a USB drive to mount the emulated storage instead of the SD card. (probably more of a pi 4 thing with the extra ports) have the SD card only run this project and the OS, have an option to make it store the videos and music on a large hard drive or SSD

**Comment by marcone** [comment]
This is only possible with the Pi4, and already being discussed in issue https://github.com/marcone/teslausb/issues/240

**Comment by GCustom** [comment]
Thank you, I have now subscribed to that thread
