### ISSUE TITLE
rsync assumes port 22

### ISSUE THREAD

**Issue by fat-tire** [marcone/teslausb#257]
To support any port in the rsync in archive-clips.sh --

add:

     -e 'ssh -p <port-number>'

to the rsync command, ie:

     num_files_moved=$(rsync -auvh -e 'ssh -p 2222' --timeout=60 ...

this can be set up in `.teslaCamRsyncConfig` and default to port 22 if unspecified.

**Comment by marcone** [comment]
This seems like a bit of a niche feature, but pull request welcome.
