### ISSUE TITLE
successfully installed, no usb shares visible

### ISSUE THREAD

**Issue by tabsl** [marcone/teslausb#259]
- installed successfully imho
- led blinks to times (wifi connected i read)
- no usb shares visible (tesla/mac/win)

thanks for help ...

[diagnose.txt](https://github.com/marcone/teslausb/files/3613550/diagnose.txt)

**Comment by marcone** [comment]
The diagnostics show it is configured correctly and the drives are exported.
If you're not seeing them on an attached car or computer, the usual cause is using a charge-only USB cable, or using the power port instead of the USB port on the Pi.

**Comment by tabsl** [comment]
i thought i´m using a data after :-( after some tests with other ones, no it´s working. ;-)
