### ISSUE TITLE
setup-teslausb fails due to not enough free space, using a 128GB microSD

### ISSUE THREAD

**Issue by cpbl** [marcone/teslausb#262]
I have followed instructions carefully, and at the setup-teslausb stage, apt installs failed with "not enough space", even though I have a 128 GB SD card! 
The SD card seemed mostly dedicated to two .bin files in  /backingfiles, with only about 5GB for the root (/) partition. 

I deleted one of the .bin files in /backingfiles and then used 

```
mv /var/cache/apt /backingfiles/
ln -s /backingfiles/apt /var/cache/apt

```
to get it to continue, but it later ran out of space again on /.

**Comment by marcone** [comment]
[diagnostics or it didn't happen](https://github.com/marcone/teslausb/issues/35)
