### ISSUE TITLE
Drive not mounting properly at boot

### ISSUE THREAD

**Issue by Nicer82** [marcone/teslausb#272]
Used the pre-built image to configure a Pi Zero W with an 128 GB SD card to use on my 2018 Tesla Model S.

Initial problem I had is that the Pi is not getting enough voltage from a single USB port, which results into an endless reboot cycle. I fixed this by connecting both USB ports of the Pi to both USB ports in the front of the model S. 

The problem I have now is that the drive doesn't get mounted in the Tesla (DashCam icon doesn't show up) every time it needed to boot (when the car was not in Sentry mode and it went to sleep, cutting the power on the USB ports). The workaround I have is, after the Pi booted up, to unplug the data-usb port of the pi and insert it again after a few seconds, this way the dashcam icon shows up and everything works perfectly. The Pi doesn't reboot this way because it still gets power from the other USB port.

Anyone else experiencing this with model S/X? I am running 2019.32.2.1 in the Tesla. Also still have the old Tegra-based MCU in the car.

**Comment by marcone** [comment]
https://github.com/marcone/teslausb/issues/35

**Comment by Nicer82** [comment]
@marcone I did, all I can see is: 'if you are using a separate power source (battery, 12V adapter, OBD2 adapter), ensure that the cable connected to the Pi's USB port is a data-only cable, and does not provide power.' but if I do that, the pi will go into the reboot cycle again. maybe an idea to clarify in the troubleshoot how to fix this one?

**Comment by marcone** [comment]
https://github.com/marcone/teslausb/issues/35 also mentions providing diagnostics, which you didn't do.
In any case, from your description this seems more like a car problem, possibly because it's an older MCU. Have you tried putting a USB hub between the car and the Pi? That seems to help for some people.

**Comment by Nicer82** [comment]
Will try the hub, if that doesnt work, I will submit diagnostics. Thx for the help.

**Comment by Nicer82** [comment]
Just to confirm: the USB hub (unpowered) fixed the issue, I can now connect the Pi using one USB port without getting into the endless reboot loop and after boot the device is mounted properly now. Thx for the support!
