### ISSUE TITLE
Out of Space Errors

### ISSUE THREAD

**Issue by raushel** [marcone/teslausb#276]
If I leave my car at the airport for a few days with sentry mode enabled (100+ events), I notice that I can no longer run setup-teslausb and /dev/root has no free space. I'm going to need to reflash for v10 shortly, but wanted to see if there was anything else to prevent this going forward. Using camsize=100% if it makes a difference on a 128GB SD card.

![image](https://user-images.githubusercontent.com/49056263/65806371-d512f980-e14e-11e9-8db0-ef82ee832ae1.png)

./setup-teslausb as it throws no space left on device errors:

![image](https://user-images.githubusercontent.com/49056263/65806338-b3b20d80-e14e-11e9-8c8d-78eac37bb38e.png)

Diagnostics:
[diagnostics.txt](https://github.com/marcone/teslausb/files/3664749/diagnostics.txt)

**Comment by marcone** [comment]
That's very strange, because the root partition is normally read-only, and so it can't fill up.
Did you remount it read-write to install some new software or something, and then forget to reboot afterwards?

**Comment by raushel** [comment]
Unlikely, but certainly possible—always run halt after running updates to teslausb.

Had it happen on two different travel weeks, but re-flashed to fix between them.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by marcone** [comment]
Nothing actionable here
