### ISSUE TITLE
USB Write Speed too slow error

### ISSUE THREAD

**Issue by ice2032** [marcone/teslausb#288]
I'm getting this error after about an hour or so.  If I unplug the Pi and plug back in, it will work for another short trip and then go back to the same error.  The SD card I'm using is a high quality, Class 10 Samsung endurance model so I'm 100% certain it's more than capable of the write speeds required.

**Comment by miles267** [comment]
This degradation in write speeds on high perf SD cards seems to be a recurring theme. Planning to do a new build today on a Sandisk Extreme Pro ultra high speed card with the latest buster code, unless I should just hold off until this is addressed first.

**Comment by marcone** [comment]
https://github.com/marcone/teslausb/issues/239
