### ISSUE TITLE
Save SentryClips in separate folder in archive

### ISSUE THREAD

**Issue by RichieB2B** [marcone/teslausb#295]
Now that Tesla makes a distinction between SavedClips and SentryClips on de SD card (see #260) it would be nice to also store the clips in those separate folders in the archive.

**Comment by prathiraj** [comment]
https://github.com/marcone/teslausb/pull/284 for this feature is merged but only for CIFS archive. If you're using CIFS, please update as per https://github.com/marcone/teslausb/wiki

**Comment by marcone** [comment]
Ir was also added for rsync and rclone.
