### ISSUE TITLE
music sync CIFS / Not all coming across

### ISSUE THREAD

**Issue by XmemphistoX** [marcone/teslausb#30]
I'm trying to sync my music over and its semi working.  Out of 100 songs, its only syncing across around 30.  Tried restarting the PI to start sync again and it says its finished copying even though it's not 1:1 synched.

Fri 17 May 20:02:50 BST 2019: Finished fsck on /mnt/music.
Fri 17 May 20:02:50 BST 2019: Copying music from  archive...
Fri 17 May 20:03:08 BST 2019: Unmounting /mnt/music...
Fri 17 May 20:03:09 BST 2019: Unmounted /mnt/music.
Fri 17 May 20:03:09 BST 2019: Finished copying music.

**Comment by marcone** [comment]
I suspect it encountered an error while copying, and then silently failed.
Try running `/root/bin/copy-music.sh` manually to see what goes wrong.

**Comment by XmemphistoX** [comment]
Getting this spammed. 

cp: cannot create regular file '/mnt/music/./tmp': Read-only file system
mv: cannot stat '/mnt/music/./tmp': No such file or directory
cp: cannot create regular file '/mnt/music/./tmp': Read-only file system
mv: cannot stat '/mnt/music/./tmp': No such file or directory
cp: cannot create regular file '/mnt/music/./tmp': Read-only file system
mv: cannot stat '/mnt/music/./tmp': No such file or directory
cp: cannot create regular file '/mnt/music/./tmp': Read-only file system
mv: cannot stat '/mnt/music/./tmp': No such file or directory
cp: cannot create regular file '/mnt/music/./tmp': Read-only file system
mv: cannot stat '/mnt/music/./tmp': No such file or directory
cp: cannot create regular file '/mnt/music/./tmp': Read-only file system
mv: cannot stat '/mnt/music/./tmp': No such file or directory
cp: cannot create regular file '/mnt/music/./tmp': Read-only file system
mv: cannot stat '/mnt/music/./tmp': No such file or directory
cp: cannot create regular file '/mnt/music/./tmp': Read-only file system
mv: cannot stat '/mnt/music/./tmp': No such file or directory
cp: cannot create regular file '/mnt/music/./tmp': Read-only file system
mv: cannot stat '/mnt/music/./tmp': No such file or directory
cp: cannot create regular file '/mnt/music/./tmp': Read-only file system
mv: cannot stat '/mnt/music/./tmp': No such file or directory
cp: cannot create regular file '/mnt/music/./tmp': Read-only file system
mv: cannot stat '/mnt/music/./tmp': No such file or directory

**Comment by XmemphistoX** [comment]
Getting this spammed.

cp: cannot create regular file '/mnt/music/./tmp': Read-only file system
mv: cannot stat '/mnt/music/./tmp': No such file or directory
cp: cannot create regular file '/mnt/music/./tmp': Read-only file system
mv: cannot stat '/mnt/music/./tmp': No such file or directory
cp: cannot create regular file '/mnt/music/./tmp': Read-only file system
mv: cannot stat '/mnt/music/./tmp': No such file or directory
cp: cannot create regular file '/mnt/music/./tmp': Read-only file system
mv: cannot stat '/mnt/music/./tmp': No such file or directory
cp: cannot create regular file '/mnt/music/./tmp': Read-only file system
mv: cannot stat '/mnt/music/./tmp': No such file or directory
cp: cannot create regular file '/mnt/music/./tmp': Read-only file system
mv: cannot stat '/mnt/music/./tmp': No such file or directory
cp: cannot create regular file '/mnt/music/./tmp': Read-only file system
mv: cannot stat '/mnt/music/./tmp': No such file or directory
cp: cannot create regular file '/mnt/music/./tmp': Read-only file system
mv: cannot stat '/mnt/music/./tmp': No such file or directory
cp: cannot create regular file '/mnt/music/./tmp': Read-only file system
mv: cannot stat '/mnt/music/./tmp': No such file or directory
cp: cannot create regular file '/mnt/music/./tmp': Read-only file system
mv: cannot stat '/mnt/music/./tmp': No such file or directory
cp: cannot create regular file '/mnt/music/./tmp': Read-only file system
mv: cannot stat '/mnt/music/./tmp': No such file or directory

**Comment by marcone** [comment]
So either the music drive is not mounted, or something went wrong with the underlying filesystem.
What do `df`, `mount` and `dmesg` say?

**Comment by XmemphistoX** [comment]
pi@teslausb:~ $ df
Filesystem                   1K-blocks       Used  Available Use% Mounted on
/dev/root                      1668536    1072972     492756  69% /
devtmpfs                        217244          0     217244   0% /dev
tmpfs                           221568          0     221568   0% /dev/shm
tmpfs                           221568       5968     215600   3% /run
tmpfs                             5120          4       5116   1% /run/lock
tmpfs                           221568          0     221568   0% /sys/fs/cgroup
tmpfs                           221568         12     221556   1% /tmp
tmpfs                           221568         12     221556   1% /var/log
tmpfs                           221568          0     221568   0% /var/tmp
/dev/mmcblk0p1                   44529      22696      21834  51% /boot
/dev/mmcblk0p3                59421620   55324860    1048568  99% /backingfiles
/dev/mmcblk0p4                   96052       1671      87142   2% /mutable
//192.168.1.117/TeslaVideos 5860520956 1524687316 4335833640  27% /mnt/archive
//192.168.1.117/TeslaMusic  5860520956 1524687940 4335833016  27% /mnt/musicarchive
/dev/loop0                    11042480    6956664    4085816  63% /mnt/music
tmpfs                            44312          0      44312   0% /run/user/1000

**Comment by XmemphistoX** [comment]
pi@teslausb:~ $ mount
/dev/mmcblk0p2 on / type ext4 (ro,noatime)
devtmpfs on /dev type devtmpfs (rw,relatime,size=217244k,nr_inodes=54311,mode=755)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,mode=755)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=31,pgrp=1,timeout=0,minproto=5,maxproto=5,direct)
sunrpc on /run/rpc_pipefs type rpc_pipefs (rw,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
mqueue on /dev/mqueue type mqueue (rw,relatime)
configfs on /sys/kernel/config type configfs (rw,relatime)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,relatime)
tmpfs on /var/log type tmpfs (rw,nosuid,nodev,relatime)
tmpfs on /var/tmp type tmpfs (rw,nosuid,nodev,relatime)
/dev/mmcblk0p1 on /boot type vfat (ro,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,errors=remount-ro)
/dev/mmcblk0p3 on /backingfiles type ext4 (rw,noatime)
/dev/mmcblk0p4 on /mutable type ext4 (rw,relatime)
//192.168.1.117/TeslaVideos on /mnt/archive type cifs (rw,relatime,vers=3.0,cache=strict,username=hai,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.1.117,file_mode=0777,dir_mode=0777,soft,nounix,serverino,mapposix,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)
//192.168.1.117/TeslaMusic on /mnt/musicarchive type cifs (rw,relatime,vers=3.0,cache=strict,username=xxx,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.1.117,file_mode=0777,dir_mode=0777,soft,nounix,serverino,mapposix,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=44312k,mode=700,uid=1000,gid=1000)

**Comment by XmemphistoX** [comment]
pi@teslausb:~ $ dmesg
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 4.19.37+ (dom@dom-XPS-13-9370) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611)) #1216 Thu May 2 13:25:42 BST 2019
[    0.000000] CPU: ARMv6-compatible processor [410fb767] revision 7 (ARMv7), cr=00c5387d
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT nonaliasing instruction cache
[    0.000000] OF: fdt: Machine model: Raspberry Pi Zero W Rev 1.1
[    0.000000] Memory policy: Data cache writeback
[    0.000000] cma: Reserved 8 MiB at 0x1b400000
[    0.000000] On node 0 totalpages: 114688
[    0.000000]   Normal zone: 1008 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 114688 pages, LIFO batch:31
[    0.000000] random: get_random_bytes called from start_kernel+0x8c/0x49c with crng_init=0
[    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
[    0.000000] pcpu-alloc: [0] 0 
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 113680
[    0.000000] Kernel command line: 8250.nr_uarts=0 bcm2708_fb.fbwidth=656 bcm2708_fb.fbheight=416 bcm2708_fb.fbswap=1 smsc95xx.macaddr=B8:27:EB:5D:3D:27 vc_mem.mem_base=0x1ec00000 vc_mem.mem_size=0x20000000  dwc_otg.lpm_enable=0 console=ttyS0,115200 console=tty1 root=PARTUUID=f06e2317-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait modules-load=dwc2 quiet fastboot noswap ro
[    0.000000] Dentry cache hash table entries: 65536 (order: 6, 262144 bytes)
[    0.000000] Inode-cache hash table entries: 32768 (order: 5, 131072 bytes)
[    0.000000] Memory: 434492K/458752K available (6931K kernel code, 633K rwdata, 2068K rodata, 456K init, 797K bss, 16068K reserved, 8192K cma-reserved)
[    0.000000] Virtual kernel memory layout:
                   vector  : 0xffff0000 - 0xffff1000   (   4 kB)
                   fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
                   vmalloc : 0xdc800000 - 0xff800000   ( 560 MB)
                   lowmem  : 0xc0000000 - 0xdc000000   ( 448 MB)
                   modules : 0xbf000000 - 0xc0000000   (  16 MB)
                     .text : 0x(ptrval) - 0x(ptrval)   (6933 kB)
                     .init : 0x(ptrval) - 0x(ptrval)   ( 456 kB)
                     .data : 0x(ptrval) - 0x(ptrval)   ( 634 kB)
                      .bss : 0x(ptrval) - 0x(ptrval)   ( 798 kB)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] ftrace: allocating 25040 entries in 74 pages
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000029] sched_clock: 32 bits at 1000kHz, resolution 1000ns, wraps every 2147483647500ns
[    0.000074] clocksource: timer: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 1911260446275 ns
[    0.000173] bcm2835: system timer (irq = 27)
[    0.000761] Console: colour dummy device 80x30
[    0.000789] console [tty1] enabled
[    0.000853] Calibrating delay loop... 697.95 BogoMIPS (lpj=3489792)
[    0.060333] pid_max: default: 32768 minimum: 301
[    0.060872] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.060893] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.062297] CPU: Testing write buffer coherency: ok
[    0.063605] Setting up static identity map for 0x8200 - 0x8238
[    0.064989] devtmpfs: initialized
[    0.076243] VFP support v0.3: implementor 41 architecture 1 part 20 variant b rev 5
[    0.076647] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.076677] futex hash table entries: 256 (order: -1, 3072 bytes)
[    0.078016] pinctrl core: initialized pinctrl subsystem
[    0.079585] NET: Registered protocol family 16
[    0.082289] DMA: preallocated 256 KiB pool for atomic coherent allocations
[    0.089927] hw-breakpoint: found 6 breakpoint and 1 watchpoint registers.
[    0.089944] hw-breakpoint: maximum watchpoint size is 4 bytes.
[    0.090094] Serial: AMBA PL011 UART driver
[    0.093752] bcm2835-mbox 2000b880.mailbox: mailbox enabled
[    0.138341] bcm2835-dma 20007000.dma: DMA legacy API manager at (ptrval), dmachans=0x1
[    0.140890] SCSI subsystem initialized
[    0.141341] usbcore: registered new interface driver usbfs
[    0.141450] usbcore: registered new interface driver hub
[    0.141629] usbcore: registered new device driver usb
[    0.161141] raspberrypi-firmware soc:firmware: Attached to firmware from 2019-03-27 15:45, variant start
[    0.171162] raspberrypi-firmware soc:firmware: Firmware hash is 2e98b31d18547962e564bdf88e57b3df7085c29b
[    0.183665] clocksource: Switched to clocksource timer
[    0.286829] VFS: Disk quotas dquot_6.6.0
[    0.286956] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    0.287272] FS-Cache: Loaded
[    0.287629] CacheFiles: Loaded
[    0.306580] NET: Registered protocol family 2
[    0.307906] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 4096 bytes)
[    0.307973] TCP established hash table entries: 4096 (order: 2, 16384 bytes)
[    0.308054] TCP bind hash table entries: 4096 (order: 2, 16384 bytes)
[    0.308148] TCP: Hash tables configured (established 4096 bind 4096)
[    0.308320] UDP hash table entries: 256 (order: 0, 4096 bytes)
[    0.308354] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    0.308755] NET: Registered protocol family 1
[    0.309839] RPC: Registered named UNIX socket transport module.
[    0.309852] RPC: Registered udp transport module.
[    0.309858] RPC: Registered tcp transport module.
[    0.309864] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.312100] hw perfevents: no irqs for PMU, sampling events not supported
[    0.312165] hw perfevents: enabled with armv6_1176 PMU driver, 3 counters available
[    0.316515] Initialise system trusted keyrings
[    0.316934] workingset: timestamp_bits=14 max_order=17 bucket_order=3
[    0.332554] FS-Cache: Netfs 'nfs' registered for caching
[    0.334005] NFS: Registering the id_resolver key type
[    0.334056] Key type id_resolver registered
[    0.334065] Key type id_legacy registered
[    0.334092] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[    0.339666] Key type asymmetric registered
[    0.339684] Asymmetric key parser 'x509' registered
[    0.339795] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 250)
[    0.340244] io scheduler noop registered
[    0.340259] io scheduler deadline registered (default)
[    0.340888] io scheduler cfq registered
[    0.340905] io scheduler mq-deadline registered (default)
[    0.340913] io scheduler kyber registered
[    0.343980] BCM2708FB: allocated DMA memory 0x5b440000
[    0.344042] BCM2708FB: allocated DMA channel 0
[    0.354470] Console: switching to colour frame buffer device 82x26
[    0.362678] bcm2835-rng 20104000.rng: hwrng registered
[    0.362956] vc-mem: phys_addr:0x00000000 mem_base=0x1ec00000 mem_size:0x20000000(512 MiB)
[    0.364312] vc-sm: Videocore shared memory driver
[    0.364987] gpiomem-bcm2835 20200000.gpiomem: Initialised: Registers at 0x20200000
[    0.386464] brd: module loaded
[    0.400146] loop: module loaded
[    0.400169] Loading iSCSI transport class v2.0-870.
[    0.401149] usbcore: registered new interface driver smsc95xx
[    0.401183] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    0.401383] dwc_otg: FIQ enabled
[    0.401392] dwc_otg: NAK holdoff enabled
[    0.401399] dwc_otg: FIQ split-transaction FSM enabled
[    0.401431] Module dwc_common_port init
[    0.401881] usbcore: registered new interface driver usb-storage
[    0.402322] mousedev: PS/2 mouse device common for all mice
[    0.403909] bcm2835-wdt 20100000.watchdog: Broadcom BCM2835 watchdog timer
[    0.404495] bcm2835-cpufreq: min=700000 max=1000000
[    0.405286] sdhci: Secure Digital Host Controller Interface driver
[    0.405299] sdhci: Copyright(c) Pierre Ossman
[    0.405942] mmc-bcm2835 20300000.mmc: could not get clk, deferring probe
[    0.406660] sdhost-bcm2835 20202000.mmc: could not get clk, deferring probe
[    0.406860] sdhci-pltfm: SDHCI platform and OF driver helper
[    0.407514] ledtrig-cpu: registered to indicate activity on CPUs
[    0.407656] hidraw: raw HID events driver (C) Jiri Kosina
[    0.407915] usbcore: registered new interface driver usbhid
[    0.407924] usbhid: USB HID core driver
[    0.409030] vchiq: vchiq_init_state: slot_zero = (ptrval), is_master = 0
[    0.411178] [vc_sm_connected_init]: start
[    0.420750] [vc_sm_connected_init]: end - returning 0
[    0.422480] Initializing XFRM netlink socket
[    0.422554] NET: Registered protocol family 17
[    0.422732] Key type dns_resolver registered
[    0.424923] registered taskstats version 1
[    0.424957] Loading compiled-in X.509 certificates
[    0.435746] uart-pl011 20201000.serial: cts_event_workaround enabled
[    0.435884] 20201000.serial: ttyAMA0 at MMIO 0x20201000 (irq = 81, base_baud = 0) is a PL011 rev2
[    0.438769] mmc-bcm2835 20300000.mmc: mmc_debug:0 mmc_debug2:0
[    0.438790] mmc-bcm2835 20300000.mmc: DMA channel allocated
[    0.466546] sdhost: log_buf @ (ptrval) (5b450000)
[    0.502284] mmc1: queuing unknown CIS tuple 0x80 (2 bytes)
[    0.504035] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    0.505766] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    0.508844] mmc1: queuing unknown CIS tuple 0x80 (7 bytes)
[    0.514389] mmc0: sdhost-bcm2835 loaded - DMA enabled (>1)
[    0.516088] of_cfs_init
[    0.516240] of_cfs_init: OK
[    0.517339] Waiting for root device PARTUUID=f06e2317-02...
[    0.542697] random: fast init done
[    0.577434] mmc0: host does not support reading read-only switch, assuming write-enable
[    0.580069] mmc0: new high speed SDXC card at address 0001
[    0.582321] mmcblk0: mmc0:0001 JC2RT 59.6 GiB
[    0.585581]  mmcblk0: p1 p2 p3 p4
[    0.617857] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[    0.617955] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
[    0.629142] devtmpfs: mounted
[    0.634567] Freeing unused kernel memory: 456K
[    0.634582] This architecture does not have kernel memory protection.
[    0.634590] Run /sbin/init as init process
[    0.647950] mmc1: new high speed SDIO card at address 0001
[    1.155670] systemd[1]: System time before build time, advancing clock.
[    1.313390] NET: Registered protocol family 10
[    1.315610] Segment Routing with IPv6
[    1.364046] random: systemd: uninitialized urandom read (16 bytes read)
[    1.374506] systemd[1]: systemd 232 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
[    1.375567] systemd[1]: Detected architecture arm.
[    1.377204] systemd[1]: Set hostname to <teslausb>.
[    1.428616] random: systemd: uninitialized urandom read (16 bytes read)
[    1.672470] random: systemd-cryptse: uninitialized urandom read (16 bytes read)
[    2.467883] systemd[1]: Listening on Journal Socket.
[    2.496768] systemd[1]: Listening on fsck to fsckd communication Socket.
[    2.497598] systemd[1]: Listening on Journal Socket (/dev/log).
[    2.498452] systemd[1]: Listening on /dev/initctl Compatibility Named Pipe.
[    2.500605] systemd[1]: Set up automount Arbitrary Executable File Formats File System Automount Point.
[    2.501422] systemd[1]: Listening on udev Kernel Socket.
[    2.503270] systemd[1]: Created slice User and Session Slice.
[    3.291423] dwc2 20980000.usb: 20980000.usb supply vusb_d not found, using dummy regulator
[    3.291627] dwc2 20980000.usb: Linked as a consumer to regulator.0
[    3.291657] dwc2 20980000.usb: 20980000.usb supply vusb_a not found, using dummy regulator
[    3.503952] dwc2 20980000.usb: dwc2_check_params: Invalid parameter lpm=1
[    3.503977] dwc2 20980000.usb: dwc2_check_params: Invalid parameter lpm_clock_gating=1
[    3.503990] dwc2 20980000.usb: dwc2_check_params: Invalid parameter besl=1
[    3.504001] dwc2 20980000.usb: dwc2_check_params: Invalid parameter hird_threshold_en=1
[    3.504068] dwc2 20980000.usb: EPs: 8, dedicated fifos, 4080 entries in SPRAM
[    3.505447] dwc2 20980000.usb: DWC OTG Controller
[    3.505517] dwc2 20980000.usb: new USB bus registered, assigned bus number 1
[    3.505601] dwc2 20980000.usb: irq 33, io mem 0x20980000
[    3.506059] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 4.19
[    3.506079] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    3.506091] usb usb1: Product: DWC OTG Controller
[    3.506102] usb usb1: Manufacturer: Linux 4.19.37+ dwc2_hsotg
[    3.506112] usb usb1: SerialNumber: 20980000.usb
[    3.507332] hub 1-0:1.0: USB hub found
[    3.507444] hub 1-0:1.0: 1 port detected
[    4.713624] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[    6.720134] systemd-journald[73]: Received request to flush runtime journal from PID 1
[    8.083507] vc_sm_cma: module is from the staging directory, the quality is unknown, you have been warned.
[    8.087047] bcm2835_vc_sm_cma_probe: Videocore shared memory driver
[    8.087071] [vc_sm_connected_init]: start
[    8.099208] media: Linux media interface: v0.10
[    8.102598] [vc_sm_connected_init]: installed successfully
[    8.203757] videodev: Linux video capture interface: v2.00
[    8.384016] bcm2835_mmal_vchiq: module is from the staging directory, the quality is unknown, you have been warned.
[    8.389483] bcm2835_mmal_vchiq: module is from the staging directory, the quality is unknown, you have been warned.
[    8.404745] bcm2835_v4l2: module is from the staging directory, the quality is unknown, you have been warned.
[    8.466463] bcm2835_codec: module is from the staging directory, the quality is unknown, you have been warned.
[    8.895882] snd_bcm2835: module is from the staging directory, the quality is unknown, you have been warned.
[    8.954020] bcm2835_audio soc:audio: card created with 8 channels
[    9.092788] bcm2835-codec bcm2835-codec: Device registered as /dev/video10
[    9.092810] bcm2835-codec bcm2835-codec: Loaded V4L2 decode
[    9.107339] bcm2835-codec bcm2835-codec: Device registered as /dev/video11
[    9.107361] bcm2835-codec bcm2835-codec: Loaded V4L2 encode
[    9.137406] bcm2835-codec bcm2835-codec: Device registered as /dev/video12
[    9.137428] bcm2835-codec bcm2835-codec: Loaded V4L2 isp
[    9.555604] cfg80211: Loading compiled-in X.509 certificates for regulatory database
[    9.799030] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
[   10.190395] EXT4-fs (mmcblk0p3): recovery complete
[   10.197160] EXT4-fs (mmcblk0p3): mounted filesystem with ordered data mode. Opts: (null)
[   10.270817] EXT4-fs (mmcblk0p4): recovery complete
[   10.272719] EXT4-fs (mmcblk0p4): mounted filesystem with ordered data mode. Opts: (null)
[   10.724140] brcmfmac: F1 signature read @0x18000000=0x1541a9a6
[   10.761954] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1
[   10.762393] usbcore: registered new interface driver brcmfmac
[   11.245621] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1
[   11.245820] brcmfmac: brcmf_c_process_clm_blob: no clm_blob available (err=-2), device may have limited channels available
[   11.246988] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM43430/1 wl0: Oct 23 2017 03:55:53 version 7.45.98.38 (r674442 CY) FWID 01-e58d219f
[   13.912648] uart-pl011 20201000.serial: no DMA platform data
[   16.641221] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   16.641279] brcmfmac: power management disabled
[   18.158174] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[   18.483994] Bluetooth: Core ver 2.22
[   18.484221] NET: Registered protocol family 31
[   18.484234] Bluetooth: HCI device and connection manager initialized
[   18.484266] Bluetooth: HCI socket layer initialized
[   18.484286] Bluetooth: L2CAP socket layer initialized
[   18.484363] Bluetooth: SCO socket layer initialized
[   18.513239] Bluetooth: HCI UART driver ver 2.3
[   18.513262] Bluetooth: HCI UART protocol H4 registered
[   18.524039] Bluetooth: HCI UART protocol Three-wire (H5) registered
[   18.524487] Bluetooth: HCI UART protocol Broadcom registered
[   19.143874] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   19.143893] Bluetooth: BNEP filters: protocol multicast
[   19.143929] Bluetooth: BNEP socket layer initialized
[   22.864766] FS-Cache: Netfs 'cifs' registered for caching
[   22.865792] Key type cifs.spnego registered
[   22.865823] Key type cifs.idmap registered
[   22.936474] CIFS VFS: Error connecting to socket. Aborting operation.
[   22.936506] CIFS VFS: cifs_mount failed w/return code = -101
[   22.955057] CIFS VFS: Error connecting to socket. Aborting operation.
[   22.955089] CIFS VFS: cifs_mount failed w/return code = -101
[   23.979676] random: crng init done
[   23.979704] random: 7 urandom warning(s) missed due to ratelimiting
[   30.692604] Mass Storage Function, version: 2009/09/11
[   30.692624] LUN: removable file: (no medium)
[   30.692796] LUN: removable file: /backingfiles/music_disk.bin
[   30.692887] LUN: removable file: /backingfiles/cam_disk.bin
[   30.692896] Number of LUNs=2
[   30.704018] g_mass_storage gadget: Mass Storage Gadget, version: 2009/09/11
[   30.704036] g_mass_storage gadget: g_mass_storage ready
[   30.704052] dwc2 20980000.usb: bound driver g_mass_storage
[   30.911016] dwc2 20980000.usb: new device is high-speed
[   31.019110] dwc2 20980000.usb: new address 32
[   32.454417] g_mass_storage gadget: high-speed config #1: Linux File-Backed Storage
[  102.647958] Mass Storage Function, version: 2009/09/11
[  102.647978] LUN: removable file: (no medium)
[  102.648136] LUN: removable file: /backingfiles/music_disk.bin
[  102.648229] LUN: removable file: /backingfiles/cam_disk.bin
[  102.648238] Number of LUNs=2
[  102.657408] g_mass_storage gadget: Mass Storage Gadget, version: 2009/09/11
[  102.657428] g_mass_storage gadget: g_mass_storage ready
[  102.657444] dwc2 20980000.usb: bound driver g_mass_storage
[  102.847736] dwc2 20980000.usb: new device is high-speed
[  102.877209] dwc2 20980000.usb: new address 33
[  103.593347] g_mass_storage gadget: high-speed config #1: Linux File-Backed Storage

**Comment by XmemphistoX** [comment]
I do see this, however i see my files mounted in /mnt/musicarchive but when I look in /mnt/music - it doesn't show anything.  However if I connect to a PC, the music folder has around a third of what /mnt/musicarchive has

[   22.936474] CIFS VFS: Error connecting to socket. Aborting operation.
[   22.936506] CIFS VFS: cifs_mount failed w/return code = -101
[   22.955057] CIFS VFS: Error connecting to socket. Aborting operation.
[   22.955089] CIFS VFS: cifs_mount failed w/return code = -101

**Comment by marcone** [comment]
The reason you're not seeing anything in /mnt/music is because the drive is not mounted on the rpi, it's exposed as a usb drive to the car/PC
What's odd though is that `df` still shows the music drive:
```
/dev/loop0 11042480 6956664 4085816 63% /mnt/music
```
but `mount` does not.
Try restarting the pi again, it should try to copy the remaining files.
If that still doesn't work, you can manually mount the music drive:
```
modprobe -r g_mass_storage     # stops exporting the usb drives
mount /mnt/music               # mounts the music drive locally on the rpi
```
then you can run `/root/bin/copy-music.sh` to copy over the music files and see any errors.

**Comment by XmemphistoX** [comment]
Got it.  Will try in a bit and report back.  Thanks for the help!

**Comment by XmemphistoX** [comment]
I went ahead and started from scratch - when its automated, it doesn't copy all the files over, just around 30-40% of them and says its finished.  However if I run copy-music.sh manually, it pops a one line error?  It's skipping this one flac file but continuing with the rest.  Im wondering if its stopping on first error when it syncs automatically but not when running manually.

I don't mind doing the sync manually if I can update it from my laptop - just an extra step.

'mv: cannot move '/mnt/music/./tmp' to a subdirectory of itself, '/mnt/music/LP.flac'

Thanks again!

**Comment by marcone** [comment]
Do you have a file and/or folder named "tmp" in the music folder you're syncing?
The copy script first copies each file to "tmp", then renames it to its final name.
I should probably have picked a name that's less likely to clash...

**Comment by XmemphistoX** [comment]
Yeah, I had a filename with a special character that i think was having issues renaming.  Leaving the TMP file behind in the folder.  Think this may be why.

Röyksopp

**Comment by marcone** [comment]
I added some better logging and error checking to the music copy script, so it will skip over problematic files, and log the problem.

**Comment by Vipercat** [comment]
I noticed that files with specific characters in it's name (e.g. "ë" in Tiësto or "é" in Céline) stops the copying of files from the share to the RPI.

**Comment by marcone** [comment]
@Vipercat looks like your setup is older (specifically, older than 15 days), since the current version of the music copying script is more error resilient, and while it may fail to copy files, it will just log the failure and continue on with the remaining files. I've verified that it in fact does so with files that contain "ë" and "é" characters.
I'll see if I can convert the filenames to something that works with a FAT filesystem.

To update your rpi to get the latest scripts, you should be able to just do:
```
sudo -i
killall archiveloop
modprobe -r g_mass_storage
/root/bin/setup-teslausb
reboot
```
