### ISSUE TITLE
Setup correctly but not seeing any recorded videos

### ISSUE THREAD

**Issue by wadewegner** [marcone/teslausb#301]
I believe I was able to setup the pi (at least reviewing the `teslausb-healess-setup.log` file everything appears to have worked properly after the 5th try`) but I'm not seeing any videos synching to my network share. When I take out the micro SD and plug into my PC, I don't see any shares with videos either. Any debug pointers?

**Comment by curiousgrge** [comment]
Unless you are mounting the partitions through some *nix flavor, you won't see the files.  Suggest you ssh into the pi to see if the files are located somewhere in /backingfiles before attempting to tackling file share issues.

**Comment by japhule** [comment]
Plug the Pi into your PC (do not remove the sd card). After a minute or two, it should detect the CAM drive with a TeslaCam folder with your footage in it. If it doesn't show then set up is not correct. If it does show, then SSH into your pi and check the archiveloop.log file found in the /mutable folder, it's possible that its not able to connect to your file share to upload data.

**Comment by davekempe** [comment]
I have a similar issue. Used the debian buster image, and I have the latest V10 software. Sentry mode says recording, but nothing appears to be recorded under the /mutable folder. I haven't tried a USB stick at all. Only other thing is my sd card is 128G, and I allocated 50G to recordings. Maybe that is too big?

**Comment by marcone** [comment]
Recordings don't go in the /mutable partition.
As noted above, plug the Pi into a computer, wait a bit, and then you should see the recording drive show up on the computer.
