### ISSUE TITLE
Not delete or check Sentry Files have transferred

### ISSUE THREAD

**Issue by simonrb2000** [marcone/teslausb#309]
Hi,

The idea behind this project is brilliant. I have used it twice and both times the car must have turned off power to USB port before it finished archiving and had lost Sentry Mode clips (as in they didn't upload).

Is there a way for TeslaUSB ensures that the all files have successfully transferred before removing them from TeslaUSB? I appreciate there are options to keep car awake however in the long term is this an option so we don't loose data?

Many Thanks

Simon

**Comment by marcone** [comment]
> Is there a way for TeslaUSB ensures that the all files have successfully transferred before removing them from TeslaUSB?

It already does this. The files aren't deleted from the recording drive until they've been archived.
However note that in v10 the car itself may delete Sentry clips if it needs space.

**Comment by simonrb2000** [comment]
This isn’t how mine behaves. Files are removed even if they are not sync’d to the shared drive. The card is a 128gb card running only TeslaUSB so space isn’t an issue. 

How does it check it’s been archived? 

Very strange..

**Comment by marcone** [comment]
What archive method do you use? (cifs/rsync/rclone)

**Comment by simonrb2000** [comment]
cifs

**Comment by marcone** [comment]
The [cifs archiving script](https://github.com/marcone/teslausb/blob/main-dev/run/cifs_archive/archive-clips.sh) works by using the `mv` (move) command to move the files from the recording drive to the destination folder on the archive server. The `mv` command only deletes the source file after successfully moving the file to the destination folder.

**Comment by simonrb2000** [comment]
Thanks marcone. If the power on the pi is cut before moving files is complete will this cause the issue I am having?

**Comment by simonrb2000** [comment]
I have just done a test at home. 6 sentry mode recordings and left Tesla login credentials and the car didn't keep it awake and all 6 sentry mode recordings lost again. Is there any logs that I can post here that would help? As it stands I can't use this as each time I have used it I have gotten home and lost all the sentry mode recordings. Cheers

**Comment by marcone** [comment]
It normally shouldn't, but loser power while writing to the card might leave it in a weird state, so possibly.

**Comment by simonrb2000** [comment]
Is it simple for me to change the mv commands in the script to cp commands just for initial testing?

**Comment by marcone** [comment]
You can certainly try that. It'll mean that the next time it archives, it'll re-archive those same files.

**Comment by simonrb2000** [comment]
Ah ok, there's no way for it to check the archive and just send over what is new? I'm using this script for a couple of blackvue cameras and does just that and its perfect. It doesn't loose any recordings at all and resumes as soon as its reconnected. Not lost a file yet 

https://dashcamtalk.com/forum/threads/blackvue-sync-a-new-portable-hands-off-automatic-recording-downloader-for-nas-or-docker.37981/
