### ISSUE TITLE
Not Uploading Files to GDrive

### ISSUE THREAD

**Issue by alexlegacy82** [marcone/teslausb#31]
I completed all steps and can connect via SSH as well as see the TeslaCam Google Drive folder created.  However, I've triggered sentry mode to see if it's uploading the video to the Gdrive but still nothing and it's been a few hours?  Any insight or information as to what's going on would be much appreciated.

**Comment by marcone** [comment]
Can't help you with the Google Drive part of this (I've never used it myself), but note that teslausb will only start backing up when it transitions from being disconnected from wifi to being connected. If you just turn on Sentry mode or hit the save button while connected to wifi, nothing's going to happen.

You can either drive out of wifi range and then come back, or simulate the process by running `touch /tmp/archive_is_unreachable`
