### ISSUE TITLE
have idea about snapshot

### ISSUE THREAD

**Issue by mikealanni** [marcone/teslausb#312]
if I understand the snapshot right, then would you replace cp with mmpeg -c copy command for at least SentryClips? this will let Tesla browser can play videos or any chrome browser, thinking to install TeslaCam browser too to play Sentry video directly from Tesla Browser

**Comment by marcone** [comment]
Snapshots don't copy the data, but using ffmpeg to rewrite the files would make a new copy of the files, resulting in a lot of I/O. So I'm not going to do that. This is something that Tesla and/or Chrome should fix.
Also, the car won't connect directly to teslausb, you'd have to have an access point inbetween that has internet access and can trick the car into thinking that the Pi is on the public internet.
