### ISSUE TITLE
Multiple wifi configs

### ISSUE THREAD

**Issue by millercentral** [marcone/teslausb#32]
Is it possible to setup multiple SSIDs to look for/connect to (ie, home wifi, and phone hotspot for on-demand syncing?)

**Comment by marcone** [comment]
I'm sure this is possible in linux/raspbian, but there's no provision for this in teslausb, and I don't have any immediate plans to add one.
You probably just have to add an entry to `/etc/wpa_supplicant/wpa_supplicant.conf`
