### ISSUE TITLE
Filesystem Mounts and Consistency Checks

### ISSUE THREAD

**Issue by abhinava** [marcone/teslausb#320]
Does the image run a consistency check on all the FAT/XFS/ext4 filesystems on startup? It seems like my Pi Zero might have gotten into some issue with either an improper power-off or something else; I see some *.REC files in the '/backingfiles' directory. I checked the /etc/fstab and I do see a "0" against some partitions (definitely the /backingfiles mount). 

I tried to manually run a fsck on the partitions through my Linux machine (plugged-in the SD Card via a card reader). I 'think' this went okay but I'm not sure (at least no data loss). Any guidelines or recommendations?

**General Question**: Is the 'create-backingfiles-partition.sh' script the one that creates all the partitions and adds mount point entries to /etc/fstab? Would be good if there is a short description on this as well as how the '/backingfiles/snapshots/snap*' is being managed.

**Comment by marcone** [comment]
>  I checked the /etc/fstab and I do see a "0" against some partitions (definitely the /backingfiles mount).

The backingfiles mount entry should look like:
```
LABEL=backingfiles /backingfiles xfs auto,rw,noatime 0 2
```
perhaps you're talking about the entries for the disk images?

> I tried to manually run a fsck on the partitions through my Linux machine (plugged-in the SD Card via a card reader). I 'think' this went okay but I'm not sure (at least no data loss). Any guidelines or recommendations?

No, this shouldn't be necessary to do manually.
 
> **General Question**: Is the 'create-backingfiles-partition.sh' script the one that creates all the partitions and adds mount point entries to /etc/fstab? Would be good if there is a short description on this as well as how the '/backingfiles/snapshots/snap*' is being managed.

There are two scripts. The one you mentioned creates the /backingfiles and /mutable partitions, while create-backingfiles.sh creates the disk images.
