### ISSUE TITLE
teslausb-buster-20190922 does not mount on 32.12.2

### ISSUE THREAD

**Issue by seattleandrew** [marcone/teslausb#321]
After the version 10 update I was unable to get TeslaUSB to work. I reflashed the rPi with teslausb-buster-20190922 and while it is powered and I can view the files on Windows 10, I cannot get the rPi to mount in my Model 3. I ensured the USB cable is a known working data cable and it is plugged into the USB port (not PWR) on the rPi. I have attached my diagnostics file.

[diagnostics.txt](https://github.com/marcone/teslausb/files/3747365/diagnostics.txt)

**Comment by marcone** [comment]
You say it works when connected to a Windows PC, but your diagnostics show that setup did not complete.
CIFS archiving was selected, but the fstab hasn't been updated (yet) to reflect that.
The archiveloop script isn't running, and that's what connects to the drives to the car/PC.
There's no way that this can work, whether connected to PC or car.
