### ISSUE TITLE
How the h*** to delete files?

### ISSUE THREAD

**Issue by bojennett** [marcone/teslausb#328]
I see the files in TeslaCam/SentryClips, which are links to files in /backingfiles/snapshots/snap-000000.  Which in of themselves seem to be files pulled from "snap.bin".  And this appears to be a read only file system??????

If I copy files over into my machine say via over the network, how do I now delete them so that I have more space for Sentry clips?  Deleting them on main TeslaCam only deletes the links.

What am I missing here?  How does this stuff get removed?  The whole reason I wanted to do this thing is so that I don't have to remove the drive and take it into the house.  But seems like it is still going to fill up.

**Comment by marcone** [comment]
They'll be deleted automatically, no need to do it manually.

**Comment by bojennett** [comment]
Thank you.
