### ISSUE TITLE
Setup say to put WiFi password in single quotes, but example shows sharepassword

### ISSUE THREAD

**Issue by mobileagellc** [marcone/teslausb#34]
_Be sure that your WiFi password is enclosed in single quotes, and that if it contains one or more single quote characters you replace each single quote character with a backslash followed by a single quote character.

For example, if your password werea'b
you would have
export sharepassword='a\'b'_

Should this be:
**export WIFIPASS='a\'b'**
?

**Comment by marcone** [comment]
Yes, the doc talks about the wifi password, but then uses the cifs share password in the example (they both have the same constraints though)

**Comment by marcone** [comment]
Fixed

**Comment by mobileagellc** [comment]
Thank you. If the wifi network name has a space in it should it be placed inside single quotes?

**Comment by marcone** [comment]
Yes, any password with special characters should be quoted.
