### ISSUE TITLE
Sentry mode "USB drive write speed is too slow for Dashcam"

### ISSUE THREAD

**Issue by jgelsey** [marcone/teslausb#342]
Marcone thanks for all your work on this!  I've had no problems other than when getting into car after it's been in Sentry Mode, I get the "USB drive write speed is too slow for Dashcam" message until I unplug/replug the Pi W, and then it works great again. Any suggestions on how to avoid this error message?

I am on the Buster one-step image btw.  

Thanks!

**Comment by marcone** [comment]
there is no conclusive fix yet, and different things seem to work for different people. There is a long discussion over in https://github.com/marcone/teslausb/issues/239
