### ISSUE TITLE
How do I know if CIFS mounted?

### ISSUE THREAD

**Issue by bojennett** [marcone/teslausb#345]
Other than putting the device in my car, driving around, and seeing if data copied over after I come back and park, is there any way to know, just by ssh-ing into the device and poking around, whether or not it successfully knows about the share to archive clips to?

**Comment by marcone** [comment]
The setup script will try to mount the cifs share during install, so if install succeeded you should be all set.
If you want to confirm, `sudo mount /mnt/archive`
