### ISSUE TITLE
It's working!!!!!!!!!

### ISSUE THREAD

**Issue by BrianDrury** [marcone/teslausb#347]
After much finger trouble teslausb is now running correctly on my pi zero.
Videos captured from the car automatically upload to my PC just as they should. The only problem is the car is too far from the WIFI to get a good signal. No problem, I installed a repeater which the car is now using so all I need do is change the teslausb SSID from BTHub4-Z9H6 to EXT2-BTHub4-Z9H6 (password remains the same) and the pi zero should then work when in the car.
After a few hours I realise this is not so easy. Initially I thought I could simply edit teslausb_setup_variables.conf but it’s read only so I replaced the file which contains the required SSID.
I then ran this:
sudo -i
/root/bin/remountfs_rw
/root/bin/setup-teslausb selfupdate
/root/bin/setup-teslausb
reboot

Unfortunately the SSID has not changed and I am stumped.
Any help much appreciated.

**Comment by marcone** [comment]
change the ssid in /etc/wpa_supplicant/wpa_supplicant.conf
