### ISSUE TITLE
Editing a read only file

### ISSUE THREAD

**Issue by BrianDrury** [marcone/teslausb#348]
This is a really basic question for which I apologise but I am getting desperate.
I wish to change the ssid in /etc/wpa_supplicant/wpa_supplicant.conf file but It’s read only.
I used sudoedit which allows me to edit the file to a new file somewhere but if I make the path equal the old path sudoedit complains that is cannot write the file.

Yes, I am new to this stuff.

**Comment by marcone** [comment]
`sudo /root/bin/remountfs_rw`
