### ISSUE TITLE
No Access Point and Samba setup instructions if doing rclone4pi archive method

### ISSUE THREAD

**Issue by iCSpotRun** [marcone/teslausb#349]
When making teslausb via this method, the "teslausb_setup_variables.conf" is not available on the SD. These are only available when using the one-step setup.

In short, I'm not sure how to enable Samba server and AP_SSID when archiving via rclone4pi

**Comment by marcone** [comment]
I suggest following the headless setup process with archive method 'none' (instead of 'cifs'), and once that is complete configuring rclone, changing the archive method to 'cifs' in the config file and rerunning testup-teslausb again.
