### ISSUE TITLE
Saves Files but doesn't transfer to Share but music works?

### ISSUE THREAD

**Issue by Kenrd** [marcone/teslausb#362]
Latest update seems to work, 
I can put music in shared directory and it gets copied to RPI 
Sentry and driving files are saved to RPI but don't copy to Shared directory?

C:\TeslaPi\Music
C:\TeslaPi\RecentClips

Both directories use same sharename  TeslaPi

**Comment by marcone** [comment]
Not enough information here. Please see https://github.com/marcone/teslausb/issues/35
