### ISSUE TITLE
Very slow write speeds 

### ISSUE THREAD

**Issue by amit-nz** [marcone/teslausb#363]
Hi,

I set up a teslapi using the latest image (logs attached). It seemed to work OK for a few days, but then I get a message stating that the drive is too slow. I plugged the drive into my computer (Win 10) and tried transferring a file to it - it only proceeds at around 2.5-3 MB/sec.

When I take out the SD card, put that into my MBP and run a dd to it, I get >30 MB/sec write speeds (the card can probably go faster - the 30MB/s is likely a limitation of my USB 2.0 card reader).

So it appears for some reason when storage is exposed through the pi, it is slow enough that the car's dashcam throws its hands up and stops recording because its too slow.

Any ideas on what could be causing this? I've tried a 32GB Kingston high endurance and a 64GB kingston high endurance card as well.

Logs: https://pastebin.com/uD0qdRsH

**Comment by marcone** [comment]
https://github.com/marcone/teslausb/issues/239
