### ISSUE TITLE
No accessible shares on Pi 0?

### ISSUE THREAD

**Issue by mrwolf78** [marcone/teslausb#364]
I'm probably missing out something very silly, but I've tried the setup three times now, and I can't get it to work in my M3; it simply doesn't recognize any USB storage.

The Pi 0 is accessible via wifi, and it seems fine. Which step am I missing (Pi 0 with 200GB SD-card)

When I connect the Pi via USB to my Win10 laptop, it also doesn't show up as a USB device (I'm sure if it's supposed to?)

Pastebin here: https://pastebin.com/iW4Lt54L

**Comment by marcone** [comment]
Your description and logs are consistent with using a charge-only cable or using the wrong port on the Pi.
