### ISSUE TITLE
Snapshot? 

### ISSUE THREAD

**Issue by simonrb2000** [marcone/teslausb#368]
I've searched for ages.. Just wondered what exactly is this feature? 

Many Thanks

**Comment by simonrb2000** [comment]
Is it to do with making a copy of a folders to get past the 1 hour recording? If so is this operational now? My backups have only done saved and sentry clips.. Nothing for the 1+ hour

**Comment by marcone** [comment]
It only backs up Saved and Sentry. The snapshots can be accessed via Samba
