### ISSUE TITLE
Pi Hole Log

### ISSUE THREAD

**Issue by vita10gy** [marcone/teslausb#369]
I just noticed in my pihole log that the teslausb looks up my computer basically once a second for the entire time it's on in my garage. Is something off the rails or is this normal? 
![image](https://user-images.githubusercontent.com/3516843/69593981-e9496a80-0fc8-11ea-908b-8ae1934cc0de.png)

**Comment by marcone** [comment]
normal. it's waiting for the archive server to become unreachable
