### ISSUE TITLE
Issues downloading buster image

### ISSUE THREAD

**Issue by paulstaylor** [marcone/teslausb#372]
I was trying to download the buster image and, for some strange reason, it keeps stopping at 30 MB, out of the 400+ MB download.  Is this just me, or is anyone else having this issue?  I'm running on a Mac on Catalina.

**Comment by DMBlakeley** [comment]
Assuming that you meant the prebuilt Buster image. Just checked and had no issue downloading on my MacBook with MacOS Catalina 10.15.1.

**Comment by paulstaylor** [comment]
Thanks for checking...  Just upgraded to a new beta of my firewall and that seemed to be my issue.  Thanks!
