### ISSUE TITLE
Sentinel for archive completion

### ISSUE THREAD

**Issue by MikeBishop** [marcone/teslausb#375]
The [tesla_dashcam project](https://github.com/ehendrix23/tesla_dashcam) has an option to monitor for the existence of a particular file before processing clips, and delete it when done.  It would be helpful, and likely trivial, to specify a file that should be created/touched on the archive target after the archive pass has completed, which could serve as the notice that new clips have been uploaded.

**Comment by marcone** [comment]
This was added a few weeks ago with commit https://github.com/marcone/teslausb/commit/585f4105a7df15223a30629e1e9fd1eb38531411
