### ISSUE TITLE
TeslaCam Folder missing from USB Filesystem

### ISSUE THREAD

**Issue by neilrees** [marcone/teslausb#376]
I noticed that the car hasn't been syncing for the last few days so plugged the Pi into the PC to see what's going on.  The TeslaCam folder is missing and it appears fsck has rescued a load of files and dropped them there.

![image](https://user-images.githubusercontent.com/282424/70652840-39703000-1c4b-11ea-9df8-490e850cbcb3.png)

Am I safe to manually delete these files and recreate the TeslaCam folder?

Could I add a `rm fsck*` and a `mkdir \TeslaCam` be added anywhere on startup to recover this situation automatically?

Diagnostics logs attached [diagnostics.txt](https://github.com/marcone/teslausb/files/3952177/diagnostics.txt)

Interesting snippet:
```
Thu 28 Nov 12:52:40 GMT 2019: Running fsck on /mnt/cam...
Thu 28 Nov 12:52:41 GMT 2019: | fsck from util-linux 2.33.1
Thu 28 Nov 12:52:42 GMT 2019: | fsck.fat 4.1 (2017-01-24)
Thu 28 Nov 12:52:42 GMT 2019: | 0x41: Dirty bit is set. Fs was not properly unmounted and some data may be corrupt.
Thu 28 Nov 12:52:42 GMT 2019: |  Automatically removing dirty bit.
Thu 28 Nov 12:52:42 GMT 2019: | Long filename fragment "ᓭ㈀ᓭ＀￿" found outside a LFN sequence.
Thu 28 Nov 12:52:42 GMT 2019: |   (Maybe the start bit is missing on the last fragment)
Thu 28 Nov 12:52:42 GMT 2019: |   Not auto-correcting this.
Thu 28 Nov 12:52:42 GMT 2019: | /
Thu 28 Nov 12:52:42 GMT 2019: |   Has a large number of bad entries. (127/127)
Thu 28 Nov 12:52:42 GMT 2019: |   Not dropping root directory.
Thu 28 Nov 12:52:42 GMT 2019: | /∞
Thu 28 Nov 12:52:42 GMT 2019: |   Bad short file name (∞).
Thu 28 Nov 12:52:42 GMT 2019: |   Auto-renaming it.
Thu 28 Nov 12:52:42 GMT 2019: |   Renamed to FSCK0000.000
Thu 28 Nov 12:52:42 GMT 2019: | /	∞
Thu 28 Nov 12:52:42 GMT 2019: |   Bad short file name (	∞).
Thu 28 Nov 12:52:42 GMT 2019: |   Auto-renaming it.
Thu 28 Nov 12:52:42 GMT 2019: |   Renamed to FSCK0000.001
Thu 28 Nov 12:52:42 GMT 2019: | /∞
```

Possibly related: it has been working fine until the Tesla Ranger visited...  In fact the time from the snippet above, 12:52 was whilst the Ranger was working on the car and flashing new updates on it

**Comment by marcone** [comment]
> Am I safe to manually delete these files and recreate the TeslaCam folder?

Yes.

> Could I add a `rm fsck*` and a `mkdir \TeslaCam` be added anywhere on startup to recover this situation automatically?

Sure. I've been meaning to add something like that.
