### ISSUE TITLE
Can't mount network path

### ISSUE THREAD

**Issue by felixnoiseux** [marcone/teslausb#381]
Following the crosstalk solutions video I encountered an error.
When I ask to display the disks / partitions I don't see my network path. It is however functional.
I send you screenshots.
thank you in advance
![CantMount](https://user-images.githubusercontent.com/12865882/71197036-bfe5cc80-225e-11ea-93c1-6643d44ef78b.PNG)
![cantMount2](https://user-images.githubusercontent.com/12865882/71197048-c5431700-225e-11ea-98ea-fa6de2147a94.PNG)

**Comment by marcone** [comment]
Working as intended. The network share is only mounted while it is archiving.
