### ISSUE TITLE
Teslausb - pi not being recognized after update 2019.40.50.1

### ISSUE THREAD

**Issue by miles267** [marcone/teslausb#382]
Has anyone else seen this?  I've tried rebooting the car, the pi, and reconnecting usb cables but the dashcam icon no longer appears with Teslausb after this update today.

**Comment by marcone** [comment]
Still works for me. Did you plug it into a PC to see if the drive shows up OK and still has the TeslaCam folder?

**Comment by yaroslavros** [comment]
Same issue here. Recognised correctly in PC and do not see any issues with g_mass_storage however Tesla model 3 with 2019.40.50.1 does not consider it to be a valid storage.

Using RPI4 with external USB disk.

**Comment by senf42** [comment]
It still shows up for me as well.

**Comment by yaroslavros** [comment]
Did complete wipe/reinstall and things seem to be back on track.

A bit strange coincidence with 2019.40.50.1 upgrade...

**Comment by mattfrautnick** [comment]
I am having this issue even after a full wipe/reinstall. P3D- running 2019.40.50.5

**Comment by ScottESanDiego** [comment]
Mine broke (fast-flashing LED, not visible as a umass device when connected to a PC), I re-imaged and it worked for about a day - then back to the same behavior.  Something is certainly odd since 2019.40.50.* .

**Comment by marcone** [comment]
@ScottESanDiego fast-flashing LED means it's archiving, and during archiving it does not present as a mass storage device.

**Comment by ScottESanDiego** [comment]
I don't think it's that fast-flash though.  It doesn't connect to WiFi (so I cannot SSH into it), and it stays in that state for over a day (not sure quite how long, but at least a day).

**Comment by NewyGuy** [comment]
I've had mine drop out a couple of times. Rather than starting from scratch, I plugged into Linux box and ran xfs_repair. ie. Mount, unmount, xfs_repair. Or xfs_repair -L if mounting doesn't work. Can't seem to do it directly on the Pi as Device busy and locks etc. Possible to have script run xfs_repair (optionally) on reboot?

**Comment by marcone** [comment]
Nothing actionable in this issue, so closing.
@ozvic to run xfs_repair on boot, create the file /forcefsck
