### ISSUE TITLE
Old music sub-directories don't get deleted

### ISSUE THREAD

**Issue by joeyeng** [marcone/teslausb#383]
Not sure if this was already posted, but I didn't see it. When I delete or rename sub-directories in my music share they stick around. It'd be nice to get these cleaned up during the next time rsync runs.

**Comment by marcone** [comment]
I assume you didn't actually mean "rsync"? (because music sync doesn't use rsync)

**Comment by marcone** [comment]
Fixed by https://github.com/marcone/teslausb/commit/9de3cb23a430542f8b5aa145fde27ffbb452061c

**Comment by joeyeng** [comment]
This is great. Thanks, @marcone!
