### ISSUE TITLE
Does not copy footage to share.

### ISSUE THREAD

**Issue by marckatznelson** [marcone/teslausb#399]
Hi Marcone - Yesterday I reimaged and one directory was observed this morning on the share. After entire day worth of driving, I expected footage to uploaded, for that I kept the car running. The pi was blinking very fast. After sometime, I checked the drive and nothing was saved. do you think you can find anything concerning in the diagnostic file that I ran just now.
I see an error code -101 with the mount process. not sure what it is.
thanks,
[diagnostics.txt](https://github.com/marcone/teslausb/files/4062208/diagnostics.txt)

**Comment by marcone** [comment]
> After entire day worth of driving, I expected footage to uploaded

teslausb does not archive footage of your driving, only sentry and manually saved clips are archived. Your diagnostics show that it does that.
