### ISSUE TITLE
keeping car awake feature

### ISSUE THREAD

**Issue by marckatznelson** [marcone/teslausb#400]
I have provided VIN and login id, but the new Tesla 3, does not keep awake. Is there anything else I have to do? few additional questions:
1. While car is parked with sentry on and connected to home wifi, should the pi immediately upload the sentry events as and when it occurs to the share? or does it need a different trigger? (assuming car is awake)
2. Does SSH'ing the pi wake up the car?
3. If my car is in parking lot and I want to see the clips, can I upload the clips to share using my cellphone wifi hot spot? What needs to be done?
4. 1 in 3 times I have to reboot the pi in the car, as it suddenly stops displaying the USB music folder. any ideas?

**Comment by marcone** [comment]
> I have provided VIN and login id, but the new Tesla 3, does not keep awake. Is there anything else I have to do?

You might be running in to https://github.com/marcone/teslausb/issues/384. No solution yet.

> few additional questions:
> 
> 1. While car is parked with sentry on and connected to home wifi, should the pi immediately upload the sentry events as and when it occurs to the share? or does it need a different trigger? (assuming car is awake)

No, clips are not continuously archived. It starts archiving when it reconnects to the server after having been away. 

> 2. Does SSH'ing the pi wake up the car?

No, but once you're ssh'd in to the Pi you could call the tesla_api.py script to wake up the car.

> 3. If my car is in parking lot and I want to see the clips, can I upload the clips to share using my cellphone wifi hot spot? What needs to be done?

If your archive is reachable through your cellphone hotspot, then that should work. You can also enable a wifi access point and Samba on the Pi to connect directly to the Pi and see the clips.

> 4. 1 in 3 times I have to reboot the pi in the car, as it suddenly stops displaying the USB music folder. any ideas?

Sorry, no idea
