### ISSUE TITLE
Adding data authenticity featurs

### ISSUE THREAD

**Issue by stephansturges** [marcone/teslausb#408]
Hi guys,
I thought you might be interested in this article I wrote, connecting my Tesla to the blockchain using TeslaUSB underneath :) 
https://medium.com/@stephan.sturges/introducing-the-blockchain-connected-car-f2f15680f6a3?source=friends_link&sk=1ddcd368c467ea491ed1e515b6542863

I will add code to allow other to do this in the near future :+1: 

Cheers,
Stephan

**Comment by marcone** [comment]
I don't know much about blockchains, but if I'm understanding your article correctly, doesn't this only prove that at some point you had a video, and that it wasn't tampered with afterwards? There's no proof that the video wasn't tampered with *before* it was uploaded, or even that it actually came from the car.
In any case, good to see teslausb put to novel use.
