### ISSUE TITLE
Can't pull diagnostic logs and set up gets stuck

### ISSUE THREAD

**Issue by Poncherelly** [marcone/teslausb#409]
When attempting to pull diagnostics:

root@teslausb-ModelY:\~#  /root/bin/setup-teslausb selfupdate
Read setup info from teslausb_setup_variables.conf (yes/no/cancel)? yes
reading config from /root/teslausb_setup_variables.conf
/root/teslausb_setup_variables.conf: line 18: l: unbound variable
root@teslausb-ModelY:\~#  /root/bin/setup-teslausb diagnose > /mutable/diagnostics.txt
-bash: /mutable/diagnostics.txt: No such file or directory

Original issue where I'm getting stuck during setup or re running /etc/rc.local:

pi@teslausb-ModelY:/boot $ tail -f teslausb-headless-setup.log
Wed 22 Jan 23:46:41 GMT 2020 : Grabbing main setup file.
Wed 22 Jan 23:47:14 GMT 2020 : Detecting whether to update wpa_supplicant.conf
Wed 22 Jan 23:47:15 GMT 2020 : Grabbing main setup file.
Wed 22 Jan 23:47:16 GMT 2020 : Starting setup.
Wed 22 Jan 23:47:16 GMT 2020 : reading config from /root/teslausb_setup_variables.conf
Fri 24 Jan 13:43:19 EST 2020 : Detecting whether to update wpa_supplicant.conf
Fri 24 Jan 13:43:19 EST 2020 : Starting setup.
Fri 24 Jan 13:43:19 EST 2020 : reading config from /root/teslausb_setup_variables.conf
Fri 24 Jan 13:51:16 EST 2020 : reading config from /root/teslausb_setup_variables.conf
Fri 24 Jan 13:53:06 EST 2020 : reading config from /root/teslausb_setup_variables.conf

I hope this is an error I made and will be a quick fix :)

Thank you in advance.

**Comment by marcone** [comment]
Your redirecting the output of `setup-teslausb selfupdate` to /mutable, but /mutable doesn't exist because setup didn't complete. Try redirecting it somewhere else, like /boot, /root or /tmp
