### ISSUE TITLE
'RecentClip' folder copy

### ISSUE THREAD

**Issue by marckatznelson** [marcone/teslausb#410]
Is there anyway we can make a change that will help specify in the configuration, what folders should be copied? since, we leave out 'RecentClips' today, if one wants to upload that too, then it will enable them to do so.

**Comment by miles267** [comment]
I would vote for this if an option.

**Comment by marcone** [comment]
https://github.com/marcone/teslausb/issues/114

**Comment by miles267** [comment]
> #114

Would it be possible to please make this inclusion of /RecentClips contents a configuration option in the teslausb_setup_variables.conf file process?
