### ISSUE TITLE
Speed up boot when no network is present

### ISSUE THREAD

**Issue by pyjamasam** [marcone/teslausb#417]
When no wifi (or any network) is present the Pi can take a while to boot.  By running the following command the Pi won't wait for network interfaces to come up and be funcitonal to continue booting.

`rm -f /etc/systemd/system/dhcpcd.service.d/wait.conf`

This line was pulled directly from `raspi-config`

I would like to suggest updating the pi-gen script to account for this.  I find it in my testing that it speeds up the booting process when there is no network by somewhere around 30 seconds.

**Comment by marcone** [comment]
How are you measuring this speedup?
I tested "no network" by changing the SSID in wpa_supplicant.conf to a nonexistent one, and that seemed to be about a second slower than connecting to my actual wifi network, but deleting wait.conf did not make a difference (it takes about 30 seconds for the Pi0 to reach the beginning of archiveloop, regardless of whether wait.conf exists)
