### ISSUE TITLE
ssh port 22 connection refused

### ISSUE THREAD

**Issue by SupplyChainRadio** [marcone/teslausb#418]
Hi,
I continue to bump into an ssh issue when trying to connect to the pi.
ssh pi@teslausb.local
ssh pi@192.168.xx.xx 

both return a 'Port 22 connection refused' error. 
I have re-booted the card and re-installed the image and double, triple checked the config file but can't find anything there. I installed the SSH server on my windows 10 machine and opened up TCP port 22 for inbound and outbound requests to no avail. 

Can this issue be related to the raspberry pi setup or is this purely a local firewall issue on my laptop?

**Comment by marcone** [comment]
Checking the obvious first: you did rename the config file to `teslausb_setup_variables.conf`, i.e. remove the `.sample` part of the filename?
You do not need to configure/install anything on the Windows 10 machine. The ssh server is on the Pi. On Windows 10 you just run the `ssh` command, which I think is standard now.
During setup/boot of the Pi there is a period of time where the ssh server is not running yet, and so you'll either get a timeout, or "connection refused". Eventually it should work though. How long have you let it boot?
