### ISSUE TITLE
Setup script (setup-teslausb) fails to complete on subsequent runs when SNS is enabled.

### ISSUE THREAD

**Issue by san** [marcone/teslausb#421]
I may have stumbled upon a bug in `setup-teslausb` script where it fails at a certain point during configuration if you have SNS enabled and configured previously.

I have tracked in down to this line in `setup/pi/configure.sh`

https://github.com/marcone/teslausb/blob/aec1085f9ddccd969cffc96686d4590f0392e54e/setup/pi/configure.sh#L300

If SNS is configured previously, `/root/.aws` already exists. So, if you want to change some other configuration (for example I needed to change ARCHIVE configuration to rclone) and re-run the setup script, it throws an error and stops at above line. And obviously any code that's supposed to run after that does not run. I had to manually delete `/root/.aws` folder and run the script again. May be we should delete the folder in that script before the `mkdir` line?

**Comment by marcone** [comment]
Fixed
