### ISSUE TITLE
GPS data synchronised with video

### ISSUE THREAD

**Issue by OpenJeDi** [marcone/teslausb#425]
Hi,

First of all: I love this project. It makes the Tesla dashcam much more useful: I can just review camera footage from my NAS. Nicely synced by the time I get to my desk. Thanks a lot everyone involved.

I was thinking about a way to use the Tesla cameras to generate footage for Mapillary. If that would work automatically, we would have up-to-date StreetView like data for everywhere we went with our Tesla.

Not only that, but features like maximum speed can be extracted automatically and synced with OpenStreetMap. That could help a lot in areas where the speed limit data is not up-to-date. Like a lot of places in Belgium where I go.

The videos are there, but we would need a GPX track that goes along with them. Do you think using the Tesla API to get the drive state would work to do this on the fly? Would the timestamps match up with the video's?

My dream solution:
* an option to store GPS tracks alongside the videos
* an option to automatically upload the videos and GPS locations to Mapillary when Wifi (internet) access is detected

Kind regards,
Jeroen

**Comment by marcone** [comment]
The car writes the videos once they are "done", i.e. after each minute of recording. In addition, the "CAM" filesystem is not writeable by the Pi while the car is recording, so you would have to essentially keep a log of your GPS positions, and then apply those to the recording files before or during archiving.
It's certainly technically possible, but it's not something I have any interest in doing.
