### ISSUE TITLE
g_mass_storage LUN slow to connect

### ISSUE THREAD

**Issue by idealerror** [marcone/teslausb#428]
I was monitoring the dmesg and noticed the USB portion takes up to 90-120 seconds to fully load.  Is there any way to speed up that process or what's the troubleshooting procedure for finding why the LUN takes a while to mount?

[   31.206525] CIFS VFS: Error connecting to socket. Aborting operation.
[   31.206555] CIFS VFS: cifs_mount failed w/return code = -101
[   36.557066]  loop0: p1
[   36.574368]  loop0: p1
[   90.563410] Mass Storage Function, version: 2009/09/11
[   90.563428] LUN: removable file: (no medium)
[   90.570317] LUN: removable file: /backingfiles/cam_disk.bin
[   90.570336] Number of LUNs=1
[   90.570599] g_mass_storage gadget: Mass Storage Gadget, version: 2009/09/11
[   90.570611] g_mass_storage gadget: g_mass_storage ready
[   90.570626] dwc2 20980000.usb: bound driver g_mass_storage
[   90.747382] dwc2 20980000.usb: new device is high-speed
[   90.780572] dwc2 20980000.usb: new address 21
[   90.814061] g_mass_storage gadget: high-speed config #1: Linux File-Backed Storage

**Comment by marcone** [comment]
My guess is it's doing an archive pass because it is connected to the network, but you could run `dmesg -T` to get actual timestamps, and then match those up with what's in /mutable/archiveloop.log and system logs to see what's happening during that time.
