### ISSUE TITLE
Feature request; watch videos in browser

### ISSUE THREAD

**Issue by andersbjarby** [marcone/teslausb#432]
Here is an idea. The Raspberry can act as a wifi-hotspot. This means that you could set the Tesla to connect to that hotspot. The raspberry can act as a webserver, this means that the Tesla can browser to it. The Tesla browser can nowdays show videos while the Tesla is in P. 

This means that the Rapsberry can act as a webserver that presents the videos directly in the Tesla browser while in P if the Tesla is connected to the raspberry wifi hotspot. Wouldn't that be a killer feature?

**Comment by marcone** [comment]
> This means that the Rapsberry can act as a webserver that presents the videos directly in the Tesla browser while in P if the Tesla is connected to the raspberry wifi hotspot. 

No, because the car does not connect to local IP addresses.
