### ISSUE TITLE
Can the copy be triggered faster?

### ISSUE THREAD

**Issue by Poncherelly** [marcone/teslausb#435]
The full set up ran and it appears to have no errors.
With that said, I'm trying to test things by connecting to my PC and copying files on to my server folders as well as directly on to the pi using the USB connection.

1) I've copied a "Music_Test_To_Car.mp3" file on to the server and a "Music_Test_From_Car.mp3" in to the Music folder on the pi via the usb connection.
    
The Music folder has accepted the file from the server and deleted the file that was on the pi (I assume this is what's supposed to happen as it's a copy and not a sync?

It's not fast however and I did have to wait a bit.  Is there a setting to have the system confirm it's connected to wifi (Maybe a DNS ping) then once confirmed copy the files right away?

2) I performed the same steps for the TeslaCam folders also with the name being "TeslaCamTest_to_Car.mp4" / "TeslaCamTest_From_Car.mp4"
   
For the Cam folder however the same isn't happening.  Is this due to the file format or maybe the program is looking for something I'm not giving it to look for?  I noticed that this might be due to the naming convention mentioned here https://github.com/marcone/teslausb/issues/210

I'll continue to look for that information but if anyone else is aware, please share.

Thank you in advance.

**Comment by marcone** [comment]
By default there is a [20 second delay](https://github.com/marcone/teslausb/blob/main-dev/pi-gen-sources/00-teslausb-tweaks/files/teslausb_setup_variables.conf.sample#L90) before archiving starts. You can change that to 0 if you want.
In addition to that delay, teslausb will take a snapshot of the cam drive, and run a filesystem check on the disk image before archiving starts.

The archive scripts expect subfolders like this:
TeslaCam/SentryClips/\<date and time of sentry event>/<filename.mp4>

If you put files directly in TeslaCam or SentryClips, they will not be archived.
