### ISSUE TITLE
Drives not showing up on PC

### ISSUE THREAD

**Issue by tom10422** [marcone/teslausb#438]
Neither the music drive or the cam drive show up when the Pi is plugged into a Windows PC.   If I ssh into the PI and run "modprobe g_mass_storage /file=/backingfiles/music_disk.bin" or "modprobe g_mass_storage /file=/backingfiles/cam_disk.bin"   I can get the one specified to show up in Windows.   The  g_mass_storage.conf file in the modprobe.d is empty and was wondering if that is related.  From what I can tell running just "modprobe g_mass_storage" is supposed to read the .conf file which seems to be all the call in archiveloop is doing.  I can't figure out how to modify the .conf file.  Also, when mounting the cam it was empty (i.e. the TeslaCam folder is missing).

 Any suggestions?  Do  I need to re-image it and start over?

I don't have a Tesla yet to see if it works fine in there (waiting on the Model Y reservation).

**Comment by marcone** [comment]
Looks like setup didn't complete successfully. Check the setup log.
