### ISSUE TITLE
Can someone help with this error?

### ISSUE THREAD

**Issue by mhuk01** [marcone/teslausb#442]
root@teslausb:~# /etc/rc.local
My IP address is 192.168.31.244 
Detecting whether to update wpa_supplicant.conf
Remounting / as read/write
Remounting /boot as read/write
Done. Make any changes needed, and reboot the Pi when ready.
Filesystems / and /boot will be mounted as read only after reboot.
Starting setup.
reading config from /root/teslausb_setup_variables.conf
/root/bin/setup-teslausb is up to date
Updating package index files...
Hit:1 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Hit:2 http://archive.raspberrypi.org/debian stretch InRelease
Reading package lists... Done
Verifying that the requested configuration is valid...
curl -o /tmp/verify-configuration.sh https://raw.githubusercontent.com/marcone/teslausb/f6e0bead51b652b2c1f2b95f6ab6b60653631afd/setup/pi/verify-configuration.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4112  100  4112    0     0   9150      0 --:--:-- --:--:-- --:--:--  9158
Downloaded /tmp/verify-configuration.sh ...
usb_drive is not set. SD card will be used.
Verifying that there is sufficient space available on the MicroSD card...
There is sufficient space available.
Downloading additional setup scripts.
curl -o /root/bin/remountfs_rw https://raw.githubusercontent.com/marcone/teslausb/f6e0bead51b652b2c1f2b95f6ab6b60653631afd/run/remountfs_rw
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   276  100   276    0     0    527      0 --:--:-- --:--:-- --:--:--   527
Downloaded /root/bin/remountfs_rw ...
curl -o /root/bin/make_snapshot.sh https://raw.githubusercontent.com/marcone/teslausb/f6e0bead51b652b2c1f2b95f6ab6b60653631afd/run/make_snapshot.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4739  100  4739    0     0   9706      0 --:--:-- --:--:-- --:--:--  9731
Downloaded /root/bin/make_snapshot.sh ...
curl -o /root/bin/mount_snapshot.sh https://raw.githubusercontent.com/marcone/teslausb/f6e0bead51b652b2c1f2b95f6ab6b60653631afd/run/mount_snapshot.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   837  100   837    0     0   1714      0 --:--:-- --:--:-- --:--:--  1718
Downloaded /root/bin/mount_snapshot.sh ...
curl -o /root/bin/mount_image.sh https://raw.githubusercontent.com/marcone/teslausb/f6e0bead51b652b2c1f2b95f6ab6b60653631afd/run/mount_image.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   533  100   533    0     0   1115      0 --:--:-- --:--:-- --:--:--  1117
Downloaded /root/bin/mount_image.sh ...
curl -o /root/bin/release_snapshot.sh https://raw.githubusercontent.com/marcone/teslausb/f6e0bead51b652b2c1f2b95f6ab6b60653631afd/run/release_snapshot.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   473  100   473    0     0   1046      0 --:--:-- --:--:-- --:--:--  1048
Downloaded /root/bin/release_snapshot.sh ...
curl -o /root/bin/force_sync.sh https://raw.githubusercontent.com/marcone/teslausb/f6e0bead51b652b2c1f2b95f6ab6b60653631afd/run/force_sync.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   517  100   517    0     0   1110      0 --:--:-- --:--:-- --:--:--  1114
Downloaded /root/bin/force_sync.sh ...
curl -o /tmp/create-backingfiles-partition.sh https://raw.githubusercontent.com/marcone/teslausb/f6e0bead51b652b2c1f2b95f6ab6b60653631afd/setup/pi/create-backingfiles-partition.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5949  100  5949    0     0   8911      0 --:--:-- --:--:-- --:--:--  8919
Downloaded /tmp/create-backingfiles-partition.sh ...
curl -o /tmp/create-backingfiles.sh https://raw.githubusercontent.com/marcone/teslausb/f6e0bead51b652b2c1f2b95f6ab6b60653631afd/setup/pi/create-backingfiles.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4949  100  4949    0     0  10260      0 --:--:-- --:--:-- --:--:-- 10288
Downloaded /tmp/create-backingfiles.sh ...
curl -o /tmp/make-root-fs-readonly.sh https://raw.githubusercontent.com/marcone/teslausb/f6e0bead51b652b2c1f2b95f6ab6b60653631afd/setup/pi/make-root-fs-readonly.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3682  100  3682    0     0   7947      0 --:--:-- --:--:-- --:--:--  7969
Downloaded /tmp/make-root-fs-readonly.sh ...
curl -o /tmp/configure.sh https://raw.githubusercontent.com/marcone/teslausb/f6e0bead51b652b2c1f2b95f6ab6b60653631afd/setup/pi/configure.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11292  100 11292    0     0  24496      0 --:--:-- --:--:-- --:--:-- 24494
Downloaded /tmp/configure.sh ...
~ ~
Fixing the modules-load parameter in /boot/cmdline.txt...
Fixed cmdline.txt.
usb_drive not set. Proceeding to SD card setup
using existing backingfiles and mutable partitions
TARGET        SOURCE         FSTYPE OPTIONS
/backingfiles /dev/mmcblk0p3 xfs    rw,noatime,attr2,inode64,noquota
calling configure.sh
configure: Pushover not configured.
configure: Pushover not configured.
configure: Gotify not configured.
configure: Gotify not configured.
configure: IFTTT not configured.
configure: IFTTT not configured.
configure: SNS not configured.
configure: SNS not configured.
curl -o /root/bin/send-push-message https://raw.githubusercontent.com/marcone/teslausb/f6e0bead51b652b2c1f2b95f6ab6b60653631afd/run/send-push-message
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1480  100  1480    0     0   2497      0 --:--:-- --:--:-- --:--:--  2500
Downloaded /root/bin/send-push-message ...
curl -o /root/bin/send_sns.py https://raw.githubusercontent.com/marcone/teslausb/f6e0bead51b652b2c1f2b95f6ab6b60653631afd/run/send_sns.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   602  100   602    0     0   1275      0 --:--:-- --:--:-- --:--:--  1275
Downloaded /root/bin/send_sns.py ...
configure: Checking archive configs: 
configure: Checking archive configs: 
configure: done
configure: done
configure: Using archive module: run/cifs_archive
configure: Using archive module: run/cifs_archive
configure: Installing base archive scripts into /root/bin
configure: Installing base archive scripts into /root/bin
curl -o /root/bin/archiveloop https://raw.githubusercontent.com/marcone/teslausb/f6e0bead51b652b2c1f2b95f6ab6b60653631afd/run/archiveloop
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11856  100 11856    0     0  26860      0 --:--:-- --:--:-- --:--:-- 26945
Downloaded /root/bin/archiveloop ...
curl -o /root/bin/waitforidle https://raw.githubusercontent.com/marcone/teslausb/f6e0bead51b652b2c1f2b95f6ab6b60653631afd/run/waitforidle
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1613  100  1613    0     0   3570      0 --:--:-- --:--:-- --:--:--  3568
Downloaded /root/bin/waitforidle ...
curl -o /root/bin/remountfs_rw https://raw.githubusercontent.com/marcone/teslausb/f6e0bead51b652b2c1f2b95f6ab6b60653631afd/run/remountfs_rw
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   276  100   276    0     0    593      0 --:--:-- --:--:-- --:--:--   593
Downloaded /root/bin/remountfs_rw ...
configure: Skipping tesla_api.py install
configure: Skipping tesla_api.py install
configure: Installing archive module scripts
configure: Installing archive module scripts
curl -o /tmp/verify-and-configure-archive.sh https://raw.githubusercontent.com/marcone/teslausb/f6e0bead51b652b2c1f2b95f6ab6b60653631afd/run/cifs_archive/verify-and-configure-archive.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4026  100  4026    0     0   8830      0 --:--:-- --:--:-- --:--:--  8848
Downloaded /tmp/verify-and-configure-archive.sh ...
curl -o /root/bin/archive-clips.sh https://raw.githubusercontent.com/marcone/teslausb/f6e0bead51b652b2c1f2b95f6ab6b60653631afd/run/cifs_archive/archive-clips.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2620  100  2620    0     0   5732      0 --:--:-- --:--:-- --:--:--  5733
Downloaded /root/bin/archive-clips.sh ...
curl -o /root/bin/connect-archive.sh https://raw.githubusercontent.com/marcone/teslausb/f6e0bead51b652b2c1f2b95f6ab6b60653631afd/run/cifs_archive/connect-archive.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   597  100   597    0     0   1305      0 --:--:-- --:--:-- --:--:--  1306
Downloaded /root/bin/connect-archive.sh ...
curl -o /root/bin/disconnect-archive.sh https://raw.githubusercontent.com/marcone/teslausb/f6e0bead51b652b2c1f2b95f6ab6b60653631afd/run/cifs_archive/disconnect-archive.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   661  100   661    0     0   1368      0 --:--:-- --:--:-- --:--:--  1371
Downloaded /root/bin/disconnect-archive.sh ...
curl -o /root/bin/write-archive-configs-to.sh https://raw.githubusercontent.com/marcone/teslausb/f6e0bead51b652b2c1f2b95f6ab6b60653631afd/run/cifs_archive/write-archive-configs-to.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   141  100   141    0     0    292      0 --:--:-- --:--:-- --:--:--   293
Downloaded /root/bin/write-archive-configs-to.sh ...
curl -o /root/bin/archive-is-reachable.sh https://raw.githubusercontent.com/marcone/teslausb/f6e0bead51b652b2c1f2b95f6ab6b60653631afd/run/cifs_archive/archive-is-reachable.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    94  100    94    0     0    170      0 --:--:-- --:--:-- --:--:--   170
Downloaded /root/bin/archive-is-reachable.sh ...
verify-and-configure-archive: Installing/updating required packages if needed
verify-and-configure-archive: Installing/updating required packages if needed
Reading package lists... Done
Building dependency tree       
Reading state information... Done
hping3 is already the newest version (3.a2.ds2-7).
0 upgraded, 0 newly installed, 0 to remove and 56 not upgraded.
verify-and-configure-archive: Done
verify-and-configure-archive: Done
verify-and-configure-archive: Verifying that the archive server your_archive_name_or_ip is reachable...
verify-and-configure-archive: Verifying that the archive server your_archive_name_or_ip is reachable...
verify-and-configure-archive: STOP: The archive server your_archive_name_or_ip is unreachable. Try specifying its IP address instead.
verify-and-configure-archive: STOP: The archive server your_archive_name_or_ip is unreachable. Try specifying its IP address instead.

**Comment by marcone** [comment]
Pretty obvious, no? You didn't fill out the teslausb_setup_variables.conf file properly. Specifically, you didn't specify your file server's name or IP.
