### ISSUE TITLE
rsync method does not remove files/directories from source

### ISSUE THREAD

**Issue by davideshay** [marcone/teslausb#45]
The rsync method successfully moves files to the remote rsync server, but it does not remove them from the raspberry pi, so it eventually fills up.

I am trying a potential fix. See attached revised contents of archive-clips.sh
[archive-clips.sh.gz](https://github.com/marcone/teslausb/files/3221309/archive-clips.sh.gz)

**Comment by davideshay** [comment]
Attempted to create a pull request as well...

**Comment by marcone** [comment]
Thanks for the fix! I'm really surprised nobody noticed this before (or at least noticed it enough to report it)
