### ISSUE TITLE
TeslaUSB Drive Full - Stuck Still? (Model S / MCU1 / AP2.5 / 2020.8.1)

### ISSUE THREAD

**Issue by jun3280net** [marcone/teslausb#450]
Continuing from my last issue #448 - I followed @marcone 's instruction and reinstalled from scratch.
1.  I wiped the micro SD Card using SD Card Formatter
2.  I used Etcher to install the teslausb-buster-20190922.zip (because I tried teslausb-20200122.zip and it hung.  Also the buster image was working for me).
3.  Copied the teslausb_setup_variables (same configuration as what I had working) to the boot drive
4.  Plugged the micro SD Card into the Raspberry Pi and let it complete the installation.
5.  SSH to confirm the installation completed properly
6.  Plugged the Raspberry Pi into Tesla Model S
7.  Confirmed it was working and drove into work.
8.  After work (9.5 hrs later) returned to the car - and noticed the camera was no longer recording.  Tesla said "Dashcam unable to write - usb drive is full".  This is a 256GB card with 187GB allocated for video recording.
9.  What's interesting from the SSH - it shows less than 10GB was used for the video snapshots (0-10), which is nowhere near capacity.
10.  Plugged the PI into my computer and the CAM drive shows 524MB of recordings in the RecentClips folder.

![image](https://user-images.githubusercontent.com/30555695/76488075-007e5d80-63ea-11ea-86e7-27c21a2da8ff.png)

![image](https://user-images.githubusercontent.com/30555695/76488573-8222bb00-63eb-11ea-8469-b7179e44acf5.png)

![image](https://user-images.githubusercontent.com/30555695/76488867-5f44d680-63ec-11ea-9954-3b7d7938351e.png)

Does anybody have an idea what is going on?  Is the micro SD card corrupt?  Is this a problem because of the latest Tesla Update (2020.8.1 for Model S MCU1 / AP2.5).  

On a separate note, given that the Snapshots (0-10) still exist per SSH, is there anyway to easily expose them to Windows like storing them on a separate partition (like CAM - have an ARCHIVE.bin)?

In the meantime, I'm going to take a smaller 64GB card and retry the installation.

**Comment by softcoder** [comment]
Is it a fake sd card? This kind of result could occur from a fake Chinese version:

https://www.raymond.cc/blog/test-and-detect-fake-or-counterfeit-usb-flash-drives-bought-from-ebay-with-h2testw/

https://youtu.be/J-D6tYBX8vE

**Comment by jun3280net** [comment]
> Is it a fake sd card? This kind of result could occur from a fake Chinese version:
> 
> https://www.raymond.cc/blog/test-and-detect-fake-or-counterfeit-usb-flash-drives-bought-from-ebay-with-h2testw/
> 
> https://youtu.be/J-D6tYBX8vE

Thanks for the tip @softcoder .  I'll give those tools a test.  That said, I was using this card for a number of months successfully without issue.  I've moved/archived several hundred gigs of videos over that period.

**Comment by jun3280net** [comment]
@softcoder did one test on the card, and it passed.  Currently, running a more intensive second test - its still going but no errors.  

On a separate note, I used a 64GB card that I initially did testing with for TeslaUSB - did a fresh install.  Everything installed smoothly, even my 2GB library of music synced properly.  However, the moment I plugged the drive into the car - it registered as full.  

I plugged the card into my computer and the drive looks empty : 
![image](https://user-images.githubusercontent.com/30555695/76585375-d12c2700-64a3-11ea-88f7-890c6214eb85.png)

SSH of what the drive looks like (there are no snapshots - as the card registered as full the moment it was plugged into the Tesla):
![image](https://user-images.githubusercontent.com/30555695/76585119-359ab680-64a3-11ea-9873-7730bf9fc227.png)

Now I'm beginning to wonder if it's related to my car configuration/software.  Will try a few more tests.

**Comment by jun3280net** [comment]
Reinstalled the 64GB drive, and pretty much the same result.  I started from scratch which includes the server.  Reduced the amount of music to be transferred, which seemed to give the card a bit of room to write to.  That said - it filled up fast in snapshots (less than 150MB) - and Tesla complained the drive was full.  I've tried plugging/replugging the TeslaUSB - and the car sees the drive as full.  It feels like Tesla is only seeing 1-2 GB of space - which is what I allocated for the music drive.

Next test will be to allocate no space for music.  Any other thoughts on how to debug?

![image](https://user-images.githubusercontent.com/30555695/76656885-32043f80-6536-11ea-8bce-1f5c2f2b49c7.png)

![image](https://user-images.githubusercontent.com/30555695/76657015-7c85bc00-6536-11ea-9679-30e6d00aff5c.png)

**Comment by marcone** [comment]
Have you tried just using a regular USB drive? Because from the Pi's point of view there is no difference between being connected to a Tesla, a PC, or any other computer, and so the fact that the drive shows up correctly (empty) in Windows while the car thinks it's full might indicate a problem with the car.

**Comment by jun3280net** [comment]
> Have you tried just using a regular USB drive? Because from the Pi's point of view there is no difference between being connected to a Tesla, a PC, or any other computer, and so the fact that the drive shows up correctly (empty) in Windows while the car thinks it's full might indicate a problem with the car.

@marcone yup that's the next step.  Last test I tried was 48% Cam / 2% Music - and same result.  The only other thing I haven't tried is turning off the snapshots.  

That said - i'm just going to wipe my 64GB card, and use it as standard storage to see how long it goes before the system complains that the drive is full.  Thanks for the suggestion.  Will update tonight after my hockey game.

**Comment by marcone** [comment]
you should also check `dmesg` on the Pi to see if there are any I/O errors on the card

**Comment by jun3280net** [comment]
@marcone - thanks for the tips.  Using just a normal USB drive - same result.  Pretty sure the issue is related to the updates from Tesla - going to see if other people experiencing the same thing.  In the meantime, the dmesg is as follows : 


pi@teslausb-mdls:~ $ dmesg
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 4.19.93+ (dom@buildbot) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611)) #1290 Fri Jan 10 16:34:37 GMT 2020
[    0.000000] CPU: ARMv6-compatible processor [410fb767] revision 7 (ARMv7), cr=00c5387d
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT nonaliasing instruction cache
[    0.000000] OF: fdt: Machine model: Raspberry Pi Zero W Rev 1.1
[    0.000000] Memory policy: Data cache writeback
[    0.000000] cma: Reserved 8 MiB at 0x1b400000
[    0.000000] On node 0 totalpages: 114688
[    0.000000]   Normal zone: 1008 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 114688 pages, LIFO batch:31
[    0.000000] random: get_random_bytes called from start_kernel+0x8c/0x494 with crng_init=0
[    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
[    0.000000] pcpu-alloc: [0] 0
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 113680
[    0.000000] Kernel command line: coherent_pool=1M 8250.nr_uarts=0 bcm2708_fb.fbwidth=656 bcm2708_fb.fbheight=416 bcm2708_fb.fbswap=1 smsc95xx.macaddr=B8:27:EB:7D:93:52 vc_mem.mem_base=0x1ec00000 vc_mem.mem_size=0x20000000  dwc_otg.lpm_enable=0 console=ttyS0,115200 console=tty1 root=PARTUUID=27cf9d8e-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait modules-load=dwc2 quiet fastboot noswap ro
[    0.000000] Dentry cache hash table entries: 65536 (order: 6, 262144 bytes)
[    0.000000] Inode-cache hash table entries: 32768 (order: 5, 131072 bytes)
[    0.000000] Memory: 434164K/458752K available (7142K kernel code, 656K rwdata, 2128K rodata, 468K init, 797K bss, 16396K reserved, 8192K cma-reserved)
[    0.000000] Virtual kernel memory layout:
                   vector  : 0xffff0000 - 0xffff1000   (   4 kB)
                   fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
                   vmalloc : 0xdc800000 - 0xff800000   ( 560 MB)
                   lowmem  : 0xc0000000 - 0xdc000000   ( 448 MB)
                   modules : 0xbf000000 - 0xc0000000   (  16 MB)
                     .text : 0x(ptrval) - 0x(ptrval)   (7144 kB)
                     .init : 0x(ptrval) - 0x(ptrval)   ( 468 kB)
                     .data : 0x(ptrval) - 0x(ptrval)   ( 657 kB)
                      .bss : 0x(ptrval) - 0x(ptrval)   ( 798 kB)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] ftrace: allocating 25651 entries in 76 pages
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000030] sched_clock: 32 bits at 1000kHz, resolution 1000ns, wraps every 2147483647500ns
[    0.000076] clocksource: timer: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 1911260446275 ns
[    0.000198] bcm2835: system timer (irq = 27)
[    0.000616] Console: colour dummy device 80x30
[    0.000644] console [tty1] enabled
[    0.000705] Calibrating delay loop... 697.95 BogoMIPS (lpj=3489792)
[    0.060347] pid_max: default: 32768 minimum: 301
[    0.060908] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.060930] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.062372] CPU: Testing write buffer coherency: ok
[    0.063680] Setting up static identity map for 0x8200 - 0x8238
[    0.065091] devtmpfs: initialized
[    0.076417] VFP support v0.3: implementor 41 architecture 1 part 20 variant b rev 5
[    0.076822] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.076853] futex hash table entries: 256 (order: -1, 3072 bytes)
[    0.078195] pinctrl core: initialized pinctrl subsystem
[    0.079786] NET: Registered protocol family 16
[    0.083263] DMA: preallocated 1024 KiB pool for atomic coherent allocations
[    0.091034] hw-breakpoint: found 6 breakpoint and 1 watchpoint registers.
[    0.091051] hw-breakpoint: maximum watchpoint size is 4 bytes.
[    0.091198] Serial: AMBA PL011 UART driver
[    0.094519] bcm2835-mbox 2000b880.mailbox: mailbox enabled
[    0.140002] bcm2835-dma 20007000.dma: DMA legacy API manager at (ptrval), dmachans=0x1
[    0.142706] SCSI subsystem initialized
[    0.142982] usbcore: registered new interface driver usbfs
[    0.143089] usbcore: registered new interface driver hub
[    0.143317] usbcore: registered new device driver usb
[    0.160982] raspberrypi-firmware soc:firmware: Attached to firmware from 2020-01-10 17:01, variant start
[    0.171001] raspberrypi-firmware soc:firmware: Firmware hash is f3e39fed4763ce4efbffabb2d4787aaacddeda0f
[    0.183699] clocksource: Switched to clocksource timer
[    0.291292] VFS: Disk quotas dquot_6.6.0
[    0.291424] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    0.291751] FS-Cache: Loaded
[    0.292102] CacheFiles: Loaded
[    0.311779] NET: Registered protocol family 2
[    0.313136] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 4096 bytes)
[    0.313203] TCP established hash table entries: 4096 (order: 2, 16384 bytes)
[    0.313289] TCP bind hash table entries: 4096 (order: 2, 16384 bytes)
[    0.313385] TCP: Hash tables configured (established 4096 bind 4096)
[    0.313549] UDP hash table entries: 256 (order: 0, 4096 bytes)
[    0.313586] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    0.314124] NET: Registered protocol family 1
[    0.315237] RPC: Registered named UNIX socket transport module.
[    0.315251] RPC: Registered udp transport module.
[    0.315257] RPC: Registered tcp transport module.
[    0.315263] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.317562] hw perfevents: no irqs for PMU, sampling events not supported
[    0.317630] hw perfevents: enabled with armv6_1176 PMU driver, 3 counters available
[    0.322003] Initialise system trusted keyrings
[    0.322407] workingset: timestamp_bits=14 max_order=17 bucket_order=3
[    0.338369] FS-Cache: Netfs 'nfs' registered for caching
[    0.339736] NFS: Registering the id_resolver key type
[    0.339805] Key type id_resolver registered
[    0.339813] Key type id_legacy registered
[    0.339841] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[    0.345633] Key type asymmetric registered
[    0.345652] Asymmetric key parser 'x509' registered
[    0.345766] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 250)
[    0.346227] io scheduler noop registered
[    0.346243] io scheduler deadline registered (default)
[    0.346883] io scheduler cfq registered
[    0.346900] io scheduler mq-deadline registered (default)
[    0.346909] io scheduler kyber registered
[    0.349752] bcm2708_fb soc:fb: FB found 1 display(s)
[    0.359030] Console: switching to colour frame buffer device 82x26
[    0.363886] bcm2708_fb soc:fb: Registered framebuffer for display 0, size 656x416
[    0.367663] bcm2835-rng 20104000.rng: hwrng registered
[    0.368125] vc-mem: phys_addr:0x00000000 mem_base=0x1ec00000 mem_size:0x20000000(512 MiB)
[    0.369267] vc-sm: Videocore shared memory driver
[    0.369946] gpiomem-bcm2835 20200000.gpiomem: Initialised: Registers at 0x20200000
[    0.390915] brd: module loaded
[    0.404965] loop: module loaded
[    0.405865] Loading iSCSI transport class v2.0-870.
[    0.406839] usbcore: registered new interface driver smsc95xx
[    0.406873] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    0.407058] dwc_otg: FIQ enabled
[    0.407069] dwc_otg: NAK holdoff enabled
[    0.407076] dwc_otg: FIQ split-transaction FSM enabled
[    0.407093] Module dwc_common_port init
[    0.407586] usbcore: registered new interface driver usb-storage
[    0.408050] mousedev: PS/2 mouse device common for all mice
[    0.409474] bcm2835-wdt bcm2835-wdt: Broadcom BCM2835 watchdog timer
[    0.409960] bcm2835-cpufreq: min=700000 max=1000000
[    0.410744] sdhci: Secure Digital Host Controller Interface driver
[    0.410758] sdhci: Copyright(c) Pierre Ossman
[    0.411395] mmc-bcm2835 20300000.mmcnr: could not get clk, deferring probe
[    0.412123] sdhost-bcm2835 20202000.mmc: could not get clk, deferring probe
[    0.412369] sdhci-pltfm: SDHCI platform and OF driver helper
[    0.413022] ledtrig-cpu: registered to indicate activity on CPUs
[    0.413179] hidraw: raw HID events driver (C) Jiri Kosina
[    0.413443] usbcore: registered new interface driver usbhid
[    0.413452] usbhid: USB HID core driver
[    0.414689] vchiq: vchiq_init_state: slot_zero = (ptrval), is_master = 0
[    0.416838] [vc_sm_connected_init]: start
[    0.426315] [vc_sm_connected_init]: end - returning 0
[    0.428140] Initializing XFRM netlink socket
[    0.428212] NET: Registered protocol family 17
[    0.428391] Key type dns_resolver registered
[    0.430492] registered taskstats version 1
[    0.430526] Loading compiled-in X.509 certificates
[    0.440701] uart-pl011 20201000.serial: cts_event_workaround enabled
[    0.440844] 20201000.serial: ttyAMA0 at MMIO 0x20201000 (irq = 81, base_baud = 0) is a PL011 rev2
[    0.444035] mmc-bcm2835 20300000.mmcnr: mmc_debug:0 mmc_debug2:0
[    0.444056] mmc-bcm2835 20300000.mmcnr: DMA channel allocated
[    0.471852] sdhost: log_buf @ (ptrval) (5b510000)
[    0.507643] mmc1: queuing unknown CIS tuple 0x80 (2 bytes)
[    0.509390] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    0.511126] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    0.514239] mmc1: queuing unknown CIS tuple 0x80 (7 bytes)
[    0.519556] mmc0: sdhost-bcm2835 loaded - DMA enabled (>1)
[    0.521394] of_cfs_init
[    0.521569] of_cfs_init: OK
[    0.522689] Waiting for root device PARTUUID=27cf9d8e-02...
[    0.547562] random: fast init done
[    0.581786] mmc0: host does not support reading read-only switch, assuming write-enable
[    0.584353] mmc0: new high speed SDXC card at address 5048
[    0.586597] mmcblk0: mmc0:5048 SD256 239 GiB
[    0.590459]  mmcblk0: p1 p2 p3 p4
[    0.617710] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[    0.617812] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
[    0.628937] devtmpfs: mounted
[    0.635101] Freeing unused kernel memory: 468K
[    0.635115] This architecture does not have kernel memory protection.
[    0.635123] Run /sbin/init as init process
[    0.653612] mmc1: new high speed SDIO card at address 0001
[    1.405897] systemd[1]: System time before build time, advancing clock.
[    1.572868] NET: Registered protocol family 10
[    1.575096] Segment Routing with IPv6
[    1.639974] systemd[1]: systemd 241 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid)
[    1.641158] systemd[1]: Detected architecture arm.
[    1.651116] systemd[1]: Set hostname to <teslausb-mdls>.
[    1.655944] systemd[1]: Failed to bump fs.file-max, ignoring: Invalid argument
[    4.166861] systemd[1]: /lib/systemd/system/smbd.service:9: PIDFile= references path below legacy directory /var/run/, updating /var/run/samba/smbd.pid → /run/samba/smbd.pid; please update the unit file accordingly.
[    4.239638] systemd[1]: /lib/systemd/system/nmbd.service:9: PIDFile= references path below legacy directory /var/run/, updating /var/run/samba/nmbd.pid → /run/samba/nmbd.pid; please update the unit file accordingly.
[    4.472914] random: systemd: uninitialized urandom read (16 bytes read)
[    4.497943] random: systemd: uninitialized urandom read (16 bytes read)
[    4.499019] systemd[1]: Listening on udev Kernel Socket.
[    4.500426] random: systemd: uninitialized urandom read (16 bytes read)
[    4.501197] systemd[1]: Started Forward Password Requests to Wall Directory Watch.
[    4.502301] systemd[1]: Started Dispatch Password Requests to Console Directory Watch.
[    4.502707] systemd[1]: Reached target Paths.
[    5.903649] dwc2 20980000.usb: 20980000.usb supply vusb_d not found, using dummy regulator
[    5.903927] dwc2 20980000.usb: Linked as a consumer to regulator.0
[    5.903962] dwc2 20980000.usb: 20980000.usb supply vusb_a not found, using dummy regulator
[    6.123926] dwc2 20980000.usb: dwc2_check_params: Invalid parameter lpm=1
[    6.123948] dwc2 20980000.usb: dwc2_check_params: Invalid parameter lpm_clock_gating=1
[    6.123960] dwc2 20980000.usb: dwc2_check_params: Invalid parameter besl=1
[    6.123972] dwc2 20980000.usb: dwc2_check_params: Invalid parameter hird_threshold_en=1
[    6.124037] dwc2 20980000.usb: EPs: 8, dedicated fifos, 4080 entries in SPRAM
[    6.125503] dwc2 20980000.usb: DWC OTG Controller
[    6.125573] dwc2 20980000.usb: new USB bus registered, assigned bus number 1
[    6.125660] dwc2 20980000.usb: irq 33, io mem 0x20980000
[    6.126120] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 4.19
[    6.126140] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    6.126151] usb usb1: Product: DWC OTG Controller
[    6.126162] usb usb1: Manufacturer: Linux 4.19.93+ dwc2_hsotg
[    6.126172] usb usb1: SerialNumber: 20980000.usb
[    6.127431] hub 1-0:1.0: USB hub found
[    6.127546] hub 1-0:1.0: 1 port detected
[    7.121652] systemd[1]: Started Apply Kernel Variables.
[    7.314552] systemd[1]: Started Journal Service.
[    7.427105] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[    9.747423] systemd-journald[84]: Received request to flush runtime journal from PID 1
[   11.150669] vc_sm_cma: module is from the staging directory, the quality is unknown, you have been warned.
[   11.158530] media: Linux media interface: v0.10
[   11.177859] bcm2835_vc_sm_cma_probe: Videocore shared memory driver
[   11.177884] [vc_sm_connected_init]: start
[   11.204850] [vc_sm_connected_init]: installed successfully
[   11.388897] videodev: Linux video capture interface: v2.00
[   11.521290] bcm2835_mmal_vchiq: module is from the staging directory, the quality is unknown, you have been warned.
[   11.528145] bcm2835_mmal_vchiq: module is from the staging directory, the quality is unknown, you have been warned.
[   11.614163] bcm2835_v4l2: module is from the staging directory, the quality is unknown, you have been warned.
[   11.694344] bcm2835_codec: module is from the staging directory, the quality is unknown, you have been warned.
[   11.787974] bcm2835-codec bcm2835-codec: Device registered as /dev/video10
[   11.788066] bcm2835-codec bcm2835-codec: Loaded V4L2 decode
[   11.800730] bcm2835-codec bcm2835-codec: Device registered as /dev/video11
[   11.800790] bcm2835-codec bcm2835-codec: Loaded V4L2 encode
[   11.811153] bcm2835-codec bcm2835-codec: Device registered as /dev/video12
[   11.811212] bcm2835-codec bcm2835-codec: Loaded V4L2 isp
[   11.990855] snd_bcm2835: module is from the staging directory, the quality is unknown, you have been warned.
[   12.212979] bcm2835_audio soc:audio: card created with 8 channels
[   12.867528] cfg80211: Loading compiled-in X.509 certificates for regulatory database
[   13.298229] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
[   13.777021] brcmfmac: F1 signature read @0x18000000=0x1541a9a6
[   13.791180] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1
[   13.791625] usbcore: registered new interface driver brcmfmac
[   14.055061] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1
[   14.055259] brcmfmac: brcmf_c_process_clm_blob: no clm_blob available (err=-2), device may have limited channels available
[   14.056341] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM43430/1 wl0: Oct 23 2017 03:55:53 version 7.45.98.38 (r674442 CY) FWID 01-e58d219f
[   17.096193] EXT4-fs (mmcblk0p4): recovery complete
[   17.105252] EXT4-fs (mmcblk0p4): mounted filesystem with ordered data mode. Opts: (null)
[   18.246078] SGI XFS with ACLs, security attributes, realtime, no debug enabled
[   18.277646] XFS (mmcblk0p3): Mounting V5 Filesystem
[   19.715641] XFS (mmcblk0p3): Starting recovery (logdev: internal)
[   19.733223] XFS (mmcblk0p3): Ending recovery (logdev: internal)
[   22.529915] uart-pl011 20201000.serial: no DMA platform data
[   23.588111] IPv6: ADDRCONF(NETDEV_UP): ap0: link is not ready
[   24.213681] IPv6: ADDRCONF(NETDEV_CHANGE): ap0: link becomes ready
[   24.475756] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   24.475816] brcmfmac: power management disabled
[   24.889849] random: crng init done
[   24.889875] random: 7 urandom warning(s) missed due to ratelimiting
[   27.779700] Bluetooth: Core ver 2.22
[   27.779898] NET: Registered protocol family 31
[   27.779911] Bluetooth: HCI device and connection manager initialized
[   27.779944] Bluetooth: HCI socket layer initialized
[   27.779965] Bluetooth: L2CAP socket layer initialized
[   27.780088] Bluetooth: SCO socket layer initialized
[   27.905920] Bluetooth: HCI UART driver ver 2.3
[   27.905943] Bluetooth: HCI UART protocol H4 registered
[   27.914621] Bluetooth: HCI UART protocol Three-wire (H5) registered
[   27.917187] Bluetooth: HCI UART protocol Broadcom registered
[   28.661891] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[   29.663981] FS-Cache: Netfs 'cifs' registered for caching
[   29.665110] Key type cifs.spnego registered
[   29.665143] Key type cifs.idmap registered
[   29.946120] CIFS VFS: Error connecting to socket. Aborting operation.
[   29.946150] CIFS VFS: cifs_mount failed w/return code = -101
[   29.954074] CIFS VFS: Error connecting to socket. Aborting operation.
[   29.954109] CIFS VFS: cifs_mount failed w/return code = -101
[   30.986496]  loop0: p1
[   32.430016]  loop1: p1
[   33.906384]  loop2: p1
[   36.232101]  loop3: p1
[   37.793920] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   37.793938] Bluetooth: BNEP filters: protocol multicast
[   37.793973] Bluetooth: BNEP socket layer initialized
[   39.622598]  loop4: p1
[   59.374007]  loop4: p1
[   67.572974]  loop4: p1
[  115.545691] Mass Storage Function, version: 2009/09/11
[  115.545710] LUN: removable file: (no medium)
[  115.545891] LUN: removable file: /backingfiles/music_disk.bin
[  115.545991] LUN: removable file: /backingfiles/cam_disk.bin
[  115.546001] Number of LUNs=2
[  115.550542] g_mass_storage gadget: Mass Storage Gadget, version: 2009/09/11
[  115.550559] g_mass_storage gadget: g_mass_storage ready
[  115.550574] dwc2 20980000.usb: bound driver g_mass_storage
[  115.950705] dwc2 20980000.usb: new device is high-speed
[  116.026961] dwc2 20980000.usb: new address 13
[  116.064460] g_mass_storage gadget: high-speed config #1: Linux File-Backed Storage

**Comment by sparky742** [comment]
I setup mine when the car was on 2020.4.x   worked great.  Since then, I've been through 2020.8 for a day, then 2020.12 and noticed that it failed last time I had a sentry event with "reformat the drive in a supported format" and "USB drive too slow"...so it may be the Tesla update that did it. I believe since these two updates, exFAT is now supported.

**Comment by jun3280net** [comment]
It took a while to find - but it appears this issue is likely related to the software update : 

[https://teslamotorsclub.com/tmc/threads/dash-cam-error-says-drive-is-full-but-its-nearly-empty.188108/#post-4564358](https://teslamotorsclub.com/tmc/threads/dash-cam-error-says-drive-is-full-but-its-nearly-empty.188108/#post-4564358)

**Comment by drlauridsen** [comment]
Same issue here, both with raspberry pi and standard USB drive.. Posted the issue on Twitter, maybe "like" if you have the issue..
https://twitter.com/JohnnyLauridse4/status/1245619926456401920?s=19

Could be related to exFat support with dashcam,  would there be any advantages using exFat on teslausb?

**Comment by sparky742** [comment]
yeah, I was guessing the exFAT change caused this.  Further to your tweet - my M3 is totally working fine with my FAT USB stick back in place, just not the rPi + TeslaUSB.

**Comment by drlauridsen** [comment]
> yeah, I was guessing the exFAT change caused this. Further to your tweet - my M3 is totally working fine with my FAT USB stick back in place, just not the rPi + TeslaUSB.

Strange. My FAT USB stick has the same error after some time..

**Comment by jun3280net** [comment]
> > yeah, I was guessing the exFAT change caused this. Further to your tweet - my M3 is totally working fine with my FAT USB stick back in place, just not the rPi + TeslaUSB.
> 
> Strange. My FAT USB stick has the same error after some time..

Just an update - looks like this issue has been addressed with 2020.12.5 update (which I received last night).  Will close this off once I can confirm things are good over the next couple days.

**Comment by jun3280net** [comment]
Not out of the woods yet - can anyone confirm whether their Music partition works?  If so, is the Music partition Fat32?  My videos are being recorded and synced, but my Music partition is not recognized in the car (Model S MCU1/AP2.5 2020.12.5).

**Comment by jun3280net** [comment]
2020.12.5 Fixes the dash cam recording issue which affected Model S/X (MCU1/AP2.5).  However it introduces the issue where the Music partition / USB Drive is no longer recognized.

[https://teslamotorsclub.com/tmc/threads/2020-12-5.190487/page-6](https://teslamotorsclub.com/tmc/threads/2020-12-5.190487/page-6)

**Comment by jun3280net** [comment]
> 2020.12.5 Fixes the dash cam recording issue which affected Model S/X (MCU1/AP2.5). However it introduces the issue where the Music partition / USB Drive is no longer recognized.
> 
> https://teslamotorsclub.com/tmc/threads/2020-12-5.190487/page-6

The music partition is now recognized too with update 2020.12.10
