### ISSUE TITLE
External storage 

### ISSUE THREAD

**Issue by jax-b** [marcone/teslausb#451]
To reduce wear and tear on the SD card it would be nice if during setup the pi looked for /dev/sdb which could be a t5 drive or usb stick to use first. That way the sd card would be used less (read only for boot) and if the usb stick fails you could just put a new one in and not have to reset up TeslaUSB.

**Comment by marcone** [comment]
"external" USB drive is already supported, see [the config file](https://github.com/marcone/teslausb/blob/main-dev/pi-gen-sources/00-teslausb-tweaks/files/teslausb_setup_variables.conf.sample#L21)
