### ISSUE TITLE
Support viewing/deleting exported footage in the car's built-in dashcam viewer

### ISSUE THREAD

**Issue by Gawdl3y** [marcone/teslausb#464]
With the 2020.12.5 update, the cars now have a built-in dashcam/sentry mode footage viewer. It'd be nice to be able to view the exported footage on the SMB share in the integrated viewer. This could likely be accomplished by mounting the CIFS share on the Pi and creating a temporary symbolic link to it from the actual TeslaCam/Sentry storage.

**Comment by marcone** [comment]
That won't work, because the CIFS share would have to be mounted on the car in order for the symbolic link target to meaningful.
