### ISSUE TITLE
Make use of new Json event metadata

### ISSUE THREAD

**Issue by washcroft** [marcone/teslausb#468]
Sentry mode in 2020.12.5 now has an event file with the reason, timestamp and location recorded:

![Imgur](https://i.imgur.com/WOlC48H.jpg)

Would this file also be archived alongside footage?

**Comment by marcone** [comment]
It should be archived for rclone and rsync, but cifs only archives files greater than 100K, so won't archive these. That needs to be fixed.

**Comment by marcone** [comment]
the json file is now archived for cifs too

**Comment by GoTeslaGo** [comment]
Awesome. Anything we have to do to get this to work? I’m running 20190615 so would a selfupdate resolve the issue for me or do I need to use a later version of TeslaUSB?

**Comment by marcone** [comment]
https://github.com/marcone/teslausb/wiki/FAQ#q-how-do-i-update-to-the-latest-version-of-teslausb
