### ISSUE TITLE
Not working with v10.2

### ISSUE THREAD

**Issue by ubehera** [marcone/teslausb#474]
Was working perfectly earlier, but I recently got FSD upgrade. It’s not being recognized by the car neither for dashcam, nor music since then. I tried reflashing latest code, but still the same issue. Switched to the other USB port, still no luck

**Comment by marcone** [comment]
Not enough information. See https://github.com/marcone/teslausb/issues/35

**Comment by jun3280net** [comment]
> Was working perfectly earlier, but I recently got FSD upgrade. It’s not being recognized by the car neither for dashcam, nor music since then. I tried reflashing latest code, but still the same issue. Switched to the other USB port, still no luck

Your issue might simply be related to the version of software you are on : 
[https://github.com/marcone/teslausb/issues/450](https://github.com/marcone/teslausb/issues/450)

Have you tried using a basic USB formatted with FAT32 for music or dashcam?

**Comment by ubehera** [comment]
> Not enough information. See #35
PFA the diagnostics file. Also added screenshot of the version I'm running, I don't think it's related to the S/X problem.
![IMG_1051](https://user-images.githubusercontent.com/3691059/80315373-6402f580-87b4-11ea-9c74-48be8fc0ab29.jpg)
 per #35 
[diagnostics.txt](https://github.com/marcone/teslausb/files/4536088/diagnostics.txt)

**Comment by ubehera** [comment]
> Not enough information. See #35

PFA diagnostics file and my current version number. I don't think this is related to the S/X issue.
[diagnostics.txt](https://github.com/marcone/teslausb/files/4536114/diagnostics.txt)
<img width="621" alt="Screen Shot 2020-04-26 at 12 00 20 PM" src="https://user-images.githubusercontent.com/3691059/80315572-a7aa2f00-87b5-11ea-8223-b4869caeeefa.png">

**Comment by ubehera** [comment]
> Have you tried using a basic USB formatted with FAT32 for music or dashcam?

Not yet, let me try to find a stick, I'll try it ASAP.

**Comment by jun3280net** [comment]
All good man.  I think with all these software updates Tesla has been
pushing through, its been breaking things.  They have too many branches of
configurations right now.  The basic USB setup is the quickest and easiest
thing to test before spending too much time debugging TeslaUsb.  Good luck!

**Comment by marcone** [comment]
Can you wait a little longer after boot before taking the diagnostics? In the diagnostics you attached, it was still trying to copy music from your server and hadn't made the drives accessible to the car/PC yet.
(and there seemed to be some problem contacting your server: `CIFS VFS: SMB signature verification returned error = -5`)

**Comment by ubehera** [comment]
Checked with USB stick, it works. I’ll pull logs again tonight.

**Comment by ubehera** [comment]
> Can you wait a little longer after boot before taking the diagnostics? In the diagnostics you attached, it was still trying to copy music from your server and hadn't made the drives accessible to the car/PC yet.
> (and there seemed to be some problem contacting your server: `CIFS VFS: SMB signature verification returned error = -5`)

@marcone attaching 2 log files, (1) was collected after a drive, and (2) was collected after a clean reboot in the garage.
[diagnostics-2.txt](https://github.com/marcone/teslausb/files/4536888/diagnostics-2.txt)
[diagnostics-1.txt](https://github.com/marcone/teslausb/files/4536889/diagnostics-1.txt)

I can confirm that a standard USB stick is working fine on both ports.

**Comment by marcone** [comment]
Your diagnostics are consistent with using a bad (or charge-only) USB cable.
You also seem to be having some issues with your archive server, as noted above.
Other than that, nothing stands out to me. Have you tried connecting the Pi to a PC?

**Comment by ubehera** [comment]
> Your diagnostics are consistent with using a bad (or charge-only) USB cable.
> 
> You also seem to be having some issues with your archive server, as noted above.
> 
> Other than that, nothing stands out to me. Have you tried connecting the Pi to a PC?
> 
> 
> 
> 

Yep. Works fine on PC. Also, nothing changed on the setup HW wise, compared to when it was working for last 4-5 months. It’s the same cable and same board. Only new FW on the car and new TeslaUSB version. Even the config file entries are the same that I used last time. The archive server is my personal Mac, so it is turned off sometimes.

**Comment by marcone** [comment]
If it works with a PC, and you're using the same cable with the car, then the problem is with the car. From the Pi/teslausb's point of view, there is no difference between being connected to a car or to a PC.

**Comment by ubehera** [comment]
@marcone Question, is there anything specific you want me to do on the PC to verify it’s working as intended. When I said it works “fine” I meant it’s booting up normally, not sure how to test the USB portion. Also, a normal USB stick is working in the car. I’ll try it again on PC and see if it shows up as a partition.

**Comment by marcone** [comment]
ah, when you said that it works with a PC I thought you meant that the cam/music drives show up on the PC.

**Comment by ubehera** [comment]
I can confirm that the USB drives do not show up on PC or Mac. I’ll try an older release and check.

**Comment by ubehera** [comment]
I’ll try an older release and check.

**Comment by marcone** [comment]
So far all signs point to a bad cable, or using the wrong USB port on the Pi.

**Comment by ubehera** [comment]
I’m gonna go to a corner and cry now. Sorry for wasting everyone’s time. I had it plugged into the power only port. I forgot that the case I use has them marked wrong. Sincere apologies.
