### ISSUE TITLE
(Workaround included) /etc/auto.master.d/teslausb.autofs: No such file or directory

### ISSUE THREAD

**Issue by maxhac03** [marcone/teslausb#479]
Issue:
After updating TeslaUSB to the latest version i got this error message:

> Downloaded /root/bin/auto.teslausb ...
> /tmp/configure-automount.sh: line 35: /etc/auto.master.d/teslausb.autofs: No such file or directory

I did a clean install using the teslausb-20190615 image and got the same error again.

Workaround:
I created both the auto.master.d folder and the teslausb.autofs file and the installation could complete.

**Comment by marcone** [comment]
Thanks, looks like perhaps that directory doesn't yet exist immediately after installing autofs. I'll update the setup script to create it.

**Comment by marcone** [comment]
Did you only try this with the teslausb-20190615 image?
I can't actually reproduce it with the latest image.

edit: looks like this only happens with the 20190615 image: the Stretch autofs package does not automatically create the auto.master.d folder, whereas the Buster package does.
