### ISSUE TITLE
Enable SAMBA but only TeslaCAM show up in Windows Network

### ISSUE THREAD

**Issue by mrteausa** [marcone/teslausb#485]
I enabled the SAMBA network share drive.  In Windows Network only TeslaCam folder show up but not the TeslaMusic.  How to make the TeslaMusic to show up also in the windows network drives.

**Comment by marcone** [comment]
Accessing music via Samba is not supported

**Comment by mrteausa** [comment]
Will you please add the TeslaMusic in Samba share for the future releases..  Thank you..
