### ISSUE TITLE
Saved and recent clips disappearing

### ISSUE THREAD

**Issue by nebukadnezar** [marcone/teslausb#487]
I've now had several instances when after pressing the camera icon to save clips, the clips it was supposed to save were missing completely. And the recent clips from after the save operation are missing for the remainder of the drive. This despite the camera icon having the red recording mark showing.

I don't even know where to begin with debugging this. Is it a Tesla fault? I even went so far as to completely reinstall TeslaUSB from scratch, which didn't fix it either. This is incredibly frustrating because I actually lost the recording of an important event because of this.

**Comment by marcone** [comment]
There isn't enough information here. See https://github.com/marcone/teslausb/issues/35
