### ISSUE TITLE
setup-teslausb fails: /tmp/verify-and-configure-archive.sh: line 140: log: command not found

### ISSUE THREAD

**Issue by RoByte** [marcone/teslausb#488]
https://github.com/marcone/teslausb/blob/0377d507b97e3e74a3bc0f2d31048399d921eb49/run/cifs_archive/verify-and-configure-archive.sh#L140

Should that line be log_progress instead?

**Comment by marcone** [comment]
Yes it should. Thanks for reporting. It's fixed now.
