### ISSUE TITLE
Doesn't recover from driving away while moving files

### ISSUE THREAD

**Issue by gchilders** [marcone/teslausb#49]
I made a brief stop at home today then left again a few minutes later. While I was home the Pi started moving the files to the network share.  I drove away before it was complete and the Pi did not recover.  15 minutes into the drive the dashcam icon still hadn't returned.  Restarting the Pi by unplugging it and plugging it back in fixed it, but can we make is so that the script notices the share is no longer working when trying to move files.

**Comment by marcone** [comment]
That's supposed to work, and works for me. Please file bugs with logs, otherwise there's not much I can do.
