### ISSUE TITLE
SNTP error

### ISSUE THREAD

**Issue by cleanev** [marcone/teslausb#490]
With latest commit that uses TeslaUSB.service and sntp using time.google.com below is what I see when I check status of teslausb.service.

Is this supposed to be throwing this error due to read-only system and does this have any impact?

● teslausb.service - TeslaUSB archiveloop service
   Loaded: loaded (/lib/systemd/system/teslausb.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2020-05-30 18:13:39 EDT; 2min 22s ago
 Main PID: 200 (bash)
   Memory: 5.4M
   CGroup: /system.slice/teslausb.service
           ├─ 200 /bin/bash /root/bin/archiveloop
           ├─ 205 flock -en -E 99 /root/bin/archiveloop /root/bin/archiveloop
           ├─ 207 /bin/bash -eu /root/bin/archiveloop
           ├─ 390 /bin/bash -eu /root/bin/archiveloop
           ├─ 395 sleep 3480
           └─1077 sleep 1

May 30 18:14:06 EL3CTRC bash[200]: sntp 4.2.8p12@1.3728-o (1)
May 30 18:14:06 EL3CTRC bash[200]: **Can't open KOD db file /var/lib/sntp/kod for writing: Read-only file system**
May 30 18:14:06 EL3CTRC bash[200]: Send to [2001:4860:4806:4::]:123 failed, Network is unreachable
May 30 18:14:08 EL3CTRC bash[200]: Send to [2001:4860:4806:c::]:123 failed, Network is unreachable
May 30 18:14:10 EL3CTRC bash[200]: Send to [2001:4860:4806::]:123 failed, Network is unreachable
May 30 18:14:12 EL3CTRC bash[200]: Send to [2001:4860:4806:8::]:123 failed, Network is unreachable
May 30 18:14:12 EL3CTRC bash[200]: time.google.com 216.239.35.0 no UCST response after 5 seconds
May 30 18:14:14 EL3CTRC bash[200]: sntp 4.2.8p12@1.3728-o (1)
May 30 18:14:14 EL3CTRC bash[200]: **Can't open KOD db file /var/lib/sntp/kod for writing: Read-only file system**
May 30 18:14:14 EL3CTRC bash[200]: 2020-05-30 18:14:14.305261 (+0500) +32.320249 +/- 21.546970 time.google.com 216.239.35.12 s1 no-leap

**Comment by marcone** [comment]
> Is this supposed to be throwing this error due to read-only system and does this have any impact?

Yes, and no.
