### ISSUE TITLE
Won't mount on computer (Mac)

### ISSUE THREAD

**Issue by automartin5000** [marcone/teslausb#492]
Using the pre-made image, I got the setup to complete (it took some extra work because of Raspbian mirror issues and pip install issues). AP works, RClone appears to work, but the drive isn't mounting on either of my Macs. It wasn't mounting before or after I setup RClone. And I've tried with both a dedicated power cable and using a single cable. What's the best way to troubleshoot?

**Comment by marcone** [comment]
See https://github.com/marcone/teslausb/issues/35

**Comment by automartin5000** [comment]
Checked all that, but I’ll ask on Discord
