### ISSUE TITLE
Question re initial setup to get music files to SDCARD fast

### ISSUE THREAD

**Issue by bit-bash** [marcone/teslausb#494]
When a new teslausb image is created, after it is setup and syncs to my PC it will download all my music files to the SDCARD over wifi.  This is slow for a LOT of music.

I'm wondering if there's some way I could mount the SDCARD in linux (ubuntu) and just copy my music files directly to the right place on the SDCARD?

I know there is a bit of time stamping magic that goes on with the music files, and IIRC the files copied to the SDCARD have their time set about 2 seconds later than the files on the PC.  What I can't remember if the copied files have to be exactly 2 seconds later or any time stamp later than the PC.  I don't want to manually copy over LOTS of music and then have telsausb think all the music is "dirty" and start copying them all over again.

If there's an easy way to do this that would be awesome!  If the time stamps can be anything later than the PC music file then I can simply "touch" all the music files I copy over.

Thanks!

**Comment by marcone** [comment]
They don't have to be exactly 2 seconds later, they just need to be the same or later.

**Comment by bit-bash** [comment]
Thanks - this all worked.
What I did was backup my "old" music image file first.
Made a new SDCARD and got it up and running (hiding all my music on the share).
Then I loopback mounted the music image file and copied all my old music to the new SDCARD directly in Ubuntu.
Before starting up the SDCARD again, I un-hid all my music on the share.  When it finally came up, yay, it was already sync'd and didn't need to download all the music over the slower wifi.
