### ISSUE TITLE
No Home WiFi

### ISSUE THREAD

**Issue by stormtrooperbatman** [marcone/teslausb#506]
Hello,
I was able to format and flash my Raspberry Pi W Zero with a 256GB microSD card.  For all intents and purposes, I do not have a home wifi (I mean, I do, but my Tesla is parked in a parking garage and can't reach my apartment WiFi).  I wanted to use this as a method of simply storing the sentry mode and dashcam footage on the microSD card until I need to access it, and my thought was if I need to access it, to take the microSD card out or connect to the Pi's WiFi with my laptop and pull the videos over.  However, it looks like I didn't read enough and only the last hour of dashcam footage is saved and not archived to the backinglog file.  

When I tried to leave the initial WiFi/sharename portion of the variables file untouched, the setup never completed with a STOP unable to connect to share error.  Ok no problem, so I uncommented those lines as it's not needed.  I reran setup (I reflashed and re imaged it actually) and now the Pi is stuck with a solid green LED and I can't connect to it.  

Am I basically trying to use this for an unintended purpose?  Should I simply just plug the microSD card into a USB reader and plug that into the Tesla?  

I can post files here if needed, but I can't access the pi right now so not sure how to get it.  

Thank you,
STBM

**Comment by marcone** [comment]
you can use `export ARCHIVE_SYSTEM=none` in the config file
