### ISSUE TITLE
Sentry/Autolock exclude home fails, both turn back on

### ISSUE THREAD

**Issue by sherrysj** [marcone/teslausb#509]
As above. Removing the rasp pi restores normal function of Sentry/Autolock exclude home option.

**Comment by marcone** [comment]
Did you configure teslausb to use the Tesla API to keep the car awake while archiving?

**Comment by sherrysj** [comment]
Yes, I set up the Teslausb to use to the Tesla API to keep the car awake while archiving, which it does, but it also might be uncovering a conflict in the way Tesla implements the exclude home preference for walk away lock and sentry mode. 

My expectation is that the car wouldn’t turn on these modes in my garage, but it does when using the Teslausb - configured with the option to keep awake while archiving, and does not when the Teslausb is unplugged.

Thanks for creating the Teslausb - it’s a great project,

-Steve

**Comment by marcone** [comment]
When configured to use the Tesla API, teslausb will turn on Sentry mode during archiving to keep the car away. If that interferes with the "exclude home" feature of Sentry mode, then the only remedy is to not have teslausb use the Tesla API. You would have to find some other way to keep the Pi awake during archiving, e.g. by turning on climate, or using a battery.
