### ISSUE TITLE
Dashcam and Music not showing up after some time. 

### ISSUE THREAD

**Issue by kdvlr** [marcone/teslausb#51]
The USB works great at the beginning transferring files, doing the initial music sync. However, after a long time, say overnight, the dashcam drive does not show up. I have to restart the pi for it to show backup. DAE have this problem? 

It looks like this might be caused by frequent connect/disconnects. Is there a way we can sync only once and not sync again till the wifi is disconnected ?

And/or unmount and remount once car transitions from asleep to online ?

**Comment by marcone** [comment]
> It looks like this might be caused by frequent connect/disconnects. Is there a way we can sync only once and not sync again till the wifi is disconnected ?

That's already what it does, so sounds like you have some other problem. Without logs, there isn't anything I can do.
