### ISSUE TITLE
How to fix "Long filename fragment" error?

### ISSUE THREAD

**Issue by Vipercat** [marcone/teslausb#511]
@marcone,

After running TeslaUSB for months and months without any issues, things changed after updating to 2020.16.2.1 somewhere in May. I then decided to do a full reinstall using the 'teslausb-20200122' release. I probably shouldn't have done that, because I now constantly get the "USB too Slow message". 
Although this message appears continuously the RPI does seem to hold recordings. Unfortunately with files that looks corrupt. The log therefore shows messages about "long filename fragments" and when I look in the /mnt/cam/TeslaCam/RecentClips folder I see MP4-files with incomplete names. I'm able to delete those files, but when I then reboot the RPI I keep getting the errors about the "long filename fragments" (see below):

==============================================
Wed 15 Jul 20:22:21 CEST 2020: Starting archiveloop at 21.63 seconds uptime...
Wed 15 Jul 20:22:21 CEST 2020: Running fsck on /backingfiles/cam_disk.bin...
Wed 15 Jul 20:22:22 CEST 2020: | fsck from util-linux 2.33.1
Wed 15 Jul 20:22:30 CEST 2020: | fsck.fat 4.1 (2017-01-24)
Wed 15 Jul 20:22:30 CEST 2020: | Long filename fragment "2020-07-15_19" found outside a LFN sequence.
Wed 15 Jul 20:22:30 CEST 2020: |   (Maybe the start bit is missing on the last fragment)
Wed 15 Jul 20:22:30 CEST 2020: |   Not auto-correcting this.
Wed 15 Jul 20:22:30 CEST 2020: | Long filename fragment "2020-07-15_20" found outside a LFN sequence.
Wed 15 Jul 20:22:30 CEST 2020: |   (Maybe the start bit is missing on the last fragment)
Wed 15 Jul 20:22:30 CEST 2020: |   Not auto-correcting this.
Wed 15 Jul 20:22:30 CEST 2020: | Long filename fragment "2020-07-15_10" found outside a LFN sequence.
Wed 15 Jul 20:22:30 CEST 2020: |   (Maybe the start bit is missing on the last fragment)
Wed 15 Jul 20:22:30 CEST 2020: |   Not auto-correcting this.
Wed 15 Jul 20:22:30 CEST 2020: | /dev/loop0p1: 7 files, 9/2094976 clusters
Wed 15 Jul 20:22:30 CEST 2020: Finished fsck on /backingfiles/cam_disk.bin.
Wed 15 Jul 20:22:30 CEST 2020: Running fsck on /backingfiles/music_disk.bin...
Wed 15 Jul 20:22:31 CEST 2020: | fsck from util-linux 2.33.1
Wed 15 Jul 20:22:33 CEST 2020: | fsck.fat 4.1 (2017-01-24)
Wed 15 Jul 20:22:33 CEST 2020: | /dev/loop0p1: 17 files, 886227/1046272 clusters
Wed 15 Jul 20:22:33 CEST 2020: Finished fsck on /backingfiles/music_disk.bin.
Wed 15 Jul 20:22:34 CEST 2020: Connecting usb to host...
Wed 15 Jul 20:22:34 CEST 2020: Connected usb to host.
Wed 15 Jul 20:22:34 CEST 2020: Waiting for archive to be reachable...
Wed 15 Jul 20:22:37 CEST 2020: Archive is reachable.
Wed 15 Jul 20:22:37 CEST 2020: Trying to set time...
Wed 15 Jul 20:23:09 CEST 2020: Time adjusted by 31.129046 seconds after 0.920000 seconds
Wed 15 Jul 20:23:29 CEST 2020: Disconnecting usb from host...
Wed 15 Jul 20:23:29 CEST 2020: Disconnected usb from host.
Wed 15 Jul 20:23:29 CEST 2020: Running fsck on /backingfiles/cam_disk.bin...
Wed 15 Jul 20:23:30 CEST 2020: | fsck from util-linux 2.33.1
Wed 15 Jul 20:23:32 CEST 2020: | fsck.fat 4.1 (2017-01-24)
Wed 15 Jul 20:23:32 CEST 2020: | Long filename fragment "2020-07-15_19" found outside a LFN sequence.
Wed 15 Jul 20:23:32 CEST 2020: |   (Maybe the start bit is missing on the last fragment)
Wed 15 Jul 20:23:32 CEST 2020: |   Not auto-correcting this.
Wed 15 Jul 20:23:32 CEST 2020: | Long filename fragment "2020-07-15_20" found outside a LFN sequence.
Wed 15 Jul 20:23:32 CEST 2020: |   (Maybe the start bit is missing on the last fragment)
Wed 15 Jul 20:23:32 CEST 2020: |   Not auto-correcting this.
Wed 15 Jul 20:23:32 CEST 2020: | Long filename fragment "2020-07-15_10" found outside a LFN sequence.
Wed 15 Jul 20:23:32 CEST 2020: |   (Maybe the start bit is missing on the last fragment)
Wed 15 Jul 20:23:32 CEST 2020: |   Not auto-correcting this.
Wed 15 Jul 20:23:32 CEST 2020: | /dev/loop0p1: 7 files, 9/2094976 clusters
Wed 15 Jul 20:23:33 CEST 2020: Finished fsck on /backingfiles/cam_disk.bin.
Wed 15 Jul 20:23:33 CEST 2020: Running fsck on /backingfiles/music_disk.bin...
Wed 15 Jul 20:23:33 CEST 2020: | fsck from util-linux 2.33.1
Wed 15 Jul 20:23:37 CEST 2020: | /dev/loop0p1: 17 files, 886227/1046272 clusters
Wed 15 Jul 20:23:37 CEST 2020: Finished fsck on /backingfiles/music_disk.bin.
Wed 15 Jul 20:23:37 CEST 2020: Archiving...
Wed 15 Jul 20:23:37 CEST 2020: Ensuring cam archive is mounted...
Wed 15 Jul 20:23:38 CEST 2020: Mounting /mnt/archive...
Wed 15 Jul 20:23:39 CEST 2020: Mounted /mnt/archive.
Wed 15 Jul 20:23:39 CEST 2020: Ensured cam archive is mounted.
Wed 15 Jul 20:23:40 CEST 2020: Ensuring music archive is mounted...
Wed 15 Jul 20:23:40 CEST 2020: Mounting /mnt/musicarchive...
Wed 15 Jul 20:23:40 CEST 2020: Mounted /mnt/musicarchive.
Wed 15 Jul 20:23:40 CEST 2020: Ensured music archive is mounted.
Wed 15 Jul 20:23:40 CEST 2020: Checking saved folder count...
Wed 15 Jul 20:23:40 CEST 2020: Ensuring cam file is mounted...
Wed 15 Jul 20:23:40 CEST 2020: Mounting /mnt/cam...
Wed 15 Jul 20:23:40 CEST 2020: Mounted /mnt/cam.
Wed 15 Jul 20:23:40 CEST 2020: Ensured cam file is mounted.
Wed 15 Jul 20:23:44 CEST 2020: There are 0 event folder(s) with 0 file(s) to move.
Wed 15 Jul 20:23:44 CEST 2020: Trimming free space in /mnt/cam, which has 3 extents
Wed 15 Jul 20:23:45 CEST 2020: Trim complete, image now has 2 extents
Wed 15 Jul 20:23:45 CEST 2020: Unmounting /mnt/cam...
Wed 15 Jul 20:23:45 CEST 2020: Unmounted /mnt/cam.
Wed 15 Jul 20:23:45 CEST 2020: Finished archiving.
Wed 15 Jul 20:23:45 CEST 2020: Copying music...
Wed 15 Jul 20:23:45 CEST 2020: Starting music sync...
Wed 15 Jul 20:23:45 CEST 2020: Ensuring music backing file is mounted...
Wed 15 Jul 20:23:45 CEST 2020: Mounting /mnt/music...
Wed 15 Jul 20:23:46 CEST 2020: Mounted /mnt/music.
Wed 15 Jul 20:23:46 CEST 2020: Ensured music drive is mounted.
Wed 15 Jul 20:23:46 CEST 2020: Copying music from archive...
Wed 15 Jul 20:23:48 CEST 2020: Copied 0 music file(s), deleted 0, skipped 15 previously-copied files, encountered 0 cop$Wed 15 Jul 20:23:48 CEST 2020: Trimming free space in /mnt/music, which has 1 extents
Wed 15 Jul 20:23:49 CEST 2020: Trim complete, image now has 1 extents
Wed 15 Jul 20:23:49 CEST 2020: Unmounting /mnt/music...
Wed 15 Jul 20:23:49 CEST 2020: Unmounted /mnt/music.
Wed 15 Jul 20:23:49 CEST 2020: Finished copying music.
Wed 15 Jul 20:23:49 CEST 2020: unmounting /mnt/archive
Wed 15 Jul 20:23:49 CEST 2020: Connecting usb to host...
Wed 15 Jul 20:23:49 CEST 2020: unmounting /mnt/musicarchive
Wed 15 Jul 20:23:50 CEST 2020: Connected usb to host.
Wed 15 Jul 20:23:50 CEST 2020: Waiting for archive to be unreachable...

Is there a way to fix these errors? The only way to fix them now is deleting the cam_disk.bin file and run the setup-teslausb again. 

And do anyone have a clue why the "USB too Slow" seems inevitable ever since v2020.16.x.x? It's driving me crazy. I've tied to tweak the performance with the vm.dirty setting and nofua=1,1 but nothing seems to help. The RPI read and write performance to a Linux OS on my notebook is +/- 22MB per second, so fast enough in my opinion....

Thanks,
Vipercat

**Comment by marcone** [comment]
Those aren't errors, they're informational messages from the filesystem checker. It's basically finding recordings/folders that the car deleted from the sd card.
As for slowness, 22MB/sec is more than enough (though if that was on a Pi0 you probably measured it wrong, as it's generally a bit lower than that), but nobody knows what method the car uses to decide that the card is too slow, so there isn't really anything that can be done.
