### ISSUE TITLE
Question: Advice on Zero W vs 4

### ISSUE THREAD

**Issue by craigkovatch** [marcone/teslausb#513]
I would like to request an addition to the FAQ explaining how to choose between a Zero W and a 4. My instinct is to get a W for the reduced power usage/heat, but I would like to understand the tradeoffs between the two before making a hardware selection.

**Comment by marcone** [comment]
I think that giving such advice is outside the scope of the teslausb project. Both work for teslausb, so it's really up to you. The only case where you must use a Pi4 is if you want to use a hard drive for storage, since the Pi0 does not support that.
