### ISSUE TITLE
What are "snapshots"? This doesn't seem to be documented anywhere

### ISSUE THREAD

**Issue by craigkovatch** [marcone/teslausb#514]
In the sample conf file:
`# Uncomment to disable snapshots. This also disables samba and RecentClips-extension`

But there's no documentation on this github or in the README etc. of what "snapshots" are and why I might want to disable them.

**Comment by marcone** [comment]
snapshots are an implementation detail, and disabling them is not something I plan on supporting for much longer, so I'm not going to document them any further.

**Comment by craigkovatch** [comment]
@marcone thanks. Until then though, I would kindly suggest adding some additional comments in the config, since it does present itself as a "must-make" decision (whether that's actually true or not) for first-time setup.
