### ISSUE TITLE
Suggestion: reverse proxy all the things

### ISSUE THREAD

**Issue by haakonstorm** [marcone/teslausb#521]
Teslausb is magic!
But extremely insecure, We need to fix this, I'll do my part, but won't have much time until end of month. Some ideas:

- ´teslausb´ needs (1) a network share to do its magic, 
  - since (1) hence we assume (2) a server with (3) e.g. a samba service is already up,
  -  and there is (4) a route from teslausb to server, perhaps also (5) a route to the internet

- we configure a simple service on the server to either poll, looking for the teslausb by pinging for open samba ports, or have teslausb let server know its home, via anything between teslausb emailing or triggering a webhook. 

- a simple technique that would work would actually be the good old ´port knocking´ technique. say we implement a pin code of 1234, teslausb can ping server:1001, wait 2 seconds, ping server:1002, wait, ping 1003, wait, ping 1004. 

- Or, if we only have regular ping available, server wait for first knock via a ping, then assuming our shared 1234, it expects a series of pings spaced with 1 second, then 2 seconds then 3 and 4 seconds, before calling the Tesla API or Home Assistant API or whatever we set up to keep the car awake, before triggering a bidirectional ´rsync --delete´ over ssh with public/private key authentication.

- Depending on details, we can disable samba on the teslausb altogether, and also remove all tesla credentials.

- In the interim, all user credentials in the ´.conf´should at least be covered in a simple layer of a base64 encoding or, i dont know vanilla freebsd that good, but some posix password tool that employs some simple means of storing credentials and only allowing those to be accessed in two particular cases 1: rsync files over ssh to the server, logging in with a user that only has write access to where it needs to dump stuff, and 2: rsync fils over ssh from the server, user has only read access to e.g. the music folder 

just my .05, I'll be back with some more when time. Sorry about formatting and my guerrilla norwegian-english, shoulve paid more attention in english class. Be seeing you

**Comment by marcone** [comment]
It's a neat idea in theory, but it's not something I want to pursue.
Some thoughts:
> ´teslausb´ needs (1) a network share to do its magic,

not actually true. It also works with rsync and more importantly rclone, letting you back up to Google Drive, DropBox, Amazon S3, etc. In these cases there is no server to ping and trigger a sync.
Even when people do use a network share, that doesn't necessarily mean that they have a server capable of running a custom service. It could just be a "dumb" NAS, for example. And even if the server is capable of running a custom service, you would then have to provide that service for a variety of different systems, e.g. a unix NAS, a Windows PC, a Mac, and who knows what else. It just adds way more complexity.

> In the interim, all user credentials in the ´.conf´should at least be covered in a simple layer of a base64 encoding

Base64 encoding doesn't add any security. If someone is smart enough to steal your Pi and then go poking around in it, they'll have no problem decoding that base64 string.

It's not clear to me what exactly you're trying to protect against. If you're worried about the presence of credentials on a device that might get stolen from your car, you could solve that by not having the Pi connect to wifi at all and only have it provide its own AP. Then when you want to archive, you connect to the Pi's AP and copy the files over. There would be no wifi or account credentials on the Pi in that scenario.
