### ISSUE TITLE
grep: /root/bin/setup-teslausb: No such file or directory (STOP: failed to update setup-teslausb)

### ISSUE THREAD

**Issue by CmSCMU** [marcone/teslausb#53]
I'm attempting a manual install with GDrive and Pushover. I keep running into the same error on the last step when I try to run the TeslaUSB setup. Specifically, I get:

grep: /root/bin/setup-teslausb: No such file or directory
setup-teslausb is outdated, attempting update
STOP: failed to update setup-teslausb

I have looked over the closed and open issues and don't see anyone who is having a similar issue. I was wondering if you could tell me where I'm going wrong. Here is the log from my setup:

PS C:\Users\chads> ssh pi@raspberrypi
The authenticity of host 'raspberrypi (fe80::57c4:d551:6557:a7a8%20)' can't be established.
ECDSA key fingerprint is SHA256:S5vf5pIwnKt+NY5HxbNRBDkNcM8xCTNNdIB54meku+4.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'raspberrypi,fe80::57c4:d551:6557:a7a8%20' (ECDSA) to the list of known hosts.
pi@raspberrypi's password:
Linux raspberrypi 4.14.98+ #1200 Tue Feb 12 20:11:02 GMT 2019 armv6l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.

SSH is enabled and the default password for the 'pi' user has not been changed.
This is a security risk - please login as the 'pi' user and type 'passwd' to set a new password.

pi@raspberrypi:~ $ passwd
Changing password for pi.
(current) UNIX password:
Enter new UNIX password:
Retype new UNIX password:
passwd: password updated successfully
pi@raspberrypi:~ $ sudo -i

SSH is enabled and the default password for the 'pi' user has not been changed.
This is a security risk - please login as the 'pi' user and type 'passwd' to set a new password.

root@raspberrypi:~# curl -L https://raw.github.com/pageauc/rclone4pi/master/rclone-install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2508  100  2508    0     0   3451      0 --:--:-- --:--:-- --:--:--  3451
bash ver 1.6 written by Claude Pageau
-------------------------------------------------------------------------------
--2019-05-29 05:01:27--  https://downloads.rclone.org/rclone-current-linux-arm.zip
Resolving downloads.rclone.org (downloads.rclone.org)... 2a02:24e0:8:61f9::1, 5.153.250.7
Connecting to downloads.rclone.org (downloads.rclone.org)|2a02:24e0:8:61f9::1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9447065 (9.0M) [application/zip]
Saving to: ‘rclone.zip’

rclone.zip                                          100%[==================================================================================================================>]   9.01M  2.00MB/s    in 5.2s

2019-05-29 05:01:33 (1.74 MB/s) - ‘rclone.zip’ saved [9447065/9447065]

unzip rclone.zip to folder rclone-tmp
Archive:  rclone.zip
  inflating: rclone-tmp/rclone.1
  inflating: rclone-tmp/README.txt
 extracting: rclone-tmp/git-log.txt
  inflating: rclone-tmp/README.html
  inflating: rclone-tmp/rclone
Install files and man pages
Purging old database entries in /usr/share/man...
Processing manual pages under /usr/share/man...
Purging old database entries in /usr/share/man/fr.UTF-8...
Processing manual pages under /usr/share/man/fr.UTF-8...
Purging old database entries in /usr/share/man/sl...
Processing manual pages under /usr/share/man/sl...
Purging old database entries in /usr/share/man/sv...
Processing manual pages under /usr/share/man/sv...
Purging old database entries in /usr/share/man/ko...
Processing manual pages under /usr/share/man/ko...
Purging old database entries in /usr/share/man/ja...
Processing manual pages under /usr/share/man/ja...
Purging old database entries in /usr/share/man/da...
Processing manual pages under /usr/share/man/da...
Purging old database entries in /usr/share/man/de...
Processing manual pages under /usr/share/man/de...
Purging old database entries in /usr/share/man/ru...
Processing manual pages under /usr/share/man/ru...
Purging old database entries in /usr/share/man/pl...
Processing manual pages under /usr/share/man/pl...
Purging old database entries in /usr/share/man/hu...
Processing manual pages under /usr/share/man/hu...
Purging old database entries in /usr/share/man/nl...
Processing manual pages under /usr/share/man/nl...
Purging old database entries in /usr/share/man/es...
Processing manual pages under /usr/share/man/es...
Purging old database entries in /usr/share/man/pt_BR...
Processing manual pages under /usr/share/man/pt_BR...
Purging old database entries in /usr/share/man/tr...
Processing manual pages under /usr/share/man/tr...
Purging old database entries in /usr/share/man/fr...
Processing manual pages under /usr/share/man/fr...
Purging old database entries in /usr/share/man/it...
Processing manual pages under /usr/share/man/it...
Purging old database entries in /usr/share/man/fi...
Processing manual pages under /usr/share/man/fi...
Purging old database entries in /usr/share/man/fr.ISO8859-1...
Processing manual pages under /usr/share/man/fr.ISO8859-1...
Purging old database entries in /usr/share/man/id...
Processing manual pages under /usr/share/man/id...
Purging old database entries in /usr/share/man/pt...
Processing manual pages under /usr/share/man/pt...
Purging old database entries in /usr/share/man/zh_CN...
Processing manual pages under /usr/share/man/zh_CN...
Purging old database entries in /usr/share/man/zh_TW...
Processing manual pages under /usr/share/man/zh_TW...
Purging old database entries in /usr/share/man/gl...
Processing manual pages under /usr/share/man/gl...
Purging old database entries in /usr/share/man/cs...
Processing manual pages under /usr/share/man/cs...
Processing manual pages under /usr/local/man...
Updating index cache for path `/usr/local/man/man1'. Wait...done.
Checking for stray cats under /usr/local/man...
Checking for stray cats under /var/cache/man/oldlocal...
1 man subdirectory contained newer manual pages.
1 manual page was added.
0 stray cats were added.
15 old database entries were purged.
Deleting rclone.zip and Folder rclone-tmp
rclone is installed at /usr/bin/rclone
rclone v1.47.0
- os/arch: linux/arm
- go version: go1.12.4
--2019-05-29 05:01:46--  https://raw.github.com/pageauc/rclone4pi/master/rclone-sync.sh
Resolving raw.github.com (raw.github.com)... 151.101.204.133
Connecting to raw.github.com (raw.github.com)|151.101.204.133|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/pageauc/rclone4pi/master/rclone-sync.sh [following]
--2019-05-29 05:01:46--  https://raw.githubusercontent.com/pageauc/rclone4pi/master/rclone-sync.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.232.32.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.232.32.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4337 (4.2K) [text/plain]
Saving to: ‘rclone-sync.sh’

rclone-sync.sh                                      100%[==================================================================================================================>]   4.24K  --.-KB/s    in 0.001s

2019-05-29 05:01:46 (4.51 MB/s) - ‘rclone-sync.sh’ saved [4337/4337]

--2019-05-29 05:01:46--  https://raw.github.com/pageauc/rclone4pi/master/Readme.md
Resolving raw.github.com (raw.github.com)... 199.232.32.133
Connecting to raw.github.com (raw.github.com)|199.232.32.133|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/pageauc/rclone4pi/master/Readme.md [following]
--2019-05-29 05:01:47--  https://raw.githubusercontent.com/pageauc/rclone4pi/master/Readme.md
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.204.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.204.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1739 (1.7K) [text/plain]
Saving to: ‘Readme.md’

Readme.md                                           100%[==================================================================================================================>]   1.70K  --.-KB/s    in 0.002s

2019-05-29 05:01:47 (900 KB/s) - ‘Readme.md’ saved [1739/1739]

--2019-05-29 05:01:47--  https://raw.github.com/pageauc/rclone4pi/master/rclone-install.sh
Resolving raw.github.com (raw.github.com)... 151.101.204.133
Connecting to raw.github.com (raw.github.com)|151.101.204.133|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/pageauc/rclone4pi/master/rclone-install.sh [following]
--2019-05-29 05:01:48--  https://raw.githubusercontent.com/pageauc/rclone4pi/master/rclone-install.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.204.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.204.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2508 (2.4K) [text/plain]
Saving to: ‘rclone-install.sh’

rclone-install.sh                                   100%[==================================================================================================================>]   2.45K  --.-KB/s    in 0.001s

2019-05-29 05:01:48 (2.68 MB/s) - ‘rclone-install.sh’ saved [2508/2508]

rclone installed at /usr/bin/rclone
-------------------------------------------------------------------------------
                 INSTRUCTIONS Google Drive Example

1 You will be required to have a login account on the remote storage service
  Open putty SSH login session to RPI and execute command below

  rclone config

  Follow rclone prompts. For more Details See
  https://github.com/pageauc/rclone4pi/wiki/Home
2 At name> prompt specify a reference name  eg gdmedia
3 At storage> prompt Enter a remote storage number from List
4 Select Auto Config, At Link: prompt, left click
  and highlight rclone url link (do not hit enter)
5 on computer web browser url bar right click paste and go.
6 On computer web browser security page, Confirm access.
7 Copy web browser access security token and paste
  into RPI SSH session rclone prompt. Enter to accept
8 To test remote service access. Execute the following where
  gdmedia is the name you gave your remote service

  rclone ls gdmedia:/

Example sync command make source identical to destination

rclone sync -v /home/pi/rpi-sync gdmedia:/rpi-sync

To upgrade

  cd rpi-sync
  ./rclone-install.sh upgrade

For more Details See https://github.com/pageauc/rclone4pi/wiki/Home
Bye

root@raspberrypi:~# rclone config
2019/05/29 05:01:58 NOTICE: Config file "/root/.config/rclone/rclone.conf" not found - using defaults
No remotes found - make a new one
n) New remote
s) Set configuration password
q) Quit config
n/s/q> n
name> gdrive
Type of storage to configure.
Enter a string value. Press Enter for the default ("").
Choose a number from below, or type in your own value
 1 / A stackable unification remote, which can appear to merge the contents of several remotes
   \ "union"
 2 / Alias for a existing remote
   \ "alias"
 3 / Amazon Drive
   \ "amazon cloud drive"
 4 / Amazon S3 Compliant Storage Provider (AWS, Alibaba, Ceph, Digital Ocean, Dreamhost, IBM COS, Minio, etc)
   \ "s3"
 5 / Backblaze B2
   \ "b2"
 6 / Box
   \ "box"
 7 / Cache a remote
   \ "cache"
 8 / Dropbox
   \ "dropbox"
 9 / Encrypt/Decrypt a remote
   \ "crypt"
10 / FTP Connection
   \ "ftp"
11 / Google Cloud Storage (this is not Google Drive)
   \ "google cloud storage"
12 / Google Drive
   \ "drive"
13 / Hubic
   \ "hubic"
14 / JottaCloud
   \ "jottacloud"
15 / Koofr
   \ "koofr"
16 / Local Disk
   \ "local"
17 / Mega
   \ "mega"
18 / Microsoft Azure Blob Storage
   \ "azureblob"
19 / Microsoft OneDrive
   \ "onedrive"
20 / OpenDrive
   \ "opendrive"
21 / Openstack Swift (Rackspace Cloud Files, Memset Memstore, OVH)
   \ "swift"
22 / Pcloud
   \ "pcloud"
23 / QingCloud Object Storage
   \ "qingstor"
24 / SSH/SFTP Connection
   \ "sftp"
25 / Webdav
   \ "webdav"
26 / Yandex Disk
   \ "yandex"
27 / http Connection
   \ "http"
Storage> 12
** See help for drive backend at: https://rclone.org/drive/ **

Google Application Client Id
Setting your own is recommended.
See https://rclone.org/drive/#making-your-own-client-id for how to create your own.
If you leave this blank, it will use an internal key which is low performance.
Enter a string value. Press Enter for the default ("").
client_id> [removed]
Google Application Client Secret
Setting your own is recommended.
Enter a string value. Press Enter for the default ("").
client_secret> [removed]
Scope that rclone should use when requesting access from drive.
Enter a string value. Press Enter for the default ("").
Choose a number from below, or type in your own value
 1 / Full access all files, excluding Application Data Folder.
   \ "drive"
 2 / Read-only access to file metadata and file contents.
   \ "drive.readonly"
   / Access to files created by rclone only.
 3 | These are visible in the drive website.
   | File authorization is revoked when the user deauthorizes the app.
   \ "drive.file"
   / Allows read and write access to the Application Data folder.
 4 | This is not visible in the drive website.
   \ "drive.appfolder"
   / Allows read-only access to file metadata but
 5 | does not allow any access to read or download file content.
   \ "drive.metadata.readonly"
scope> 3
ID of the root folder
Leave blank normally.
Fill in to access "Computers" folders. (see docs).
Enter a string value. Press Enter for the default ("").
root_folder_id>
Service Account Credentials JSON file path
Leave blank normally.
Needed only if you want use SA instead of interactive login.
Enter a string value. Press Enter for the default ("").
service_account_file>
Edit advanced config? (y/n)
y) Yes
n) No
y/n> n
Remote config
Use auto config?
 * Say Y if not sure
 * Say N if you are working on a remote or headless machine
y) Yes
n) No
y/n> n
If your browser doesn't open automatically go to the following link: [removed]
Log in and authorize rclone for access
Enter verification code> [removed]
Configure this as a team drive?
y) Yes
n) No
y/n> n
--------------------
[gdrive]
type = drive
client_id = [removed]
client_secret = [removed]
scope = drive.file
token = [removed]
--------------------
y) Yes this is OK
e) Edit this remote
d) Delete this remote
y/e/d> y
Current remotes:

Name                 Type
====                 ====
gdrive               drive

e) Edit existing remote
n) New remote
d) Delete remote
r) Rename remote
c) Copy remote
s) Set configuration password
q) Quit config
e/n/d/r/c/s/q> q
root@raspberrypi:~# export ARCHIVE_SYSTEM=rclone
root@raspberrypi:~# export RCLONE_DRIVE=gdrive
root@raspberrypi:~# export RCLONE_PATH=TeslaCam
root@raspberrypi:~# rclone mkdir "$RCLONE_DRIVE:$RCLONE_PATH"
root@raspberrypi:~# rclone lsd "$RCLONE_DRIVE":
          -1 2019-05-29 02:08:48        -1 TeslaCam
root@raspberrypi:~# export pushover_enabled=true
root@raspberrypi:~# export pushover_user_key=[removed]
root@raspberrypi:~# export pushover_app_key=[removed]
root@raspberrypi:~# wget https://raw.githubusercontent.com/marcone/teslausb/main-dev/setup/pi/setup-teslausb
--2019-05-29 05:06:32--  https://raw.githubusercontent.com/marcone/teslausb/main-dev/setup/pi/setup-teslausb
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.232.32.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.232.32.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8192 (8.0K) [text/plain]
Saving to: ‘setup-teslausb’

setup-teslausb                                      100%[==================================================================================================================>]   8.00K  --.-KB/s    in 0.003s

2019-05-29 05:06:33 (2.39 MB/s) - ‘setup-teslausb’ saved [8192/8192]

root@raspberrypi:~# chmod +x setup-teslausb
root@raspberrypi:~# ./setup-teslausb
Updating package index files...
Get:1 http://archive.raspberrypi.org/debian stretch InRelease [25.4 kB]
Get:2 http://raspbian.raspberrypi.org/raspbian stretch InRelease [15.0 kB]
Get:3 http://raspbian.raspberrypi.org/raspbian stretch/main armhf Packages [11.7 MB]
Get:4 http://archive.raspberrypi.org/debian stretch/main armhf Packages [221 kB]
Get:5 http://archive.raspberrypi.org/debian stretch/ui armhf Packages [45.0 kB]
Get:6 http://raspbian.raspberrypi.org/raspbian stretch/non-free armhf Packages [95.5 kB]
Fetched 12.1 MB in 26s (464 kB/s)
Reading package lists... Done
Verifying that the requested configuration is valid...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1804  100  1804    0     0   4382      0 --:--:-- --:--:-- --:--:--  4400
Downloaded /tmp/verify-configuration.sh ...
grep: /root/bin/setup-teslausb: No such file or directory
setup-teslausb is outdated, attempting update
STOP: failed to update setup-teslausb

**Comment by marcone** [comment]
I think you just need to download setup-teslausb to /root/bin instead of to /root

**Comment by CmSCMU** [comment]
Crap. Thanks.
