### ISSUE TITLE
Change to setup-teslausb 

### ISSUE THREAD

**Issue by DonC52** [marcone/teslausb#534]
Should we use HOSTNAME in the export for TESLAUSB_HOSTNAME  as a default?

Like:
export TESLAUSB_HOSTNAME=${TESLAUSB_HOSTNAME:-$(hostname)}

**Comment by marcone** [comment]
Either one works for the common case. Not worth changing in my opinion.

**Comment by DonC52** [comment]
Sounds good to me.
