### ISSUE TITLE
Can you post instructions on how to build your own image?

### ISSUE THREAD

**Issue by dandanio** [marcone/teslausb#543]
@marcone Great job! But I feel like the latest release is getting long in the tooth. I would like to build my own "snapshot" image and burn it. Can you more or less post steps necessary to do that?
Thanks and keep up the good work!

**Comment by marcone** [comment]
https://github.com/marcone/teslausb/tree/main-dev/pi-gen-sources

It's possible those instructions are outdated, but they should point you in the right direction.

**Comment by marcone** [comment]
(also: https://github.com/marcone/teslausb/wiki/FAQ#q-those-images-are-really-old-why-havent-you-updated-them)
