### ISSUE TITLE
I finished installing the one step setup but when i use the command "df -h", i don't see my nas 

### ISSUE THREAD

**Issue by mambabfk** [marcone/teslausb#544]
<img width="394" alt="Screen Shot 2020-10-20 at 11 05 06 PM" src="https://user-images.githubusercontent.com/71360636/96679670-f382fe80-1328-11eb-80db-f4ab1bbb78ac.png">
Please see my screenshot above.

**Comment by marcone** [comment]
The share is only mounted while the Pi is archiving.
If you want to verify that it works, run `sudo mount /mnt/archive`
