### ISSUE TITLE
Seeing issues on Pi 4 model B 2GB model 

### ISSUE THREAD

**Issue by suryadevarauday** [marcone/teslausb#546]
Wed 22 Jan 23:46:21 GMT 2020 : Detecting whether to update wpa_supplicant.conf
Wed 22 Jan 23:46:21 GMT 2020 : Wifi variables specified, and no /boot/WIFI_ENABLED. Building wpa_supplicant.conf.
Wed 22 Jan 23:46:21 GMT 2020 : Rebooting...
Wed 22 Jan 23:46:56 GMT 2020 : Detecting whether to update wpa_supplicant.conf
Wed 22 Jan 23:46:56 GMT 2020 : Grabbing main setup file.
Wed 22 Jan 23:46:56 GMT 2020 : get_script failed, retrying
Wed 22 Jan 23:46:59 GMT 2020 : get_script failed, retrying
Wed 22 Jan 23:47:02 GMT 2020 : get_script failed, retrying
Wed 22 Jan 23:47:05 GMT 2020 : get_script failed, retrying

Any recommendations? I updated teslausb_setup_variables.conf with just these updates, and evrything defaults with teslausb-20200709 v2.1: 

export CAM_SIZE=16G
export SSID='network-link'
export WIFIPASS='P@ss@12345'

**Comment by marcone** [comment]
It's likely because the date is set incorrectly. It should normally be set automatically by NTP, assuming your network connection is working.
