### ISSUE TITLE
Suggestion: viewer app, anyone? 

### ISSUE THREAD

**Issue by MarcFinns** [marcone/teslausb#550]
Hi there, TeslaCam works like a charm.
The only issue is the flood of data. Has anyone experimented with apps that are able to sift through the directories in the SMB share?

**Comment by mossibat** [comment]
We built a web app to view and search the videos. Check out https://collisure.club/driver-demo/. Send me an email if you wanna try it out.

**Comment by MarcFinns** [comment]
thanks. do you need to upload each event or can it just connect to the teslamate share and show the list of events?

**Comment by mossibat** [comment]
Right now you can do a manual upload of any TeslaCam files to view and search 10 classes of objects in them. We're launching the S3 fetch soon.
