### ISSUE TITLE
Copy any new clips created while at home?

### ISSUE THREAD

**Issue by sjonez** [marcone/teslausb#553]
Am I right in thinking that if I have sentry mode enabled while at home (so teslausb is already connected to my wifi) and some new sentry mode clips get created, they're not going to get copied until the wifi disconnects and then reconnects again? Or will it periodically check for anything new to copy while connected?

**Comment by marcone** [comment]
They don't get copied until wifi disconnects and then reconnects again. Or more precisely until the Pi finds the archive server unreachable and then reachable again.
