### ISSUE TITLE
setup scripts for pre-installed systems?

### ISSUE THREAD

**Issue by ktiedt** [marcone/teslausb#554]
I've been looking around and while I see the "recommend one step install" and pre-built flash image, I was wondering if their is any work on more basic setup that just runs on top of an existing linux system?

I was hoping to run the new rpi4 with an NVMe bootable drive that was planned to run Ubuntu LTS for some additional applications (and consistency with the rest of our network services).

As it stands it looks like I may be able to boot off the memory card and use the NVMe drive via the "external usb" config possibly... but would love a more "wget [script] | bash" type setup that works across more generic platforms -- would also of course be willing to help test and put together some of the varied scripts to make it happen if there was a more clear roadmap to what is doing what. 

I am about to setup just off the prebuilt flash drive and test the nvme out, but thought I would post this idea and get some feedback. Looks like an awesome project - hoping I can get it working with our setup :)

**Comment by marcone** [comment]
Using a standard base image limits the number of things that can go wrong, so I don't have any plans to increase support for installing on top of a different system.
