### ISSUE TITLE
s3.us-west-2.amazonaws.com server misbehaving

### ISSUE THREAD

**Issue by mossibat** [marcone/teslausb#558]
Hi @marcone I know that the rclone/S3 is not tested. Just putting this out here so to see if anyone else has had this issue or success with S3?

I am getting no errors syncing SavedClips to my S3 bucket, but just took a look at the logs and saw these errors with SentryClips. Any thoughts?

**Comment by marcone** [comment]
This doesn't seem like a teslausb issue. Maybe ask over on the rclone project's github?
