### ISSUE TITLE
Change Archive location after installation

### ISSUE THREAD

**Issue by tomsteenbakkers** [marcone/teslausb#56]
I have installed TeslaUSB today and it works perfect on the Model S. I notice that for correct archiving additional power is need besides the USB. When in park  the connection is lost on WiFi and therefor no archiving. After adding a powerbank everything runs smooth. I will no try to use the charger in de cigarette outlet, hopefully the power stays on.

Question: how can I change the location of the archive after installation. Is there a configuration file which can be edited?

**Comment by marcone** [comment]
If you're just looking to use a different server or different folder on the server, then the easiest way is to ssh in to the rpi and edit the entry for /mnt/archive in /etc/fstab accordingly.
If you also need to need to update the login credentials for the server, then edit /root/.teslaCamArchiveCredentials as well.
