### ISSUE TITLE
How to use a script to change CAM and MUSIC drive size

### ISSUE THREAD

**Issue by aaronac8** [marcone/teslausb#560]
I do not know how to use a script to change the MUSIC and CAM drive sizes on my raspberry pi?  I am fairly new to programing a raspberry pi.

Thank you for all your help.

**Comment by marcone** [comment]
ssh in to the Pi, then run:
```
sudo -i
bin/setup-teslausb install tools/resize-image.sh
bin/resize-image.sh 32G /backingfiles/cam_disk.bin
```
Replace "32G" with the size you want, and use "/backingfiles/cam_disk.bin" to change the "CAM" drive, or "/backingfiles/music_disk.bin" to change the music drive.
Reboot afterwards by typing `reboot`
