### ISSUE TITLE
Setup successful, Pi W LED not blinking, CAM drive doesn't show up.

### ISSUE THREAD

**Issue by murtuzahabib** [marcone/teslausb#572]
The setup is a success, both TESLAUSB_SETUP_FINISHED or WIFI_ENABLED files present. The log ends with 'All done'.

I can see the 'Teslausb' wifi and can connect to the pi using my phone.

Whilst connected to my Mac, Pi LED is lit up and not blinking. CAM folder doesn't show up.

Could you please look into this issue?

Thanks.

**Comment by marcone** [comment]
There isn't enough information here. Please see https://github.com/marcone/teslausb/issues/35
