### ISSUE TITLE
Cannot connect to Hidden Network

### ISSUE THREAD

**Issue by TonyBrobston** [marcone/teslausb#576]
When I have my wireless network set to hidden, my pi will not connect. If I flip this one setting, making the network visible, my pi is able to connect.
![image](https://user-images.githubusercontent.com/4724577/102294657-69fa4200-3f0f-11eb-9a1b-ec4f0e604350.png)

From a bit of googling it sounds like it is possible, involving adding `scan_ssid=1` to `wpa_supplicant`. However this seems to go outside the route of using `teslausb_setup_variables.conf` and I'm not sure if that is a good thing or bad thing?

https://www.raspberrypi.org/forums/viewtopic.php?t=250588

A little more backstory. I recently created a few vLANs on my network in order to separate my Home Automation devices from other devices they shouldn't be able to see or talk to. The result is that I have 6 wireless networks: Main, Guest, IoT, NoT (however IoT and NoT end up with 2 wireless networks each to lock in which AP a device is connect to). In an effort to decrease the number of SSID's I'm showing, I hide my IoT and NoT networks. So far, all of my 40-some devices have worked great.

**Comment by marcone** [comment]
You can add this option to wpa_supplicant.conf yourself if you want/need it.
See also https://github.com/marcone/teslausb/issues/254

**Comment by TonyBrobston** [comment]
@marcone Sorry to ask a dumb question, but can you help with more detailed steps?

I am assuming I need to `cp wpa_supplicant.conf.sample wpa_supplicant.conf`, then updated `ssid` and `psk` and add `scan_ssid=1` to `network`. Unfortunately when I run that copy command I am faced with an error: `cp: cannot create regular file 'wpa_supplicant.conf': Read-only file system`. What causes this to become read-only? Once I am able to copy/modify the `wpa_supplicant.conf`, do I have to rerun a command or will it pick up these modified settings on the fly?

**Comment by marcone** [comment]
If you have a working installation already, run `/root/bin/remountfs_rw` first, then edit /etc/wpa_supplicant/wpa_supplicant.conf

If you're doing a new install, add the scan_ssid line to the wpa_supplicant.conf.sample file. Setup will take care of the rest.

**Comment by TonyBrobston** [comment]
Thanks for the details @marcone, this worked perfectly.
