### ISSUE TITLE
UI_a111 "dashcam usb drive not plugged into glovebox" 2021 Model 3 SR+ with 2020.48.12.1

### ISSUE THREAD

**Issue by hanleyp** [marcone/teslausb#578]
Mentions something about sentry mode using higher power.

Also model came with TESLADRIVE exFAT formatted branded USB drive with "TESLA DRIVE Media" as model name. I'm wondering if the new software is looking for this drive and not finding it when I use teslausb.

**Comment by marcone** [comment]
issue https://github.com/marcone/teslausb/issues/564
