### ISSUE TITLE
Please Fully Support the "no-delete" branch as an option

### ISSUE THREAD

**Issue by shawnbissell** [marcone/teslausb#580]
Ever since the cars were able to view footage themselves, I've been using the "no-delete" branch and struggling to manage the storage on the sd card. There is no documented way to delete the footage from say "older than the last 30 days", and I know you can ssh into the pi and delete the files manually, but I really think the "no-delete" branch should become the default with an additional option to delete archived footage that is older than X days.

**Comment by marcone** [comment]
https://github.com/marcone/teslausb/issues/467
