### ISSUE TITLE
When raspberry pi is plugged into my usb port on my computer, light flashes for a long time

### ISSUE THREAD

**Issue by aaronac8** [marcone/teslausb#584]
When I plug my raspberry pi teslausb into my usb on my desktop, the green light flashes fast for a long time before it is recognized as a plugged in drive.  How do I speed up this process and why does it take to long?  I have no sentry files on it and 26 GB of music, that has not been updated recently.  Does the pi go through all of my music every time it connects to my home network, even though there has been no change in that file?

**Comment by marcone** [comment]
Not enough information. See https://github.com/marcone/teslausb/issues/35
