### ISSUE TITLE
When using rclone to OneDrive the -L (or --copy-links) switch should be used

### ISSUE THREAD

**Issue by KloudGeek** [marcone/teslausb#591]
When using the rclone method to a OneDrive destination, the `rclone move` operation does not move any files. When running the command manually, the output reports that the `-L` (or `--copy-links`) switch should be used. After modifying `archiveloop` with `-L` files are able to be archived successfully.

**Comment by marcone** [comment]
Did you make any changes to any of the scripts? The archive script archives /mnt/cam/TeslaCam, and there are no links there.
