### ISSUE TITLE
read only?

### ISSUE THREAD

**Issue by CMDRPhaedra** [marcone/teslausb#601]
Is there a reason the the filesystem is ready only? the reason I ask is I've installed a PiSuger device to act as a UPS.. however the control software doesn't seem to run when the filesystem is read only.

pi@teslausb:~ $ sudo systemctl status pisugar-server
● pisugar-server.service - pisugar-server
   Loaded: loaded (/lib/systemd/system/pisugar-server.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2021-01-19 18:03:59 GMT; 3s ago
  Process: 1110 ExecStart=/usr/bin/pisugar-server $OPTS (code=exited, status=1/FAILURE)
  Process: 1115 ExecStopPost=/bin/rm -f /tmp/pisugar-server.sock (code=exited, status=0/SUCCESS)
 Main PID: 1110 (code=exited, status=1/FAILURE)

when I run /root/bin/remountfs_rw it starts working..

an 19 18:11:00 teslausb systemd[1]: Started pisugar-server.
Jan 19 18:11:00 teslausb pisugar-server[2513]: [2021-01-19T18:11:00Z INFO  pisugar_server] TCP listening...
Jan 19 18:11:00 teslausb pisugar-server[2513]: [2021-01-19T18:11:00Z INFO  pisugar_server] WS listening...
Jan 19 18:11:00 teslausb pisugar-server[2513]: [2021-01-19T18:11:00Z INFO  pisugar_server] UDS listening...
Jan 19 18:11:00 teslausb pisugar-server[2513]: [2021-01-19T18:11:00Z INFO  pisugar_server] Http web server listening...

any ideas?

**Comment by marcone** [comment]
> Is there a reason the the filesystem is ready only?

As mentioned [here](https://github.com/marcone/teslausb#optional-making-changes-to-the-system-after-setup), "This is to protect against corruption of the operating system when the Tesla cuts power to the Pi."
Depending on what pisugar needs, I'd look into configuring it to use /mutable or a tmpfs.
