### ISSUE TITLE
constant quick flashing 

### ISSUE THREAD

**Issue by Poncherelly** [marcone/teslausb#602]
Hello, I've just rebuilt my pi to use a 128gb sd.  My old one was working and I used the same .conf file but for some reason it's not working now.  When I run the install if seems to fully run / complete but now it's just constantly flashing and I do not get the drives (music and cam) showing up on my PC like my old one did.

I can SSH to the pi without issue and I'm happy to share logs but using the troubleshooting steps so far, I've confirmed that the TESLAUSB-setup.log does end in "All Done", and the boot location has the WIFI_enabled and TESLAUSB_setup_FINISHED there.  

I also checked /mutable/archiveloop.log and the output of dmesg for errors.  I don't see errors and I think I see that the music folder is copying.  The closest to an error is 
Sat 12 Dec 00:19:14 EST 2020: Starting archiveloop at 23.98 seconds uptime...
Sat 12 Dec 00:19:15 EST 2020: warning: low space for snapshots

Wed 20 Jan 17:05:54 EST 2021: Copying music from archive...
Wed 20 Jan 17:05:49 EST 2021: Ensured cam file is mounted.
Wed 20 Jan 17:05:52 EST 2021: There are 0 event folder(s) with 0 file(s) and 0 track mode file(s) to move. 0 short recording(s) will be skipped.
Wed 20 Jan 17:05:52 EST 2021: Trimming free space in /mnt/cam, which has 3 extents
Wed 20 Jan 17:05:53 EST 2021: Trim complete, image now has 3 extents
Wed 20 Jan 17:05:53 EST 2021: Unmounting /mnt/cam...
Wed 20 Jan 17:05:53 EST 2021: Unmounted /mnt/cam.
Wed 20 Jan 17:05:53 EST 2021: Finished archiving.
Wed 20 Jan 17:05:53 EST 2021: Copying music...
Wed 20 Jan 17:05:53 EST 2021: Starting music sync...
Wed 20 Jan 17:05:53 EST 2021: Ensuring music backing file is mounted...
Wed 20 Jan 17:05:54 EST 2021: Mounting /mnt/music...
Wed 20 Jan 17:05:54 EST 2021: Mounted /mnt/music.
Wed 20 Jan 17:05:54 EST 2021: Ensured music drive is mounted.
Wed 20 Jan 17:05:54 EST 2021: Copying music from archive...  <-- is this where it currently ends

Could this be why the led is flashing like crazy?  Can you think of why the shares aren't showing up on my PC?  My next step will be to plug it in to the car and see if the car recognizes it.

Any assistance or direction to go next would be much appreciated.

Thank you in advance.
Ponch

**Comment by marcone** [comment]
If your log ends with "Copying music from archive", then it's currently still copying music. The led will be flashing rapidly during copying, and the cam/music drives won't be available to an attached PC/car.
You can run `ps aux` to see if it's actually still copying or perhaps crashed for some reason.
