### ISSUE TITLE
Token refresh failed: %TeslaApi.Error

### ISSUE THREAD

**Issue by rmyadsk** [marcone/teslausb#615]
Seems persistent, but may not impact data collection.

How can I best help troubleshoot further?

Here is my `docker-compose telsamate logs`, reasonably truncated as it is most repetitive:

> teslamate_1  | 2021-03-02 16:10:02.039 car_id=2 [info] Derived efficiency factor: 145.41000000000003 Wh/km (18x confirmed)
teslamate_1  | 2021-03-02 16:10:02.040 car_id=2 [info] Charging / Disconnected / 41.77 kWh – 413 min
teslamate_1  | 2021-03-02 16:10:02.044 car_id=2 [info] Start / :online
teslamate_1  | 2021-03-02 16:10:02.089 car_id=2 [info] Connecting ...
teslamate_1  | 2021-03-02 16:10:31.685 car_id=2 [info] Driving / Start
teslamate_1  | 2021-03-02 16:24:50.153 [info] Refreshing access token ...
teslamate_1  | 2021-03-02 16:24:50.360 [error] POST https://auth.tesla.com/oauth2/v3/token -> 400 (205.971 ms)
teslamate_1  | 2021-03-02 16:24:50.364 [warn] Token refresh failed: %TeslaApi.Error{
teslamate_1  |   env: %Tesla.Env{
teslamate_1  |     __client__: %Tesla.Client{adapter: nil, fun: nil, post: [], pre: []},
teslamate_1  |     __module__: TeslaApi.Auth,
teslamate_1  |     body: %{
teslamate_1  |       "error" => "server_error",
teslamate_1  |       "error_description" => "Internal server error",
teslamate_1  |       "error_uri" => "https://auth.tesla.com/error/reference/460053ab-2601-4a0a-8d77-a461cde1785a-1614720290307"
teslamate_1  |     },
teslamate_1  |     headers: [
teslamate_1  |       {"server", "nginx"},
teslamate_1  |       {"content-type", "application/json"},
teslamate_1  |       {"x-dns-prefetch-control", "off"},
teslamate_1  |       {"x-frame-options", "DENY"},
teslamate_1  |       {"strict-transport-security", "max-age=15552000; includeSubDomains"},
teslamate_1  |       {"x-download-options", "noopen"},
teslamate_1  |       {"x-content-type-options", "nosniff"},
teslamate_1  |       {"x-xss-protection", "1; mode=block"},
teslamate_1  |       {"x-request-id", "460053ab-2601-4a0a-8d77-a461cde1785a"},
teslamate_1  |       {"x-correlation-id", "460053ab-2601-4a0a-8d77-a461cde1785a"},
teslamate_1  |       {"access-control-allow-origin", "*"},
teslamate_1  |       {"x-response-time", "3.318ms"},
teslamate_1  |       {"date", "Tue, 02 Mar 2021 21:24:50 GMT"},
teslamate_1  |       {"connection", "close"}
teslamate_1  |     ],
teslamate_1  |     method: :post,
teslamate_1  |     opts: [],
teslamate_1  |     query: [],
teslamate_1  |     status: 400,
teslamate_1  |     url: "https://auth.tesla.com/oauth2/v3/token"
teslamate_1  |   },
teslamate_1  |   message: nil,
teslamate_1  |   reason: :token_refresh
teslamate_1  | }
teslamate_1  | 2021-03-02 16:24:50.364 [warn] Retrying in 1 hour...
teslamate_1  | 2021-03-02 16:40:23.454 car_id=2 [info] Driving / Ended / 32 km – 29 min
teslamate_1  | 2021-03-02 16:40:23.458 car_id=2 [info] Start / :online
teslamate_1  | 2021-03-02 16:43:41.224 car_id=2 [info] Suspending logging
teslamate_1  | 2021-03-02 17:11:05.871 [info] GET /
teslamate_1  | 2021-03-02 17:11:05.889 [info] Sent 200 in 17ms
teslamate_1  | 2021-03-02 17:12:46.948 car_id=2 [info] Resuming logging
teslamate_1  | 2021-03-02 17:12:49.525 car_id=2 [info] Received stream data: :inactive
teslamate_1  | 2021-03-02 17:12:57.263 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/40149755796008394/vehicle_data -> 408 (9313.108 ms)
teslamate_1  | 2021-03-02 17:13:07.573 car_id=2 [info] Start / :offline
teslamate_1  | 2021-03-02 17:13:07.604 car_id=2 [info] Disconnecting ...
teslamate_1  | 2021-03-02 17:13:20.145 [warn] GET https://owner-api.teslamotors.com/api/1/vehicles/40149755796008394/vehicle_data -> 540 (2410.264 ms)
teslamate_1  | 2021-03-02 17:13:20.146 [warn] TeslaApi.Error / https://mothership-api.vn.teslamotors.com:443/vehicles/174286848/user_command/vehicle_data => vehicle error: it is online but not responsive
teslamate_1  | 2021-03-02 17:13:20.146 car_id=2 [error] Error / :unknown
teslamate_1  | 2021-03-02 17:13:50.609 car_id=2 [info] Start / :online
teslamate_1  | 2021-03-02 17:13:50.617 car_id=2 [info] Logged missing software udpate: 2021.4.11 8af6a4f84c84
teslamate_1  | 2021-03-02 17:13:50.686 car_id=2 [info] Connecting ...
teslamate_1  | 2021-03-02 17:16:53.375 car_id=2 [info] Suspending logging
teslamate_1  | 2021-03-02 17:24:50.365 [info] Refreshing access token ...
teslamate_1  | 2021-03-02 17:24:50.646 [error] POST https://auth.tesla.com/oauth2/v3/token -> 400 (279.988 ms)
teslamate_1  | 2021-03-02 17:24:50.650 [warn] Token refresh failed: %TeslaApi.Error{
teslamate_1  |   env: %Tesla.Env{
teslamate_1  |     __client__: %Tesla.Client{adapter: nil, fun: nil, post: [], pre: []},
teslamate_1  |     __module__: TeslaApi.Auth,
teslamate_1  |     body: %{
teslamate_1  |       "error" => "server_error",
teslamate_1  |       "error_description" => "Internal server error",
teslamate_1  |       "error_uri" => "https://auth.tesla.com/error/reference/3f0eb491-5ead-4152-b1fe-a4d45a46c890-1614723890555"
teslamate_1  |     },
teslamate_1  |     headers: [
teslamate_1  |       {"server", "nginx"},
teslamate_1  |       {"content-type", "application/json"},
teslamate_1  |       {"x-dns-prefetch-control", "off"},
teslamate_1  |       {"x-frame-options", "DENY"},
teslamate_1  |       {"strict-transport-security", "max-age=15552000; includeSubDomains"},
teslamate_1  |       {"x-download-options", "noopen"},
teslamate_1  |       {"x-content-type-options", "nosniff"},
teslamate_1  |       {"x-xss-protection", "1; mode=block"},
teslamate_1  |       {"x-request-id", "3f0eb491-5ead-4152-b1fe-a4d45a46c890"},
teslamate_1  |       {"x-correlation-id", "3f0eb491-5ead-4152-b1fe-a4d45a46c890"},
teslamate_1  |       {"access-control-allow-origin", "*"},
teslamate_1  |       {"x-response-time", "3.342ms"},
teslamate_1  |       {"date", "Tue, 02 Mar 2021 22:24:50 GMT"},
teslamate_1  |       {"connection", "close"}
teslamate_1  |     ],
teslamate_1  |     method: :post,
teslamate_1  |     opts: [],
teslamate_1  |     query: [],
teslamate_1  |     status: 400,
teslamate_1  |     url: "https://auth.tesla.com/oauth2/v3/token"
teslamate_1  |   },
teslamate_1  |   message: nil,
teslamate_1  |   reason: :token_refresh
teslamate_1  | }
teslamate_1  | 2021-03-02 17:24:50.650 [warn] Retrying in 1 hour...
teslamate_1  | 2021-03-02 17:34:26.089 [warn] Too many disconnects from streaming API
teslamate_1  | 2021-03-02 17:34:26.089 car_id=2 [info] Creating new connection … 
teslamate_1  | 2021-03-02 17:34:26.089 car_id=2 [info] Disconnecting ...
teslamate_1  | 2021-03-02 17:34:26.106 car_id=2 [info] Connecting ...
teslamate_1  | 2021-03-02 17:40:51.992 [warn] Too many disconnects from streaming API
teslamate_1  | 2021-03-02 17:40:51.992 car_id=2 [info] Creating new connection … 
teslamate_1  | 2021-03-02 17:40:51.992 car_id=2 [info] Disconnecting ...
teslamate_1  | 2021-03-02 17:40:52.012 car_id=2 [info] Connecting ...
teslamate_1  | 2021-03-02 17:46:53.929 car_id=2 [info] Vehicle is still online. Falling asleep for: 33 min
teslamate_1  | 2021-03-02 17:47:17.500 [warn] Too many disconnects from streaming API
teslamate_1  | 2021-03-02 17:47:17.500 car_id=2 [info] Creating new connection … 
teslamate_1  | 2021-03-02 17:47:17.500 car_id=2 [info] Disconnecting ...
teslamate_1  | 2021-03-02 17:47:17.512 car_id=2 [info] Connecting ...
teslamate_1  | 2021-03-02 17:53:43.370 [warn] Too many disconnects from streaming API
teslamate_1  | 2021-03-02 17:53:43.370 car_id=2 [info] Creating new connection … 
teslamate_1  | 2021-03-02 17:53:43.370 car_id=2 [info] Disconnecting ...
teslamate_1  | 2021-03-02 17:53:43.390 car_id=2 [info] Connecting ...
teslamate_1  | 2021-03-02 18:00:10.648 [warn] Too many disconnects from streaming API
teslamate_1  | 2021-03-02 18:00:10.648 car_id=2 [info] Creating new connection … 
teslamate_1  | 2021-03-02 18:00:10.648 car_id=2 [info] Disconnecting ...
teslamate_1  | 2021-03-02 18:00:10.667 car_id=2 [info] Connecting ...
teslamate_1  | 2021-03-02 18:06:35.870 [warn] Too many disconnects from streaming API
teslamate_1  | 2021-03-02 18:06:35.870 car_id=2 [info] Creating new connection … 
teslamate_1  | 2021-03-02 18:06:35.870 car_id=2 [info] Disconnecting ...
teslamate_1  | 2021-03-02 18:06:35.890 car_id=2 [info] Connecting ...
teslamate_1  | 2021-03-02 18:13:02.088 [warn] Too many disconnects from streaming API
teslamate_1  | 2021-03-02 18:13:02.088 car_id=2 [info] Creating new connection … 
teslamate_1  | 2021-03-02 18:13:02.088 car_id=2 [info] Disconnecting ...
teslamate_1  | 2021-03-02 18:13:02.105 car_id=2 [info] Connecting ...
teslamate_1  | 2021-03-02 18:14:37.715 car_id=2 [info] Fetching vehicle state ...
teslamate_1  | 2021-03-02 18:16:54.651 car_id=2 [info] Vehicle is still online. Falling asleep for: 1 h 3 min
teslamate_1  | 2021-03-02 18:24:50.651 [info] Refreshing access token ...
teslamate_1  | 2021-03-02 18:24:50.868 [error] POST https://auth.tesla.com/oauth2/v3/token -> 400 (216.031 ms)
teslamate_1  | 2021-03-02 18:24:50.872 [warn] Token refresh failed: %TeslaApi.Error{
teslamate_1  |   env: %Tesla.Env{
teslamate_1  |     __client__: %Tesla.Client{adapter: nil, fun: nil, post: [], pre: []},
teslamate_1  |     __module__: TeslaApi.Auth,
teslamate_1  |     body: %{
teslamate_1  |       "error" => "server_error",
teslamate_1  |       "error_description" => "Internal server error",
teslamate_1  |       "error_uri" => "https://auth.tesla.com/error/reference/fb0573f0-ffe1-4112-b96a-e29c5d2e1c53-1614727490802"
teslamate_1  |     },
teslamate_1  |     headers: [
teslamate_1  |       {"server", "nginx"},
teslamate_1  |       {"content-type", "application/json"},
teslamate_1  |       {"x-dns-prefetch-control", "off"},
teslamate_1  |       {"x-frame-options", "DENY"},
teslamate_1  |       {"strict-transport-security", "max-age=15552000; includeSubDomains"},
teslamate_1  |       {"x-download-options", "noopen"},
teslamate_1  |       {"x-content-type-options", "nosniff"},
teslamate_1  |       {"x-xss-protection", "1; mode=block"},
teslamate_1  |       {"x-request-id", "fb0573f0-ffe1-4112-b96a-e29c5d2e1c53"},
teslamate_1  |       {"x-correlation-id", "fb0573f0-ffe1-4112-b96a-e29c5d2e1c53"},
teslamate_1  |       {"access-control-allow-origin", "*"},
teslamate_1  |       {"x-response-time", "3.176ms"},
teslamate_1  |       {"date", "Tue, 02 Mar 2021 23:24:50 GMT"},
teslamate_1  |       {"connection", "close"}
teslamate_1  |     ],
teslamate_1  |     method: :post,
teslamate_1  |     opts: [],
teslamate_1  |     query: [],
teslamate_1  |     status: 400,
teslamate_1  |     url: "https://auth.tesla.com/oauth2/v3/token"
teslamate_1  |   },
teslamate_1  |   message: nil,
teslamate_1  |   reason: :token_refresh
teslamate_1  | }
teslamate_1  | 2021-03-02 18:24:50.872 [warn] Retrying in 1 hour...
teslamate_1  | 2021-03-02 18:24:50.937 car_id=2 [info] Fetching vehicle state ...
teslamate_1  | 2021-03-02 18:25:32.748 [warn] Too many disconnects from streaming API
teslamate_1  | 2021-03-02 18:25:32.749 car_id=2 [info] Creating new connection … 
teslamate_1  | 2021-03-02 18:25:32.749 car_id=2 [info] Disconnecting ...
teslamate_1  | 2021-03-02 18:25:32.768 car_id=2 [info] Connecting ...
teslamate_1  | 2021-03-02 18:33:13.082 car_id=1 [info] Start / :online
teslamate_1  | 2021-03-02 18:33:13.133 car_id=1 [info] Connecting ...
teslamate_1  | 2021-03-02 18:36:15.328 car_id=1 [info] Suspending logging
teslamate_1  | 2021-03-02 18:38:53.468 [warn] Too many disconnects from streaming API
teslamate_1  | 2021-03-02 18:38:53.468 car_id=2 [info] Creating new connection … 
teslamate_1  | 2021-03-02 18:38:53.468 car_id=2 [info] Disconnecting ...
teslamate_1  | 2021-03-02 18:38:53.489 car_id=2 [info] Connecting ...
teslamate_1  | 2021-03-02 18:46:55.053 car_id=2 [info] Start / :asleep
teslamate_1  | 2021-03-02 18:46:55.075 car_id=2 [info] Disconnecting ...
teslamate_1  | 2021-03-02 19:06:24.595 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/5853617637379554/vehicle_data -> 408 (9147.088 ms)
teslamate_1  | 2021-03-02 19:06:24.596 car_id=1 [error] Error / :vehicle_unavailable
teslamate_1  | 2021-03-02 19:07:02.550 car_id=1 [info] Vehicle is still online. Falling asleep for: 33 min
teslamate_1  | 2021-03-02 19:19:02.825 car_id=1 [info] Fetching vehicle state ...
teslamate_1  | 2021-03-02 19:19:02.995 car_id=1 [info] Start / :asleep
teslamate_1  | 2021-03-02 19:19:03.012 car_id=1 [info] Disconnecting ...
teslamate_1  | 2021-03-02 19:24:50.873 [info] Refreshing access token ...
teslamate_1  | 2021-03-02 19:24:51.122 [error] POST https://auth.tesla.com/oauth2/v3/token -> 400 (247.989 ms)
teslamate_1  | 2021-03-02 19:24:51.126 [warn] Token refresh failed: %TeslaApi.Error{
teslamate_1  |   env: %Tesla.Env{
teslamate_1  |     __client__: %Tesla.Client{adapter: nil, fun: nil, post: [], pre: []},
teslamate_1  |     __module__: TeslaApi.Auth,
teslamate_1  |     body: %{
teslamate_1  |       "error" => "server_error",
teslamate_1  |       "error_description" => "Internal server error",
teslamate_1  |       "error_uri" => "https://auth.tesla.com/error/reference/3bf7fed1-560f-481f-a12c-5ef301972685-1614731091060"
teslamate_1  |     },
teslamate_1  |     headers: [
teslamate_1  |       {"content-type", "application/json"},
teslamate_1  |       {"content-length", "172"},
teslamate_1  |       {"x-dns-prefetch-control", "off"},
teslamate_1  |       {"x-frame-options", "DENY"},
teslamate_1  |       {"strict-transport-security", "max-age=15552000; includeSubDomains"},
teslamate_1  |       {"x-download-options", "noopen"},
teslamate_1  |       {"x-content-type-options", "nosniff"},
teslamate_1  |       {"x-xss-protection", "1; mode=block"},
teslamate_1  |       {"x-request-id", "3bf7fed1-560f-481f-a12c-5ef301972685"},
teslamate_1  |       {"x-correlation-id", "3bf7fed1-560f-481f-a12c-5ef301972685"},
teslamate_1  |       {"access-control-allow-origin", "*"},
teslamate_1  |       {"x-response-time", "5.955ms"},
teslamate_1  |       {"date", "Wed, 03 Mar 2021 00:24:51 GMT"},
teslamate_1  |       {"connection", "close"}
teslamate_1  |     ],
teslamate_1  |     method: :post,
teslamate_1  |     opts: [],
teslamate_1  |     query: [],
teslamate_1  |     status: 400,
teslamate_1  |     url: "https://auth.tesla.com/oauth2/v3/token"
teslamate_1  |   },
teslamate_1  |   message: nil,
teslamate_1  |   reason: :token_refresh
teslamate_1  | }
teslamate_1  | 2021-03-02 19:24:51.126 [warn] Retrying in 1 hour...
teslamate_1  | 2021-03-02 20:24:51.127 [info] Refreshing access token ...
teslamate_1  | 2021-03-02 20:24:51.331 [error] POST https://auth.tesla.com/oauth2/v3/token -> 400 (203.596 ms)
teslamate_1  | 2021-03-02 20:24:51.336 [warn] Token refresh failed: %TeslaApi.Error{
teslamate_1  |   env: %Tesla.Env{
teslamate_1  |     __client__: %Tesla.Client{adapter: nil, fun: nil, post: [], pre: []},
teslamate_1  |     __module__: TeslaApi.Auth,
teslamate_1  |     body: %{
teslamate_1  |       "error" => "server_error",
teslamate_1  |       "error_description" => "Internal server error",
teslamate_1  |       "error_uri" => "https://auth.tesla.com/error/reference/2f97c05b-4c05-4f2a-8c37-fe5012360c3b-1614734691277"
teslamate_1  |     },
teslamate_1  |     headers: [
teslamate_1  |       {"content-type", "application/json"},
teslamate_1  |       {"content-length", "172"},
teslamate_1  |       {"x-dns-prefetch-control", "off"},
teslamate_1  |       {"x-frame-options", "DENY"},
teslamate_1  |       {"strict-transport-security", "max-age=15552000; includeSubDomains"},
teslamate_1  |       {"x-download-options", "noopen"},
teslamate_1  |       {"x-content-type-options", "nosniff"},
teslamate_1  |       {"x-xss-protection", "1; mode=block"},
teslamate_1  |       {"x-request-id", "2f97c05b-4c05-4f2a-8c37-fe5012360c3b"},
teslamate_1  |       {"x-correlation-id", "2f97c05b-4c05-4f2a-8c37-fe5012360c3b"},
teslamate_1  |       {"access-control-allow-origin", "*"},
teslamate_1  |       {"x-response-time", "2.219ms"},
teslamate_1  |       {"date", "Wed, 03 Mar 2021 01:24:51 GMT"},
teslamate_1  |       {"connection", "close"}
teslamate_1  |     ],
teslamate_1  |     method: :post,
teslamate_1  |     opts: [],
teslamate_1  |     query: [],
teslamate_1  |     status: 400,
teslamate_1  |     url: "https://auth.tesla.com/oauth2/v3/token"
teslamate_1  |   },
teslamate_1  |   message: nil,
teslamate_1  |   reason: :token_refresh
teslamate_1  | }
teslamate_1  | 2021-03-02 20:24:51.336 [warn] Retrying in 1 hour...
teslamate_1  | 2021-03-02 20:59:41.908 car_id=2 [info] Start / :online
teslamate_1  | 2021-03-02 20:59:42.568 car_id=2 [info] Connecting ...
teslamate_1  | 2021-03-02 21:00:10.537 car_id=2 [info] Charging detected: -1 kW
teslamate_1  | 2021-03-02 21:00:11.488 car_id=2 [info] Charging / SOC: 58% / Home
teslamate_1  | 2021-03-02 21:00:11.488 car_id=2 [info] Disconnecting ...
teslamate_1  | 2021-03-02 21:24:51.337 [info] Refreshing access token ...
teslamate_1  | 2021-03-02 21:24:51.541 [error] POST https://auth.tesla.com/oauth2/v3/token -> 400 (203.415 ms)
teslamate_1  | 2021-03-02 21:24:51.546 [warn] Token refresh failed: %TeslaApi.Error{
teslamate_1  |   env: %Tesla.Env{
teslamate_1  |     __client__: %Tesla.Client{adapter: nil, fun: nil, post: [], pre: []},
teslamate_1  |     __module__: TeslaApi.Auth,
teslamate_1  |     body: %{
teslamate_1  |       "error" => "server_error",
teslamate_1  |       "error_description" => "Internal server error",
teslamate_1  |       "error_uri" => "https://auth.tesla.com/error/reference/e773f68d-0167-4d29-92d8-1a65df8686bc-1614738291489"
teslamate_1  |     },
teslamate_1  |     headers: [
teslamate_1  |       {"server", "nginx"},
teslamate_1  |       {"content-type", "application/json"},
teslamate_1  |       {"x-dns-prefetch-control", "off"},
teslamate_1  |       {"x-frame-options", "DENY"},
teslamate_1  |       {"strict-transport-security", "max-age=15552000; includeSubDomains"},
teslamate_1  |       {"x-download-options", "noopen"},
teslamate_1  |       {"x-content-type-options", "nosniff"},
teslamate_1  |       {"x-xss-protection", "1; mode=block"},
teslamate_1  |       {"x-request-id", "e773f68d-0167-4d29-92d8-1a65df8686bc"},
teslamate_1  |       {"x-correlation-id", "e773f68d-0167-4d29-92d8-1a65df8686bc"},
teslamate_1  |       {"access-control-allow-origin", "*"},
teslamate_1  |       {"x-response-time", "3.057ms"},
teslamate_1  |       {"date", "Wed, 03 Mar 2021 02:24:51 GMT"},
teslamate_1  |       {"connection", "close"}
teslamate_1  |     ],
teslamate_1  |     method: :post,
teslamate_1  |     opts: [],
teslamate_1  |     query: [],
teslamate_1  |     status: 400,
teslamate_1  |     url: "https://auth.tesla.com/oauth2/v3/token"
teslamate_1  |   },
teslamate_1  |   message: nil,
teslamate_1  |   reason: :token_refresh
teslamate_1  | }
teslamate_1  | 2021-03-02 21:24:51.546 [warn] Retrying in 1 hour...
teslamate_1  | 2021-03-02 22:01:29.424 [info] GET /
teslamate_1  | 2021-03-02 22:01:29.445 [info] Sent 200 in 20ms
teslamate_1  | 2021-03-02 22:01:30.004 [info] GET /
teslamate_1  | 2021-03-02 22:01:30.020 [info] Sent 200 in 16ms
teslamate_1  | 2021-03-02 22:24:51.547 [info] Refreshing access token ...
teslamate_1  | 2021-03-02 22:24:51.786 [error] POST https://auth.tesla.com/oauth2/v3/token -> 400 (238.050 ms)
teslamate_1  | 2021-03-02 22:24:51.791 [warn] Token refresh failed: %TeslaApi.Error{
teslamate_1  |   env: %Tesla.Env{
teslamate_1  |     __client__: %Tesla.Client{adapter: nil, fun: nil, post: [], pre: []},
teslamate_1  |     __module__: TeslaApi.Auth,
teslamate_1  |     body: %{
teslamate_1  |       "error" => "server_error",
teslamate_1  |       "error_description" => "Internal server error",
teslamate_1  |       "error_uri" => "https://auth.tesla.com/error/reference/26fe80dc-ca33-45fe-b126-7c85a0739d72-1614741891705"
teslamate_1  |     },
teslamate_1  |     headers: [
teslamate_1  |       {"server", "nginx"},
teslamate_1  |       {"content-type", "application/json"},
teslamate_1  |       {"x-dns-prefetch-control", "off"},
teslamate_1  |       {"x-frame-options", "DENY"},
teslamate_1  |       {"strict-transport-security", "max-age=15552000; includeSubDomains"},
teslamate_1  |       {"x-download-options", "noopen"},
teslamate_1  |       {"x-content-type-options", "nosniff"},
teslamate_1  |       {"x-xss-protection", "1; mode=block"},
teslamate_1  |       {"x-request-id", "26fe80dc-ca33-45fe-b126-7c85a0739d72"},
teslamate_1  |       {"x-correlation-id", "26fe80dc-ca33-45fe-b126-7c85a0739d72"},
teslamate_1  |       {"access-control-allow-origin", "*"},
teslamate_1  |       {"x-response-time", "2.803ms"},
teslamate_1  |       {"date", "Wed, 03 Mar 2021 03:24:51 GMT"},
teslamate_1  |       {"connection", "close"}
teslamate_1  |     ],
teslamate_1  |     method: :post,
teslamate_1  |     opts: [],
teslamate_1  |     query: [],
teslamate_1  |     status: 400,
teslamate_1  |     url: "https://auth.tesla.com/oauth2/v3/token"
teslamate_1  |   },
teslamate_1  |   message: nil,
teslamate_1  |   reason: :token_refresh
teslamate_1  | }
teslamate_1  | 2021-03-02 22:24:51.791 [warn] Retrying in 1 hour...
teslamate_1  | 2021-03-02 23:24:51.792 [info] Refreshing access token ...
teslamate_1  | 2021-03-02 23:24:52.058 [error] POST https://auth.tesla.com/oauth2/v3/token -> 400 (265.332 ms)
teslamate_1  | 2021-03-02 23:24:52.063 [warn] Token refresh failed: %TeslaApi.Error{
teslamate_1  |   env: %Tesla.Env{
teslamate_1  |     __client__: %Tesla.Client{adapter: nil, fun: nil, post: [], pre: []},
teslamate_1  |     __module__: TeslaApi.Auth,
teslamate_1  |     body: %{
teslamate_1  |       "error" => "server_error",
teslamate_1  |       "error_description" => "Internal server error",
teslamate_1  |       "error_uri" => "https://auth.tesla.com/error/reference/4c7223bf-3c52-48e7-927e-60c6fe9a5112-1614745491957"
teslamate_1  |     },
teslamate_1  |     headers: [
teslamate_1  |       {"server", "nginx"},
teslamate_1  |       {"content-type", "application/json"},
teslamate_1  |       {"x-dns-prefetch-control", "off"},
teslamate_1  |       {"x-frame-options", "DENY"},
teslamate_1  |       {"strict-transport-security", "max-age=15552000; includeSubDomains"},
teslamate_1  |       {"x-download-options", "noopen"},
teslamate_1  |       {"x-content-type-options", "nosniff"},
teslamate_1  |       {"x-xss-protection", "1; mode=block"},
teslamate_1  |       {"x-request-id", "4c7223bf-3c52-48e7-927e-60c6fe9a5112"},
teslamate_1  |       {"x-correlation-id", "4c7223bf-3c52-48e7-927e-60c6fe9a5112"},
teslamate_1  |       {"access-control-allow-origin", "*"},
teslamate_1  |       {"x-response-time", "2.884ms"},
teslamate_1  |       {"date", "Wed, 03 Mar 2021 04:24:52 GMT"},
teslamate_1  |       {"connection", "close"}
teslamate_1  |     ],
teslamate_1  |     method: :post,
teslamate_1  |     opts: [],
teslamate_1  |     query: [],
teslamate_1  |     status: 400,
teslamate_1  |     url: "https://auth.tesla.com/oauth2/v3/token"
teslamate_1  |   },
teslamate_1  |   message: nil,
teslamate_1  |   reason: :token_refresh
teslamate_1  | }
teslamate_1  | 2021-03-02 23:24:52.063 [warn] Retrying in 1 hour...
teslamate_1  | 2021-03-02 23:35:35.580 [info] GET /
teslamate_1  | 2021-03-02 23:35:35.622 [info] Sent 200 in 42ms
teslamate_1  | 2021-03-03 00:20:34.749 car_id=1 [info] Start / :online
teslamate_1  | 2021-03-03 00:20:34.799 car_id=1 [info] Connecting ...
teslamate_1  | 2021-03-03 00:23:36.931 car_id=1 [info] Suspending logging
teslamate_1  | 2021-03-03 00:24:52.064 [info] Refreshing access token ...
teslamate_1  | 2021-03-03 00:24:52.310 [error] POST https://auth.tesla.com/oauth2/v3/token -> 400 (244.806 ms)
teslamate_1  | 2021-03-03 00:24:52.314 [warn] Token refresh failed: %TeslaApi.Error{
teslamate_1  |   env: %Tesla.Env{
teslamate_1  |     __client__: %Tesla.Client{adapter: nil, fun: nil, post: [], pre: []},
teslamate_1  |     __module__: TeslaApi.Auth,
teslamate_1  |     body: %{
teslamate_1  |       "error" => "server_error",
teslamate_1  |       "error_description" => "Internal server error",
teslamate_1  |       "error_uri" => "https://auth.tesla.com/error/reference/0626697f-40f3-4b4c-9734-e14b63830664-1614749092221"
teslamate_1  |     },
teslamate_1  |     headers: [
teslamate_1  |       {"server", "nginx"},
teslamate_1  |       {"content-type", "application/json"},
teslamate_1  |       {"x-dns-prefetch-control", "off"},
teslamate_1  |       {"x-frame-options", "DENY"},
teslamate_1  |       {"strict-transport-security", "max-age=15552000; includeSubDomains"},
teslamate_1  |       {"x-download-options", "noopen"},
teslamate_1  |       {"x-content-type-options", "nosniff"},
teslamate_1  |       {"x-xss-protection", "1; mode=block"},
teslamate_1  |       {"x-request-id", "0626697f-40f3-4b4c-9734-e14b63830664"},
teslamate_1  |       {"x-correlation-id", "0626697f-40f3-4b4c-9734-e14b63830664"},
teslamate_1  |       {"access-control-allow-origin", "*"},
teslamate_1  |       {"x-response-time", "7.046ms"},
teslamate_1  |       {"date", "Wed, 03 Mar 2021 05:24:52 GMT"},
teslamate_1  |       {"connection", "close"}
teslamate_1  |     ],
teslamate_1  |     method: :post,
teslamate_1  |     opts: [],
teslamate_1  |     query: [],
teslamate_1  |     status: 400,
teslamate_1  |     url: "https://auth.tesla.com/oauth2/v3/token"
teslamate_1  |   },
teslamate_1  |   message: nil,
teslamate_1  |   reason: :token_refresh
teslamate_1  | }
teslamate_1  | 2021-03-03 00:24:52.314 [warn] Retrying in 1 hour...
teslamate_1  | 2021-03-03 00:26:53.863 [info] GET /
teslamate_1  | 2021-03-03 00:26:53.882 [info] Sent 200 in 19ms
teslamate_1  | 2021-03-03 00:26:54.649 [info] GET /
teslamate_1  | 2021-03-03 00:26:54.666 [info] Sent 200 in 17ms
teslamate_1  | 2021-03-03 00:53:46.450 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/5853617637379554/vehicle_data -> 408 (9137.932 ms)
teslamate_1  | 2021-03-03 00:53:46.450 car_id=1 [error] Error / :vehicle_unavailable
teslamate_1  | 2021-03-03 00:54:22.024 car_id=1 [info] Vehicle is still online. Falling asleep for: 33 min

**Comment by raushel** [comment]
Err, this is the TeslaUSB github, not TeslaMate, but basically you need to update your docker for TeslaMate for the latest API Auth changes from awhile back and then Log Out / Log Back in.

**Comment by rmyadsk** [comment]
D'oh! My mistake. Please close with indignity pointed here: I can confirm the teslausb-20201211 image works terrificly absent a `apt-get update; apt-get upgrade -y; apt autoremove -y` for Raspian things. Thanks @raushel!
