### ISSUE TITLE
rsync archival method does not seem to follow export trigger_file*

### ISSUE THREAD

**Issue by rmyadsk** [marcone/teslausb#617]
After several months as a Mac user (as a person hosting a Mac archival server, to two teslausb clients) suffering along with Apple's implementation of SMB/CIFS/whatevs, and ultimately finding it broken with a recent Big Sur release, I decided to implement the rsync archival method instead.

Great success. Though the ARCHIVE_UPLOADED files are no longer to be seen.

I worked from the instructions at https://github.com/cimryan/teslausb/blob/master/doc/SetupRSync.md but had preloaded my system to be ready for it. Specifically, in lieu of a CIFS section, the first lines of my config file are:

export ARCHIVE_SYSTEM=rsync
export RSYNC_USER=piuser
export RSYNC_SERVER=0.0.420.69
export RSYNC_PATH=/Volumes/To/The/Moon/

Anyway, I can assure you that rsync archiving succeeds from first run, but the associated below does not: 

> export trigger_file_saved=ARCHIVE_UPLOADED
> export trigger_file_sentry=ARCHIVE_UPLOADED
> export trigger_file_any=ARCHIVE_UPLOADED

Can we make teslausb write these files upon successful rsync write?

**Comment by marcone** [comment]
The best way to do this is probably to have archiveloop create the trigger files in a directory under /tmp, and then simply have archive-clips.sh copy them over. Then it would work with each archive method.

**Comment by rmyadsk** [comment]
Updated my installation and observed the desired file present following an archive, thanks!
