### ISSUE TITLE
rclone s3

### ISSUE THREAD

**Issue by cavit99** [marcone/teslausb#624]
rclone to s3 logs error:
Command move needs 2 arguments maximum: you provided 3 non flag arguments: ["" "/tmp/cam/merged" "MyRemote:MyPath"]

https://pastebin.com/xXVnajyH

**Comment by marcone** [comment]
Thanks for the report, should be fixed now. Run `setup-teslausb upgrade` to get the fix.

**Comment by cavit99** [comment]
Thank you! that works
