### ISSUE TITLE
rclone - how to delete files on SD

### ISSUE THREAD

**Issue by HolgerGERMANY** [marcone/teslausb#627]
I am using clone to sync with dropbox. I received the files. Delete on Dropbox but how do they get deleted on the teslausb?
I assumed it would sync the delete. I can see the files by smb: into teslausb via Mac Server. There I can not delete the files manually. Thank you for your time using on the teslausb and my issue.
[diagnostics.txt](https://github.com/marcone/teslausb/files/6327956/diagnostics.txt)

**Comment by marcone** [comment]
Teslausb manages the files. They'll get deleted when the space is needed.
