### ISSUE TITLE
monitoring which files are accessed on the virtual usb drive

### ISSUE THREAD

**Issue by stepir** [marcone/teslausb#628]
Hi

apologies the ask is not really related to this project - but I'm looking to achieve something similar and wondering if someone familiar with this project can help me confirm the approach is feasible:

I have a locked (meaning the manufacturer disabled mouse/keyboard etc etc) that is looking for an update file on a usb drive. I need to discover the name of that file. I thought about using something similar to Teslausb approach and leveraging a PI Zero to emulate a USB disk.

Do you know if from the PI is there a way to monitor what file system activities the USB HOST is doing (or trying to do) on the PI's virtualised usb drive?

Thanks

**Comment by marcone** [comment]
The Pi doesn't see the host's file system activities, it only sees block access to the device.
