### ISSUE TITLE
Integrate MiniDLNA (Feature Request)

### ISSUE THREAD

**Issue by stefaanbolle** [marcone/teslausb#629]
Some possibility to add (I did it manually)
Install minidlna via teslausb-setup script 
Change friendly name to "teslaUSB (miniDLNA)" or similar in minidlna.conf
Change paths to media_dir=V,/mutable/TeslaCam/SavedClips/ and media_dir=V,/mutable/TeslaCam/SentryClips/ in minidlna.conf

As a result, you can view the videos via a streaming client on phone, PC,... when connected to TeslaUSB AP or via your network

**Comment by marcone** [comment]
PR welcome
