### ISSUE TITLE
Webook to Home Assistant Issue

### ISSUE THREAD

**Issue by jun3280net** [marcone/teslausb#632]
Hi there.  I recently updated Teslausb - and noticed the significant improvements since the last time I did a fresh install.  While everything works, I wanted to enable notifications to my phone when the files were being processed.  I noticed the ability to use Webhooks and Home Assistant, so I decided to enable it.  I configured Home Assistant according to their documentation : 

[https://www.home-assistant.io/docs/automation/trigger/#webhook-trigger](https://www.home-assistant.io/docs/automation/trigger/#webhook-trigger)

My entry in HA is as follows :
![image](https://user-images.githubusercontent.com/30555695/115962878-a3087b80-a4da-11eb-8390-453e8542eb90.png)

I ran the CURL command : curl -X POST https://hassio.xyz.ddns.net/api/webhook/teslausb
![image](https://user-images.githubusercontent.com/30555695/115962995-16aa8880-a4db-11eb-8dba-bdcf64029c59.png)

I confirmed I received messages on my phone (with the word "payload") for 2/3 tests (2nd one failed as I adjusted network config).

Teslausb config file is setup as follows : 
![image](https://user-images.githubusercontent.com/30555695/115963335-1fe82500-a4dc-11eb-9964-85f52b96f2fe.png)

Teslausb logs (using the newly implemented web interface - which is awesome) shows the following : 
![image](https://user-images.githubusercontent.com/30555695/115963411-62a9fd00-a4dc-11eb-9da2-8d028b25c3f8.png)

However - I receive no notifications on my phone.   I would have expected at a minimum the same notification as generated by the Curl command above. Any idea what I might have done wrong? or how I can debug / troubleshoot this?

Thanks in advance for any insights.

**Comment by marcone** [comment]
The webhook notification also sends along data as part of the POST: https://github.com/marcone/teslausb/blob/main-dev/run/send-push-message#L56
Maybe Home Assistant doesn't like that?
Or maybe it just wasn't able to connect. The fact that it apparently only archived 7 files in 9 minutes tells me your Pi has really poor wifi reception.

You can try just running `/root/bin/send-push-message title message` on the command line on the Pi, and see if that works or reports something useful.

**Comment by jun3280net** [comment]
> The webhook notification also sends along data as part of the POST: https://github.com/marcone/teslausb/blob/main-dev/run/send-push-message#L56
> Maybe Home Assistant doesn't like that?
> Or maybe it just wasn't able to connect. The fact that it apparently only archived 7 files in 9 minutes tells me your Pi has really poor wifi reception.
> 
> You can try just running `/root/bin/send-push-message title message` on the command line on the Pi, and see if that works or reports something useful.

Thank you for your prompt response @marcone!  Is there any way to check the speed of the file transfers or check the strength of the wifi connection?  That said, Teslausb from what I've observed, the files have always made it to the NAS.

On that note - I've run the command you've suggested.  I must have something configured wrong.  
![image](https://user-images.githubusercontent.com/30555695/115967231-a3ab0d00-a4ee-11eb-8916-b24ec23736f5.png)

That said I navigated to the bin directory, and did a "nano send-push-message" to see what might be inside : 
![image](https://user-images.githubusercontent.com/30555695/115967696-39e03280-a4f1-11eb-8b5d-1542920c7af7.png)

I searched through the thread to see how that command might be used - and saw a comment you made in another thread.  Same issue with the command.
![image](https://user-images.githubusercontent.com/30555695/115967816-f33f0800-a4f1-11eb-9a05-ecab91104fb7.png)

Thanks again for your help

**Comment by marcone** [comment]
Try:
```
sudo -i
bash -c bash notbash
function log { echo "$@"; }
export -f log
bin/send-push-message title message
```

**Comment by jun3280net** [comment]
> Try:
> 
> ```
> sudo -i
> bash -c bash notbash
> function log { echo "$@"; }
> export -f log
> bin/send-push-message title message
> ```

Great - PROGRESS!
![image](https://user-images.githubusercontent.com/30555695/115968875-1ae49f00-a4f7-11eb-9d6b-1cb4a5b1eb37.png)

It is now registering with Home Assistant!  I am now getting the same message as the original CURL command.  I think I need to adjust the Home Assistant side of things to process whatever information is being sent via Webhook.

Cheers and thanks

**Comment by jun3280net** [comment]
@marcone thanks for your help.  Getting it to work from the Raspberry Pi was the key.  I was able to figure out what was required in the Home Assistant - Automations.yaml file.  Teslausb Webhook passes in JSON data.

![image](https://user-images.githubusercontent.com/30555695/115975775-01f2e280-a525-11eb-8866-4a2a11dbda72.png)

![image](https://user-images.githubusercontent.com/30555695/115975852-a7a65180-a525-11eb-8db0-e4d3243d03dd.png)
