### ISSUE TITLE
using 2020-12-11 img, clips not deleted from SD card after archive

### ISSUE THREAD

**Issue by maximus9696** [marcone/teslausb#638]
After upgrading, I see the clips now remain in the SD card after a successful archive. Is this intentional? The previous version that I started with would delete the clips from the SD card after archiving. Thank you

**Comment by marcone** [comment]
Yes, this is intentional. See issue https://github.com/marcone/teslausb/issues/467 for context.

**Comment by marcone** [comment]
(also note that this has nothing to do with the image that you flashed. The image just contains the basic linux system, the actual teslausb code is downloaded during setup)
