### ISSUE TITLE
The sample config file in the image is not up to date

### ISSUE THREAD

**Issue by henroFall** [marcone/teslausb#639]
The .sample config file that comes in the prebuilt image is too early to contain the extra parameters for true/false on uploading the non-sentry clips (recent, track, etc.). pi-gen-sources/00-teslausb-tweaks/files/ contains a more up-to-date version with those values.

**Comment by marcone** [comment]
Yes, that's why in the comment section at the top it links to the location of the latest config file.
I don't want to update the image every time a new config option is added.
