### ISSUE TITLE
TeslaUSB - Sync Music Only

### ISSUE THREAD

**Issue by jun3280net** [marcone/teslausb#643]
Hi @marcone, I was wondering if there's a way to sync just the music and NOT the video.  I'm noticing the videos never sync with my storage because the Tesla sleeps within minutes by the time I get home.  Or  it could be that my wifi connection speed is too slow - is there a way to check transfer speed?  It is however fast enough for synching the music I find.

That said, the web interface you've designed is fantastic for viewing files, and I think I'm satisfied with just leaving the videos on the sdcard now.  Adding additional functionality to the web interface to drop snapshots to recover disk space would be perfect?  To be honest, I'm not entirely sure how the sd card space is managed.  I have a 256GB card, 128GB for TeslaCam, 10GB for Music, is the remainder of the space used for Snapshots?

Thanks for all the great work!

**Comment by marcone** [comment]
Perhaps I misunderstood what you meant, but what you describe can't happen. Teslausb syncs music after it finishes archiving, so if the car goes to sleep during archiving, it will not sync music.
The remaining space is indeed used for snapshots, and snapshots are managed automatically by teslausb so it doesn't seem super useful to manage them manually through the web interface.

**Comment by jun3280net** [comment]
> Perhaps I misunderstood what you meant, but what you describe can't happen. Teslausb syncs music after it finishes archiving, so if the car goes to sleep during archiving, it will not sync music.
> The remaining space is indeed used for snapshots, and snapshots are managed automatically by teslausb so it doesn't seem super useful to manage them manually through the web interface.

Hi @marcone, thanks for the response.  Synching music is only a few hundred MBs, so it should finish before Teslausb sleeps.  However, the video files are a few GBs which is why archiving never finishes.   As the web interface you developed works so well, I'm not sure there's any value in synching the video to the NAS for me.  I'd rather Teslausb be used to synch my music updates instead now going forward if that's possible.  

Or is the snapshot management part of the archiving process?  On that note, is there a way to have Teslausb send an MQTT command perhaps (archive start and archive end), where I could leverage Home Assistant/NodeRED to keep Tesla awake until archive is completed?

Thanks again for your great work!

**Comment by marcone** [comment]
> is there a way to have Teslausb send an MQTT command perhaps

Maybe the IFTTT or generic webhook messaging would work for that?

**Comment by jun3280net** [comment]
> > is there a way to have Teslausb send an MQTT command perhaps
> 
> Maybe the IFTTT or generic webhook messaging would work for that?

@marcone good suggestion.  I will look into seeing if I can get HA/NODERED to see if it can leverage the webhooks to trigger actions.  

On that note - do you know what would cause TESLAUSB not to mount in the Tesla?  I even tried unplugging and re-plugging in the device while driving.  Nothing ended up getting recorded on the day (Jun 15, 2021).  However, when I returned home, I could confirm I could connect to Teslausb via your web interface - so it appears it is running.

Screenshot noted below : 
![image](https://user-images.githubusercontent.com/30555695/122156164-aa3a6e80-ce25-11eb-8271-c68d875d46d7.png)



Archive Loop : 
==============================================
Tue 15 Jun 08:17:03 MDT 2021: Starting archiveloop at 23.94 seconds uptime...
Tue 15 Jun 08:17:04 MDT 2021: taking snapshot of cam disk in /backingfiles/snapshots/snap-000112
Tue 15 Jun 08:17:20 MDT 2021: took snapshot
Tue 15 Jun 08:17:24 MDT 2021: comparing new snapshot with /backingfiles/snapshots/snap-000111/snap.bin
Tue 15 Jun 08:17:24 MDT 2021: making links for /tmp/snapshots/snap-000112, retargeted to /backingfiles/snapshots/snap-000112/mnt
Tue 15 Jun 08:17:44 MDT 2021: made all links for /tmp/snapshots/snap-000112
Tue 15 Jun 08:17:44 MDT 2021: Running fsck on /backingfiles/cam_disk.bin...
Tue 15 Jun 08:17:45 MDT 2021: | fsck from util-linux 2.33.1
Tue 15 Jun 08:17:48 MDT 2021: | fsck.fat 4.1 (2017-01-24)
Tue 15 Jun 08:17:48 MDT 2021: | 0x41: Dirty bit is set. Fs was not properly unmounted and some data may be corrupt.
Tue 15 Jun 08:17:48 MDT 2021: |  Automatically removing dirty bit.
Tue 15 Jun 08:17:48 MDT 2021: | Long filename fragment "2021-06-14_05" found outside a LFN sequence.
Tue 15 Jun 08:17:48 MDT 2021: |   (Maybe the start bit is missing on the last fragment)
Tue 15 Jun 08:17:48 MDT 2021: |   Not auto-correcting this.
Tue 15 Jun 08:17:48 MDT 2021: | Long filename fragment "2021-06-13_17" found outside a LFN sequence.
Tue 15 Jun 08:17:48 MDT 2021: |   (Maybe the start bit is missing on the last fragment)
Tue 15 Jun 08:17:48 MDT 2021: |   Not auto-correcting this.
Tue 15 Jun 08:17:48 MDT 2021: | Long filename fragment "2021-06-06_15" found outside a LFN sequence.
Tue 15 Jun 08:17:48 MDT 2021: |   (Maybe the start bit is missing on the last fragment)
Tue 15 Jun 08:17:48 MDT 2021: |   Not auto-correcting this.
Tue 15 Jun 08:17:48 MDT 2021: | Performing changes.
Tue 15 Jun 08:17:48 MDT 2021: | /dev/loop1p1: 770 files, 507217/2882847 clusters
Tue 15 Jun 08:17:49 MDT 2021: Finished fsck on /backingfiles/cam_disk.bin.
Tue 15 Jun 08:17:49 MDT 2021: Running fsck on /backingfiles/music_disk.bin...
Tue 15 Jun 08:17:49 MDT 2021: | fsck from util-linux 2.33.1
Tue 15 Jun 08:17:50 MDT 2021: | fsck.fat 4.1 (2017-01-24)
Tue 15 Jun 08:17:50 MDT 2021: | /dev/loop1p1: 289 files, 96983/1310015 clusters
Tue 15 Jun 08:17:50 MDT 2021: Finished fsck on /backingfiles/music_disk.bin.
Tue 15 Jun 08:17:50 MDT 2021: Trying to set time...
Tue 15 Jun 22:03:45 MDT 2021: Time adjusted by 49554.711534 seconds after 0.150000 seconds
Tue 15 Jun 22:03:45 MDT 2021: Archiving...
Tue 15 Jun 22:03:45 MDT 2021: Ensuring cam archive is mounted...
Tue 15 Jun 22:03:45 MDT 2021: Mounting /mnt/archive...
Tue 15 Jun 22:03:46 MDT 2021: Mounted /mnt/archive.
Tue 15 Jun 22:03:46 MDT 2021: Ensured cam archive is mounted.
Tue 15 Jun 22:03:46 MDT 2021: Ensuring music archive is mounted...
Tue 15 Jun 22:03:46 MDT 2021: Mounting /mnt/musicarchive...
Tue 15 Jun 22:03:46 MDT 2021: Mounted /mnt/musicarchive.
Tue 15 Jun 22:03:46 MDT 2021: Ensured music archive is mounted.
Tue 15 Jun 22:03:46 MDT 2021: Checking saved folder count...
Tue 15 Jun 22:03:46 MDT 2021: Ensuring cam file is mounted...
Tue 15 Jun 22:03:46 MDT 2021: Mounting /mnt/cam...
Tue 15 Jun 22:03:47 MDT 2021: Mounted /mnt/cam.
Tue 15 Jun 22:03:47 MDT 2021: Ensured cam file is mounted.
Tue 15 Jun 22:03:48 MDT 2021: There are 0 event folder(s) with 0 file(s) and 0 track mode file(s) to move.  0 short recording(s) will be skipped.
Tue 15 Jun 22:03:48 MDT 2021: cleaning cam mount
Tue 15 Jun 22:03:52 MDT 2021: done cleaning cam mount
Tue 15 Jun 22:03:53 MDT 2021: Trimming free space in /mnt/cam, which has 4314 extents
Tue 15 Jun 22:03:53 MDT 2021: Trim complete, image now has 3807 extents
Tue 15 Jun 22:03:53 MDT 2021: Unmounting /mnt/cam...
Tue 15 Jun 22:03:54 MDT 2021: Unmounted /mnt/cam.
Tue 15 Jun 22:03:54 MDT 2021: Finished archiving.
Tue 15 Jun 22:03:54 MDT 2021: Copying music...
Tue 15 Jun 22:03:54 MDT 2021: Starting music sync...
Tue 15 Jun 22:03:54 MDT 2021: Ensuring music backing file is mounted...
Tue 15 Jun 22:03:54 MDT 2021: Mounting /mnt/music...
Tue 15 Jun 22:03:54 MDT 2021: Mounted /mnt/music.
Tue 15 Jun 22:03:54 MDT 2021: Ensured music drive is mounted.
Tue 15 Jun 22:03:54 MDT 2021: Syncing music from archive...
Tue 15 Jun 22:03:57 MDT 2021: Copied 0 music file(s), deleted 0, skipped 273 previously-copied files, and encountered 0 errors.
Tue 15 Jun 22:03:57 MDT 2021: Trimming free space in /mnt/music, which has 1 extents
Tue 15 Jun 22:03:57 MDT 2021: Trim complete, image now has 1 extents
Tue 15 Jun 22:03:58 MDT 2021: Unmounting /mnt/music...
Tue 15 Jun 22:03:58 MDT 2021: Unmounted /mnt/music.
Tue 15 Jun 22:03:58 MDT 2021: Finished copying music.
Tue 15 Jun 22:03:58 MDT 2021: unmounting /mnt/archive
Tue 15 Jun 22:03:58 MDT 2021: Connecting usb to host...
Tue 15 Jun 22:03:58 MDT 2021: Connected usb to host.
Tue 15 Jun 22:03:58 MDT 2021: Waiting for archive to be unreachable...

Diagnostics : 
[TeslaUSB_diagnostics.txt](https://github.com/marcone/teslausb/files/6660379/TeslaUSB_diagnostics.txt)

**Comment by marcone** [comment]
I think you only copied part of the diagnostics, since a large part is missing. You might try plugging the Pi in to a PC and see if the CAM drive shows up there.

**Comment by jun3280net** [comment]
> I think you only copied part of the diagnostics, since a large part is missing. You might try plugging the Pi in to a PC and see if the CAM drive shows up there.

Thanks for the quick reply @marcone.  I've uploaded the full diagnostics.  

On that note, plugging it into the computer will mount and fixes the problem temporarily, until it no longer mounts in the Tesla again.  Is it possible this is a result of the archiving process getting interrupted and not completing?

**Comment by marcone** [comment]
That shouldn't be an issue. The only odd thing i see in your diagnostics is that there were two instances (on June 9 and 14) where the "autofs" system service apparently didn't start up. That would prevent teslausb from working correctly.

**Comment by jun3280net** [comment]
> That shouldn't be an issue. The only odd thing i see in your diagnostics is that there were two instances (on June 9 and 14) where the "autofs" system service apparently didn't start up. That would prevent teslausb from working correctly.

@marcone thanks for taking the time to review the logs.  Those would be the two dates that recently had problems.  Unplugging the device for 30 sec, then plugging it back into the Tesla will not fix the issue.  Plugging into the computer however has fixed the problem though.  Should I reinstall the device perhaps - although this was just reinstalled at the beginning of the month.

**Comment by jun3280net** [comment]
@marcone  hooking the Teslausb back to the computer works - but plugging it back into the car didn't work.  I ended up reinstalling, and that fixed it - it loaded up in 30 seconds.  Can I ask if you use CIFS or RSYNC?  From experience Teslausb seems to work well for a couple weeks, then something causes it to not to mount when connected to the Tesla (although it works fine connected to the computer).  The only thing I noticed when I SSH into the device, were 3-4 folders in the MUTABLE folder that did not adhere to the SNAPSHOT naming convention.  Those looked like errors.  Could that be causing the problem?

**Comment by marcone** [comment]
The Pi just acts as a USB storage device. It has no real knowledge of the host, so it shouldn't make a difference whether it's connected to a PC or to the car. It publishes the same drive in both cases.
I'm not sure what you mean about folders in the mutable partition not adhering to the snapshot naming convention. The snapshots are in the backingfiles partition, there are no snapshots in the mutable partition.

**Comment by jun3280net** [comment]
@marcone, sorry I misspoke.  I was referring to the Recent Drives folder.  The folders are usually a date stamp (eg 2021-06-18), but what I noticed some weird folder names that did not adhere to that standard.  I was curious that might cause the problem.  I had captured these weird folders in a previous post.
![image](https://user-images.githubusercontent.com/30555695/122661600-3fe93d00-d149-11eb-9f43-0f088994b8d5.png)

  
Tesla must be sensitive to something running in the PI that the Windows PC is not.  I've even tried rebooting the MCU in the Tesla to confirm if its the car.  When things work in the Tesla - it's usually up within 30 seconds.  Plugging into the computer, it is always up in 30 seconds. 

Since I've reinstalled from the 20201211 image - things seem to be working ok for now.  I'll hold up on updating for now to see if this mounting problem shows up again.  


Thanks for your insights

UPDATE : HOLY SMOKES - you added a viewer to the web interface.  This is AMAZING.

**Comment by jun3280net** [comment]
Reinstall seems to have fixed most of the issues I was experiencing.  I suppose configuring Teslausb at setup no to synch any of the videos would have achieved my original request - but I never tried.

The new online viewer eliminates the need to synch though.

On that note - @marcone is there a way to access the snapshots directly plugging the PI into a computer?  For instance if I notice something from the Sentry capture, but I want to see observe the details around the time of the event - I would need to check the snapshot right?

**Comment by marcone** [comment]
> is there a way to access the snapshots directly plugging the PI into a computer?

no, there isn't. The recordings in the snapshots are accessible via Samba or the web interface.
