### ISSUE TITLE
Unable to increase cam folder size to 32GB

### ISSUE THREAD

**Issue by chappyboy** [marcone/teslausb#646]
I am running the [scripts](https://github.com/marcone/teslausb/issues/560#issuecomment-730722972) to increase the CAM folder size to 32GB, however I am getting this following error.

> root@teslausb:~# bin/resize-image.sh 32G /backingfiles/cam_disk.bin
> growing
> fallocate: fallocate failed: No space left on device

My current CAM folder size is 17GB and the samba share of teslausb shows a total of 90GB of files. How can I remove some files from the recent clips to allow space to grow. My microsd is 128GB

**Comment by marcone** [comment]
You'll need to remove some of the snapshots in /backingfiles/snapshots
