### ISSUE TITLE
I’m having an issue where it says it can’t find cmdline.txt and the config.txt

### ISSUE THREAD

**Issue by keelant03** [marcone/teslausb#647]
But I can go to the boot drive and see the files![image](https://user-images.githubusercontent.com/85359400/123001697-03068b80-d37f-11eb-9559-0bc21be3fd07.jpeg)

**Comment by marcone** [comment]
It looks like you're trying to use the Windows-based manual setup process. I strongly recommend you use the "one step" setup instead: https://github.com/marcone/teslausb/blob/main-dev/doc/OneStepSetup.md
