### ISSUE TITLE
My custom settings were initialized after reboot

### ISSUE THREAD

**Issue by missflash** [marcone/teslausb#653]
Hi marcone,

I modified **/root/bin/archive-is-reachable.sh** and **~/bin/send-push-message** for my own purposes.
It works fine just after modification, and before reboot.

However, after reboot those files were initialized.
How can I keep my modification?

Another question,
I also want to add some scripts by using `crontab -e`
`@reboot /root/MY_SCRIPT.sh`
Those were also initialized after reboot.

**Comment by marcone** [comment]
The only way rebooting would change those files is if setup wasn't complete yet and continued after the reboot.
Once setup is complete, you can edit those files all you want and they won't be changed unless you run setup again.
