### ISSUE TITLE
SSH to music folder to delete files

### ISSUE THREAD

**Issue by Poncherelly** [marcone/teslausb#655]
Since the music folder doesn't sync, is it possible to ssh to the folder to delete files then new files could copy over the next time it connects?  I'd just prefer not having to pull the device out to make changes with my desktop.

**Comment by mrd0n** [comment]
Yes, you can ssh into a terminal session.  Try connecting via ‘ssh pi@teslausb.local’ or ‘ssh pi@<ip addr>‘ ensuring that the device is powered on. 

I’ve changed the default pi account password long ago and don’t recall the default, but I’m sure a quick look through the docs will reveal if you don’t know it.

**Comment by Poncherelly** [comment]
What would the path be?


Richard

Purchasing a TESLA?  Please use My Referral Code<https://ts.la/richard48613> for free supercharging

From: ***@***.***
Sent: July 22, 2021 8:52 p.m.
To: ***@***.***
Reply-to: ***@***.***
Cc: ***@***.***; ***@***.***
Subject: Re: [marcone/teslausb] SSH to music folder to delete files (#655)


Yes, you can ssh into a terminal session. Try connecting via ‘ssh ***@***.******@***.***>’ or ‘ssh pi@‘ ensuring that the device is powered on.

I’ve changed the default pi account password long ago and don’t recall the default, but I’m sure a quick look through the docs will reveal if you don’t know it.

**Comment by marcone** [comment]
(please don't advertise your referral code here)

Not sure why said "Since the music folder doesn't sync", but you can always ssh in to the Pi and mount it manually using `mount /mnt/music`

**Comment by Poncherelly** [comment]
Sorry, it was attached as my signature.

The music syncs one way but if I delete a file on the server, it doesn't update the pi. I figured I could ssh to the pi to manually delete files I no longer want.


From: ***@***.***
Sent: July 22, 2021 9:25 p.m.
To: ***@***.***
Reply-to: ***@***.***
Cc: ***@***.***; ***@***.***
Subject: Re: [marcone/teslausb] SSH to music folder to delete files (#655)


(please don't advertise your referral code here)

Not sure why said "Since the music folder doesn't sync", but you can always ssh in to the Pi and mount it manually using mount /mnt/music

**Comment by marcone** [comment]
> The music syncs one way but if I delete a file on the server, it doesn't update the pi.

Music sync has deleted files on the Pi that no longer exist on the server since 2019. Have you not updated teslausb since then?

**Comment by Poncherelly** [comment]
I'll try updating again but I'm certain I've updated the pi at least once this year.


If deleting a file in the music folder on the server will delete the file on the pi at next sync, then I'm a happy camper.


Thank you.

From: ***@***.***
Sent: July 22, 2021 9:40 p.m.
To: ***@***.***
Reply-to: ***@***.***
Cc: ***@***.***; ***@***.***
Subject: Re: [marcone/teslausb] SSH to music folder to delete files (#655)


The music syncs one way but if I delete a file on the server, it doesn't update the pi.

Music sync has deleted files on the Pi that no longer exist on the server since 2019. Have you not updated teslausb since then?
