### ISSUE TITLE
PI Zero W Single Blink no wireless

### ISSUE THREAD

**Issue by trinitron79** [marcone/teslausb#659]
[diagnostics.txt](https://github.com/marcone/teslausb/files/6971606/diagnostics.txt)
I've tried two different SD Cards at this point and a new USB cable.   The unit will boot and configure itself just fine and act normal, even the LED will do the 2 blinks that everything is normal.   However after some time it will change to a steady single blink and lose network connectivity.

The Pi Zero seems to be working fine as I've used a 3rd SD card and installed the normal PI software which had zero problems for a over 24 hrs, never dropped a ping nor did the unit reboot or NOT display video.

Any log files I could grab to help understand this problem?  I get about 2 mins or so that I'm able to SSH into the unit before it drops that connection.

**Comment by trinitron79** [comment]
was able to get the diag file created and copied before unit dropped from wifi.  Was doing the double blink now back to single blink and no wireless connection

**Comment by marcone** [comment]
IIRC from discussion in the Discord, you narrowed this down to a problem with a specific access point?
Closing this for now, but if there's something to be done in the Pi/teslausb side please let me know.
