### ISSUE TITLE
How to periodically upload videos using router?

### ISSUE THREAD

**Issue by missflash** [marcone/teslausb#660]
In my apartment parking lot, it is pretty difficult to connect WiFi.
So I installed 5G router in my Tesla, and it works fine at first time.

However, additional videos cannot automatically upload because TeslaUSB still connected WiFi.
If I reboot my router, TeslaUSB reconnect WiFi again and restart upload.

How to periodically upload videos using router?

**Comment by marcone** [comment]
That is not currently supported.
