### ISSUE TITLE
Jeda USB hub not working with Pi 4 zero

### ISSUE THREAD

**Issue by lynndixon** [marcone/teslausb#661]
I recent have been running TeslaUSB on a Pi zero W with no problems, directly plugged into the USB ports on my Model 3.  But I recently purchased the new version of the Jeda USB hub, and am trying to use the same Pi and setup plugged into the Jeda USB hub, (interior port on the hub) and its been very sketchy.  

Sometimes it will work without issue, flashing two lights and happy.  Sometimes the Pi will boot, get to 2 flashes but the car never sees the USB drive.  

Has anyone else had problems running a Pi Zero W with TeslaUSB in a Jeda hub?

**Comment by marcone** [comment]
Closing because there's nothing to be done on teslausb's side.
