### ISSUE TITLE
Can not use "Raspberry Pi Compute Module 4"

### ISSUE THREAD

**Issue by Travid** [marcone/teslausb#663]
Receiving this error when using a CM4 in a USB IO Board:
Sun 15 Aug 01:16:40 BST 2021 : STOP: unsupported hardware: 'Raspberry Pi Compute Module 4 Rev 1.0'
Sun 15 Aug 01:16:40 BST 2021 : (only Pi Zero W and Pi 4 have the necessary hardware to run teslausb)

Please allow this hardware as it DOES have all the necessary hardware.

**Comment by marcone** [comment]
That seems like a pretty niche use case to me. You're welcome to submit a PR to add support for it though.

**Comment by t-jonesy** [comment]
https://github.com/marcone/teslausb/pull/740
