### ISSUE TITLE
Latest version one step setup / after unable to SSH. Invalid credentials

### ISSUE THREAD

**Issue by jtslade777** [marcone/teslausb#665]
After the one step setup Tesla USB - Marcone is working perfectly but no matter what combination of default credentials found in documentation am unable to SSH to the Pi. Has credentials or SSH been disabled in the latest version.

**Comment by marcone** [comment]
ssh is still enabled and the default credentials are the same (user: pi, password: raspberry)
Can you reach the web interface?

**Comment by jtslade777** [comment]
Yes I am able to reach the Web interface

**Comment by marcone** [comment]
So what happens when you `ssh pi@teslausb` (where "teslausb" should be replaced with whatever name or IP address you use to access the web interface)

**Comment by jtslade777** [comment]
When I try and connect with putty: (using rasberry as password)

Using username "pi".
pi@192.168.1.121's password:
Access denied
pi@192.168.1.121's password:

**Comment by marcone** [comment]
> When I try and connect with putty: (using rasberry as password)

Just in case that wasn't a typo: it's "raspberry", not "rasberry"

**Comment by jtslade777** [comment]
That fixed it, I had been cut /pasting the password and it had a mistake. TY!
