### ISSUE TITLE
Does this project support the use of a larger USB antennae connected to the PI for better uploads?

### ISSUE THREAD

**Issue by w4rc0n** [marcone/teslausb#666]
I dont mind keeping a big ass antennae in my center console if it means better uploads.

**Comment by marcone** [comment]
I assume you mean a USB wifi adapter. That should work, though of course only with the Raspberry Pi 4.

**Comment by w4rc0n** [comment]
Oh, RPi4 is the only one that supports USB wifi antennae like: https://smile.amazon.com/TurboTenna-NextG-USB-Yagi-antenna-2200mW/dp/B0044D7J1W as an extreme example

**Comment by marcone** [comment]
Well, the Rpi0W only has one USB port and that's already used for connecting to the car, so if you need to connect any other USB device, you're gonna have to use an RPi4.

**Comment by w4rc0n** [comment]
Gotcha, perfect. Thanks!
