### ISSUE TITLE
Random missing time from recordings

### ISSUE THREAD

**Issue by calvarez** [marcone/teslausb#668]
I've noticed this happen a number of times.  I will go look for a recording and find a missing block of time.  Here is one example.  I was definitely driving for most of that missing time.  In fact I took a photo of something interesting, and then decided to go look for the video.  So I have a photo timestamped 16:34 but that block of time is missing from the recordings.  This isn't the only time, but it's one where I had complete assurance that I had indeed been driving at the time.

![image](https://user-images.githubusercontent.com/39809/130370194-0b865a14-ec80-498b-805e-570fcc6cbff7.png)

**Comment by marcone** [comment]
The script that the car uses to save recordings to the USB storage (https://twitter.com/greentheonly/status/1214669344933896192) simply drops the recordings when there's any kind of error. This seems consistent with that, and it's not something teslausb can do anything about.
