### ISSUE TITLE
Unable to upgrade

### ISSUE THREAD

**Issue by sanjert** [marcone/teslausb#672]
Hello,
Trying to upgrade but getting this error:

preparing for full upgrade
/tmp/setup-teslausb is up to date
rc.local is up to date
Updating package index files...
E: Command line option --allow-releaseinfo-change is not understood in combination with the other options
Failed, retrying
E: Command line option --allow-releaseinfo-change is not understood in combination with the other options
Failed, retrying
E: Command line option --allow-releaseinfo-change is not understood in combination with the other options
Failed, retrying
E: Command line option --allow-releaseinfo-change is not understood in combination with the other options
Failed, retrying
E: Command line option --allow-releaseinfo-change is not understood in combination with the other options
Failed, retrying
E: Command line option --allow-releaseinfo-change is not understood in combination with the other options
Failed, retrying

"--allow-releaseinfo-change" only works with apt update and not apt upgrade.
https://manpages.debian.org/unstable/apt/apt-get.8.en.html

**Comment by marcone** [comment]
`setup-teslausb` only calls `apt-get update --allow-releaseinfo-change`, so not sure what "other options" it is complaining about there.
Which version of `apt` do you have installed? (just run `apt` without arguments and it will tell you)

**Comment by sanjert** [comment]
Just updated it because it didnt work. But getting same error even after upgrade.
apt 1.4.11 (armhf)

Running apt-get update --allow-releaseinfo-change manually throwing the same error as well.

**Comment by marcone** [comment]
Are you still running the "Stretch" release of Raspbian?

**Comment by sanjert** [comment]
Maybe, i have another setup that works fine. Not sure if that's Buster or Stretch..
I'll reinstall and try again.
