### ISSUE TITLE
Unable to update the latest version due to the custom port

### ISSUE THREAD

**Issue by missflash** [marcone/teslausb#673]
I used custom port (1234) of cifs at the previous version of TeslaUSB.
I can mount target directory well with the following script.
mount -t cifs -o **port=1234**,user='ID',password='PASSWORD' //xxx.duckdns.org/MF_2/TeslaUSB /mnt/cam

However, I can't update the latest version due to the custom port although I already modified "/root/bin/archive-is-reachable.sh".

```
#!/bin/bash -eu

ARCHIVE_HOST_NAME="$1"

nc -z -w 5 "$ARCHIVE_HOST_NAME" 1234 > /dev/null 2>&1
```

The followings are current error messages.

===

verify-and-configure-archive: Done
verify-and-configure-archive: Verifying that the archive server xxx.duckdns.org is reachable...
verify-and-configure-archive: The archive server is reachable.
verify-and-configure-archive: Verifying that the archive share is mountable...
Trying all combinations of vers=(@@ default 3.0 2.1 2.0 1.0) and sec=(@@ ntlmssp ntlmv2 ntlm)
verify-and-configure-archive: Trying mount command-line:
**verify-and-configure-archive: mount -t cifs '//xxx.duckdns.org/MF_2/TeslaUSB' '/tmp/archivetestmount' -o 'credentials=/tmp/teslaCamArchiveCredentials,iocharset=utf8,file_mode=0777,dir_mode=0777,,'**
Unable to find suitable address.

===

I found this file (verify-and-configure-archive.sh) and modified port number.
However, it was changed to default port again when I executed "/root/bin/setup-teslausb" script.

**Comment by marcone** [comment]
Yes, setup always downloads the current scripts. You can either fork this project, update the scripts as needed and point your config file at it, or submit a PR to support alternate port numbers (I suggest just adding a generic "extra mount options" string rather than making it specific to the port number).
