### ISSUE TITLE
Setup Variables File Changes

### ISSUE THREAD

**Issue by GizmoGoody** [marcone/teslausb#675]
What is the easiest way to make a quick change to the setup variables file (e.g. new IFTTT config) for an installation already in use? I know to make the file system RW per the instructions, but not sure where to edit the file currently in use with 'sudo nano..."

**Comment by rmyadsk** [comment]
You'll first want to make the filesystem r/w, then edit `/root/teslausb_setup_variables.conf` to fit your desired changes, then run `/root/bin/setup-teslausb upgrade` to make those changes take effect. The end of that last step will set the filesystem back to r/o and trigger a reboot with your changes intact.

**Comment by marcone** [comment]
What @rmyadsk said. Note that not all options can be changed after initial setup, but changing the IFTTT config shouldn't be a problem.
