### ISSUE TITLE
Update failing due to wrong date

### ISSUE THREAD

**Issue by chrismarquardt** [marcone/teslausb#677]
During update, I got this output:

# /root/bin/setup-teslausb upgrade
preparing for full upgrade
/tmp/setup-teslausb is up to date
rc.local is up to date
Updating package index files...
Get:1 http://archive.raspberrypi.org/debian buster InRelease [32.7 kB]
Get:2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
Reading package lists... Done                                     
E: Release file for http://archive.raspberrypi.org/debian/dists/buster/InRelease is not valid yet (invalid for another 10d 19h 25min 59s). Updates for this repository will not be applied.
E: Release file for http://raspbian.raspberrypi.org/raspbian/dists/buster/InRelease is not valid yet (invalid for another 10d 17h 34min 5s). Updates for this repository will not be applied.
Get:1 http://archive.raspberrypi.org/debian buster InRelease [32.7 kB]
Get:2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]                            
Reading package lists... Done                                           
E: Release file for ....

looping indefinitely.

Turns out date and time were set 10 days in the past. 

To fix this, I had to manually set date/time to today.

Update: running diagnostics to /tmp/diagnostics.txt only yielded this:
====== summary ======
hardware: Raspberry Pi Zero W Rev 1.1
OS: Raspbian GNU/Linux 10 (buster)
CIFS archiving selected

**Comment by marcone** [comment]
Time/date should be set by NTP. If that's not happening, something on your network may be blocking it.
