### ISSUE TITLE
Change pi login password at configure time?

### ISSUE THREAD

**Issue by alanhoyle** [marcone/teslausb#681]
Would it be possible/desirable to modify the setup script so that it changes the `pi@teslacam` user password at configuration time, rather than insisting on doing an ssh login and manual `passwd`?  

I'm having trouble getting teslausb running to test, but I think this should be possible to do.

**Comment by marcone** [comment]
There are many security measures that could be applied (change the password, remove the "pi" user altogether, only allow key-based authentication, add password protection to the web interface), but ultimately I think those are outside the scope of teslausb, and people that care about them should be knowledgeable enough to apply them manually after getting teslausb to work.
