### ISSUE TITLE
issue upon first use after rebuild of SD card

### ISSUE THREAD

**Issue by jamesp132** [marcone/teslausb#686]
Hello, 

I have just rebuilt my SD card as I was facing some issues with the usb not backing up my data to google drive

but now when the build completes I get this error:

> Welcome to nginx!

> If you see this page, the nginx web server is successfully installed and working. Further configuration is required.

> For online documentation and support please refer to nginx.org.
> Commercial support is available at nginx.com.

> Thank you for using nginx.

I am unable to work out how I can get past this webpage to show the normal webpage again, I can SSH into the raspberry pi no problem, but unsure what "further configuration is required"

I have attempted to restore the SD card from 2 different computers and still the same issue. 

image I'm using for the build: 2021-08-15-teslausb.img

I have searched the issue pages but couldn't see anything similar to this, so if anyone knows what to do ill greatly appreciate the support.
<img width="1541" alt="Screenshot 2021-10-10 at 22 24 21" src="https://user-images.githubusercontent.com/16858684/136713452-ea632d20-d2be-41b7-ba28-ac6b509b294b.png">

**Comment by marcone** [comment]
Can you describe what exactly you did, starting with flashing 2021-08-15-teslausb.img onto the sd card?

**Comment by jamesp132** [comment]
sure! thanks for your response, 

so I formatted the drive as fat32 on my MacBook to remove all the data before. 

I then downloaded the latest image from https://github.com/marcone/teslausb/releases/tag/v3.0, and used the .img file in Etcher and set the wiped SD card as the one to put the image onto it then completed

then I remounted and changed the file teslausb_setup_variables to include my wifi - change the storage of the drive for the videos

moved the SD card over to the raspberry pi zero WH and proceeded to boot it, I've let it sit for 15 mins or more before touching it, when I SSH into the device it works fine I can run commands and connect it but if I try visit the "TeslaUSB.local" website I get the above error.

this happens every time even after a reinstall of the image, I have tried two computers both have the exact same error

if I am doing a step wrong please let me know

Edit: it's worth noting I can also see the cam folder on the desktop perfectly fine

**Comment by jamesp132** [comment]
Some good news! 

Worked it out the date and time was so far out of date (not sure why as I don't get a option to set it!)

But this has fixed it [NTP issue / fix ](https://github.com/marcone/teslausb/issues/93)

Appreciate your help anyway!

**Comment by marcone** [comment]
This doesn't make sense. If the Pi doesn't set the correct time from NTP then setup won't complete and you won't have the cam folder/drive. But you say the cam drive shows on the desktop, so setup completed, or at least progressed far enough to create the drive. Maybe setup was still in progress when you connected to the web interface? You can check the setup log in /boot to see if it's done.

**Comment by jamesp132** [comment]
[teslausb-headless-setup.log](https://github.com/marcone/teslausb/files/7318540/teslausb-headless-setup.log)
how weird here is the setup log if you want to have a look through it as I'm not too sure what I would be looking for adding diags also
[diagnostics.txt](https://github.com/marcone/teslausb/files/7318544/diagnostics.txt)

**Comment by marcone** [comment]
Logs show that you initially didn't provide a configuration file. Once you did, setup completed (and then you reran setup 2 more times after that)
My guess is that when nginx was showing the standard welcome page you showed above, setup simply hadn't completed yet.
