### ISSUE TITLE
external ssd

### ISSUE THREAD

**Issue by mihailvovk** [marcone/teslausb#687]
Hey,
  tried today multiple times, thought maybe I did a mistake somewhere.
But cannot make it work.
Pi4
```
Preparing to unpack .../5-sntp_1%3a4.2.8p12+dfsg-4_armhf.deb ...
Unpacking sntp (1:4.2.8p12+dfsg-4) ...
Setting up libopts25:armhf (1:5.18.12-4) ...
Setting up ntp (1:4.2.8p12+dfsg-4) ...
Created symlink /etc/systemd/system/multi-user.target.wants/ntp.service → /lib/systemd/system/ntp.service.
Setting up busybox-syslogd (1:1.30.1-4) ...
Setting up libevent-core-2.1-6:armhf (2.1.8-stable-4) ...
Setting up libevent-pthreads-2.1-6:armhf (2.1.8-stable-4) ...
Setting up sntp (1:4.2.8p12+dfsg-4) ...
Processing triggers for systemd (241-7~deb10u8+rpi1) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for libc-bin (2.28-10+rpi1) ...
W: --force-yes is deprecated, use one of the options starting with --allow instead.
(Reading database ... 42416 files and directories currently installed.)
Purging configuration files for rsyslog (8.1901.0-1) ...
Processing triggers for systemd (241-7~deb10u8+rpi1) ...
make-root-fs-readonly: Configuring system...
make-root-fs-readonly: Moving fake-hwclock data
make-root-fs-readonly: done
Skipping package upgrade.
All done.
(reboot now for changes to take effect)
```
and it's never booting again. forcing HDMI config in /boot, ... cannot access box anymore. it's kinda dead. cannot make display work or somehow get access to a live system.

**Comment by marcone** [comment]
Not enough information here. It looks like you ran setup manually. Why? Please post the entire setup log, not just the last part of it.

**Comment by mihailvovk** [comment]
Setup was redone manually (sudo /etc/rc.local), because MUSIC folder was not created on a remote share and it failed almost very last step. and I cannot access anything. If doing everything a proper way as it is supposed to, - it's rebooting and just dying. I cannot get access to the console after that. I bought a micro HDMI cable, but it's going till the initial startup and then the screen is just turning off. I would love to share logs but just cannot make it. Without SSD installation getting through without any errors and I am able to use my pi4 in the car. So, I gave up today with SSD and ordered 1tb microsd instead. 

Probably need to look at how to mount the partition to an external system.

This is all what I catched before it rebooted and went "offline":

root@huesla3:/boot# tail -f *.log
Mon 11 Oct 05:12:17 BST 2021 : Downloaded /root/bin/force_sync.sh ...
Mon 11 Oct 05:12:17 BST 2021 : Downloaded /tmp/create-backingfiles-partition.sh ...
Mon 11 Oct 05:12:17 BST 2021 : Downloaded /tmp/create-backingfiles.sh ...
Mon 11 Oct 05:12:17 BST 2021 : Downloaded /tmp/make-root-fs-readonly.sh ...
Mon 11 Oct 05:12:17 BST 2021 : Downloaded /tmp/configure.sh ...
Mon 11 Oct 05:12:17 BST 2021 : Fixing the modules-load parameter in /boot/cmdline.txt...
Mon 11 Oct 05:12:17 BST 2021 : Fixed cmdline.txt.
Mon 11 Oct 05:12:22 BST 2021 : create-backingfiles-partition: USB_DRIVE is set to /dev/sda
Mon 11 Oct 05:12:22 BST 2021 : create-backingfiles-partition: WARNING !!! This will delete EVERYTHING in /dev/sda.
Mon 11 Oct 05:12:53 BST 2021 : create-backingfiles-partition: /dev/sda fully erased. Creating partitions...




Mon 11 Oct 05:14:18 BST 2021 : create-backingfiles-partition: Backing files and mutable partitions created.
Mon 11 Oct 05:14:18 BST 2021 : create-backingfiles-partition: Formatting new partitions...
Mon 11 Oct 05:14:22 BST 2021 : create-backingfiles-partition: Done.
Mon 11 Oct 05:14:22 BST 2021 : Mounting the partition for the backing files...
Mon 11 Oct 05:14:53 BST 2021 : Mounted the partition for the backing files.
Mon 11 Oct 05:14:53 BST 2021 : Mounting the mutable partition...
Mon 11 Oct 05:14:53 BST 2021 : Mounted the mutable partition.
Mon 11 Oct 05:14:53 BST 2021 : Creating backing disk files.
Mon 11 Oct 05:14:53 BST 2021 : create-backingfiles: starting
Mon 11 Oct 05:14:53 BST 2021 : create-backingfiles: cam: 880G, music: 12G, mountpoint: /backingfiles, exfat: false
Mon 11 Oct 05:14:54 BST 2021 : create-backingfiles: Allocating 922746880K for /backingfiles/cam_disk.bin...
Mon 11 Oct 05:14:54 BST 2021 : create-backingfiles: Creating filesystem with label 'CAM'
Mon 11 Oct 05:15:07 BST 2021 : create-backingfiles: updated /etc/fstab for /mnt/cam
Mon 11 Oct 05:15:07 BST 2021 : create-backingfiles: created camera backing file
Mon 11 Oct 05:15:07 BST 2021 : create-backingfiles: Allocating 12582912K for /backingfiles/music_disk.bin...
Mon 11 Oct 05:15:08 BST 2021 : create-backingfiles: Creating filesystem with label 'MUSIC'
Mon 11 Oct 05:15:09 BST 2021 : create-backingfiles: updated /etc/fstab for /mnt/music
Mon 11 Oct 05:15:09 BST 2021 : create-backingfiles: created music backing file
Mon 11 Oct 05:15:20 BST 2021 : create-backingfiles: done
Mon 11 Oct 05:15:20 BST 2021 : calling configure.sh
Mon 11 Oct 05:15:20 BST 2021 : configure: Pushover not enabled.
Mon 11 Oct 05:15:20 BST 2021 : configure: Gotify not enabled.
Mon 11 Oct 05:15:20 BST 2021 : configure: IFTTT not enabled.
Mon 11 Oct 05:15:20 BST 2021 : configure: Discord not enabled.
Mon 11 Oct 05:15:20 BST 2021 : configure: Webhook not enabled.
Mon 11 Oct 05:15:21 BST 2021 : configure: Slack not enabled.
Mon 11 Oct 05:15:21 BST 2021 : configure: Matrix not configured.
Mon 11 Oct 05:15:21 BST 2021 : configure: Telegram not enabled.
Mon 11 Oct 05:15:21 BST 2021 : configure: SNS not configured.
Mon 11 Oct 05:15:21 BST 2021 : Downloaded /root/bin/send-push-message ...
Mon 11 Oct 05:15:21 BST 2021 : Downloaded /root/bin/send_sns.py ...
Mon 11 Oct 05:15:21 BST 2021 : Downloaded /root/bin/send_matrix.py ...
Mon 11 Oct 05:15:21 BST 2021 : configure: Checking archive configs: 
Mon 11 Oct 05:15:21 BST 2021 : configure: default rsync doesn't work, installing prebuilt 3.2.3
Mon 11 Oct 05:15:24 BST 2021 : configure: rsync works OK now
Mon 11 Oct 05:15:24 BST 2021 : configure: done
Mon 11 Oct 05:15:24 BST 2021 : configure: Using archive module: run/cifs_archive
Mon 11 Oct 05:15:24 BST 2021 : configure: Installing base archive scripts into /root/bin
Mon 11 Oct 05:15:24 BST 2021 : Downloaded /root/bin/archiveloop ...
Mon 11 Oct 05:15:24 BST 2021 : Downloaded /root/bin/waitforidle ...
Mon 11 Oct 05:15:24 BST 2021 : Downloaded /root/bin/remountfs_rw ...
Mon 11 Oct 05:15:24 BST 2021 : Downloaded /root/bin/awake_start ...
Mon 11 Oct 05:15:24 BST 2021 : Downloaded /root/bin/awake_stop ...
Mon 11 Oct 05:15:24 BST 2021 : configure: Skipping tesla_api.py install because no credentials were provided
Mon 11 Oct 05:15:24 BST 2021 : configure: Installing archive module scripts
Mon 11 Oct 05:15:24 BST 2021 : Downloaded /tmp/verify-and-configure-archive.sh ...
Mon 11 Oct 05:15:24 BST 2021 : Downloaded /root/bin/archive-clips.sh ...
Mon 11 Oct 05:15:24 BST 2021 : Downloaded /root/bin/connect-archive.sh ...
Mon 11 Oct 05:15:25 BST 2021 : Downloaded /root/bin/disconnect-archive.sh ...
Mon 11 Oct 05:15:25 BST 2021 : Downloaded /root/bin/archive-is-reachable.sh ...
Mon 11 Oct 05:15:25 BST 2021 : Downloaded /root/bin/copy-music.sh ...
Mon 11 Oct 05:15:25 BST 2021 : verify-and-configure-archive: Installing/updating required packages if needed
Mon 11 Oct 05:15:27 BST 2021 : verify-and-configure-archive: Done
Mon 11 Oct 05:15:27 BST 2021 : verify-and-configure-archive: Verifying that the archive server 172.16.0.23 is reachable...
Mon 11 Oct 05:15:28 BST 2021 : verify-and-configure-archive: The archive server is reachable.
Mon 11 Oct 05:15:28 BST 2021 : verify-and-configure-archive: Verifying that the archive share is mountable...
Mon 11 Oct 05:15:28 BST 2021 : verify-and-configure-archive: Trying mount command-line:
Mon 11 Oct 05:15:28 BST 2021 : verify-and-configure-archive: mount -t cifs '//172.16.0.23/TESLA' '/tmp/archivetestmount' -o 'credentials=/tmp/teslaCamArchiveCredentials,iocharset=utf8,file_mode=0777,dir_mode=0777,,'
Mon 11 Oct 05:15:28 BST 2021 : verify-and-configure-archive: The archive share is mountable using: mount -t cifs '//172.16.0.23/TESLA' '/tmp/archivetestmount' -o 'credentials=/tmp/teslaCamArchiveCredentials,iocharset=utf8,file_mode=0777,dir_mode=0777,,'
Mon 11 Oct 05:15:28 BST 2021 : verify-and-configure-archive: Verifying that the archive share is mountable...
Mon 11 Oct 05:15:28 BST 2021 : verify-and-configure-archive: Trying mount command-line:
Mon 11 Oct 05:15:28 BST 2021 : verify-and-configure-archive: mount -t cifs '//172.16.0.23/TESLA/MUSIC' '/tmp/archivetestmount' -o 'credentials=/tmp/teslaCamArchiveCredentials,iocharset=utf8,file_mode=0777,dir_mode=0777,,'
Mon 11 Oct 05:15:28 BST 2021 : verify-and-configure-archive: STOP: no working combination of vers and sec mount options worked
^C
root@huesla3:/boot# ^C
root@huesla3:/boot# ^C
root@huesla3:/boot# sudo /etc/rc.local
My IP address is 172.16.0.112 
Detecting whether to update wpa_supplicant.conf
Remounting / as read/write
Remounting /boot as read/write
Done. Make any changes needed, and reboot the Pi when ready.
Filesystems / and /boot will be mounted as read only after reboot.
Starting setup.
/root/bin/setup-teslausb is up to date
rc.local is up to date
Updating package index files...
Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:2 http://archive.raspberrypi.org/debian buster InRelease
Reading package lists... Done
Verifying that the requested configuration is valid...
Downloaded /tmp/verify-configuration.sh ...
USB_DRIVE is set to /dev/sda. This will be used for /mutable and backingfiles.
Verifying that there is sufficient space available on the USB drive ...
There is sufficient space available.
Downloading additional setup scripts.
Downloaded /root/bin/remountfs_rw ...
Downloaded /root/bin/make_snapshot.sh ...
Downloaded /root/bin/mount_snapshot.sh ...
Downloaded /root/bin/release_snapshot.sh ...
Downloaded /root/bin/force_sync.sh ...
Downloaded /tmp/create-backingfiles-partition.sh ...
Downloaded /tmp/create-backingfiles.sh ...
Downloaded /tmp/make-root-fs-readonly.sh ...
Downloaded /tmp/configure.sh ...
~ /boot
Fixing the modules-load parameter in /boot/cmdline.txt...
Fixed cmdline.txt.
create-backingfiles-partition: USB_DRIVE is set to /dev/sda
create-backingfiles-partition: Looks like backingfiles and mutable partitions already exist. Skipping partition creation.
create-backingfiles-partition: backingfiles already defined in /etc/fstab. Not modifying /etc/fstab.
create-backingfiles-partition: mutable already defined in /etc/fstab. Not modifying /etc/fstab.
create-backingfiles-partition: Done.
umount: /mnt/cam: not mounted.
calling configure.sh
configure: Pushover not enabled.
configure: Gotify not enabled.
configure: IFTTT not enabled.
configure: Discord not enabled.
configure: Webhook not enabled.
configure: Slack not enabled.
configure: Matrix not configured.
configure: Telegram not enabled.
configure: SNS not configured.
Downloaded /root/bin/send-push-message ...
Downloaded /root/bin/send_sns.py ...
Downloaded /root/bin/send_matrix.py ...
configure: Checking archive configs: 
building file list ... done
testfile.dat

sent 106 bytes  received 43 bytes  298.00 bytes/sec
total size is 9  speedup is 0.06
configure: rsync seems to work OK
configure: done
configure: Using archive module: run/cifs_archive
configure: Installing base archive scripts into /root/bin
Downloaded /root/bin/archiveloop ...
Downloaded /root/bin/waitforidle ...
Downloaded /root/bin/remountfs_rw ...
Downloaded /root/bin/awake_start ...
Downloaded /root/bin/awake_stop ...
configure: Skipping tesla_api.py install because no credentials were provided
configure: Installing archive module scripts
Downloaded /tmp/verify-and-configure-archive.sh ...
Downloaded /root/bin/archive-clips.sh ...
Downloaded /root/bin/connect-archive.sh ...
Downloaded /root/bin/disconnect-archive.sh ...
Downloaded /root/bin/archive-is-reachable.sh ...
run/cifs_archive
Downloaded /root/bin/copy-music.sh ...
verify-and-configure-archive: Installing/updating required packages if needed
Reading package lists... Done
Building dependency tree       
Reading state information... Done
hping3 is already the newest version (3.a2.ds2-7).
The following packages were automatically installed and are no longer required:
  bluez-firmware libasound2 libasound2-data libfftw3-single3 libsamplerate0
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 39 not upgraded.
W: --force-yes is deprecated, use one of the options starting with --allow instead.
verify-and-configure-archive: Done
verify-and-configure-archive: Verifying that the archive server 172.16.0.23 is reachable...
verify-and-configure-archive: The archive server is reachable.
verify-and-configure-archive: Verifying that the archive share is mountable...
Trying all combinations of vers=(@@ default 3.0 2.1 2.0 1.0) and sec=(@@ ntlmssp ntlmv2 ntlm)
verify-and-configure-archive: Trying mount command-line:
verify-and-configure-archive: mount -t cifs '//172.16.0.23/TESLA' '/tmp/archivetestmount' -o 'credentials=/tmp/teslaCamArchiveCredentials,iocharset=utf8,file_mode=0777,dir_mode=0777,,'
verify-and-configure-archive: The archive share is mountable using: mount -t cifs '//172.16.0.23/TESLA' '/tmp/archivetestmount' -o 'credentials=/tmp/teslaCamArchiveCredentials,iocharset=utf8,file_mode=0777,dir_mode=0777,,'
verify-and-configure-archive: Verifying that the archive share is mountable...
Trying all combinations of vers=(@@) and sec=(@@)
verify-and-configure-archive: Trying mount command-line:
verify-and-configure-archive: mount -t cifs '//172.16.0.23/TESLA/MUSIC' '/tmp/archivetestmount' -o 'credentials=/tmp/teslaCamArchiveCredentials,iocharset=utf8,file_mode=0777,dir_mode=0777,,'
verify-and-configure-archive: The archive share is mountable using: mount -t cifs '//172.16.0.23/TESLA/MUSIC' '/tmp/archivetestmount' -o 'credentials=/tmp/teslaCamArchiveCredentials,iocharset=utf8,file_mode=0777,dir_mode=0777,,'
verify-and-configure-archive: Configuring the archive...
verify-and-configure-archive: Configured the archive.
Failed to disable unit: Unit file teslausb.service does not exist.
Created symlink /etc/systemd/system/backingfiles.mount.wants/teslausb.service → /lib/systemd/system/teslausb.service.
Downloaded /tmp/configure-automount.sh ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
autofs is already the newest version (5.1.2-4).
The following packages were automatically installed and are no longer required:
  bluez-firmware libasound2 libasound2-data libfftw3-single3 libsamplerate0
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 39 not upgraded.
W: --force-yes is deprecated, use one of the options starting with --allow instead.
Downloaded /root/bin/auto.teslausb ...
configure-automount: converting snapshot mountpoints to links
configure-automount: configured automount
Downloaded /tmp/configure-web.sh ...
configuring nginx
Reading package lists... Done
Building dependency tree       
Reading state information... Done
fcgiwrap is already the newest version (1.1.0-12).
libfuse-dev is already the newest version (2.9.9-1+deb10u1).
libnginx-mod-http-fancyindex is already the newest version (1.14.2-2+deb10u4).
nginx is already the newest version (1.14.2-2+deb10u4).
The following packages were automatically installed and are no longer required:
  bluez-firmware libasound2 libasound2-data libfftw3-single3 libsamplerate0
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 39 not upgraded.
W: --force-yes is deprecated, use one of the options starting with --allow instead.
done configuring nginx
make-root-fs-readonly: start
make-root-fs-readonly: Disabling unnecessary service...
Removed /etc/systemd/system/timers.target.wants/apt-daily.timer.
Removed /etc/systemd/system/timers.target.wants/apt-daily-upgrade.timer.
make-root-fs-readonly: Removing unwanted packages...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'triggerhappy' is not installed, so not removed
Package 'alsa-utils' is not installed, so not removed
Package 'bluez' is not installed, so not removed
The following packages were automatically installed and are no longer required:
  bluez-firmware dc libasound2 libasound2-data libfftw3-single3 libsamplerate0
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  dphys-swapfile* logrotate*
0 upgraded, 0 newly installed, 2 to remove and 39 not upgraded.
After this operation, 204 kB disk space will be freed.
(Reading database ... 42767 files and directories currently installed.)
Removing dphys-swapfile (20100506-5+rpt2) ...
Removing logrotate (3.14.0-4) ...
Processing triggers for man-db (2.8.5-2) ...
(Reading database ... 42740 files and directories currently installed.)
Purging configuration files for logrotate (3.14.0-4) ...
Purging configuration files for dphys-swapfile (20100506-5+rpt2) ...
Processing triggers for systemd (241-7~deb10u8+rpi1) ...
W: --force-yes is deprecated, use one of the options starting with --allow instead.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  bluez-firmware* dc* libasound2* libasound2-data* libfftw3-single3* libsamplerate0*
0 upgraded, 0 newly installed, 6 to remove and 39 not upgraded.
After this operation, 5,042 kB disk space will be freed.
(Reading database ... 42733 files and directories currently installed.)
Removing bluez-firmware (1.2-4+rpt8) ...
Removing dc (1.07.1-2) ...
Removing libasound2:armhf (1.1.8-1+rpt1) ...
Removing libasound2-data (1.1.8-1+rpt1) ...
Removing libfftw3-single3:armhf (3.3.8-2) ...
Removing libsamplerate0:armhf (0.1.9-2) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for install-info (6.5.0.dfsg.1-4+b1) ...
Processing triggers for libc-bin (2.28-10+rpi1) ...
(Reading database ... 42367 files and directories currently installed.)
Purging configuration files for dc (1.07.1-2) ...
W: --force-yes is deprecated, use one of the options starting with --allow instead.
make-root-fs-readonly: Installing ntp and busybox-syslogd...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libevent-core-2.1-6 libevent-pthreads-2.1-6 libopts25 sntp
Suggested packages:
  ntp-doc
The following packages will be REMOVED:
  rsyslog
The following NEW packages will be installed:
  busybox-syslogd libevent-core-2.1-6 libevent-pthreads-2.1-6 libopts25 ntp sntp
0 upgraded, 6 newly installed, 1 to remove and 39 not upgraded.
Need to get 1,108 kB of archives.
After this operation, 1,178 kB of additional disk space will be used.
Get:1 http://raspbian.mirrors.lucidnetworks.net/raspbian buster/main armhf busybox-syslogd all 1:1.30.1-4 [26.1 kB]
Get:2 http://raspbian.mirrors.lucidnetworks.net/raspbian buster/main armhf libevent-core-2.1-6 armhf 2.1.8-stable-4 [117 kB]
Get:3 http://raspbian.mirrors.lucidnetworks.net/raspbian buster/main armhf libevent-pthreads-2.1-6 armhf 2.1.8-stable-4 [47.6 kB]
Get:4 http://raspbian.mirrors.lucidnetworks.net/raspbian buster/main armhf libopts25 armhf 1:5.18.12-4 [61.1 kB]
Get:5 http://raspbian.mirrors.lucidnetworks.net/raspbian buster/main armhf ntp armhf 1:4.2.8p12+dfsg-4 [695 kB]
Get:6 http://raspbian.mirrors.lucidnetworks.net/raspbian buster/main armhf sntp armhf 1:4.2.8p12+dfsg-4 [161 kB]
Fetched 1,108 kB in 3s (442 kB/s)
(Reading database ... 42367 files and directories currently installed.)
Removing rsyslog (8.1901.0-1) ...
Selecting previously unselected package busybox-syslogd.
(Reading database ... 42309 files and directories currently installed.)
Preparing to unpack .../0-busybox-syslogd_1%3a1.30.1-4_all.deb ...
Unpacking busybox-syslogd (1:1.30.1-4) ...
Selecting previously unselected package libevent-core-2.1-6:armhf.
Preparing to unpack .../1-libevent-core-2.1-6_2.1.8-stable-4_armhf.deb ...
Unpacking libevent-core-2.1-6:armhf (2.1.8-stable-4) ...
Selecting previously unselected package libevent-pthreads-2.1-6:armhf.
Preparing to unpack .../2-libevent-pthreads-2.1-6_2.1.8-stable-4_armhf.deb ...
Unpacking libevent-pthreads-2.1-6:armhf (2.1.8-stable-4) ...
Selecting previously unselected package libopts25:armhf.
Preparing to unpack .../3-libopts25_1%3a5.18.12-4_armhf.deb ...
Unpacking libopts25:armhf (1:5.18.12-4) ...
Selecting previously unselected package ntp.
Preparing to unpack .../4-ntp_1%3a4.2.8p12+dfsg-4_armhf.deb ...
Unpacking ntp (1:4.2.8p12+dfsg-4) ...
Selecting previously unselected package sntp.
Preparing to unpack .../5-sntp_1%3a4.2.8p12+dfsg-4_armhf.deb ...
Unpacking sntp (1:4.2.8p12+dfsg-4) ...
Setting up libopts25:armhf (1:5.18.12-4) ...
Setting up ntp (1:4.2.8p12+dfsg-4) ...
Created symlink /etc/systemd/system/multi-user.target.wants/ntp.service → /lib/systemd/system/ntp.service.
Setting up busybox-syslogd (1:1.30.1-4) ...
Setting up libevent-core-2.1-6:armhf (2.1.8-stable-4) ...
Setting up libevent-pthreads-2.1-6:armhf (2.1.8-stable-4) ...
Setting up sntp (1:4.2.8p12+dfsg-4) ...
Processing triggers for systemd (241-7~deb10u8+rpi1) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for libc-bin (2.28-10+rpi1) ...
W: --force-yes is deprecated, use one of the options starting with --allow instead.
(Reading database ... 42416 files and directories currently installed.)
Purging configuration files for rsyslog (8.1901.0-1) ...
Processing triggers for systemd (241-7~deb10u8+rpi1) ...
make-root-fs-readonly: Configuring system...
make-root-fs-readonly: Moving fake-hwclock data
make-root-fs-readonly: done
Skipping package upgrade.
All done.
(reboot now for changes to take effect)

**Comment by marcone** [comment]
You set USB_DRIVE, which is for booting from sd card and using another drive for storage. I recommend not using an sd card at all and just booting from the SSD instead, as it's simpler and better tested. (just "flash" the prebuilt image to the SSD instead of the sd card, but *don't* set USB_DRIVE in the config file).

You can get the full setup log from the /boot partition, which is fat32 so you can just read it on a PC with an sd card reader.
