### ISSUE TITLE
TeslaMusic path

### ISSUE THREAD

**Issue by Poncherelly** [marcone/teslausb#691]
What would the path be to view the Music folder when SSH in to the pi?  I found the TeslaCam files under mutable, but I can't find the music / boombox folder.

Are you able to share the path with me?  Using Find doesn't work.

Thanks in advance.

**Comment by marcone** [comment]
The files you found in /mutable aren't _the_ TeslaCam files, they are links to files that exist in image snapshots.
To access the drive images that the car sees, you need to mount them, e.g. `mount /mnt/music`. You should ensure that the car isn't also accessing them at the same time, e.g. by running `modprobe -r g_mass_storage` first.
