### ISSUE TITLE
Raspberry Pi Zero 2 Rev 1.0 support

### ISSUE THREAD

**Issue by basalblas** [marcone/teslausb#692]
@marcone

I bought a new Pi Zero 2, but teslausb doesn't seem to support it yet. It's basically the same a the original Pi Zero, just a quicker CPU. Can you add support for it?

```
STOP: unsupported hardware: 'Raspberry Pi Zero 2 Rev 1.0'
(only Pi Zero W and Pi 4 have the necessary hardware to run teslausb)
```

**Comment by marcone** [comment]
Try it now.

**Comment by basalblas** [comment]
Seems to work thanks. It would be great if you also update the prebuild image to include support for the Raspberry Pi Zero 2. The current image doesn't work (I tried).

**Comment by marcone** [comment]
Doesn't work in what way?

**Comment by basalblas** [comment]
As in that it simply wouldn't boot from an SD card that was created using the prebuild image. I'll try again tomorrow. Maybe it works now after your update to the repo.

**Comment by basalblas** [comment]
The prebuild image doesn't work on a Raspberry Pi Zero 2
[teslausb-headless-setup.log](https://github.com/marcone/teslausb/files/7446221/teslausb-headless-setup.log)

The network doesn't even come up.

**Comment by marcone** [comment]
There could be other reasons for that, but I'll look at it once I can get a Zero 2

**Comment by basalblas** [comment]
It is notably quicker. It also seems to have fixed my mounting issue in my 2018 MS. No more need to add a 30 seconds sleep before enabling USB mount in archiveloop script

**Comment by marcone** [comment]
What did you do to get it working, given that the prebuilt image does not work? Manual install on top of a more recent Raspberry Pi OS?

**Comment by basalblas** [comment]
> What did you do to get it working, given that the prebuilt image does not work? Manual install on top of a more recent Raspberry Pi OS?

Exactly that. I used [https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2021-05-28/2021-05-07-raspios-buster-armhf-lite.zip](url) to create a bootable SD card, Amended the /boot/cmdline.txt file to remove the `init=/usr/lib/raspi-config/init_resize.sh` option (so it did not use all free space of the SD card after booting).

Then simply did a manual install as per your instructions, resizing the root partition with the `export INCREASE_ROOT_SIZE=2G` option in `teslausb_setup_variables.conf` otherwise the root partition is too small.

I also managed to get the awake function working using [https://github.com/tdorssers/TeslaPy](url) and copying the `TESLA_ACCESS_TOKEN` and `TESLA_REFRESH_TOKEN` from the cache.json file created by running TeslaPy manually on my Windows machine to `teslausb_setup_variables.conf`, copying that same cache.json to /mutable and manually amending /mutable/tesla_api.json using those values. Not sure if the tokens will be refreshed automatically when they expire though, but we'll see.

**Comment by marcone** [comment]
Interesting. That's from May, several months older than the prebuilt teslausb image.

**Comment by marcone** [comment]
On 2nd thought: were you actually using the latest teslausb image? You said "the root partition is too small", but the current prebuilt image has a 2GB root partition with over 600 MB of free space, which should be plenty I would think.

**Comment by DaveRuijter** [comment]
I can confirm that the current prebuilt image does not work with the Zero 2. It seems the WiFi setup is failing. 
After putting the same SD card in the Zero 1 it works well and completes the configuration.

Maybe it does work if you manually specify the WPA stuff, I will try that later.

**Comment by basalblas** [comment]
> On 2nd thought: were you actually using the latest teslausb image? You said "the root partition is too small", but the current prebuilt image has a 2GB root partition with over 600 MB of free space, which should be plenty I would think.

Yes I used the latest teslausb image. The prebuild teslausb image root partition is large enough. But the one created by https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2021-05-28/2021-05-07-raspios-buster-armhf-lite.zip after amending the /boot/cmdline.txt file to remove the init=/usr/lib/raspi-config/init_resize.sh option does not. From memory I think it only had a 500GB root partition.

**Comment by basalblas** [comment]
> On 2nd thought: were you actually using the latest teslausb image? You said "the root partition is too small", but the current prebuilt image has a 2GB root partition with over 600 MB of free space, which should be plenty I would think.

Is your latest telsausb image based on https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2021-05-28/2021-05-07-raspios-buster-armhf-lite.zip or maybe on an earlier version?

**Comment by marcone** [comment]
> Is your latest telsausb image based on https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2021-05-28/2021-05-07-raspios-buster-armhf-lite.zip or maybe on an earlier version?

I built the prebuilt image using pi-gen (which is also how the official Raspberry Pi images are built, from what I understand), so I think it would have used whatever was the current version of the code when I built it in August 2021.

**Comment by basalblas** [comment]
> > What did you do to get it working, given that the prebuilt image does not work? Manual install on top of a more recent Raspberry Pi OS?
> 
> Exactly that. I used [https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2021-05-28/2021-05-07-raspios-buster-armhf-lite.zip](url) to create a bootable SD card, Amended the /boot/cmdline.txt file to remove the `init=/usr/lib/raspi-config/init_resize.sh` option (so it did not use all free space of the SD card after booting).
> 
> Then simply did a manual install as per your instructions, resizing the root partition with the `export INCREASE_ROOT_SIZE=2G` option in `teslausb_setup_variables.conf` otherwise the root partition is too small.
> 
> I also managed to get the awake function working using [https://github.com/tdorssers/TeslaPy](url) and copying the `TESLA_ACCESS_TOKEN` and `TESLA_REFRESH_TOKEN` from the cache.json file created by running TeslaPy manually on my Windows machine to `teslausb_setup_variables.conf`, copying that same cache.json to /mutable and manually amending /mutable/tesla_api.json using those values. Not sure if the tokens will be refreshed automatically when they expire though, but we'll see.

The awake function worked for one day only. Today the Archiveloop log shows `Tue  2 Nov 21:48:55 CET 2021: failed to contact car, retrying`. Running tesla_api.py manually shows
`raceback (most recent call last):
  File "/root/bin/tesla_api.py", line 603, in <module>
    main()
  File "/root/bin/tesla_api.py", line 585, in main
    result = function(**kwargs)
  File "/root/bin/tesla_api.py", line 258, in list_vehicles
    return _execute_request(base_url, None, None, False)
  File "/root/bin/tesla_api.py", line 71, in _execute_request
    json_response = _rest_request(url, method, data)
  File "/root/bin/tesla_api.py", line 98, in _rest_request
    'Authorization': 'Bearer {}'.format(_get_api_token()),
  File "/root/bin/tesla_api.py", line 141, in _get_api_token
    tesla.refresh_token()
TypeError: refresh_token() missing 1 required positional argument: 'token_url'`

Looks like the tokens need to be refreshed every day now?

**Comment by marcone** [comment]
The problem is that the latest image only contains the "+" and "v7l+" architecture kernel+modules (for Pi0W and Pi4 32-bit, respectively). The "v7+" and "v8+" were removed from the image to save space.
The new Pi Zero 2 W needs the "v7+" binaries.

Using the previous prebuilt, 20201211, works.

**Comment by DaveRuijter** [comment]
Great to hear!

**Comment by basalblas** [comment]
> The problem is that the latest image only contains the "+" and "v7l+" architecture kernel+modules (for Pi0W and Pi4 32-bit, respectively). The "v7+" and "v8+" were removed from the image to save space. The new Pi Zero 2 W needs the "v7+" binaries.
> 
> Using the previous prebuilt, 20201211, works.

Will you create a new image at some point that includes "v7+" again? Is there any downside of using the original lite image from Raspberry and manually installing teslausb?

**Comment by marcone** [comment]
> Will you create a new image at some point that includes "v7+" again?

Yes.

> Is there any downside of using the original lite image from Raspberry and manually installing teslausb?

It's more work, which means more ways for things to go wrong.

**Comment by DaveRuijter** [comment]
> Using the previous prebuilt, 20201211, works.

Confirmed.

**Comment by marcone** [comment]
New prebuilt supports Raspberry Pi Zero 2 W

**Comment by marcone** [comment]
BTW, @basalblas and @DaveRuijter, how are you finding wifi connectivity on the RPiZero2W? On mine, wifi seems much worse than on the old RPi0W. Really high packet loss, to the point where it constantly triggers the "connection dead" checker. Good for testing I suppose, but not for actual use.

**Comment by miles267** [comment]
Was hoping RasPi Zero V2 would somehow have 5 ghz WiFi. Instead with the RPi0 and 2.4 ghz you must wait until the teslausb disconnects, wakes, reconnects and resumes WiFi file transfer numerous times before it completes; the car isn’t kept awake.

**Comment by marcone** [comment]
I discovered that having AP enabled causes about 40% packet loss on wlan0. It works fine with AP disabled. My old Raspberry Pi Zero W has no such issue.

**Comment by basalblas** [comment]
> I discovered that having AP enabled causes about 40% packet loss on wlan0. It works fine with AP disabled. My old Raspberry Pi Zero W has no such issue.

I never use AP. I see no notable difference in Wi-Fi performance between the Zero W and Zero v2. The Zero v2 is much quicker in general though.
