### ISSUE TITLE
Raspberry Pi Zero 2 W wont install

### ISSUE THREAD

**Issue by TrudiKing** [marcone/teslausb#694]
This is my first time using GitHub so sorry if this is a silly question.

I have a Raspberry Pi Zero 2 W but can't get the TeslaUSB to install.  I started with the latest version teslausb-20210815 but that seemed to get stuck with something to do about CA certificates and could not connect to the network.  I found an article about using the previous version, so I have now tried to install teslausb-20201211.

This earlier version seemed to work better and I was able to ssh onto the Pi and it also worked in the Tesla but does not complete the installation.

It just keeps saying 

Sat 12 Dec 11:01:41 GMT 2020 : 'curl -L https://github.com/marcone/teslausb/archive/main-dev.tar.gz' failed, retrying
Sat 12 Dec 11:01:45 GMT 2020 : 'curl -L https://github.com/marcone/teslausb/archive/main-dev.tar.gz' failed, retrying
Sat 12 Dec 11:01:48 GMT 2020 : 'curl -L https://github.com/marcone/teslausb/archive/main-dev.tar.gz' failed, retrying
Sat 12 Dec 11:01:51 GMT 2020 : 'curl -L https://github.com/marcone/teslausb/archive/main-dev.tar.gz' failed, retrying

Is it the wrong version of the Pi or am I doing something wrong?

Thanks for your help.

**Comment by marcone** [comment]
https://github.com/marcone/teslausb/issues/692
