### ISSUE TITLE
tried to do update to latest version of teslausb

### ISSUE THREAD

**Issue by aaronac8** [marcone/teslausb#695]
I tired to update to latest version of teslausb and had this error:
![jpg](https://user-images.githubusercontent.com/74563201/140302841-46009c2c-7982-429c-a766-31c74b388830.jpg)

**Comment by aaronac8** [comment]
Also, my tesla cam files are NOT downloading to my PC now.  See diagnostics below.
[diagnostics.txt](https://github.com/marcone/teslausb/files/7474382/diagnostics.txt)

**Comment by marcone** [comment]
hmm, upgrading from an older version works for me. What happens if you run `setup-teslausb upgrade` again?

**Comment by aaronac8** [comment]
I tried it again, I see the following:
![putty_3UPVBhUwZM](https://user-images.githubusercontent.com/74563201/140430722-797418f1-45a4-472f-9fee-8e8b92ca2f14.jpg)

**Comment by marcone** [comment]
The clock isn't set correctly, which is where those "not valid yet" messages come from.
Try running `sntp -S time.google.com` before running the upgrade command.

**Comment by aaronac8** [comment]
I ran the clock set up command, and now get this error:
[KSErNl7.png (1263×961).pdf](https://github.com/marcone/teslausb/files/7482345/KSErNl7.png.1263x961.pdf)

**Comment by aaronac8** [comment]
Also, I cannot upload my saved sentry clips to my PC.  This function worked fine before and now stopped.  That is why I wanted to try an upgrade.  Thanks for your help

**Comment by marcone** [comment]
I think you might need to update linux first, e.g. do:
```
sudo -i
rm -rf /lib/modules/!($(uname -r)) # this frees up space by deleting unused kernel modules, not needed if you have sufficient space already
apt update
apt upgrade
```
Then reboot and try updating teslausb again.

**Comment by aaronac8** [comment]
I did the updating:
![AdMhsi2b6r](https://user-images.githubusercontent.com/74563201/140588163-7f254d87-5c33-47bb-830d-423615551399.jpg)

I am still unable to have the saved sentry clips sent to my PC
[teslausb-headless-setup.log](https://github.com/marcone/teslausb/files/7489286/teslausb-headless-setup.log)
.

**Comment by aaronac8** [comment]
here is my archiveloop.log
[archiveloop.log](https://github.com/marcone/teslausb/files/7489291/archiveloop.log)
:

**Comment by marcone** [comment]
It looks you either didn't run all the commands I listed earlier, or they failed, since you're still at kernel 4.19.93.

**Comment by marcone** [comment]
I was able to reproduce this. No idea what's going on yet. It works with the latest image, but not when upgrading from the 202000709 image.

**Comment by marcone** [comment]
ok, I see: with the latest image, /sbin is a symbolic link to /usr/sbin, whereas with the older image(s), /sbin and /usr/sbin were separate folders.

**Comment by marcone** [comment]
If you run `setup-teslausb upgrade` again, it should work. Thanks for reporting the issue.

**Comment by aaronac8** [comment]
Still getting STOP: Couldn't check image error
[teslausb-headless-setup.log](https://github.com/marcone/teslausb/files/7489976/teslausb-headless-setup.log)

**Comment by aaronac8** [comment]
updated linux, but still getting error
[teslausb-headless-setup (1).log](https://github.com/marcone/teslausb/files/7490005/teslausb-headless-setup.1.log)

**Comment by aaronac8** [comment]
I figured out the problem with my upgrade.....my PC IP address changed, so that is why I could not download my sentry clips.  Thank you.
