### ISSUE TITLE
How often should I update linux?

### ISSUE THREAD

**Issue by aaronac8** [marcone/teslausb#696]
How often should I use the following commands:
sudo -i
rm -rf /lib/modules/!($(uname -r)) # this frees up space by deleting unused kernel modules, not needed if you have sufficient space already
apt update
apt upgrade

Thanks again....I am very new to using linux

**Comment by marcone** [comment]
There's always a chance of something breaking when updating, so unless you have a specific reason to run these commands I wouldn't run them at all.
