### ISSUE TITLE
Running into issues copying files to my remote ssh machine

### ISSUE THREAD

**Issue by cortesimone** [marcone/teslausb#697]
Hi,
I'm running into issues copying files to my remote ssh machine. By logging into teslausb I can access my remote machine without user/pass, since I did use a private/public keypair.

It seems this file https://github.com/marcone/teslausb/blob/main-dev/run/rsync_archive/archive-clips.sh is never executed

how do I check?

I did setup teslausb on a Raspberry Pi 2 W, seems to be working, I can see files on the CAM partition

Thanks for your help,
Simone.

**Comment by marcone** [comment]
> how do I check?

See https://github.com/marcone/teslausb/issues/35
