### ISSUE TITLE
Connecting to WiFi OK, but Shares never appear

### ISSUE THREAD

**Issue by SemoTech** [marcone/teslausb#70]
Hello, 
I just installed latest build ([teslausb-20190505](https://github.com/marcone/teslausb/releases/tag/v1.2a)) onto a brand new Pi Zero W v1.1 using a 32Gb uSD card, and am testing while still connected to my Mac via either the [USB Stem](https://www.sparkfun.com/products/14526) or with a micro USB cable (no diference in behaviour). LED on the Pi is solid green either way.

Created and updated the "teslausb_setup_variables.conf" file on the /boot of the uSD card before inserting in the Pi, and also ran "./setup-teslausb" in /root/bin several times (with a fresh "teslausb_setup_variables.conf" in /boot) while troubleshooting.  At one point I think the kernel was updated.  

Anyway, while WiFi is connecting to my SSID just fine, and I can SSH into teslacam as "pi", the "Music" and TeslaCam" shares are not created/do not appear on the Mac.  

The "TESLAUSB_SETUP_FINISHED" file IS created in /boot but the "WIFI_ENABLED" file is NOT.

I have linked the "diagnostics.txt" file contents [HERE](https://pastebin.com/pe2bsTeQ).   

Any help would be greatly appreciated.  Thank you in advance.

**Comment by marcone** [comment]
Looks you initially tried to setup Gotify, which failed, then tried again without it?
You also have no archiveloop log, though the setup log shows /root/bin/archiveloop was installed. Can you check whether /root/bin/archiveloop actually exists, and whether the archiveloop process is running?

**Comment by SemoTech** [comment]
Thank you for the prompt reply @marcone 
Actually I just uncommented the line in the config file that said "# export gotify_enabled=false" since logically it seemed like removing the "#" would actually set Gotify to false.  I did the same for "# export ifttt_enabled=false", however after seeing something in the logs about it erring out, I commented both lines back and re-ran the "./setup-teslausb" file.  

As for the /root/bin/archiveloop file, it exists but it is not running, and the log file /mutable/archiveloop.log is not present.  I am linking the directory contents and a list of running processes [HERE](https://pastebin.com/URTimDiH)

The "teslausb_setup_variables.conf" file I am using is [HERE](https://pastebin.com/yuFcAL8T)

Should I just re-flash the uSD with the latest release again, and start the Pi from scratch with the "teslausb_setup_variables.conf" linked above in /boot?

**Comment by marcone** [comment]
You can try running archiveloop manually and see if it prints any helpful error messages.
I.e, ssh into the pi and
```
sudo -i
/root/bin/archiveloop
```

**Comment by SemoTech** [comment]
OK, I got eager and restarted from scratch.  After internal processing and a self-reboot, I did get a "CAM" shared folder, but no "Music" folder.

In order for Tesla to write to the folder it needs to be called "TeslaCam" not "CAM".  How/where can I change that and also get the "Music" folder?

**Comment by marcone** [comment]
You shouldn't have to create a TeslaCam folder, setup already did that.
"CAM" is the label  of the emulated drive. If you doubleclick on it to open the drive you'll see the TeslaCam folder.
You're not getting the music drive because you've specified all space (100%) to be used for dashcam recordings. Set that to a lower amount in the .conf file, and you'll get the music drive.

**Comment by SemoTech** [comment]
Got it!  Appreciated @marcone looks like I am almost there...

Currently the  "teslausb_setup_variables.conf" file is no longer in the /boot drive, I assume for security reasons.  So basically I have to issue: "/root/bin/remountfs_rw" to re-enable writing, re-create the config file with nano, copy the customized contents, and just change the 100% for video to a lower percentage, halt the system, unplug/replug and it should create both shares, correct?

**Comment by marcone** [comment]
You don't have to rewrite the setup config to /boot. The setup scripts move it to /root, and will read it from there too. So just edit the version in /root, then run /root/bin/setup-teslausb, and reboot afterwards.

**Comment by SemoTech** [comment]
OK, edited root/teslausb_setup_variables.conf and just changed "export camsize=100%" to "export camsize=60%", saved the file, then ran /root/bin/setup-teslausb, and once done, rebooted.  

The CAM share came back on the Mac, but inside it is just the "TeslaCam" folder, there is no "Music" folder.

[HERE](https://pastebin.com/EDC7MW08) are the contents of "archiveloop.log"

1) Did I miss something to get the "Music" folder?
  
2) While I understand that the filesystem will check and self-repair, is that done in real-time or based on a cron/timer?  

3) Also, if the video partition gets full, will Tesla override the oldest files or does your code do cleanup?

**Comment by marcone** [comment]
There is no Music folder. The rpi emulates a separate drive that contains the music.  The car sees them as two separate USB drives. If you plug the rpi into a PC, you'll see the CAM drive and a MUSIC drive. The car does not require there to be a specific folder for music.

Filesystem check is done whenever the drive(s) are disconnected from the car and mounted on the rpi to do archiving.

The car erases non-saved recordings after one hour, and teslausb erases saved recordings after they've been backed up. Therefore, if you make sure the camera drive is large enough for 1 hour of recordings, plus however much footage you think you (or Sentry mode) will save before it has access to wifi again, you'll be OK. It needs about 5.5 GB per hour.

**Comment by SemoTech** [comment]
Thanks for all the expanantions @marcone seems I am almost there.  

The CAM/TeslaCam volume and share appear and are writable by the car!
The MUSIC volume does NOT appear/get mounted!

1) Contents of “/root/teslausb_setup_variables.conf” are [HERE](https://pastebin.com/8T7nTnrw) - Note that Music has been given 11GB of space.
1) List of files in /boot folder is [HERE](https://pastebin.com/rEayWpft)
2) Contents of "teslausb-headless-setup.log" is [HERE](https://pastebin.com/De3ja7Zs)
3) Contents of /root/bin folder are [HERE](https://pastebin.com/mF0V47gG)
4) Contents of /mutable folder and “archiveloop.log” are [HERE](https://pastebin.com/URX0XLbU) - Note “No music archive configured” entry towards the end of the log!

How do I get the MUSIC volume to mount?

**Comment by SemoTech** [comment]
OK, looks like problem is finally Solved!

Seems there is an issue with expecting things to change by modifying the "/root/teslausb_setup_variables.conf" file AFTER the initial setup, then running /root/bin/setup-teslausb and then rebooting.  At least for the MUSIC volume, it does not work.  

Only way to get everything working was to flash the uSD card again, copy the updated "teslausb_setup_variables.conf" config file to /boot so it can be processed the 1st time with all changes.  There is definitely a bug with processing changes afterwards.

@marcone my sincere thanks for all your help and maybe the logs and info I posted above will help you figure out the re-configuration bug.

**Comment by marcone** [comment]
Oh right, setup won't recreate the music file if there's already a camera file. If you delete that it will reconfigure both.
Note that "No music archive configured" means it wasn't configured to automatically sync music to the music drive, not that no music drive was configured.

BTW an easier way to get all that info and more is to run `/root/bin/setup-teslausb diagnose`
