### ISSUE TITLE
Add Support for the new "LightShow" Feature

### ISSUE THREAD

**Issue by idominiki** [marcone/teslausb#705]
Hello @marcone 

Tesla just announced Software Version 11 with the new "LightShow" Feature.

Drivers can create own lightshows which runs from a usb stick.

It would be great if the new folder is created via teslausb script.

Please look here for additional informations: https://github.com/teslamotors/light-show

"USB flash drive requirements

Must contain a base-level folder called "LightShow" (without quotation marks and case sensitive).
The LightShow folder must contain 2 files:
"lightshow.fseq"
"lightshow.mp3" or "lightshow.wav" (wav is recommended)
Must be formatted as exFAT, FAT 32 (for Windows), MS-DOS FAT (for Mac), ext3, or ext4. NTFS is currently not supported.
Must not contain a base-level TeslaCam folder.
Must not contain any map update or firmware update files."

Would be great, if this folder is created via teslausb script.

Merry Christmas and Thanks for your great work!
Dominik

**Comment by marcone** [comment]
See https://github.com/marcone/teslausb/issues/704#issuecomment-1001046483
