### ISSUE TITLE
Req: Able to access LightShow folder via WiFi

### ISSUE THREAD

**Issue by radhoo2k10** [marcone/teslausb#706]
Hi

The newest Tesla update enables a lightshow feature. You can even create your own lightshow. The files need for this has to be stored in a folder named LightShow. Instead of taking the usb out for each time you want to change the lightshow, is it possible to enable access to this folder via wifi?

https://github.com/teslamotors/light-show#usb-flash-drive-requirements

**Comment by miles267** [comment]
Looking forward to this. Or a way to create the necessary folder and do it over SSH is fine.

**Comment by marcone** [comment]
https://github.com/marcone/teslausb/issues/704#issuecomment-1001046483
