### ISSUE TITLE
CTTS eraser compatibility for V11 software?

### ISSUE THREAD

**Issue by 599316527** [marcone/teslausb#708]
Videos captured by v11 software(2021.44.25.2) can not be played on web interface while previous videos can still be played. 

I downloaded videos and inspect them by `ffprobe`:  

```
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fffe9e21cc0] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fffe9e21cc0] moov atom not found
2021-12-30_09-06-39-front.mp4: Invalid data found when processing input
```

<details>
<summary>ffprobe version</summary>
<pre>
ffprobe version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2007-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
  configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
</pre>
</details>

(Video exceeds github's 10M limit so I can't upload it)

I'm curious about whether there is any change inside video format so that ctts eraser can not hold it?

May be I'll check raw video file from usb directly later.

**Comment by marcone** [comment]
This was fixed a few days ago in https://github.com/marcone/teslausb/commit/07782001304601c074c88645c025422f403ef7d6
