### ISSUE TITLE
Add option to have lightshow volume

### ISSUE THREAD

**Issue by gilesmartin** [marcone/teslausb#710]
As of v11 owners can now add custom lightshows to a folder on a usb drive. Previous issues were closed saying that users could create a folder “lightshow” in the music volume, however, when this folder is present on the music volume the car no longer loads and music on the volume.

**Comment by marcone** [comment]
> when this folder is present on the music volume the car no longer loads and music on the volume

Interesting, and unfortunate. I still won't be implementing lightshow support because I don't think it is a compelling enough use case to justify the additional complexity. Hopefully Tesla will fix the issue with lightshow having to be on a completely separate drive.
