### ISSUE TITLE
Multiple LightShow via WebUI

### ISSUE THREAD

**Issue by MrPaulAR** [marcone/teslausb#712]
I see that you have already added LightShow feature via #704 but was wondering if you have considered adding more features around that.

- Ability to upload via WebUI
  - Uploading zips through WebUI would be a bonus
- Ability to switch the currently active LightShow via WebUI

I'm still looking through the code but if you aren't interested in the WebUI route what about rsync from a SMB share to the teslausb lightshows folder IF there is the ability to switch the active LightShow.

**Comment by marcone** [comment]
See https://github.com/marcone/teslausb/issues/707
