### ISSUE TITLE
Allocating space correctly?

### ISSUE THREAD

**Issue by lixee** [marcone/teslausb#713]
I'm a little confused about how I should allocate my space correctly.

I'm using a 256GB microSD card. If I set"export CAM_SIZE=30%" for example (which sould be more than enough) , should I then use the full remaining space (70%) for music? Or would I then loose the possibilty to preserve recordings older than one hour? In that case I would only use like 50%, so that some space is left (free space), which would be used for recent events?

**Comment by marcone** [comment]
I recommend using specific sizes instead of percentages, e.g. `export CAM_SIZE=30G`.
If you use the remaining space for music you will lose the ability to keep older recordings, so you should limit MUSIC_SIZE to the size you actually need.
