### ISSUE TITLE
Raspberry Pi Zero W Alternatives

### ISSUE THREAD

**Issue by bt** [marcone/teslausb#717]
Hi all,

I recently came across this repository and I'd like to implement it into my new Tesla. However, it's currently almost impossible to get a Raspberry Pi Zero W in my country due to stock shortages and so I'm trying to see if there would be any alternative SBC that we could use in its place.

As I understand, any RPi compatible SBC should be fine (eg. Banana Pi BPI-M2 ZERO) but before I go and make a purchase, is there any requirements that I should keep in mind that is required as part of the repository?

**Comment by marcone** [comment]
Any SBC that has wifi and supports USB OTG/Peripheral mode can theoretically provide the _functionality_ of TeslaUSB, however TeslaUSB  very much assumes that it is running and installing on a Raspberry Pi OS system, so some work would likely be required to support the other Linux flavors that these other SBCs usually run.
The Banana Pi BPI-M2 ZERO you mentioned apparently [supports Raspbian](https://wiki.banana-pi.org/Banana_Pi_BPI-M2_ZERO#Raspbian), but only the "Stretch" version  which TeslaUSB no longer supports.
You should also be mindful of power requirements and temperatures. These non-Raspberry SBCs generally seem to use more power and run hotter, which might not work well in car.
