### ISSUE TITLE
Raspberry pi zero 2 w

### ISSUE THREAD

**Issue by MartinSymphonyIT** [marcone/teslausb#720]
### Describe the problem

Having issues with NTP working, after installation date and is 16 Nov 2021. i have checked the other solutions and non of them perminately resolve the problem.

i was getting pool dns errors

I have however come across a solution i think needs looking into more, and thats if you edit
/etc/systemd/system/ntp.service

and change PrivateTmp=true to PrivateTmp=false

has something to do with the ntp service not liking to run in readonly mode.

after rebooting ntp sync'd straight away no problem. and no further dns pool errors in the log.

### Device

Raspberry Pi Zero 2 W

### Car Model

Model 3

### USB connection

Glove box

**Comment by marcone** [comment]
> /etc/systemd/system/ntp.service

This file does not exist on a standard TeslaUSB install using the prebuilt image (it is in /lib, not in /etc). What OS version did you try to install TeslaUSB on?

**Comment by MartinSymphonyIT** [comment]
yep, sorry my bad, /lib/ not etc

im using 2021-11-06-tesla.img. i have 8 to do, and all doing the same, once i updated that file i have perfect time sync and no errors in the log. only thing i have installed addtionally is rclone

**Comment by marcone** [comment]
What's the actual problem you were having? The time/date being wrong shouldn't normally be an issue, since it is set with `sntp` before archiving.
(and if your installs are anything like mine, those "error resolving pool" messages in the log only happen while away from wifi, and will continue to happen while away from wifi, even with the PrivateTmp change)

**Comment by MartinSymphonyIT** [comment]
i was getting the error resolving pool  messages whilst on wifi, and the time would not automatically set, it meant i could run the rclone install, change the password, install update etc. and wouldnt perform an initial archive becouse the time and date were so far out.

**Comment by marcone** [comment]
archiving doesn't depend on the ntp service though. It uses sntp, which queries a given ntp server directly (teslausb uses time.google.com)

**Comment by MartinSymphonyIT** [comment]
strange then, i was having problems perhaps more probably at the setup stage but changing that file just made life easier, and i don't like seeing errors in log files.

thought it might be of some use to others.

**Comment by marcone** [comment]
OK. A diagnostics file might have provided more info.
For what it's worth, the "official" way to make changes like this is not to manually edit the service definition file, but to use an override. You can use `systemctl edit ntp` to create one.
