### ISSUE TITLE
Building image with bullseye

### ISSUE THREAD

**Issue by cleanev** [marcone/teslausb#721]
### Describe the problem

I have followed [https://github.com/marcone/teslausb/tree/main-dev/pi-gen-sources](url) however every time build.sh is run root partition remains 1.6GB even though changes to qcow2_handling is exercised.

Is there something I am missing here. Any assistance appreciated.

Following lines Italicized have been added each time a new build is completed
…..
e2fsck -y -f $MAP_ROOT_DEV || true

_let DATA_SIZE=2*1024*1024*1024/$BLOCK_SIZE_
DATA_SIZE=`resize2fs -P $MAP_ROOT_DEV | awk -F': ' ' { print $2 } '
BLOCK_SIZE=$(dumpe2fs -h $MAP_ROOT_DEV | grep 'Block size' | awk -F': ' ' { print $2 }')
BLOCK_SIZE=${BLOCK_SIZE// /}

_let DATA_SIZE=$DATA_SIZE+$ROOT_MARGIN/$BLOCK_SIZE
let DATA_SIZE=2* 1024* 1024*1024/$BLOCK_SIZE_
_DATA_SIZE=2147483648_
_let DATA_SIZE=2147483648_
resize2fs -p $MAP_ROOT_DEV $DATA_SIZE
……

### Device

Raspberry Pi 4

### Car Model

Model 3

### USB connection

Center console

**Comment by marcone** [comment]
A few months ago pi-gen [went back to making qcow2 an experimental feature](https://github.com/RPi-Distro/pi-gen/commit/68fee340f95eb630a706e2dbf75615c6be4e980b) instead of the default. You can either re-enable it, or modify the export-image/prerun.sh script instead.
