### ISSUE TITLE
script cannot complete - stack at backingfiles

### ISSUE THREAD

**Issue by jjlucas76** [marcone/teslausb#732]
### Describe the problem

RPi4 with USB (512GB SSD) drive and 16GB micro SD.
script cannot complete and get stuck at  create-backingfiles.

I tried to specify both percentage and/or fixed sizes, but same result.

### Device

Raspberry Pi 4

### Car Model

Model Y

### USB connection

Glove box

### Logs

Sat  6 Nov 17:45:24 GMT 2021 : Detecting whether to update wpa_supplicant.conf
Sat  6 Nov 17:45:24 GMT 2021 : Wifi variables specified, and no /boot/WIFI_ENABLED. Building wpa_supplicant.conf.
Sat  6 Nov 17:45:24 GMT 2021 : Rebooting...
Sat  6 Nov 17:45:42 GMT 2021 : Detecting whether to update wpa_supplicant.conf
Sat  6 Nov 17:45:42 GMT 2021 : Grabbing main setup file.
Sat  6 Nov 17:45:42 GMT 2021 : get_script failed, retrying
Mon 13 Jun 07:55:57 BST 2022 : Starting setup.
Mon 13 Jun 07:55:58 BST 2022 : Configuring the hostname...
Mon 13 Jun 07:55:58 BST 2022 : Configured hostname: teslausb
Mon 13 Jun 07:55:58 BST 2022 : curl -L https://github.com/marcone/teslausb/archive/main-dev.tar.gz
Mon 13 Jun 07:56:00 BST 2022 : Downloaded /tmp/717/setup-teslausb ...
Mon 13 Jun 07:56:00 BST 2022 : /root/bin/setup-teslausb is up to date
Mon 13 Jun 07:56:00 BST 2022 : Downloaded /tmp/717/rc.local ...
Mon 13 Jun 07:56:00 BST 2022 : rc.local is up to date
Mon 13 Jun 07:56:00 BST 2022 : Updating package index files...
Mon 13 Jun 07:56:28 BST 2022 : Verifying that the requested configuration is valid...
Mon 13 Jun 07:56:28 BST 2022 : Downloaded /tmp/verify-configuration.sh ...
Mon 13 Jun 07:56:28 BST 2022 : USB_DRIVE is set to /dev/sda. This will be used for /mutable and backingfiles.
Mon 13 Jun 07:56:28 BST 2022 : Verifying that there is sufficient space available on the USB drive ...
Mon 13 Jun 07:56:28 BST 2022 : There is sufficient space available.
Mon 13 Jun 07:56:32 BST 2022 : Downloading additional setup scripts.
Mon 13 Jun 07:56:32 BST 2022 : Downloaded /root/bin/remountfs_rw ...
Mon 13 Jun 07:56:32 BST 2022 : Downloaded /root/bin/make_snapshot.sh ...
Mon 13 Jun 07:56:32 BST 2022 : Downloaded /root/bin/release_snapshot.sh ...
Mon 13 Jun 07:56:32 BST 2022 : Downloaded /root/bin/force_sync.sh ...
Mon 13 Jun 07:56:32 BST 2022 : Downloaded /root/bin/mountoptsforimage ...
Mon 13 Jun 07:56:32 BST 2022 : Downloaded /root/bin/mountimage ...
Mon 13 Jun 07:56:32 BST 2022 : Downloaded /root/bin/enable_gadget.sh ...
Mon 13 Jun 07:56:32 BST 2022 : Downloaded /root/bin/disable_gadget.sh ...
Mon 13 Jun 07:56:32 BST 2022 : Downloaded /tmp/create-backingfiles-partition.sh ...
Mon 13 Jun 07:56:32 BST 2022 : Downloaded /tmp/create-backingfiles.sh ...
Mon 13 Jun 07:56:32 BST 2022 : Downloaded /tmp/make-root-fs-readonly.sh ...
Mon 13 Jun 07:56:32 BST 2022 : Downloaded /tmp/configure.sh ...
Mon 13 Jun 07:56:32 BST 2022 : /boot/cmdline.txt is up to date
Mon 13 Jun 07:56:37 BST 2022 : create-backingfiles-partition: USB_DRIVE is set to /dev/sda
Mon 13 Jun 07:56:37 BST 2022 : create-backingfiles-partition: Looks like backingfiles and mutable partitions already exist. Skipping partition creation.
Mon 13 Jun 07:56:38 BST 2022 : create-backingfiles-partition: Done.
Mon 13 Jun 07:56:38 BST 2022 : Mounting the partition for the backing files...
Mon 13 Jun 07:56:38 BST 2022 : Mounted the partition for the backing files.
Mon 13 Jun 07:56:38 BST 2022 : Mounting the mutable partition...
Mon 13 Jun 07:56:38 BST 2022 : Mounted the mutable partition.
Mon 13 Jun 07:56:38 BST 2022 : Creating backing disk files.
Mon 13 Jun 07:56:38 BST 2022 : create-backingfiles: starting
Mon 13 Jun 07:56:38 BST 2022 : create-backingfiles: cam: 32G, music: 450G, mountpoint: /backingfiles, exfat: false

**Comment by jjlucas76** [comment]
`### Additional information

`#####################################################################
`# SAMPLE CONFIGURATION FILE FOR TESLAUSB Pi Setup
`#
`# Example config file for teslausb_setup. Lines with "#" are comments/ignored.
`# Remove the "#" before "export" to activate a line. Be sure to rename this file
`# to "teslausb_setup_variables.conf" and place it in the "boot" folder of your
`# SD card.
`# Please check the latest version of this file at:
`# https://github.com/marcone/teslausb/blob/main-dev/pi-gen-sources/00-teslausb-tweaks/files/teslausb_setup_variables.conf.sample
`#
`######################################################################

`# Variables for CIFS (Windows/Mac file sharing) archiving
export ARCHIVE_SYSTEM=cifs
export ARCHIVE_SERVER="xx"
export SHARE_NAME="TeslaCam"
export SHARE_USER="xx"
export SHARE_PASSWORD="xx"
`# the cifs options below usually don't need to be specified
`# export SHARE_DOMAIN=domain
`# export CIFS_VERSION="3.0"
`# export CIFS_SEC="ntlm"

`# Variables for rsync archiving
`#export ARCHIVE_SYSTEM=rsync
`#export RSYNC_USER=username
`#export RSYNC_SERVER=hostname_or_ip
`#export RSYNC_PATH=path_on_server

`# Variables for rclone archiving
`#export ARCHIVE_SYSTEM=rclone
`#export RCLONE_DRIVE="remotename"
`#export RCLONE_PATH="remotepathname"
`# The following is optional
`#export RCLONE_FLAGS=()

`# The following option is only for the Pi4. If you wish to boot the Pi4 from
`# sd card, but store recordings on a USB drive or SSD, uncomment the following
`# line. If you don't plan on using an sd card at all (i.e. you are both booting
`# from and storing recordings on the USB drive), or are ONLY using an sd card
`# (i.e. boot from and store recordings on sd card), do NOT uncommment this line.
export USB_DRIVE=/dev/sda

`# uncomment this to archive RecentClips in addition to SavedClips and SentryClips
export ARCHIVE_RECENTCLIPS=true

`# SavedClips, SentryClips and track mode clips are archived by default, but
`# you can turn that off by uncommenting the settings below
`#export ARCHIVE_SAVEDCLIPS=false
`#export ARCHIVE_SENTRYCLIPS=false
`#export ARCHIVE_TRACKMODECLIPS=false

`# Notes on sd card and image sizes:
`#   * A 128 GB or larger sd card (or USB drive, when using Pi4) is recommended. The
`#     minimum supported size is 64 GB.
`#   * When specifying sizes for the recordings and music drives, you can use specific
`#     sizes (e.g. 24G) or use sizes relative to the available space (e.g. 10%)
`#   * The setup script will reserve a fixed 6 GB of space regardless of sd card size.
`#   * CAM_SIZE should generally be somewhat small, around 16G to 32G, unless you plan
`#     on accumulating a lot of footage between archive operations, in which case you
`#     should increase the value (an hour of recordings, or 6 Sentry events, is about
`#     7-9 GB of data).
`#   * As of Tesla software version 2020.48.10, the car will warn when the recording drive
`#     is smaller than 32 GB, but smaller values will still work. Tesla appears to use
`#     power-of-ten based sizes, presumably because most storage manufacturers do too.
`#     Because teslausb uses power-of-two sizes, you can specify "30G" for the size and
`#     not get the warning.
`#   * MUSIC_SIZE should be large enough to hold your music library, obviously.
`#   * If no music size is specified, no music drive will be created.
export CAM_SIZE=32G
export MUSIC_SIZE=450G

`# Use ExFAT filesystem instead of FAT32. 
`# 
`# ExFAT is the filesystem used by Tesla when the drive is formatted
`# in the car. While TeslaUSB supports ExFAT, it is recommended to
`# use the FAT32 format because the Linux ExFAT implementation
`# does not support TRIM.
`# export USE_EXFAT=true

`# If you want to automatically copy music from a CIFS share every time
`# the Pi connects to wifi, set the following variable. The share is
`# assumed to exist on the same server as the archive share. It can
`# be the same share as the share used for backing up recordings, but
`# the folder needs to be different.
export MUSIC_SHARE_NAME="xx/TeslaMusic"

`# Wifi setup information. Note that Raspberry Pi Zero W only supports 2.4 GHz wifi.
`# If you are you are trying to connect to a network with a _hidden_ SSID,
`#   edit /boot/wpa_supplicant.conf.sample and un-comment the indicated line.
export SSID="xx"
export WIFIPASS="xx"

`# uncomment to enable a Samba/CIFS server that makes the recordings
`# available as a network share
export SAMBA_ENABLED=true
`# uncomment to enable guest access to the Samba server
export SAMBA_GUEST=true

`# uncomment to enable teslausb to act as a wifi access point with the given
`# SSID, so you can access it while on the road.
`#export AP_SSID='TESLAUSB WIFI'
`# Change this! The setup script will not accept the default 'password'
`# Also note that the wifi password must be at least 8 characters.
`#export AP_PASS='password'
`# IP address is optional. The AP will give its clients IP addresses in the
`# x.x.x.100-150 range so make sure you don't put the AP's IP address in
`# that range.
`#export AP_IP='192.168.66.1'

`# uncomment if you want to set the time zone to something other than the default 'BST'
`# Can be an actual time zone, or "auto" to attempt automatic timezone detection
`# export TIME_ZONE="America/Los_Angeles"

`# By default there is a 20 second delay between connecting to wifi and
`# starting the archiving of recorded clips. Uncomment this to change
`# the duration of that delay
`# export ARCHIVE_DELAY=20

`# Uncomment if you want to override the default hostname of "teslausb"
`# export TESLAUSB_HOSTNAME=teslausb-Model3

`# Uncomment if setting up Pushover push notifications
`# export PUSHOVER_ENABLED=true
`# export PUSHOVER_USER_KEY=user_key
`# export PUSHOVER_APP_KEY=app_key

`# Uncomment if setting up Gotify push notifications
`# export GOTIFY_ENABLED=true
`# export GOTIFY_DOMAIN=https://gotify.domain.com
`# export GOTIFY_APP_TOKEN=put_your_token_here
`# export GOTIFY_PRIORITY=5

`# Uncomment if setting up IFTTT push notifications
`# export IFTTT_ENABLED=true
`# export IFTTT_EVENT_NAME=put_your_event_name_here
`# export IFTTT_KEY=put_your_key_here

`# Uncomment if setting up Discord push notifications
`# export DISCORD_ENABLED=true
`# export DISCORD_WEBHOOK_URL=put_your_webhook_url_here

`# Uncomment if setting up AWS SNS notifications
`# export SNS_ENABLED=true
`# export AWS_REGION=us-east-1
`# export AWS_ACCESS_KEY_ID=put_your_accesskeyid_here
`# export AWS_SECRET_ACCESS_KEY=put_your_secretkey_here
`# export AWS_SNS_TOPIC_ARN=put_your_sns_topicarn_here

`# Uncomment if setting up Telegram notifications
`# export TELEGRAM_ENABLED=true
`# export TELEGRAM_CHAT_ID=123456789
`# export TELEGRAM_BOT_TOKEN=bot123456789:abcdefghijklmnopqrstuvqxyz987654321
`# export TELEGRAM_SILENT_NOTIFY=false

`# Uncomment if setting up Webhook notifications
`# export WEBHOOK_ENABLED=true
`# export WEBHOOK_URL=http://domain/path

`# Uncomment if setting up Slack notifications
`# export SLACK_ENABLED=true
`# export SLACK_WEBHOOK_URL=http://domain/path

`# Uncomment if setting up Matrix notifications
`# export MATRIX_ENABLED=true
`# export MATRIX_SERVER_URL=https://matrix.org
`# export MATRIX_USERNAME=put_your_matrix_username_here
`# export MATRIX_PASSWORD='put_your_matrix_password_here'
`# export MATRIX_ROOM='put_the_matrix_target_room_id_here'

`# tesla_dashcam / Trigger file support.
`# Uncomment any TRIGGER_FILE_xxxxx below to create trigger file(s) in the
`# archive directory for the listed clip type after all clips have been
`# transferred for that type.
`# e.g: export TRIGGER_FILE_SAVED=ARCHIVE_UPLOADED would create a file in
`# $ARCHIVE_BASE/SavedClips/ARCHIVE_UPLOADED.
`# Uncomment TRIGGER_FILE_ANY to create a trigger file in $ARCHIVE_BASE. This will
`# make tesla_dashcam process both SavedClips and SentryClips when either changes.
`# This is useful if using https://github.com/ehendrix23/tesla_dashcam to further
`# process clips.
`# e.g: tesla_dashcom --monitor --monitor_trigger $ARCHIVE_BASE/SavedClips/ARCHIVE_UPLOADED $ARCHIVE_BASE/SavedClips
`#
`# You may modify the value to your desired trigger filename. Remember to alter your tesla_dashcam trigger filename to match.
`#.
`# export TRIGGER_FILE_SAVED=ARCHIVE_UPLOADED
`# export TRIGGER_FILE_SENTRY=ARCHIVE_UPLOADED
`# export TRIGGER_FILE_RECENT=ARCHIVE_UPLOADED
`# export TRIGGER_FILE_ANY=ARCHIVE_UPLOADED

`# NOTE: the Tesla API functionality described below is currently broken, as
`# teslausb has not yet been updated to use Tesla's new authentication service.
`#
`# TeslaUSB can optionally use the Tesla API to keep your car awake, so it can
`# power the Pi long enough for the archiving process to complete. To enable
`# that, provide your Tesla account email and password below.
`# TeslaUSB will only send your credentials to the Tesla API itself.
`#
`# NOTE:  if you do this, it's highly recommended that you set up 'PIN to Drive'
`#   as if the Pi or the car is stolen, the thief has access to your Tesla account
`#   and could change the password, add their own devices as a key, steal the car,
`#   etc.  If either is stolen, CHANGE YOUR TESLA PASSWORD IMMEDIATELY.
`#
`# ALSO NOTE: having sentry mode enabled in your Tesla will keep your car awake.
`#   But, make sure you have not excluded your home in the sentry mode settings.
`#
`# export TESLA_EMAIL=joeshmo@gmail.com
`# export TESLA_PASSWORD=teslapass
`#
`# If you have more than one Tesla vehicle on the account, you must also provide
`# the name or VIN for the vehicle for which this TeslaUSB install will be used,
`# so that TeslaUSB can keep the correct vehicle awake.
`# If you only have one car on the account, you do not need to specify this.
`# export TESLA_NAME="Elon's CyberTruck"
`# export TESLA_VIN=5YJ3E1EA4JF000001
`#
`# By default, TeslaUSB uses a combination of APIs to keep the car awake,
`# similar to how to the Tesla app can wake up the car.
`# If you find your car isn't staying awake, you can try setting the
`# following to "sentry" to keep the car awake by temporarily turning
`# on Sentry mode while archiving.
`# export TESLA_WAKE_MODE=stream

`# Uncomment if you want to increase the size of the root
`# filesystem so there's extra space for installing additional
`# software. This only works if the backing store partition hasn't
`# been created yet, i.e. during early setup, and requires an extra
`# reboot. Sizes can be specified as for example "500M" or "2G"
`# export INCREASE_ROOT_SIZE=500M

`# Uncomment if you want to use different vm/cpu parameters.
`# Leave commented to use teslausb's defaults, or set to 'default'
`# to use the system defaults.
`# See https://www.kernel.org/doc/Documentation/sysctl/vm.txt
`# and https://www.kernel.org/doc/Documentation/cpu-freq/governors.txt
`# for details.
`#export DIRTY_BACKGROUND_BYTES=65536
`#export DIRTY_RATIO=80
`#export CPU_GOVERNOR=conservative

`# Uncomment and change if you want setup scripts to be pulled
`# from a different repo than github.com/marcone/teslausb
`# export REPO=marcone

`# Uncomment and change if you want a different branch than main-dev
`# export BRANCH=main-dev

**Comment by marcone** [comment]
Fixed by https://github.com/marcone/teslausb/commit/9c213fbfc77742acbc0808903164b1d30fcc18f5
