### ISSUE TITLE
configure: Skipping tesla_api.py install because no credentials were provided

### ISSUE THREAD

**Issue by chilman408** [marcone/teslausb#737]
### Describe the problem

Getting this error in the Setup logs when I provided my Tesla credentials...

configure: Skipping tesla_api.py install because no credentials were provided

### Device

Raspberry Pi Zero 2 W

### Car Model

Model 3

### USB connection

Center console

**Comment by marcone** [comment]
I assume you specified your email and password? That doesn't work anymore. You need to specify a refresh token, as described in [the latest version of the config file](https://github.com/marcone/teslausb/blob/main-dev/pi-gen-sources/00-teslausb-tweaks/files/teslausb_setup_variables.conf.sample#L192)

**Comment by chilman408** [comment]
Yes, used email and pwd.  But I reas that the token expires in 8hrs now, will Teslausb be able to auto update the token?

**Comment by marcone** [comment]
it should automatically refresh/update when needed
