### ISSUE TITLE
USB not mounting - Mounts everyone on FSD beta

### ISSUE THREAD

**Issue by Poncherelly** [marcone/teslausb#738]
This thread is more of an FYI about an issue. Many including myself noticed the TESLAUSB not remount after the car goes to sleep. 

I can say that this issue doesn't affect me now on FSD beta. I wanted to share this before .69 is release to a wider audience case the problem comes back. 

If there is any value in my running specific tests or providing specific information to see what's been introduced to non beta users that causes this, just ask.

**Comment by marcone** [comment]
Sorry, didn't notice this report until now.
I'm not seeing this problem on a non-FSD Model Y with recent firmware (2022.24.8)

**Comment by marcone** [comment]
Nothing actionable here.
