### ISSUE TITLE
USB drive not found

### ISSUE THREAD

**Issue by Str1atum** [marcone/teslausb#747]
### Describe the problem

Latest teslausb on Pi Zero 2 W connected to 2022 Model Y in the glovebox

256 GB Sandisk with Camsize 128G

Setup worked fine, wifi connection established and Samba share available in my home network. When connected to the Tesla it boots correctly and flashes once per second but the car doesn’t find the USB drive at all. 

Any ideas?

### Device

Raspberry Pi Zero 2 W

### Car Model

Model Y

### USB connection

Glove box

**Comment by marcone** [comment]
Have you looked at https://github.com/marcone/teslausb/wiki/Troubleshooting ?
(specifically the parts about trying different cables, and connecting to a PC)

**Comment by marcone** [comment]
Closing due to no response
