### ISSUE TITLE
Error when running rc.local - E: Unable to locate package python-requests

### ISSUE THREAD

**Issue by imthisguymike** [marcone/teslausb#753]
### Describe the problem

Error when running rc.local - E: Unable to locate package python-requests

root@GiR-USB:/etc# ./rc.local 
My IP address is 10.10.0.138 
Detecting whether to update wpa_supplicant.conf
Starting setup.
increasing root filesystem size to match partition size
resize2fs 1.45.5 (07-Jan-2020)
The filesystem is already 1310720 (4k) blocks long.  Nothing to do!

/root/bin/setup-teslausb is up to date
rc.local is up to date
Updating package index files...
Hit:1 http://mirrors.jevincanders.net/armbian/apt focal InRelease
Hit:2 http://ports.ubuntu.com focal InRelease       
Hit:3 http://ports.ubuntu.com focal-security InRelease
Hit:4 http://ports.ubuntu.com focal-updates InRelease
Hit:5 http://ports.ubuntu.com focal-backports InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Unable to locate package python-requests

### Device

Radxa Zero

### OS Image

Armbian

### Car Model

Model 3

### USB connection

Center console

### Logs

root@GiR-USB:~# /root/bin/setup-teslausb diagnose > /tmp/diagnostics.txt
resize2fs 1.45.5 (07-Jan-2020)
The filesystem is already 1310720 (4k) blocks long.  Nothing to do!

### Additional information

root@10.10.0.138's password: 
 ____           _             _____              
|  _ \ __ _  __| |_  ____ _  |__  /___ _ __ ___  
| |_) / _` |/ _` \ \/ / _` |   / // _ \ '__/ _ \ 
|  _ < (_| | (_| |>  < (_| |  / /|  __/ | | (_) |
|_| \_\__,_|\__,_/_/\_\__,_| /____\___|_|  \___/ 
                                                 
Welcome to Armbian 22.11.4 Focal with Linux 6.0.13-meson64

No end-user support: unsupported (focal) userspace!

System load:   4%           	Up time:       18 min	
Memory usage:  18% of 945M   	IP:	       10.10.0.138
CPU temp:      36°C           	Usage of /:    29% of 4.9G   	

[ General system configuration (beta): armbian-config ]

Last login: Fri Feb 24 14:34:19 2023 from 10.10.0.129
+------------------------------------------------------------------------+
| To continue teslausb setup, edit the file                              |
| /boot/teslausb_setup_variables.conf with your favorite                 |
| editor, e.g. 'nano /boot/teslausb_setup_variables.conf' and fill in    |
| the required variables. Instructions are in the file, and at           |
| https://github.com/marcone/teslausb/blob/main-dev/doc/OneStepSetup.md  |
| (though ignore the Raspberry Pi specific bits about flashing and       |
| mounting the sd card on a PC)                                          |
|                                                                        |
| When done, save changes and run /etc/rc.local                          |
+------------------------------------------------------------------------+
root@GiR-USB:~# cd /etc
root@GiR-USB:/etc# ./rc.local 
My IP address is 10.10.0.138 
Detecting whether to update wpa_supplicant.conf
Starting setup.
increasing root filesystem size to match partition size
resize2fs 1.45.5 (07-Jan-2020)
The filesystem is already 1310720 (4k) blocks long.  Nothing to do!

/root/bin/setup-teslausb is up to date
rc.local is up to date
Updating package index files...
Hit:1 http://mirrors.jevincanders.net/armbian/apt focal InRelease
Hit:2 http://ports.ubuntu.com focal InRelease       
Hit:3 http://ports.ubuntu.com focal-security InRelease
Hit:4 http://ports.ubuntu.com focal-updates InRelease
Hit:5 http://ports.ubuntu.com focal-backports InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Unable to locate package python-requests
root@GiR-USB:/etc# sudo -i
+------------------------------------------------------------------------+
| To continue teslausb setup, edit the file                              |
| /boot/teslausb_setup_variables.conf with your favorite                 |
| editor, e.g. 'nano /boot/teslausb_setup_variables.conf' and fill in    |
| the required variables. Instructions are in the file, and at           |
| https://github.com/marcone/teslausb/blob/main-dev/doc/OneStepSetup.md  |
| (though ignore the Raspberry Pi specific bits about flashing and       |
| mounting the sd card on a PC)                                          |
|                                                                        |
| When done, save changes and run /etc/rc.local                          |
+------------------------------------------------------------------------+
root@GiR-USB:~# /root/bin/setup-teslausb selfupdate
increasing root filesystem size to match partition size
resize2fs 1.45.5 (07-Jan-2020)
The filesystem is already 1310720 (4k) blocks long.  Nothing to do!

The 'selfupdate' command is no longer supported. Run '/root/bin/setup-teslausb upgrade' instead.
root@GiR-USB:~# /root/bin/setup-teslausb diagnose > /tmp/diagnostics.txt
resize2fs 1.45.5 (07-Jan-2020)
The filesystem is already 1310720 (4k) blocks long.  Nothing to do!

root@GiR-USB:~#

**Comment by marcone** [comment]
https://github.com/marcone/teslausb/commit/a5690f3ee8e21b7d0f10643221a86a9b1ca7f19f should fix this.

Since you're using Armbian though, you should probably just let Armbian set the timezone during initial setup, and not have TeslaUSB do it (i.e. comment out the `export TIME_ZONE ...` line in the TeslaUSB config file.
