### ISSUE TITLE
Setting up a new Raspberry Pi 4 for a new car (a 2nd car) without success

### ISSUE THREAD

**Issue by miles267** [marcone/teslausb#760]
### Describe the problem

Hi - we've added a second vehicle to household on same wifi network.  First car is successfully running on a Raspberry Pi 4 with latest image without issue (including sync of both cam and music)  Am now assembling a second Raspberry 4 device (identical hardware) on same network.  I've copied the original config file to the new device only modifying the following variables but it isn't synching music_share contents from the same smb location.

### Device

Raspberry Pi 4

### OS Image

Prebuilt TeslaUSB image

### Car Model

Model Y

### USB connection

Glove box

### Logs

[diagnostics.txt](https://github.com/marcone/teslausb/files/11256417/diagnostics.txt)

**Comment by miles267** [comment]
The new raspberry pi mounts as expected in the car without issue, however it isn't syncing any data to or from the smb file share whereas the other, nearly identical device does without issue.

**Comment by miles267** [comment]
I'm able to get camera footage to sync without issue, however music is not syncing despite setting the following on a 256 GB SD card:

export musicsize=64G
export musicsharename=teslamusic (this is the name of my share)

It just seems to ignore the music part of the sync.

Mon 17 Apr 20:04:56 CDT 2023: Copying music...
Mon 17 Apr 20:04:56 CDT 2023: Starting music sync...
Mon 17 Apr 20:04:56 CDT 2023: Ensuring music backing file is mounted...
Mon 17 Apr 20:04:56 CDT 2023: Disconnecting usb from host...
Mon 17 Apr 20:04:56 CDT 2023: Disconnected usb from host.
Mon 17 Apr 20:04:56 CDT 2023: Mounting /mnt/music...
Mon 17 Apr 20:04:56 CDT 2023: Mounted /mnt/music.
Mon 17 Apr 20:04:56 CDT 2023: Ensured music drive is mounted.
Mon 17 Apr 20:04:56 CDT 2023: Trimming free space in /mnt/music, which has 1 extents
Mon 17 Apr 20:04:56 CDT 2023: Trim complete, image now has 1 extents
Mon 17 Apr 20:04:56 CDT 2023: Unmounting /mnt/music...
Mon 17 Apr 20:04:56 CDT 2023: Unmounted /mnt/music.
Mon 17 Apr 20:04:56 CDT 2023: Finished copying music.
Mon 17 Apr 20:04:56 CDT 2023: unmounting /mnt/archive
Mon 17 Apr 20:04:56 CDT 2023: Stopping wake background task.
Mon 17 Apr 20:04:56 CDT 2023: Connecting usb to host...
Mon 17 Apr 20:04:56 CDT 2023: unmounting /mnt/musicarchive

**Comment by miles267** [comment]
My install doesn't seem to be grabbing the bin/copy-music.sh upon setup.  That must be the issue.  It is able to mount to music archive fine otherwise. And it's creating the music chare on setup at 64G (large card 256 GB).  During setup, it is creating the music volume but not downloading the copy-music.sh script for some reason.  Any reason why it would do this? or is it possible to force it to download it manually?

Upon manually copying copy-music.sh script to /root/bin and doing a chmod u+x running the script then returns. 

/root/bin/copy-music.sh: line 8: syntax error near unexpected token newline'
/root/bin/copy-music.sh: line 8: <!DOCTYPE html>'

**Comment by marcone** [comment]
This is fixed now
