### ISSUE TITLE
stack smashing detected

### ISSUE THREAD

**Issue by harmstorf** [marcone/teslausb#762]
### Describe the problem

I am running Armbian 23.02.2 Jammy with Linux 5.15.93-rockchip64 on a Rock 4C+ and followed the instructions on https://github.com/marcone/teslausb/wiki/Installation

The installation aborts:

`root@rockpi-4cplus:~# curl https://raw.githubusercontent.com/marcone/teslausb/main-dev/setup/generic/install.sh | bash
*** stack smashing detected ***: terminated`

### Device

Rock Pi 4C plus

### OS Image

Armbian

### Car Model

Model 3

### USB connection

Glove box

**Comment by marcone** [comment]
Can you link the specific Armbian image you used?

**Comment by harmstorf** [comment]
I used the 4C+ Image Armbian_23.02.2_Rockpi-4cplus_jammy_current_5.15.93_minimal.img.xz provided here: https://www.armbian.com/rockpi4/

I have tried other images but all of them had I/O issues with eMMC.

**Comment by marcone** [comment]
I used that same image but did not encounter the "stack smashing detected" problem. Is this reproducible for you?

**Comment by harmstorf** [comment]
Thanks for the valid question which made me start from scratch again. This time, no issues with stack smashing.
