### ISSUE TITLE
E: Unable to locate package python-is-python3

### ISSUE THREAD

**Issue by Str1atum** [marcone/teslausb#764]
### Describe the problem

during setup I get the following error:

E: Unable to locate package python-is-python3

whole log:
Updating package index files...
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Get:2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
Fetched 15.0 kB in 2s (9,629 B/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Unable to locate package python-is-python3

### Device

Raspberry Pi Zero W

### OS Image

Prebuilt TeslaUSB image

### Car Model

Model Y

### USB connection

Center console

**Comment by marcone** [comment]
Thanks for the report. This should be fixed now.
