### ISSUE TITLE
STOP: this device does not have a UDC driver

### ISSUE THREAD

**Issue by harmstorf** [marcone/teslausb#769]
### Describe the problem

I cannot install teslausb on my ROCK Pi 4C+, because of a missing UDC driver.

Would someone please give me hint where to obtain this driver?

### Device

Rock Pi 4C plus

### OS Image

Armbian

### Car Model

Model 3

### USB connection

Glove box

### Logs

increasing root filesystem size to match partition size
resize2fs 1.46.5 (30-Dec-2021)
The filesystem is already 1310720 (4k) blocks long.  Nothing to do!

WARNING: main-dev contains a different version of bin/setup-teslausb. It is recommended to run 'bin/setup-teslausb upgrade' to get the latest version.
rc.local is up to date
Updating package index files...
Hit:1 http://ports.ubuntu.com jammy InRelease
Hit:2 http://ports.ubuntu.com jammy-security InRelease
Hit:3 http://ports.ubuntu.com jammy-updates InRelease
Hit:4 http://ports.ubuntu.com jammy-backports InRelease
Hit:5 http://mirror.albony.xyz/armbian jammy InRelease
Reading package lists... Done
Verifying that the requested configuration is valid...
Downloaded /tmp/verify-configuration.sh ...
/tmp/verify-configuration.sh: line 39: warning: command substitution: ignored null byte in input
STOP: this device (Radxa ROCK Pi 4C+) does not have a UDC driver

**Comment by marcone** [comment]
Which Armbian image did you install exactly? The UDC driver should normally be installed and active by default, but perhaps Armbian changed that.

**Comment by harmstorf** [comment]
Good question - has been a long time since initial try. Gave up for some weeks and picked it up again.  I remember having many issues with eMMC as well.

Is there an image you can recommend for your project?

**Comment by marcone** [comment]
> Good question - has been a long time since initial try. Gave up for some weeks and picked it up again. I remember having many issues with eMMC as well.

Sorry, I can't help with that since my 4C+ does not have eMMC.

> Is there an image you can recommend for your project?

Unfortunately it looks like all of the current Armbian 4C+ images are broken in some way. The official Armbian images have the UDC driver activated, but it does not appear to work. The community images don't work at all for me (they won't boot without ethernet connected, and then try to boot from the network).

Even the latest official Radxa images appear to be broken in various ways.

**Comment by Arthur-Philip-Dent** [comment]
Got similar message, when trying to install in a CM4 module (lite version...) with IO-board, that has a vl805 controller onboard. It supports host mode. On another IO-board from same brand the USB2.0-A sockets were host only. 
At least there the USB-C showed the "gadget devices" (the very same plug used for power, so all good.
Get in contact with the board-manufacturer. In my case this helped a lot.
Good luck!

**Comment by marcone** [comment]
Looks like the most recent Armbian image for Rock Pi 4C+ works again.
https://github.com/marcone/teslausb/wiki/Rock-Pi-4C--Installation
