### ISSUE TITLE
Multiple instances of archiveloop running

### ISSUE THREAD

**Issue by gkwok1** [marcone/teslausb#77]
Is there a reason why multiple instances of archiveloop running when I start up?

root@teslausb:~# ps -ef | grep archive
root       445     1  0 13:11 ?        00:00:00 /bin/bash -eu /root/bin/archiveloop
root       457   445  0 13:11 ?        00:00:00 flock -en -E 99 /root/bin/archiveloop /root/bin/archiveloop
root       460   457  0 13:11 ?        00:00:00 /bin/bash -eu /root/bin/archiveloop

[diagnostics.txt](https://github.com/marcone/teslausb/files/3288035/diagnostics.txt)

**Comment by marcone** [comment]
> Is there a reason why multiple instances of archiveloop running when I start up?

This is working as intended. Only one instance is actually running.
 
> root@teslausb:~# ps -ef | grep archive
> root 445 1 0 13:11 ? 00:00:00 /bin/bash -eu /root/bin/archiveloop

This is the "outer" one that's started from rc.local

> root 457 445 0 13:11 ? 00:00:00 flock -en -E 99 /root/bin/archiveloop /root/bin/archiveloop

This is flock being run from the outer archiveloop (see `man flock`)

> root 460 457 0 13:11 ? 00:00:00 /bin/bash -eu /root/bin/archiveloop

This is the instance that actually does the work, being run by `flock`
