### ISSUE TITLE
Music Stopped Working

### ISSUE THREAD

**Issue by everitj** [marcone/teslausb#809]
[diagnostics.txt](https://github.com/marcone/teslausb/files/13928686/diagnostics.txt)
### Describe the problem

Music sync has always worked fine but has recently stopped working and I cannot get it to work again. Drive appears when connected to a computer and the cam function operates fine. Car must be able to see drive as lightshow folder is seen and can access the lightshows from car and also the LockChime works. Have tied everything but wonder if this an issue with the latest software? 

### Device

Raspberry Pi Zero W

### OS Image

Prebuilt TeslaUSB image

### Car Model

Model 3

### USB connection

Glove box

**Comment by marcone** [comment]
The logs seem to show that music sync was still in progress when you took the diagnostics, but that music sync did run and complete about 15 minutes prior to that. What exactly is the problem you're having?

**Comment by everitj** [comment]
Yeah log was taken after a rebuild and multiple attempts to try different things. The issue is that the USB icon never appears in the car for music playback.. Used to work fine so not sure if what has changed to stop it from working. All other USB functions like lightshow and custom lock sound work fine...

**Comment by marcone** [comment]
If the lightshow and lock sound are on the music drive, then the car is clearly seeing the music drive. If it's not showing the music files you have on that drive, but you can see the music files when connected to a computer, then I think that's a car problem. TeslaUSB emulates the entire drive, it doesn't do anything special with the individual files on that drive.

**Comment by everitj** [comment]
After further testing it would seem that as soon as you add lightshows to the drive it then won't recognise and play the music. Is it possible to add a third partition with the current config? Thanks

**Comment by marcone** [comment]
> After further testing it would seem that as soon as you add lightshows to the drive it then won't recognise and play the music. Is it possible to add a third partition with the current config? Thanks

There already is support for a third drive, for boombox. Can lightshow share a drive with boombox?
