### ISSUE TITLE
Question reguarding NFS

### ISSUE THREAD

**Issue by mabushey** [marcone/teslausb#816]
### Describe the problem

Yes, you asked to use Discord, but they blocked my account after I joined and asked this question. I don't think they like my email server.

CIFS/SMB will NOT work for me. Is there any reason I can't easily modify this to use NFS? As there is a SSH server is there any reason why I can't use rsync over SSH to sync the files?

### Device

Raspberry Pi Zero 2 W

### OS Image

Prebuilt TeslaUSB image

### Car Model

Model Y

### USB connection

Glove box

**Comment by marcone** [comment]
> Yes, you asked to use Discord, but they blocked my account after I joined and asked this question. I don't think they like my email server.

Discord shows you as an active Discord member since April 2022, so it doesn't look like you're blocked.
 
> CIFS/SMB will NOT work for me. Is there any reason I can't easily modify this to use NFS? As there is a SSH server is there any reason why I can't use rsync over SSH to sync the files?

rsync has been supported since the beginning of the project:
- [relevant section in the config file](https://github.com/marcone/teslausb/blob/main-dev/pi-gen-sources/00-teslausb-tweaks/files/teslausb_setup_variables.conf.sample#L25)
- [instructions](https://github.com/marcone/teslausb/blob/main-dev/doc/SetupRSync.md)

**Comment by mabushey** [comment]
> Discord shows you as an active Discord member since April 2022

I created this account today

> it doesn't look like you're blocked.

Might want to eat some more carrots.

> rsync has been supported since the beginning of the project

Perfect, that completely resolves my issue. Thank you for this project and for responding to my question.

**Comment by marcone** [comment]
> > Discord shows you as an active Discord member since April 2022
> 
> I created this account today

You joined the TeslaUSB Discord today, but you're a Discord member since April 29, 2022:

![image](https://github.com/marcone/teslausb/assets/48169102/9c49c107-8a68-44b0-b434-9ec1d1a0012c)

**Comment by mabushey** [comment]
![2024-02-03_Discord](https://github.com/marcone/teslausb/assets/7863135/74578442-94fc-43d2-abb4-4a877b9c897f)

Discord probably outsourced the account creation to Microsoft.
