### ISSUE TITLE
Doesn't mount network folders

### ISSUE THREAD

**Issue by Elmeric001** [marcone/teslausb#836]
### Describe the problem

Hi,

I have installed on a Raspberry Pi 0 W 2 and it works so that the car get upload files to the backingfiles catalogue etc.

But for some reason it doesn't mount my network share when it boots up.

When i ran the upgrade function it shows in the log that it could connect, but then later on when it has restarted it is not mounted when I run a df -h (but I can manually mount it as you can see in the "additional information" part below.

I am really a total noob when it comes to ssh, should I try to add the mounting in some sort of startup-script etc or have I done something else wrong?

### Device

Raspberry Pi Zero 2 W

### OS Image

Prebuilt TeslaUSB image

### Car Model

Model Y

### USB connection

Glove box

### Logs

cifs-utils is already the newest version (2:6.8-2+deb10u1).
hping3 is already the newest version (3.a2.ds2-7).
0 upgraded, 0 newly installed, 0 to remove and 157 not upgraded.
W: --force-yes is deprecated, use one of the options starting with --allow instead.
verify-and-configure-archive: Done
verify-and-configure-archive: Verifying that the archive server 192.168.100.217 is reachable...
verify-and-configure-archive: The archive server is reachable.
verify-and-configure-archive: Verifying that the archive share is mountable...
Trying all combinations of vers=(default 3.1.1 3.0 2.1 2.0 @@) and sec=(@@ ntlmssp ntlmv2 ntlm)
verify-and-configure-archive: Trying mount command-line:
verify-and-configure-archive: mount -t cifs '//192.168.100.217/TeslaCam' '/tmp/archivetestmount' -o 'credentials=/tmp/teslaCamArchiveCredentials,iocharset=utf8,file_mode=0777,dir_mode=0777,vers=default,'
verify-and-configure-archive: The archive share is mountable using: mount -t cifs '//192.168.100.217/TeslaCam' '/tmp/archivetestmount' -o 'credentials=/tmp/teslaCamArchiveCredentials,iocharset=utf8,file_mode=0777,dir_mode=0777,vers=default,'
verify-and-configure-archive: Configuring the archive...
verify-and-configure-archive: Configured the archive.
R

### Additional information

root@teslausb:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root       2.0G  1.2G  674M  64% /
devtmpfs        182M     0  182M   0% /dev
tmpfs           214M     0  214M   0% /dev/shm
tmpfs           214M  5.8M  209M   3% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           214M     0  214M   0% /sys/fs/cgroup
tmpfs           214M  4.0K  214M   1% /tmp
tmpfs           214M     0  214M   0% /var/tmp
tmpfs           214M     0  214M   0% /var/spool
tmpfs           214M     0  214M   0% /var/lib/nginx
tmpfs           214M     0  214M   0% /var/lib/ntp
tmpfs           214M     0  214M   0% /var/log/nginx
/dev/mmcblk0p4   96M  1.6M   87M   2% /mutable
/dev/mmcblk0p1  247M   49M  199M  20% /boot
/dev/mmcblk0p3   57G  449M   57G   1% /backingfiles
tmpfs            43M     0   43M   0% /run/user/1000
root@teslausb:~# mount -t cifs '//192.168.100.217/TeslaCam'
root@teslausb:~# df -h
Filesystem                  Size  Used Avail Use% Mounted on
/dev/root                   2.0G  1.2G  674M  64% /
devtmpfs                    182M     0  182M   0% /dev
tmpfs                       214M     0  214M   0% /dev/shm
tmpfs                       214M  5.8M  209M   3% /run
tmpfs                       5.0M     0  5.0M   0% /run/lock
tmpfs                       214M     0  214M   0% /sys/fs/cgroup
tmpfs                       214M  4.0K  214M   1% /tmp
tmpfs                       214M     0  214M   0% /var/tmp
tmpfs                       214M     0  214M   0% /var/spool
tmpfs                       214M     0  214M   0% /var/lib/nginx
tmpfs                       214M     0  214M   0% /var/lib/ntp
tmpfs                       214M     0  214M   0% /var/log/nginx
/dev/mmcblk0p4               96M  1.6M   87M   2% /mutable
/dev/mmcblk0p1              247M   49M  199M  20% /boot
/dev/mmcblk0p3               57G  449M   57G   1% /backingfiles
tmpfs                        43M     0   43M   0% /run/user/1000
//192.168.100.217/TeslaCam  953G  888G   65G  94% /mnt/archive

**Comment by marcone** [comment]
> But for some reason it doesn't mount my network share when it boots up.

https://github.com/marcone/teslausb/wiki/FAQ#q-i-sshd-into-the-pi-but-am-not-seeing-my-network-share
