### ISSUE TITLE
Can't view drive when plugged into Window 10 machine

### ISSUE THREAD

**Issue by awysocki** [marcone/teslausb#84]
Everything works like a champ.

One item I did try that I couldn't get to work. If I take the RP out of the car and plug in the USB (on the windows machine) to USB (not the power that looks like a usb on the RPzw) it boots up and wifi is started, but the windows machine never attaches the drive as a USB drive.  I was just doing this as a test.

Is this something that is suppose to work?  Or since WiFi is attached it won't look like a drive at that time?

This is a very very very low item and doesn't need to be solved. I'm just asking.

Thanks
Andy

**Comment by marcone** [comment]
This should work. While teslausb is starting up it will check the drive and see if there's anything to back up (you will see the LED flashing rapidly during this phase), but after that the drive will be connected to the car or computer (the LED will do a single or double-flash once per second at that time).
Check that the USB cable you're using for attaching to the computer isn't a charge-only cable.
