### ISSUE TITLE
Not syncing all the time when it is turned ON

### ISSUE THREAD

**Issue by stauffenberg2020** [marcone/teslausb#840]
### Describe the problem

As per the answer in #782, The syncing happens only when teslausb connects after having been unable to connect to it.

Why it needs to be fixed

**Car in Garage with Sentry active**
1. Car is in garage and has finished syncing and sentry mode is active -->Some thief is trying to open the car --> Sentry mode takes a nice video, and sends a notification to Tesla app in the phone at mid night and saves it in the OTG USB --> Wake up from bed and try to see whether the sentry video is available to see (from NAS' network drive) through mobile --> **_Can't find any videos_** (since teslausb has not synced anything at all - Because it has remained connected to the Wifi network) --> Walk upto the garage (from bedroom) by making all kinds of wooden floor creaking and wake up the kids too
2. I plan for a long drive today and I am one of the few who likes to hear songs that are not available in Apple Music/Spotify. So I copy the music to the local Music Folder where teslausb is supposed to sync. I go into the car and started to drive - But could not find any music synced to it

**Car not in garage and/or Home Wifi cannot be extended upto the car** (tailscale can help if you do not want to open laptop in the car)
1. Only option to wirelessly sync the recorded videos is to enable hotspot in phone and connect both teslausb and a laptop to the hotspot and then sync --> This means, I am driving in the traffic and some other person is making a wrong turn/move --> I honk at him for notifying him and also to save the dashcam videos --> I open the laptop in the car before I exit the car --> **_Videos are not synced_** because hotspot Network has remain connected

### Device

Raspberry Pi Zero 2 W

### OS Image

other

### Car Model

Model 3

### USB connection

Glove box

**Comment by marcone** [comment]
> Sentry mode takes a nice video, and sends a notification to Tesla app in the phone

I wasn't aware that Tesla notifies you of sentry events in the app. Is this a new feature?

I'm not sure I understand your comment about the laptop. If you enable a mobile hotspot while driving, and that hotspot allows TeslaUSB to reach the archive server, then it will start archiving at that point. This also means that the emulated drive will be temporarily disconnected from the car at the end of archiving though.

In any case, continuous syncing likely isn't something I will ever get around to supporting. You're welcome to try and  implement it.

**Comment by stauffenberg2020** [comment]
> > Sentry mode takes a nice video, and sends a notification to Tesla app in the phone
> 
> I wasn't aware that Tesla notifies you of sentry events in the app. Is this a new feature?
> 
No, its not a new feature. Car sends a notification to your app and it starts honking. Its there since long time.


> In any case, continuous syncing likely isn't something I will ever get around to supporting. You're welcome to try and implement it.

Can you point me to some linux references so that I can read, understand and chatGPT a bit and see if I can do something?

**Comment by marcone** [comment]
> > > Sentry mode takes a nice video, and sends a notification to Tesla app in the phone
> > 
> > I wasn't aware that Tesla notifies you of sentry events in the app. Is this a new feature?
> 
> No, its not a new feature. Car sends a notification to your app and it starts honking. Its there since long time.

That's when the alarm goes. Very different from a sentry event.
 
> > In any case, continuous syncing likely isn't something I will ever get around to supporting. You're welcome to try and implement it.
> 
> Can you point me to some linux references so that I can read, understand and chatGPT a bit and see if I can do something?

I wouldn't even know where to start.

**Comment by marcone** [comment]
Original request for continuous syncing is https://github.com/marcone/teslausb/issues/171
