### ISSUE TITLE
AP_PASS not set, not changed from default, or too short

### ISSUE THREAD

**Issue by bcorbs** [marcone/teslausb#842]
### Describe the problem

When i check the teslausb-headless-setup.log file "configure-ap: AP_PASS not set, not changed from default, or too short" is the last line in the file.

The Pi connects to my WiFi fine and seems to be mounting to the drives for Cam and Music but nothing is getting saved.

### Device

Raspberry Pi Zero W

### OS Image

Prebuilt TeslaUSB image

### Car Model

Model 3

### USB connection

Glove box

**Comment by marcone** [comment]
Looks like you tried to enable access point functionality, but did not follow the [instructions](https://github.com/marcone/teslausb/blob/main-dev/pi-gen-sources/00-teslausb-tweaks/files/teslausb_setup_variables.conf.sample#L134) in the config file, causing setup to not complete.
