### ISSUE TITLE
Changing time zone once up and running

### ISSUE THREAD

**Issue by bcorbs** [marcone/teslausb#843]
### Describe the problem

I want to change the default timezone from BST to EST but when i try to edit the teslausb_setup_variables.conf file now it says its uneditable. Is there another way to edit the timezone?

### Device

Raspberry Pi Zero W

### OS Image

Prebuilt TeslaUSB image

### Car Model

Model 3

### USB connection

Glove box

**Comment by marcone** [comment]
https://github.com/marcone/teslausb/wiki/FAQ#q-how-do-i-change-the-teslausb-configuration
