### ISSUE TITLE
Orange Pi Zero 2 w 4 g. Will there be support?

### ISSUE THREAD

**Issue by dessty45** [marcone/teslausb#844]
### Describe the problem

[/init]: getty is tty1
[/init]: RootDevice is "/dev/mtdblock4", GPT_SUPPORT=1
[/init]: Try to load Nor
mount: mounting /dev/mtdblock4 on /mnt failed: No such file or directory
[/init]: Failed to mount /dev/mtdblock4!

Hello, wanted to run **Orange Pi Zero 2 w 4 g**. Will there be support?

### Device

Other

### OS Image

Prebuilt TeslaUSB image

### Car Model

Model Y

### USB connection

Center console

**Comment by marcone** [comment]
> ### Describe the problem
> [/init]: getty is tty1
> [/init]: RootDevice is "/dev/mtdblock4", GPT_SUPPORT=1
> [/init]: Try to load Nor
> mount: mounting /dev/mtdblock4 on /mnt failed: No such file or directory
> [/init]: Failed to mount /dev/mtdblock4!
> 
> Hello, wanted to run **Orange Pi Zero 2 w 4 g**. Will there be support?
> 
> ### Device
> Other
> 
> ### OS Image
> Prebuilt TeslaUSB image

The prebuilt TeslaUSB image *only* works on Raspberry Pi. If you want to use any other hardware, you will need to use an image appropriate for that hardware (for example, Armbian) and follow the [manual installation process](https://github.com/marcone/teslausb/wiki/Installation).
