### ISSUE TITLE
After a few days teslausb does not connect to wifi any more but still mounted and recording.

### ISSUE THREAD

**Issue by thesourcerer** [marcone/teslausb#856]
### Describe the problem

Running on Pi Zero W2,
Working fine for a few days, then stops connecting to wifi (router says device is not connected).
Device is still mounted to tesla and recording during this time.
Power cycling resolves the issue until it comes back a few days later.

What can i check? 

### Device

Raspberry Pi Zero 2 W

### OS Image

Prebuilt TeslaUSB image

### Car Model

Model Y

### USB connection

Glove box

### Logs

Not connected to wifi

**Comment by marcone** [comment]
The kernel log might have information as to why it's not connecting to wifi, but the only way to get that is by logging in to the Pi, and you'd need a wifi connection for that.

**Comment by thesourcerer** [comment]
Yep... 
For now i have added a loop in the archiveloop that monitors the connection every 15 min and logs the issue if found and also tries to recover with stopping\starting the interface.

**Comment by Sportwyse** [comment]
I'm having the same issue. It will stay connected for 3-4 days then stop connecting to wifi. It looks like when the drive gets full. The wifi won't connect.

**Comment by marcone** [comment]
> I'm having the same issue. It will stay connected for 3-4 days then stop connecting to wifi. It looks like when the drive gets full. The wifi won't connect.

Which drive gets full?

**Comment by marcone** [comment]
Nothing actionable here.

**Comment by thesourcerer** [comment]
I managed to work around it by creating a cron task to reboot the pie twice a day. Fixed all issues.
