### ISSUE TITLE
Google Drive Corrupted Files? 

### ISSUE THREAD

**Issue by appark** [marcone/teslausb#88]
<img width="828" alt="Screen Shot 2019-06-20 at 10 01 45 AM" src="https://user-images.githubusercontent.com/20006067/59867293-b4165d80-9342-11e9-8f83-b7106ca053a7.png">

Some of my files in google drive have no file size? Are these files corrupted?

**Comment by marcone** [comment]
I don't use rclone/gdrive myself, but you're not the first one to report this: https://github.com/marcone/teslausb/issues/15
