### ISSUE TITLE
Pi zero not rebooting multiptle times after manual installating

### ISSUE THREAD

**Issue by Sjorsa** [marcone/teslausb#881]
### Describe the problem

I installed Raspberry Pi OS Lite (32bit) on a Pi Zero W using the official Raspberry Imager. 

After booting into that and updating with `sudo apt update`and `sudo apt upgrade`, I run the installation command `curl https://raw.githubusercontent.com/marcone/teslausb/main-dev/setup/generic/install.sh | bash` as root and it does a whole bunch of stuff.

According to the instructions, the Pi should reboot multiple times now, but it only reboots once and doesn't do anything after that. 

If I run the installation command again, it returns `STOP: Previous resize attempt failed. Delete /root/RESIZE_ATTEMPTED before retrying.`. Also, there is no `/boot/teslausb-headless-setup.log` file created, so I cannot debug what is going wrong.

What could I be doing wrong?

### Device

Raspberry Pi Zero W

### OS Image

other

### Car Model

Model 3

### USB connection

Center console

**Comment by marcone** [comment]
Note that the instructions say that the Pi _may_ reboot multiple times, not that it _will_ reboot multiple times.
Regardless, it looks like it either got stuck or was still busy doing the initial file system resize. How long did you wait before running the installation command again?

**Comment by marcone** [comment]
OK, I can reproduce the problem. Must be something new/different about the current Raspberry Pi 32 bit lite image, since I installed this same way a few weeks ago. For now I'd recommend using the prebuilt TeslaUSB image.

**Comment by marcone** [comment]
So far I've found that just flashing the "Raspberry Pi OS Lite (32 bit)" and then running the `curl ... | bash` install command works.
However if first I `apt update` and `apt upgrade`, then the install command fails as described above.

**Comment by Sjorsa** [comment]
Sorry for the late response but I can confirm it works now too
