### ISSUE TITLE
Archiving not retried

### ISSUE THREAD

**Issue by mulka** [marcone/teslausb#893]
### Describe the problem

With rclone, I don't believe that the archiving is retried for files that failed. For example, if the device is turned off in the middle of archiving, or if the wifi connection is poor and unable to complete.

### Device

Raspberry Pi Zero W

### OS Image

Prebuilt TeslaUSB image

### Car Model

Model Y

### USB connection

Glove box

**Comment by marcone** [comment]
> With rclone, I don't believe that the archiving is retried for files that failed

And what makes you believe that?
