### ISSUE TITLE
Marker file does not get created for RecentClips

### ISSUE THREAD

**Issue by deangoldhill** [marcone/teslausb#901]
### Describe the problem

I am using https://github.com/ehendrix23/tesla_dashcam to merge clips,
So I have enabled the ARCHIVE_UPLOADED marker for all 3 Recent, Saved and Sentry clips
export TRIGGER_FILE_SAVED=ARCHIVE_UPLOADED
export TRIGGER_FILE_SENTRY=ARCHIVE_UPLOADED
export TRIGGER_FILE_RECENT=ARCHIVE_UPLOADED

Once the archive is complete, the marker is created for both Saved and Sentry clips, but not for RecentClips.
I get the telegram notification once complete, indicating the archive is succesful.

I did an upgrade just yeaterday, and still have the issue today
/root/bin/setup-teslausb upgrade

### Device

Raspberry Pi Zero W

### OS Image

Prebuilt TeslaUSB image

### Car Model

Model S

### USB connection

Center console

### Logs

Sun 24 Nov 09:41:54 GMT 2024: cleaning cam mount
Sun 24 Nov 09:41:54 GMT 2024: Ensuring cam file is mounted...
Sun 24 Nov 09:41:54 GMT 2024: Disconnecting usb from host...
Sun 24 Nov 09:41:54 GMT 2024: Running fsck on /backingfiles/cam_disk.bin...
Sun 24 Nov 09:41:54 GMT 2024: | fsck from util-linux 2.33.1
Sun 24 Nov 09:41:55 GMT 2024: | fsck.fat 4.1 (2017-01-24)
Sun 24 Nov 09:41:55 GMT 2024: | 0x41: Dirty bit is set. Fs was not properly unmounted and some data may be corrupt.
Sun 24 Nov 09:41:55 GMT 2024: |  Automatically removing dirty bit.
Sun 24 Nov 09:41:55 GMT 2024: | Long filename fragment "2024-11-13_18" found outside a LFN sequence.
Sun 24 Nov 09:41:55 GMT 2024: |   (Maybe the start bit is missing on the last fragment)
Sun 24 Nov 09:41:55 GMT 2024: |   Not auto-correcting this.
Sun 24 Nov 09:41:55 GMT 2024: | Performing changes.
Sun 24 Nov 09:41:55 GMT 2024: | /dev/loop1p1: 186 files, 333074/1572031 clusters
Sun 24 Nov 09:41:55 GMT 2024: Finished fsck on /backingfiles/cam_disk.bin.
Sun 24 Nov 09:41:55 GMT 2024: Running fsck on /backingfiles/music_disk.bin...
Sun 24 Nov 09:41:55 GMT 2024: | fsck from util-linux 2.33.1
Sun 24 Nov 09:41:56 GMT 2024: | fsck.fat 4.1 (2017-01-24)
Sun 24 Nov 09:41:56 GMT 2024: | /dev/loop1p1: 2106 files, 1956173/2094976 clusters
Sun 24 Nov 09:41:56 GMT 2024: Finished fsck on /backingfiles/music_disk.bin.
Sun 24 Nov 09:41:56 GMT 2024: Disconnected usb from host.
Sun 24 Nov 09:41:57 GMT 2024: Mounting /mnt/cam...
Sun 24 Nov 09:41:57 GMT 2024: Mounted /mnt/cam.
Sun 24 Nov 09:41:57 GMT 2024: Ensured cam file is mounted.
Sun 24 Nov 09:41:57 GMT 2024: Trimming free space in /mnt/cam, which has 279 extents
Sun 24 Nov 09:41:57 GMT 2024: Trim complete, image now has 279 extents
Sun 24 Nov 09:41:57 GMT 2024: Unmounting /mnt/cam...
Sun 24 Nov 09:41:57 GMT 2024: Unmounted /mnt/cam.
Sun 24 Nov 09:41:57 GMT 2024: done cleaning cam mount
Sun 24 Nov 09:41:58 GMT 2024: Finished archiving.
Sun 24 Nov 09:42:03 GMT 2024: Music archive not configured or unreachable
Sun 24 Nov 09:42:03 GMT 2024: unmounting /mnt/archive
Sun 24 Nov 09:42:03 GMT 2024: Connecting usb to host...
Sun 24 Nov 09:42:03 GMT 2024: Connected usb to host.
Sun 24 Nov 09:42:08 GMT 2024: Waiting for archive to be unreachable...
Sun 24 Nov 09:42:08 GMT 2024: Sleeping before retry ...
Sun 24 Nov 09:42:09 GMT 2024: Retrying (1) 'archive_is_reachable' ...
Sun 24 Nov 09:42:09 GMT 2024: Sleeping before retry ...
Sun 24 Nov 09:42:10 GMT 2024: Retrying (2) 'archive_is_reachable' ...
Sun 24 Nov 09:42:10 GMT 2024: Sleeping before retry ...
Sun 24 Nov 09:42:11 GMT 2024: Retrying (3) 'archive_is_reachable' ...
Sun 24 Nov 09:42:11 GMT 2024: Sleeping before retry ...
Sun 24 Nov 09:42:12 GMT 2024: Retrying (4) 'archive_is_reachable' ...
Sun 24 Nov 09:42:12 GMT 2024: Sleeping before retry ...
Sun 24 Nov 09:42:13 GMT 2024: Retrying (5) 'archive_is_reachable' ...
Sun 24 Nov 09:42:13 GMT 2024: Sleeping before retry ...
Sun 24 Nov 09:42:14 GMT 2024: Retrying (6) 'archive_is_reachable' ...
Sun 24 Nov 09:42:14 GMT 2024: Sleeping before retry ...
Sun 24 Nov 09:42:15 GMT 2024: Retrying (7) 'archive_is_reachable' ...
Sun 24 Nov 09:42:15 GMT 2024: Sleeping before retry ...
Sun 24 Nov 09:42:16 GMT 2024: Retrying (8) 'archive_is_reachable' ...
Sun 24 Nov 09:42:16 GMT 2024: Sleeping before retry ...
Sun 24 Nov 09:42:18 GMT 2024: Retrying (9) 'archive_is_reachable' ...
Sun 24 Nov 09:42:18 GMT 2024: Sleeping before retry ...
Sun 24 Nov 09:42:19 GMT 2024: Retrying (10) 'archive_is_reachable' ...
Sun 24 Nov 09:42:19 GMT 2024: Attempts exhausted.
Sun 24 Nov 09:42:19 GMT 2024: Archive is unreachable.
Sun 24 Nov 09:42:19 GMT 2024: Waiting for archive to be reachable...
Sun 24 Nov 10:18:03 GMT 2024: low space, deleting /backingfiles/snapshots/snap-000041
Sun 24 Nov 10:30:04 GMT 2024: low space, deleting /backingfiles/snapshots/snap-000042
Sun 24 Nov 10:37:31 GMT 2024: waiting up to 90 seconds for idle interval
Sun 24 Nov 10:37:34 GMT 2024: write in progress
Sun 24 Nov 10:37:36 GMT 2024: no longer writing, wrote 26300416
Sun 24 Nov 10:37:37 GMT 2024: going back to writing state
Sun 24 Nov 10:37:38 GMT 2024: no longer writing, wrote 25673728
Sun 24 Nov 10:37:39 GMT 2024: going back to writing state
Sun 24 Nov 10:37:40 GMT 2024: no longer writing, wrote 24842240
Sun 24 Nov 10:37:41 GMT 2024: going back to writing state
Sun 24 Nov 10:37:46 GMT 2024: no longer writing, wrote 36536320
Sun 24 Nov 10:37:52 GMT 2024: no writes seen in the last 5 seconds
Sun 24 Nov 10:37:52 GMT 2024: taking snapshot of cam disk in /backingfiles/snapshots/snap-000048
Sun 24 Nov 10:37:54 GMT 2024: took snapshot
Sun 24 Nov 10:37:54 GMT 2024: comparing new snapshot with /backingfiles/snapshots/snap-000047/snap.bin
Sun 24 Nov 10:37:54 GMT 2024: making links for /tmp/snapshots/snap-000048, retargeted to /backingfiles/snapshots/snap-000048/mnt
Sun 24 Nov 10:37:56 GMT 2024: made all links for /tmp/snapshots/snap-000048
Sun 24 Nov 11:35:57 GMT 2024: waiting up to 90 seconds for idle interval
Sun 24 Nov 11:36:43 GMT 2024: write in progress
Sun 24 Nov 11:36:51 GMT 2024: no longer writing, wrote 110997504
Sun 24 Nov 11:36:58 GMT 2024: no writes seen in the last 5 seconds
Sun 24 Nov 11:36:58 GMT 2024: taking snapshot of cam disk in /backingfiles/snapshots/snap-000049
Sun 24 Nov 11:37:00 GMT 2024: took snapshot
Sun 24 Nov 11:37:00 GMT 2024: comparing new snapshot with /backingfiles/snapshots/snap-000048/snap.bin
Sun 24 Nov 11:37:00 GMT 2024: making links for /tmp/snapshots/snap-000049, retargeted to /backingfiles/snapshots/snap-000049/mnt
Sun 24 Nov 11:37:02 GMT 2024: made all links for /tmp/snapshots/snap-000049
Sun 24 Nov 11:56:08 GMT 2024: low space, deleting /backingfiles/snapshots/snap-000043
Sun 24 Nov 11:56:09 GMT 2024: low space, deleting /backingfiles/snapshots/snap-000044
Sun 24 Nov 12:35:02 GMT 2024: waiting up to 90 seconds for idle interval
Sun 24 Nov 12:35:17 GMT 2024: write in progress
Sun 24 Nov 12:35:26 GMT 2024: no longer writing, wrote 109637632
Sun 24 Nov 12:35:32 GMT 2024: no writes seen in the last 5 seconds
Sun 24 Nov 12:35:32 GMT 2024: taking snapshot of cam disk in /backingfiles/snapshots/snap-000050
Sun 24 Nov 12:35:34 GMT 2024: took snapshot
Sun 24 Nov 12:35:35 GMT 2024: comparing new snapshot with /backingfiles/snapshots/snap-000049/snap.bin
Sun 24 Nov 12:35:35 GMT 2024: making links for /tmp/snapshots/snap-000050, retargeted to /backingfiles/snapshots/snap-000050/mnt
Sun 24 Nov 12:35:37 GMT 2024: made all links for /tmp/snapshots/snap-000050
Sun 24 Nov 13:20:43 GMT 2024: low space, deleting /backingfiles/snapshots/snap-000045
Sun 24 Nov 13:22:14 GMT 2024: low space, deleting /backingfiles/snapshots/snap-000046
Sun 24 Nov 13:30:46 GMT 2024: low space, deleting /backingfiles/snapshots/snap-000047
Sun 24 Nov 13:31:46 GMT 2024: low space, deleting /backingfiles/snapshots/snap-000048
Sun 24 Nov 13:31:46 GMT 2024: low space, deleting /backingfiles/snapshots/snap-000049
Sun 24 Nov 13:31:47 GMT 2024: Warning: low space for new snapshots, but only one snapshot exists.
Sun 24 Nov 13:31:47 GMT 2024: Please use a larger storage medium or reduce CAM_SIZE
Sun 24 Nov 13:32:47 GMT 2024: Warning: low space for new snapshots, but only one snapshot exists.
Sun 24 Nov 13:32:47 GMT 2024: Please use a larger storage medium or reduce CAM_SIZE
Sun 24 Nov 13:33:37 GMT 2024: waiting up to 90 seconds for idle interval
Sun 24 Nov 13:33:47 GMT 2024: Warning: low space for new snapshots, but only one snapshot exists.
Sun 24 Nov 13:33:47 GMT 2024: Please use a larger storage medium or reduce CAM_SIZE
Sun 24 Nov 13:34:11 GMT 2024: write in progress
Sun 24 Nov 13:34:13 GMT 2024: no longer writing, wrote 38973440
Sun 24 Nov 13:34:14 GMT 2024: going back to writing state
Sun 24 Nov 13:34:16 GMT 2024: no longer writing, wrote 38260736
Sun 24 Nov 13:34:17 GMT 2024: going back to writing state
Sun 24 Nov 13:34:19 GMT 2024: no longer writing, wrote 37171200
Sun 24 Nov 13:34:20 GMT 2024: going back to writing state
Sun 24 Nov 13:34:23 GMT 2024: no longer writing, wrote 38223872
Sun 24 Nov 13:34:29 GMT 2024: no writes seen in the last 5 seconds
Sun 24 Nov 13:34:29 GMT 2024: taking snapshot of cam disk in /backingfiles/snapshots/snap-000051
Sun 24 Nov 13:34:31 GMT 2024: took snapshot
Sun 24 Nov 13:34:32 GMT 2024: comparing new snapshot with /backingfiles/snapshots/snap-000050/snap.bin
Sun 24 Nov 13:34:32 GMT 2024: making links for /tmp/snapshots/snap-000051, retargeted to /backingfiles/snapshots/snap-000051/mnt
Sun 24 Nov 13:34:34 GMT 2024: made all links for /tmp/snapshots/snap-000051
Sun 24 Nov 13:34:47 GMT 2024: low space, deleting /backingfiles/snapshots/snap-000050
Sun 24 Nov 13:52:41 GMT 2024: Archive is reachable.
Sun 24 Nov 13:52:41 GMT 2024: Trying to set time...
Sun 24 Nov 13:52:43 GMT 2024: Time adjusted by 2.382049 seconds after 2.390000 seconds
Sun 24 Nov 13:52:43 GMT 2024: Not keeping car awake.
Sun 24 Nov 13:53:03 GMT 2024: taking snapshot of cam disk in /backingfiles/snapshots/snap-000052
Sun 24 Nov 13:53:06 GMT 2024: took snapshot
Sun 24 Nov 13:53:06 GMT 2024: comparing new snapshot with /backingfiles/snapshots/snap-000051/snap.bin
Sun 24 Nov 13:53:06 GMT 2024: making links for /tmp/snapshots/snap-000052, retargeted to /backingfiles/snapshots/snap-000052/mnt
Sun 24 Nov 13:53:12 GMT 2024: made all links for /tmp/snapshots/snap-000052
Sun 24 Nov 13:53:12 GMT 2024: Archiving...
Sun 24 Nov 13:53:13 GMT 2024: Ensuring cam archive is mounted...
Sun 24 Nov 13:53:13 GMT 2024: Mounting /mnt/archive...
Sun 24 Nov 13:53:14 GMT 2024: Mounted /mnt/archive.
Sun 24 Nov 13:53:14 GMT 2024: Ensured cam archive is mounted.
Sun 24 Nov 13:53:14 GMT 2024: Ensuring music archive is mounted...
Sun 24 Nov 13:53:14 GMT 2024: /mnt/musicarchive is already mounted.
Sun 24 Nov 13:53:14 GMT 2024: Ensured music archive is mounted.
Sun 24 Nov 13:53:14 GMT 2024: Checking saved folder count...
Sun 24 Nov 13:53:18 GMT 2024: There are 3 event folder(s) with 216 file(s) and 0 track mode file(s) to move.  0 short recording(s) will be skipped.
Sun 24 Nov 13:53:18 GMT 2024: Starting recording archiving
Sun 24 Nov 13:53:18 GMT 2024: Archiving 216 file(s) including 3 event folder(s) starting at Sun 24 Nov 13:53:18 GMT 2024
Sun 24 Nov 13:53:18 GMT 2024: Sending Pushover message.
Sun 24 Nov 13:53:19 GMT 2024: Sending Telegram message.
Sun 24 Nov 14:32:34 GMT 2024: waiting up to 90 seconds for idle interval
Sun 24 Nov 14:34:10 GMT 2024: couldn't determine idle interval
Sun 24 Nov 14:34:10 GMT 2024: taking snapshot of cam disk in /backingfiles/snapshots/snap-000053
Sun 24 Nov 14:34:13 GMT 2024: took snapshot
Sun 24 Nov 14:34:14 GMT 2024: comparing new snapshot with /backingfiles/snapshots/snap-000052/snap.bin
Sun 24 Nov 14:34:14 GMT 2024: new snapshot is identical to previous one, discarding
Sun 24 Nov 15:16:40 GMT 2024: Archiving completed successfully. Archived 216 files in 1h23m22s
Sun 24 Nov 15:16:40 GMT 2024: Sending Pushover message.
Sun 24 Nov 15:16:41 GMT 2024: Sending Telegram message.
Sun 24 Nov 15:16:41 GMT 2024: cleaning cam mount
Sun 24 Nov 15:16:41 GMT 2024: Ensuring cam file is mounted...
Sun 24 Nov 15:16:41 GMT 2024: Disconnecting usb from host...
Sun 24 Nov 15:16:42 GMT 2024: Running fsck on /backingfiles/cam_disk.bin...
Sun 24 Nov 15:16:42 GMT 2024: | fsck from util-linux 2.33.1
Sun 24 Nov 15:16:43 GMT 2024: | fsck.fat 4.1 (2017-01-24)
Sun 24 Nov 15:16:43 GMT 2024: | 0x41: Dirty bit is set. Fs was not properly unmounted and some data may be corrupt.
Sun 24 Nov 15:16:43 GMT 2024: |  Automatically removing dirty bit.
Sun 24 Nov 15:16:43 GMT 2024: | Long filename fragment "2024-11-13_18" found outside a LFN sequence.
Sun 24 Nov 15:16:43 GMT 2024: |   (Maybe the start bit is missing on the last fragment)
Sun 24 Nov 15:16:43 GMT 2024: |   Not auto-correcting this.
Sun 24 Nov 15:16:43 GMT 2024: | Performing changes.
Sun 24 Nov 15:16:43 GMT 2024: | /dev/loop1p1: 279 files, 513113/1572031 clusters
Sun 24 Nov 15:16:43 GMT 2024: Finished fsck on /backingfiles/cam_disk.bin.
Sun 24 Nov 15:16:43 GMT 2024: Running fsck on /backingfiles/music_disk.bin...
Sun 24 Nov 15:16:43 GMT 2024: | fsck from util-linux 2.33.1
Sun 24 Nov 15:16:46 GMT 2024: | fsck.fat 4.1 (2017-01-24)
Sun 24 Nov 15:16:46 GMT 2024: | /dev/loop1p1: 2106 files, 1956173/2094976 clusters
Sun 24 Nov 15:16:46 GMT 2024: Finished fsck on /backingfiles/music_disk.bin.
Sun 24 Nov 15:16:46 GMT 2024: Disconnected usb from host.
Sun 24 Nov 15:16:46 GMT 2024: Mounting /mnt/cam...
Sun 24 Nov 15:16:46 GMT 2024: Mounted /mnt/cam.
Sun 24 Nov 15:16:46 GMT 2024: Ensured cam file is mounted.
Sun 24 Nov 15:16:48 GMT 2024: Trimming free space in /mnt/cam, which has 7485 extents
Sun 24 Nov 15:16:48 GMT 2024: Trim complete, image now has 5340 extents
Sun 24 Nov 15:16:48 GMT 2024: Unmounting /mnt/cam...
Sun 24 Nov 15:16:49 GMT 2024: Unmounted /mnt/cam.
Sun 24 Nov 15:16:49 GMT 2024: done cleaning cam mount
Sun 24 Nov 15:16:49 GMT 2024: Finished archiving.
Sun 24 Nov 15:16:49 GMT 2024: Copying music...
Sun 24 Nov 15:16:49 GMT 2024: Starting music sync...
Sun 24 Nov 15:16:49 GMT 2024: Ensuring music backing file is mounted...
Sun 24 Nov 15:16:49 GMT 2024: Disconnecting usb from host...
Sun 24 Nov 15:16:49 GMT 2024: Disconnected usb from host.
Sun 24 Nov 15:16:49 GMT 2024: Mounting /mnt/music...
Sun 24 Nov 15:16:49 GMT 2024: Mounted /mnt/music.
Sun 24 Nov 15:16:49 GMT 2024: Ensured music drive is mounted.
Sun 24 Nov 15:16:49 GMT 2024: Syncing music from archive...
Sun 24 Nov 15:16:54 GMT 2024: Copied 0 music file(s), deleted 0, skipped 1958 previously-copied files, and encountered 0 errors.
Sun 24 Nov 15:16:54 GMT 2024: Trimming free space in /mnt/music, which has 57 extents
Sun 24 Nov 15:16:54 GMT 2024: Trim complete, image now has 57 extents
Sun 24 Nov 15:16:54 GMT 2024: Unmounting /mnt/music...
Sun 24 Nov 15:16:54 GMT 2024: Unmounted /mnt/music.
Sun 24 Nov 15:16:54 GMT 2024: Finished copying music.
Sun 24 Nov 15:16:54 GMT 2024: unmounting /mnt/archive
Sun 24 Nov 15:16:54 GMT 2024: Connecting usb to host...
Sun 24 Nov 15:16:55 GMT 2024: unmounting /mnt/musicarchive
Sun 24 Nov 15:16:55 GMT 2024: Connected usb to host.
Sun 24 Nov 15:17:00 GMT 2024: Waiting for archive to be unreachable...
Sun 24 Nov 15:32:15 GMT 2024: waiting up to 90 seconds for idle interval
Sun 24 Nov 15:33:50 GMT 2024: couldn't determine idle interval
Sun 24 Nov 15:33:50 GMT 2024: taking snapshot of cam disk in /backingfiles/snapshots/snap-000053
Sun 24 Nov 15:33:53 GMT 2024: took snapshot
Sun 24 Nov 15:33:53 GMT 2024: comparing new snapshot with /backingfiles/snapshots/snap-000052/snap.bin
Sun 24 Nov 15:33:53 GMT 2024: new snapshot is identical to previous one, discarding
Sun 24 Nov 16:31:54 GMT 2024: waiting up to 90 seconds for idle interval
Sun 24 Nov 16:33:30 GMT 2024: couldn't determine idle interval
Sun 24 Nov 16:33:30 GMT 2024: taking snapshot of cam disk in /backingfiles/snapshots/snap-000053
Sun 24 Nov 16:33:32 GMT 2024: took snapshot
Sun 24 Nov 16:33:32 GMT 2024: comparing new snapshot with /backingfiles/snapshots/snap-000052/snap.bin
Sun 24 Nov 16:33:32 GMT 2024: new snapshot is identical to previous one, discarding
Sun 24 Nov 17:31:33 GMT 2024: waiting up to 90 seconds for idle interval
Sun 24 Nov 17:33:08 GMT 2024: couldn't determine idle interval
Sun 24 Nov 17:33:09 GMT 2024: taking snapshot of cam disk in /backingfiles/snapshots/snap-000053
Sun 24 Nov 17:33:11 GMT 2024: took snapshot
Sun 24 Nov 17:33:11 GMT 2024: comparing new snapshot with /backingfiles/snapshots/snap-000052/snap.bin
Sun 24 Nov 17:33:11 GMT 2024: new snapshot is identical to previous one, discarding
==============================================

### Additional information

I have not changed the marker config since initial setup.
I have changed other config though (telegram setup).
Its not a major issue because I just use a cronjob to on the archive server to add the marker before the tesla_dashcam processing kicks in.

Thanks for your effrorts on this brilliant project!

**Comment by marcone** [comment]
Thanks for the report. Funny how apparently nobody else noticed in all the years since this feature was added.

**Comment by jjermany** [comment]
Nice work guys. How do I update to this? I have custom wake_start and wake_stop scripts. If I update, will it affect them?

**Comment by marcone** [comment]
> Nice work guys. How do I update to this? I have custom wake_start and wake_stop scripts. If I update, will it affect them?

Yes, if you run `setup-teslausb upgrade` then any changes you made to any of the TeslaUSB scripts or other code will be overwritten. This particular change was just one line, so you could easily just apply it yourself if you need it.
You might also consider contributing your awake_start and awake_stop changes back to the project, if they are generally useful.

**Comment by jjermany** [comment]
I can attach them here later and you guys can mess with it. It needs to be
rewritten to include other use cases. But it works great for people who use
TeslaFi.

**Comment by deangoldhill** [comment]
working perfectly now since upgrade, marker files in all 3 directories post archive.
Thanks again for your efforts!
