### ISSUE TITLE
Tesla’s new feature “Dashcam Clips” won’t work when using TeslaUSB

### ISSUE THREAD

**Issue by f4llenz** [marcone/teslausb#907]
### Describe the problem

![IMG_5112](https://github.com/user-attachments/assets/e385fad3-2505-4248-b95b-ef3e2d188a4d)

Car is parked and charging, but not sleeping. The new feature makes sentry videos available for watching through the Tesla app. TeslaUSB still works fine as before, only having the “connect a faster USB” warning show up on the Tesla.

### Device

Raspberry Pi Zero 2 W

### OS Image

Prebuilt TeslaUSB image

### Car Model

Model Y

### USB connection

Glove box

**Comment by f4llenz** [comment]
Come to think of it, now that Tesla has a backend to expose the USB to the app, that might opens up another way to do what TeslaUSB does, but pulling it from the NAS/server rather than pushing from the raspberry pi. 

If I get time after the holidays I'll try to log the app network traffic

**Comment by marcone** [comment]
You said "Car is parked and charging, but not sleeping", but not sleeping doesn't mean the USB ports are powered. It looks like maybe when you opened the "Dashcam Clips" view in the app, the Pi was still off or in the process of booting up. There isn't really anything TeslaUSB can do about this. You'll need to ensure the Pi is booted and connected to the car before using the new app feature.
