### ISSUE TITLE
No /Boot folder on SD card after flashing

### ISSUE THREAD

**Issue by firstel** [marcone/teslausb#96]
The one step instructions say that there is a /Boot folder and to create the conf file there.  The SD card itself is named "Boot" after being flashed.  The instructions are confusing.

**Comment by marcone** [comment]
Noted

**Comment by chrispi68** [comment]
So where should teslausb_setup_variables.conf be located?

**Comment by DMBlakeley** [comment]
Boot is the main folder on the SD card.
