### ISSUE TITLE
Disable TESLA API temporarily

### ISSUE THREAD

**Issue by kdvlr** [marcone/teslausb#97]
Is there a way to temporarily disable the tesla API. My 14-50 is not working and I am running off my 120v and I don't want to wake up my car while archiving. 

It does not look like there is a flag that we can add that can be enabled ?

A suggestion
```
if (( $SECONDS / 300 > 0 ))
```
can be changed to 
```
if (( $SECONDS / 300 > 0 )) && WAKEUP_TESLA = 'Y'
```
and add WAKEUP_TESLA to /root/teslausb.conf; it should work.

**Comment by marcone** [comment]
That doesn't seem like a common enough problem to warrant adding and documenting support for. I'd suggest deleting or renaming /root/bin/tesla_api.py
